### ISSUE TITLE
computing loss

### ISSUE THREAD

**Issue by derekwong66** [MaybeShewill-CV/lanenet-lane-detection#100]
Hi@MaybeShewill-CV ,

请问在computing loss里， 为什么要对decode_deconv，再做一次conv2d & relu?  做这一次的filter weight 也是通过训练的到的吗？Thanks！

**Comment by MaybeShewill-CV** [comment]
@derekwong66 这个是在做feature embedding. filter weight是通过学习得到的。关于feature embedding你可以阅读下原文:)

**Comment by derekwong66** [comment]
@MaybeShewill-CV 
deconv_final的ouput channel 是64， 在这基础上做一次conv&relu得到4 -dimensional embedding per lane pixel，用于更好地clustering.
