### ISSUE TITLE
请问作者有没有在tuSimple lane dataset上评估您复现的代码的FP,FN,ACC等评价指标？

### ISSUE THREAD

**Issue by BDMLLang** [MaybeShewill-CV/lanenet-lane-detection#101]
现在我想自己评估一些您复现的模型在tuSimple lane dataset上的FP,FN,ACC等评价指标，如果我需要这样做的话该怎么入手呢？

**Comment by cardwing** [comment]
@BDMLLang , please refer to [my repo](https://github.com/cardwing/Codes-for-Lane-Detection) which implements SCNN using Tensorflow and [this issue](https://github.com/cardwing/Codes-for-Lane-Detection/issues/4) to generate pred_file.json.

**Comment by BDMLLang** [comment]
> @BDMLLang，请参考[我的repo](https://github.com/cardwing/Codes-for-Lane-Detection)，它使用Tensorflow实现SCNN，[这个问题](https://github.com/cardwing/Codes-for-Lane-Detection/issues/4)生成pred_file.json。

您提供的这个生成pred_file.py脚本，适用于本库中模型的输出吗？感谢！

**Comment by cardwing** [comment]
@BDMLLang , 不是的，你需要用我的repo下的模型的输出。请参考之前我给的那个issue，里面有说明。或者你可以按照我的test_lanenet.py来修改本库的模型的输出方式。

**Comment by BDMLLang** [comment]
> @BDMLLang，不是的，你需要用我的repo下的模型的输出。请参考之前我给的那个问题，里面有说明。或者你可以按照我的test_lanenet.py来修改本库的模型的输出方式。

请教您一个问题，在评估图森数据集的时候需要提供y坐标=[160-710]对应的x坐标，但我预测的x,y坐标对应不上，是不是需要使用曲线去拟合预测的车道线，再使用y坐标=[160-710]去拟合的曲线中找到对应的预测x坐标，最后使用评估脚本评估acc，是这样的逻辑吗？
还要您提供的生成label.png的脚本，中lane_cmp()函数应该传什么参数进去呢？您代码的这里未传参
![image](https://user-images.githubusercontent.com/32613079/49860227-61f4fc80-fe34-11e8-91af-82c9f2b3458f.png)
