### ISSUE TITLE
About the instance picture and instance picture

### ISSUE THREAD

**Issue by OneMondy** [MaybeShewill-CV/lanenet-lane-detection#103]
Hello, I just got in touch with this field. Can you provide the source code for how to convert to instance picture and binary picture? thank you very much!!!@MaybeShewill-CV

**Comment by MaybeShewill-CV** [comment]
@OneMondy You may read the tusimple dataset for details or you can search the script on google:)

**Comment by MaybeShewill-CV** [comment]
@OneMondy You may also search it on baidu:)
