### ISSUE TITLE
Tensorflow version of SCNN is available now

### ISSUE THREAD

**Issue by cardwing** [MaybeShewill-CV/lanenet-lane-detection#104]
I have implemented SCNN using Tensorflow and put the full codes [here](https://github.com/cardwing/Codes-for-Lane-Detection). You can test the code in popular lane detection benchmarks like TuSimple, CULane and BDD100K or your custom dataset with minor modification. Welcome to raising issues if you have problems in reproducing the results. My code is based on [this repo](https://github.com/MaybeShewill-CV/lanenet-lane-detection). Thanks for your shared codes. @MaybeShewill-CV

**Comment by MaybeShewill-CV** [comment]
@cardwing Thanks a lot:)

**Comment by yinhai86924** [comment]
> 我已经使用Tensorflow实现了SCNN并在[此处输入](https://github.com/cardwing/Codes-for-Lane-Detection)了完整的代码。您可以在流行的车道检测基准测试中测试代码，如TuSimple，CULane和BDD100K，或者您的自定义数据集，只需稍加修改即可。如果您在复制结果时遇到问题，欢迎提出问题。我的代码基于[这个回购](https://github.com/MaybeShewill-CV/lanenet-lane-detection)。感谢您的共享代码。@ MaybeShewill-CV
关于自己定义的数据集需要满足什么格式，模型才能用！即如何标注，有没有现成的标注工具 谢谢！

**Comment by yinhai86924** [comment]
关于自己定义的数据集需要满足什么格式，模型才能用！即如何标注，有没有现成的标注工具谢谢！

**Comment by yinhai86924** [comment]
SCNN-Tensorflow与之前的SCNN torch版本的有什么不同！ 检测方法是一样的吗

**Comment by MaybeShewill-CV** [comment]
@yinhai86924 检测方法是一样的 实现框架不同 自定义的数据可以看看readme文件

**Comment by yinhai86924** [comment]
训练采自定义的数据集! 关于自己定义的数据集需要满足什么格式。即如何标注，有没有现成的标注工具 谢谢!
