### ISSUE TITLE
import error from a folder

### ISSUE THREAD

**Issue by skymatte** [MaybeShewill-CV/lanenet-lane-detection#109]
In dense_encoder.py", line 14, in ,
from collections import OrderedDict

But there is no such directory named collections
Kindly help me with it

**Comment by skymatte** [comment]
In dense_encoder.py", line 14, in <module>,
from collections import OrderedDict

But there is no such directory named collections
Kindly help me with it

**Comment by mikeedi** [comment]
It is built-in python3 module
https://docs.python.org/3/library/collections.html

**Comment by skymatte** [comment]
Thanks for reply, but why the following error is being shown
ImportError: No module named collections

**Comment by skymatte** [comment]
Also same error was occurring for other modules as lane-model etc.
Why such error is occurring.
Note:I fixed it's python path in .zshrc file too but then also same error was taking place

**Comment by MaybeShewill-CV** [comment]
@skymatte Which version of python are you using?

**Comment by skymatte** [comment]
> @skymatte Which version of python are you using?

Python 2.7 but tried it with 3.0 too

**Comment by MaybeShewill-CV** [comment]
@skymatte The model was tested under python 3.5. Maybe you can try to upgrade your python and test it again:)
