### ISSUE TITLE
vgg16.npy missing

### ISSUE THREAD

**Issue by cxy7452** [MaybeShewill-CV/lanenet-lane-detection#11]
Tried to train using your pre-trained vgg model, the error message indicates that vgg16.npy is not found. Can you provide that as well? Thanks!

**Comment by MaybeShewill-CV** [comment]
@cxy7452 I have uploaded the pre-trained vgg16 file in dropbox.

**Comment by ding-hai-tao** [comment]
I didn't find vgg16.npy in dropbox.

**Comment by MaybeShewill-CV** [comment]
@ding-hai-tao I will check it tomorrow

**Comment by ding-hai-tao** [comment]
I want to know how your vgg16.npy is generated? At the same time, I have not found the vgg16.npy file in dropbox.Can you provide that as well? Thanks!

**Comment by MaybeShewill-CV** [comment]
@ding-hai-tao The vgg16 pretrained weights is generated by training the net on imagenet dataset. I will upload the vgg16 weights file once the network condition is premitted. Thanks

**Comment by ding-hai-tao** [comment]
Can I use vgg16.h5 instead of your vgg.npy file?

**Comment by MaybeShewill-CV** [comment]
@ding-hai-tao Yes you can use your own pretrained weights to init the vgg 16 net

**Comment by yiyichun** [comment]
Hello, did you upload the vgg16.npy file? Can you tell me where to find the file? Thank you :)

**Comment by yiyichun** [comment]
Excuse me, can you provide training set data?

**Comment by MaybeShewill-CV** [comment]
@yiyichun The model is trained on an open dataset called Tusimple Lane Dataset. You can find it here http://benchmark.tusimple.ai/

**Comment by wangqingyang105** [comment]
@cxy7452 did you solve this problem? Where could I download vgg16.npy file? Thx

**Comment by cxy7452** [comment]
I've downloaded a pre-trained vgg16.npy here: https://github.com/machrisaa/tensorflow-vgg

**Comment by MaybeShewill-CV** [comment]
@cxy7452 Good job

**Comment by Chris-code1** [comment]
> I've downloaded a pre-trained vgg16.npy here: https://github.com/machrisaa/tensorflow-vgg

inside the repo you shared there is no vgg16.npy file or am I missing something?
