### ISSUE TITLE
May I ask a question about your training data?

### ISSUE THREAD

**Issue by cancooCHQ** [MaybeShewill-CV/lanenet-lane-detection#110]
What is the marking tool used for your lane line data annotation, is it using  the Lableme?

**Comment by MaybeShewill-CV** [comment]
@cancooCHQ I use the public dataset tusimple dataset which is well labeled. But I do not know how they make those labeled data:)

**Comment by cardwing** [comment]
@cancooCHQ , you can refer to [this issue](https://github.com/cardwing/Codes-for-Lane-Detection/issues/11).

**Comment by MaybeShewill-CV** [comment]
@cardwing Thanks a lot:)

**Comment by cardwing** [comment]
^_^
