### ISSUE TITLE
Should I resize the pictures in my training set to the same size?

### ISSUE THREAD

**Issue by Chen-Su** [MaybeShewill-CV/lanenet-lane-detection#112]
Hi, I noticed that the h-sample is all the same for any item in tusimple dataset json file. Now I want to train the net in my datasets, but the images in my set is in various scale. Should I resize them to the same size?
Thank you for your code, looking forward to your reply : )

**Comment by MaybeShewill-CV** [comment]
@Chen-Su Yep all the training samples should be rescaled to the same size:)

**Comment by Chen-Su** [comment]
@MaybeShewill-CV Got it, thank you again : )

**Comment by MaybeShewill-CV** [comment]
@Chen-Su Welcome:)

**Comment by MaybeShewill-CV** [comment]
@yinhai86924 标注问题我觉得每隔20个像素也是没有问题的，但是如果点太稀疏的话可能不能用polyline直接连接可能需要做曲线拟合:)
