### ISSUE TITLE
您好，方便写几行检测视屏的脚本吗？

### ISSUE THREAD

**Issue by HITjialanyu** [MaybeShewill-CV/lanenet-lane-detection#113]
新手写了好久，一直运行不对。

**Comment by MaybeShewill-CV** [comment]
@HITjialanyu 只要抓取视频帧 剩下的就和单张检测一样流程了:)

**Comment by HITjialanyu** [comment]
您好，在def test_lanenet函数上加了cv2的读取，可是结果只显示第一帧，然后自动运行结束，没有循环读取下一帧，请问是该函数下with模块的原因吗？还是该函数return的原因呀？

**Comment by HITjialanyu** [comment]
写完啦，可以关啦

**Comment by MaybeShewill-CV** [comment]
@HITjialanyu 👍 :)

**Comment by MengHuiLei** [comment]
@HITjialanyu 您好，方便分享一下检测视频的脚本吗？辛苦辛苦，，，

**Comment by Jerry-LMB** [comment]
@HITjialanyu 可以分享一下检测视频的代码吗？谢谢
