### ISSUE TITLE
您好，请问h-net的部分如何使用？

### ISSUE THREAD

**Issue by sy8008** [MaybeShewill-CV/lanenet-lane-detection#114]
请问h-net是已经完成了吗？应该如何使用呢？

**Comment by MaybeShewill-CV** [comment]
@sy8008 这部分被我自己的ipm模块代替了:)

**Comment by MaybeShewill-CV** [comment]
@passion3394 没有 我不需要这个module了

**Comment by MaybeShewill-CV** [comment]
@passion3394 感兴趣可以移步https://github.com/MaybeShewill-CV/Easy-Ipm-Client

**Comment by passion3394** [comment]
@MaybeShewill-CV 那如果我想在车道线检测中加入ipm模块，怎么办呢？

**Comment by passion3394** [comment]
@MaybeShewill-CV 厉害，我看了一下这个Ipm的效果，目的是为了做道路的全景拼接吗？

**Comment by MaybeShewill-CV** [comment]
@passion3394 可以考虑我的这个ipm模型:)
