### ISSUE TITLE
你好，batch size 大于1的时候  训练出现 recursionerror 是怎么回事呢？

### ISSUE THREAD

**Issue by sc1234qwer** [MaybeShewill-CV/lanenet-lane-detection#115]

**Comment by MaybeShewill-CV** [comment]
@sc1234qwer 应该是你的数据准备出了问题，请按照readme准备你的训练数据。 如果还有问题可以贴一下你的train.txt文件截图:)

**Comment by sc1234qwer** [comment]
我用的example里面的train.txt 只改了下路径    batch size=1的时候可以训练，大于1就不行了。训练开始有UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "

**Comment by cardwing** [comment]
@sc1234qwer , you can check the annotations according to the suggestion given by MaybeShewill-CV or have a try of [my repo](https://github.com/cardwing/Codes-for-Lane-Detection) which implements SCNN using tensorflow.

**Comment by sc1234qwer** [comment]
> @sc1234qwer , you can check the annotations according to the suggestion given by MaybeShewill-CV or have a try of [my repo](https://github.com/cardwing/Codes-for-Lane-Detection) which implements SCNN using tensorflow.

I'll try it when I finish the lanenet.
