### ISSUE TITLE
你的model参数下载来不能读取啊

### ISSUE THREAD

**Issue by deeplearner12138** [MaybeShewill-CV/lanenet-lane-detection#117]
ValueError: The passed save_path is not a valid checkpoint: model/tusimple_lanenet/

**Comment by deeplearner12138** [comment]
can you offer help?

**Comment by fayechou** [comment]
@deeplearner12138 
FYI:
python tools/test_lanenet.py --is_batch True --batch_size 2 --save_dir data/tusimple_test_image/ret --weights_path model/tusimple_lanenet/tusimple_lanenet_vgg_2018-10-19-13-33-56.ckpt-200000 --image_path data/tusimple_test_image/

**Comment by MaybeShewill-CV** [comment]
@deeplearner12138 You may use the wrong model weights file path:)

**Comment by deeplearner12138** [comment]
我把你放在网上的下载来放在这个目录下啊\model\tusimple_lanenet\  ，引用时是weights_path model/tusimple_lanenet/ 这样引用的  不知道哪里错了

**Comment by MaybeShewill-CV** [comment]
@deeplearner12138 --weights_path model/tusimple_lanenet/tusimple_lanenet_vgg_2018-10-19-13-33-56.ckpt-200000 这个是weights_path 你可以先熟悉熟悉tensorflow:)
