### ISSUE TITLE
想请教一下弯道曲线拟合的经验

### ISSUE THREAD

**Issue by MentorEzio** [MaybeShewill-CV/lanenet-lane-detection#119]
我在检测弯道车道线时发现，由于摄像头盲区与视角有限，有时只能拍摄到一根车道线，这种情况车道线拟合应该怎么做？（想做车道线保持）

**Comment by MaybeShewill-CV** [comment]
@MentorEzio 我还没有太明白你的意思 如果摄像头只能拍到一根车道线 那就没办法做车道线保持了:)
