### ISSUE TITLE
Dimensions must be equal, but are 44 and 45 for 'lanenet_loss/inference/decode/fuse_1' (op: Add)

### ISSUE THREAD

**Issue by jess2422** [MaybeShewill-CV/lanenet-lane-detection#12]
Thank you for sharing your code! I've formatted the BDD dataset to train your model on, but I keep running into this error: 
![image](https://user-images.githubusercontent.com/26938589/41876118-d1e7eb3a-789a-11e8-9484-21db22d67fb1.png)

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/common_shapes.py", line 654, in _call_cpp_shape_fn_impl
    input_tensors_as_shapes, status)
  File "/usr/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimensions must be equal, but are 44 and 45 for 'lanenet_loss/inference/decode/fuse_1' (op: 'Add') with input shapes: [4,44,80,64], [4,45,80,64].

My command is: python3 tools/train_lanenet.py --net vgg --dataset_dir ~/data/bdd100k/ --weights_path model/tusimple_lanenet/tusimple_lanenet_vgg_2018-05-21-11-11-03.ckpt-94000, and ~/data/bdd100k/ has the three image directories along with train.txt and val.txt as specified in the example. The only configuration I've changed is image height and width to 720 x 1280. Do you have any ideas on what may be the problem here?

**Comment by MaybeShewill-CV** [comment]
@jess2422 Rescale your tensor shape which must be equal after applying transpose conv operation.

**Comment by jess2422** [comment]
Does this happen because of the different training data or do you have to do this every time? I somewhat understand the conv_2d_tranpose operation, but do you mean to also pad the output of regular conv_2d to match the transpose?

**Comment by yuhenry** [comment]
j

**Comment by yuhenry** [comment]
Hi, I'm new to lane detection. I came cross the same problem.
How to adjust the input sensor shape?

**Comment by MaybeShewill-CV** [comment]
@jess2422 You should adjust your input tensor shape to make sure the tensors which are added together have the same shape.
