### ISSUE TITLE
Suggestion for code organization

### ISSUE THREAD

**Issue by david-bernstein** [MaybeShewill-CV/lanenet-lane-detection#122]
Hey thanks for writing such great code! One suggestions: instead of having to change PYTHONPATH to get all the imports right, what I've done in my copy is to move the training and test scripts out of tools to the top level directory and then add empty __init__.py files to all the folders. Then the scripts run without having to change or alter system paths. This organization is more in line with other open source NN codes I've used.

**Comment by MaybeShewill-CV** [comment]
@david-bernstein Thanks for your suggestion. In my local computer all the module in this repo was created via pycharm so a empty __init__.py file will be created automatically but these file was added to the .gitignore file so they were shown here. Apology for the inconvenient:)
