### ISSUE TITLE
Does the code support multi GPU to train?

### ISSUE THREAD

**Issue by passion3394** [MaybeShewill-CV/lanenet-lane-detection#125]
does the code support multi GPU to train? In my dataset, the training process is too slow, and I wonder whether the lanenet code support multi GPU to train or not?

**Comment by MaybeShewill-CV** [comment]
@passion3394 This repo does not support that now. You're welcome to promote this repo with that features:)

**Comment by passion3394** [comment]
@MaybeShewill-CV maybe sooner. The following are my figures about my dataset training on lanenet.
![train_accuracy](https://user-images.githubusercontent.com/14256482/50050890-3464c780-0142-11e9-85a5-6f7deb08c203.jpg)
![train_cost](https://user-images.githubusercontent.com/14256482/50050891-362e8b00-0142-11e9-98ea-c668ec68119a.jpg)
![val_accuracy](https://user-images.githubusercontent.com/14256482/50050894-3d559900-0142-11e9-9177-e45b77dd137c.jpg)
![val_cost](https://user-images.githubusercontent.com/14256482/50050897-447ca700-0142-11e9-93da-2981c0cb0033.jpg)

It is strange that the train accuracy is always up, but the val accuracy is always horizontal. Why? is that overfit?

**Comment by passion3394** [comment]
@MaybeShewill-CV ok, thanks.

**Comment by MaybeShewill-CV** [comment]
@passion3394 You're welcome to share some of your test result with us here:)

**Comment by longtong-system** [comment]
> @MaybeShewill-CV maybe sooner. The following are my figures about my dataset training on lanenet.
> ![train_accuracy](https://user-images.githubusercontent.com/14256482/50050890-3464c780-0142-11e9-85a5-6f7deb08c203.jpg)
> ![train_cost](https://user-images.githubusercontent.com/14256482/50050891-362e8b00-0142-11e9-98ea-c668ec68119a.jpg)
> ![val_accuracy](https://user-images.githubusercontent.com/14256482/50050894-3d559900-0142-11e9-9177-e45b77dd137c.jpg)
> ![val_cost](https://user-images.githubusercontent.com/14256482/50050897-447ca700-0142-11e9-93da-2981c0cb0033.jpg)
> 
> It is strange that the train accuracy is always up, but the val accuracy is always horizontal. Why? is that overfit?

hello,can you give me a copy of the code you downloaded at that time? Because the current code has been updated, the accuracy of the call part has been deleted, so I want to refer to the code at that time, thank you
