### ISSUE TITLE
找到个笔误bug

### ISSUE THREAD

**Issue by vell001** [MaybeShewill-CV/lanenet-lane-detection#127]
https://github.com/MaybeShewill-CV/lanenet-lane-detection/blob/master/tools/test_lanenet.py
line 100:
sess_config = tf.ConfigProto(device_count={'CPU': 0})
应该是：
sess_config = tf.ConfigProto(device_count={'GPU': 0})

**Comment by MaybeShewill-CV** [comment]
@vell001 谢谢更正,应该是当时测试的时候两个显卡都在跑训练所以用了CPU:)

**Comment by MaybeShewill-CV** [comment]
@vell001 不好意思 刚才没有看清出

**Comment by MaybeShewill-CV** [comment]
@vell001 那个地方是如果不适用GPU的话就使用CPU资源进行计算的意思哈:)
