### ISSUE TITLE
训练结果疑问

### ISSUE THREAD

**Issue by BDMLLang** [MaybeShewill-CV/lanenet-lane-detection#128]
我完全按照您给readme里面的参数训练的，现在已经epoch超过20w次了，准确率在95%震荡，未超过97%，看您给出的tensorboard可视化结果都是99%，我不知道是哪里错了，是数据集train test  val test 划分不合理，还是陷入局部最优了呢？
/home/user/桌面/2018-12-20 14-22-02屏幕截图.png

**Comment by hellosher** [comment]
@BDMLLang 您好，我想问一下您在训练过程中，大概前4万个epoch的时候准确率可以到达90%吗，我的准确率一直没有超过70%，样本数据都是使用作者给出的代码生成的，代码也没有修改，这样的结果是正常的吗，我该怎么调整呢 ？

**Comment by gabaebae123** [comment]
> [@BDMLLang](https://github.com/BDMLLang) 您好，我想问一下您在训练过程中，大概前4万个epoch的时候准确率可以到达90%吗，我的准确率一直没有超过70%，样本数据都是使用作者给出的代码生成的，代码也没有修改，这样的结果是正常的吗，我该怎么调整呢 ？

您好，请问您后来精度提升了吗？
