### ISSUE TITLE
请问我这个训练是出现了什么问题呢?

### ISSUE THREAD

**Issue by ASONG0506** [MaybeShewill-CV/lanenet-lane-detection#130]
![image](https://user-images.githubusercontent.com/26050577/50369638-dddd0a80-05d3-11e9-9b33-e900e7c1eb79.png)
如图所示，我用tusimple的数据进行训练，首先训练了30000轮，然后再次基础上重新开始训练了16000轮，期间精度一直上不去，位置在80左右，请问这是什么问题呢？
谢谢

**Comment by MaybeShewill-CV** [comment]
@ASONG0506 loss始终不下降最有可能是收敛到了不太好的局部极小,需要重新调整参数训练:)
