### ISSUE TITLE
多项式拟合

### ISSUE THREAD

**Issue by 111Moderato** [MaybeShewill-CV/lanenet-lane-detection#132]
请问lanenet_cluster文件里面定义的_lane_fit函数是在哪里调用了呢?

**Comment by MaybeShewill-CV** [comment]
@111Moderato 测试结果是直接使用polylines生成最后的车道线，没有使用曲线拟合，我本地的代码会使用ipm模块转换成俯视图然后在俯视图上使用b样条拟合车道线:)

**Comment by 111Moderato** [comment]
采用ipm转换拟合出的车道线是不是会更精确一些呢?

**Comment by MaybeShewill-CV** [comment]
@111Moderato 没事:)

**Comment by pengyiwu** [comment]
请问一下如何更好地进行弯道拟合，这个hnet貌似不能用，我准备用四组点实验的方法来ipm变换，坡度这个问题不知道怎么解决，只能忽视。。。

**Comment by MaybeShewill-CV** [comment]
@pengyiwu 可以参考我的easy-ipm-client project https://github.com/MaybeShewill-CV/Easy-Ipm-Client
