### ISSUE TITLE
看了lannent论文 对论文中图2有点疑问

### ISSUE THREAD

**Issue by yinhai86924** [MaybeShewill-CV/lanenet-lane-detection#138]
大致思想我理解是一部分基于像素级的语义分割：利用生成二值标签来训练二值分割网络，以获取预测的二值图（我理解是获取车道线的大类）。另一部分是进行实例分割：是利用生成实例标签来训练二值分割网络，以获取实例分割图吗？（我理解是给每个车道的分配类别：那些像素属于那个车道），疑问是实例分割出来的是不是已经完成聚类了？ 而图2后面是二值分割网络和instance embedding 分支网络进行了组合 再进行聚类，最后实现实例分割，输出每个不同的车道。请问一下聚类是哪里完成的？谢谢您  可能我理解有误，多谢指教！instance embedding 分支为每根车道线像素训练出pixel embedding ，pixel embedding具体指的是什么意思

**Comment by ethan02147** [comment]
您好，我对DL的造诣还不太深，所以想从您提供的训练好的模型中直接执行一次着手研究，想请问您在第一步骤所提到的，您有提供已经训练好的model file利我们直接运行一张测试图像，观察他出来的结果，想请问您提供的model_file在dropbox的网站里哪一个才是训练好的模型档，而我是直接把这个模型档加到以下路径 - -weights_path“”path/to/ your/model_weights_file“”这边就好了吗？因为试了很久还是没有头绪，望您有空能回复

**Comment by yinhai86924** [comment]
用训练集中的instance标签来训练embedding instance分支以获取embedding特征图（是运行测试代码结果中的instance image吗）  其目的是什么  ？这一步是完成实例分割吗 但是有了二值分割图 不就直接采用合适的聚类方法进行聚类输出结果 为什么还要进行embedding操作，感谢您的回复！这一点我一直很困惑 论文看了几遍没有看懂






------------------ 原始邮件 ------------------
发件人: "MaybeShewill-CV"<notifications@github.com>;
发送时间: 2019年1月14日(星期一) 中午11:28
收件人: "MaybeShewill-CV/lanenet-lane-detection"<lanenet-lane-detection@noreply.github.com>;
抄送: "尹海"<454960553@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [MaybeShewill-CV/lanenet-lane-detection] 看了lannent论文 对论文中图2有点疑问 (#138)




@yinhai86924 1.实例分割和二值分割是两个独立的分支，相互没有影响。只是最后聚类的时候只聚类处理二值分割里车道线的部分。2.实例分割的损失函数设计是为了生成一个更好的embedding特征图，但是网络本身没有做聚类操作。所以在inference的时候进行聚类操作。3.pixel embedding是指给每个像素都生成一个特征向量来对这个像素点进行描述。

**Comment by MaybeShewill-CV** [comment]
@yinhai86924 1.embedding特征图不是instance segmentation的结果。只是embedding feature的一种可视化显示方法。2.如果只有二值分割图而没有embedding的feature map那么你聚类的目标是什么？你可以再仔细读读论文:)

**Comment by yinhai86924** [comment]
我看了图2感觉整个过程就是执行车道线实例分割，是吧？就是不明白embedding feature map 与 二制图 聚类之间关系 embedding feature map是用数据集中实例标签训练生成的吗

**Comment by yinhai86924** [comment]
那么embedding feature map 在整个实例分割中扮演什么角色， 二值图生成的掩码用来确定哪些像素点进入后续的聚类，聚类采用什么方法？很感谢您的细心指导！

**Comment by MaybeShewill-CV** [comment]
@yinhai86924 1.embedding feature map生成特征图用来提供每个像素点的特征。2.聚类方法你可以采用任意方法，比如我使用过dbscan，meanshift等方法:)

**Comment by yinhai86924** [comment]
embedding feature map生成特征图用来提供每个像素点的特征，这些像素的特征主要是那些，位置信息，每个像素点都是3通道（空间信息），有点人评论说lannent是的多分支任务体系结构，车道分割分支输出密集的车道像素（二值分割），而车道嵌入embemding分支进一步将分割的车道像素分解成不同的车道实例 可以这样理解吗？

**Comment by MaybeShewill-CV** [comment]
@yinhai86924 embedding只负责提供feature不分配类别,类别分配是聚类器的工作:)

**Comment by yinhai86924** [comment]
我想问一下 具体哪部分分支网络执行的是实例分割任务，是embedding分支吗？对于embedding 分支好像是通过训练聚类损失函数，让同一车道线的像素距离近，而不同的车道线像素距离远。论文给了两个公式。而您说的类别分配时在mean-shift中完成的吗

**Comment by yinhai86924** [comment]
论文说：By using their clustering loss function, the instance embedding branch is trained to output an embedding for each lane pixel so that the distance between pixel embeddings belonging to the same lane is small, whereas the distance between pixel embeddings belonging to different lanes is maximized. By doing so, the pixel embeddings of the same lane will cluster together, forming unique clusters per lane  这里的an embedding for each lane piexl 中embedding 具体指的哪些？ 之后的提到的pixel embeddings。嵌入分支输出每个像素特征主要是为了实现聚类吗？

**Comment by MaybeShewill-CV** [comment]
@yinhai86924 1.embedding指的就是生成的feature map. 2.embedding feature map就是为聚类提供原材料(特征信息):)

**Comment by yinhai86924** [comment]
二值分割出来的车道线像素有没有具备特征信息，具体为聚类提供的特征信息包括哪些？感谢您的指导！

**Comment by MaybeShewill-CV** [comment]
@yinhai86924 .......==! 说了好几遍了都 特征就是embedding出来的feature map.这个特征没有明确的物理含义,不是你想的rgb值或者什么东西. 对每个像素的描述就是一个特征向量:)

**Comment by yinhai86924** [comment]
嗯！ 知道了！ 非常感谢你的指导！
