### ISSUE TITLE
Vgg16.npy missing

### ISSUE THREAD

**Issue by wangqingyang105** [MaybeShewill-CV/lanenet-lane-detection#14]
I got a problem to train the dataset, could you please tell me where i can download vgg16.npy file?

**Comment by MaybeShewill-CV** [comment]
@wangqingyang105 I will upload the vgg16.npy once the network condition is prermitted

**Comment by cardwing** [comment]
@wangqingyang105 , please refer to this issue [11](https://github.com/MaybeShewill-CV/lanenet-lane-detection/issues/11).
