### ISSUE TITLE
为什么不用嵌入分支网络训练得出的特征点 进行聚类？而用二值分割？

### ISSUE THREAD

**Issue by yinhai86924** [MaybeShewill-CV/lanenet-lane-detection#143]
有点不太明白，测试lanenet显示实例分割的效果 比二值分割要好！

**Comment by yinhai86924** [comment]
embedding实例分割出来的是整张图像素点的特征 还是只有车道线的一些特征信息。

**Comment by MaybeShewill-CV** [comment]
@yinhai86924 整张图, 具体可以仔细看论文:)

**Comment by yinhai86924** [comment]
那用车道线的实例标签训练出来 得到的是什么？抱歉！ 我认为只有车道线的像素被嵌入到了特征空间。

**Comment by MaybeShewill-CV** [comment]
@yinhai86924 实例标签训练出来的就是整张特征图,这个特征图会被用来做聚类然后得到最后的实例分割结果.由于实例损失函数的特殊设计使得特征图上的特征具有类内距离小,类间距离大的特点:)

**Comment by yinhai86924** [comment]
您好！ 请问一下tensorboard tools 是在哪里调用？ 可以观察训练参数变化情况。
