### ISSUE TITLE
The pretrained model produces some issues in output results

### ISSUE THREAD

**Issue by kaisark** [MaybeShewill-CV/lanenet-lane-detection#146]
I ran the pretrained model against my video data example and I noticed some issues (see examples below):
1. The clouds are detected as lanes??? This may just be a post-processing drawing issue???
2.  When another car overtakes the dashcam vehicle, lane detection had an issue. Was this due to reflection of some sort?

Original vid:
https://drive.google.com/open?id=1aM1JrHvG8XL1KQLG0buGvNFNk7rj3WTe

Thanks. 

![lanedetection gif-downsized_large](https://user-images.githubusercontent.com/3580312/51452811-381fd700-1d0a-11e9-9e13-f7fda42ec7f6.gif)

![madrive-dcam1_7](https://user-images.githubusercontent.com/3580312/51452846-6998a280-1d0a-11e9-91b2-19b12cd8cb4c.png)

![madrive-dcam1_88](https://user-images.githubusercontent.com/3580312/51453018-2a1e8600-1d0b-11e9-9f66-f0d392f54f87.png)

![madrive-dcam1_158](https://user-images.githubusercontent.com/3580312/51453028-31de2a80-1d0b-11e9-8b99-2c4adf70e2dd.png)

**Comment by yinhai86924** [comment]
what is about post process strategy?   and  I want to know the binary segmentation is not good as instance segmentation , why not cluster use  instance segmentation  replace binary segmentation?

**Comment by MaybeShewill-CV** [comment]
@yinhai86924 As I sait before the cluster use the embedding feats which is in instance segmentation branch. You're supposed to read the paper carefully

**Comment by danieladea** [comment]
@kaisark how did you run the lanenet on a video?
