### ISSUE TITLE
cluster issue

### ISSUE THREAD

**Issue by pengyiwu** [MaybeShewill-CV/lanenet-lane-detection#149]
请问一下是否可以对二值分割的结果进行采样精简像素，然后再利用嵌入分支的特征进行聚类，感谢

**Comment by pengyiwu** [comment]
额，我的意思是车道线拟合不需要那么多像素点，可以在二值分割后用一些数学方法筛选出概率大的点，然后再聚类吗，因为分割效果不好的时候聚类太慢了，感谢回复

**Comment by MaybeShewill-CV** [comment]
@pengyiwu 本来聚类的时候就不是所有的点都参与聚类,binary segmentation就是给聚类提供掩码的,可能你没有仔细看代码和文章,可以再仔细看看:)
