### ISSUE TITLE
ImportError: No module named lanenet_model

### ISSUE THREAD

**Issue by linhw3** [MaybeShewill-CV/lanenet-lane-detection#15]
Traceback (most recent call last):
  File "tools/test_lanenet.py", line 28, in <module>
    from lanenet_model import lanenet_merge_model
ImportError: No module named lanenet_model

**Comment by happog** [comment]
just add the module root dir to your PYTHONPATH😎

**Comment by MaybeShewill-CV** [comment]
@linhw3 Configure your python path

**Comment by WangShuu** [comment]
> just add the module root dir to your PYTHONPATH

do you have specific operations?i don't know how to handle this.

**Comment by WangShuu** [comment]
> > > just add the module root dir to your PYTHONPATH
> > 
> > 
> > do you have specific operations?i don't know how to handle this.
> > In your terminal, input below:
> 
> `export PYTHONPATH="${PYTHONPATH}:your_path/lanenet-lane-detection/lanenet_model"`
> 
> Change your_path to your personal path for `lanenet` folder. You can append this line to your `~/.bashrc` then `source ~/.bashrc ` to activate it.

Thanks!!

**Comment by JeremyCKT** [comment]
> > > > just add the module root dir to your PYTHONPATH
> > > 
> > > 
> > > do you have specific operations?i don't know how to handle this.
> > > In your terminal, input below:
> > 
> > 
> > `export PYTHONPATH="${PYTHONPATH}:your_path/lanenet-lane-detection/lanenet_model"`
> > Change your_path to your personal path for `lanenet` folder. You can append this line to your `~/.bashrc` then `source ~/.bashrc ` to activate it.
> 
> Thanks!!

I already try to put these in .bashrc but not works

export WORKON_HOME=/home/jeremydl/.virtualenvs
export PROJECT_HOME=/home/jeremydl/Devel
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
export VIRTUALENVWRAPPER_VIRTUALENV=/usr/local/bin/virtualenv
export PYTHONPATH="${PYTHONPATH}:home/jeremydl/Downloads/lanenet-lane-detection-master/lanenet_model"
export PYTHONPATH="${PYTHONPATH}:home/jeremydl/Downloads/lanenet-lane-detection-master/config"
source /usr/local/bin/virtualenvwrapper.sh

The error still occurs 
ImportError: cannot import name 'global_config'

**Comment by SAIVENKATARAJU** [comment]
I have added path in google colab like this, but still getting the same issue.

import os
os.environ['PYTHONPATH'] += ":Codes-for-Lane-Detection/SCNN-Tensorflow/lane-detection-model/lanenet_model"``

**Comment by Luishfs** [comment]
@SAIVENKATARAJU 
I solved this using:
`import sys
sys.path.append('/content/drive/My Drive/lanenet-lane-detection')`

**Comment by Dylee-y** [comment]
> > > > just add the module root dir to your PYTHONPATH
> > > 
> > > 
> > > do you have specific operations?i don't know how to handle this.
> > > In your terminal, input below:
> > 
> > 
> > `export PYTHONPATH="${PYTHONPATH}:your_path/lanenet-lane-detection/lanenet_model"`
> > Change your_path to your personal path for `lanenet` folder. You can append this line to your `~/.bashrc` then `source ~/.bashrc ` to activate it.
> 
> Thanks!!
