### ISSUE TITLE
Some questions about th e model

### ISSUE THREAD

**Issue by OneMondy** [MaybeShewill-CV/lanenet-lane-detection#150]
Hello, how can I view the model of the entire network? Is the output only a picture? Is there any coordinate information or some other output? Thanks Reply.

**Comment by MaybeShewill-CV** [comment]
@OneMondy You can get the lane's coordinate via the binary segmentation result image:)

**Comment by MaybeShewill-CV** [comment]
@OneMondy what do you men view the whole model? if you want to know the whole model architecture you can either refer to the origin paper or you can see the tensorboard file:)
