### ISSUE TITLE
Test model 报错

### ISSUE THREAD

**Issue by xiaozi-ML** [MaybeShewill-CV/lanenet-lane-detection#151]
初学，想先跑下代码看看，结果报错了，求解答
python tools/test_lanenet.py --is_batch False --batch_size 1 --weights_path ath/to/your/model_weights_file 
--image_path data/tusimple_test_image/0.jpg
*报错1：
 from lanenet_model import lanenet_merge_model
ImportError: No module named 'lanenet_model'
解决：将test_lanenet放在文件夹外面运行，在lanenet_model中放——init——文件
*报错2：
tensorflow.python.framework.errors_impl.NotFoundError: FindFirstFile failed for: model/tusimple_lanenet : \u03f5\u0373\udcd5\u04b2\udcbb\udcb5\udcbd\u05b8\udcb6\udca8\udcb5\udcc4·\udcbe\udcb6\udca1\udca3
; No such process
不知道怎么解决

**Comment by MaybeShewill-CV** [comment]
@xiaozi-ML 1.模块添加进你的PYHTONPATH，如何添加请自己搜索 2.weights path需要指定到你自己的weights路径，可以去前面翻阅相关的issue，或者先了解了解tensorflow

**Comment by xiaozi-ML** [comment]
感谢，已经解决
根据文档下载新的权重解压到model/tusimple_lanenet/路径，并将运行代码修改为：
python test_lanenet.py --is_batch False --batch_size 1 --weights_path model/tusimple_lanenet/tusimple_lanenet_vgg_2018-10-19-13-33-56.ckpt-200000 --image_path data/tusimple_test_image/0.jpg

**Comment by MaybeShewill-CV** [comment]
@xiaozi-ML :) :+1:
