### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by lunana123** [MaybeShewill-CV/lanenet-lane-detection#152]
![image](https://user-images.githubusercontent.com/41152300/51581318-87305c80-1f02-11e9-9be1-ad3ae7416e95.png)

![image](https://user-images.githubusercontent.com/41152300/51581323-90b9c480-1f02-11e9-8181-4ff96250dea3.png)

请问路径哪里出了问题呢？

**Comment by MaybeShewill-CV** [comment]
@lunana123 自行检查文件的路径是否正确,然后import error可以查询相关package的说明网站:)

**Comment by shoujingluan** [comment]
@lunana123 请问兄弟，你的问题解决了吗？是如何解决的，我遇到了和您一样的问题！请不吝赐教！

**Comment by zoeveryday** [comment]
> @lunana123 请问兄弟，你的问题解决了吗？是如何解决的，我遇到了和您一样的问题！请不吝赐教！

检查train.txt 以及val.txt 中文件的路径名称是否正确。Repo中这两个文件中的ROOT_PATH，需要修改为你当前工作目录的路径，如：/home/***/

**Comment by lunana123** [comment]
是生成标签出错吗？，你看一下自己的路径对吗




------------------ 原始邮件 ------------------
发件人: "zoeveryday"<notifications@github.com>;
发送时间: 2019年5月6日(星期一) 晚上7:39
收件人: "MaybeShewill-CV/lanenet-lane-detection"<lanenet-lane-detection@noreply.github.com>;
抄送: "1739598652"<1739598652@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [MaybeShewill-CV/lanenet-lane-detection] AttributeError:'NoneType' object has no attribute 'shape' (#152)



 
@lunana123 请问兄弟，你的问题解决了吗？是如何解决的，我遇到了和您一样的问题！请不吝赐教！
  
检查train.txt 以及val.txt 中文件的路径名称是否正确。Repo中这两个文件中的ROOT_PATH，需要修改为你当前工作目录的路径，如：/home/***/

**Comment by shoujingluan** [comment]
收到，谢谢您的回复，问题已解决。


在 2019-05-06 19:39:09，"zoeveryday" <notifications@github.com> 写道：


@lunana123 请问兄弟，你的问题解决了吗？是如何解决的，我遇到了和您一样的问题！请不吝赐教！

检查train.txt 以及val.txt 中文件的路径名称是否正确。Repo中这两个文件中的ROOT_PATH，需要修改为你当前工作目录的路径，如：/home/***/
