### ISSUE TITLE
I need some help about   classification

### ISSUE THREAD

**Issue by sc1234qwer** [MaybeShewill-CV/lanenet-lane-detection#155]
It's effective for me to train solid and dotted lines separately, but I still don't know how to classify them in a model. Can you describe exactly what needs to be changed? Thank you.

**Comment by MaybeShewill-CV** [comment]
@sc1234qwer 1.Change the label data 2.Change the binary segmentation logit's dimension 3.Change the instance label. You can google some examples of image segmentation model:)
