### ISSUE TITLE
多个json格式标签文件训练问题

### ISSUE THREAD

**Issue by yinhai86924** [MaybeShewill-CV/lanenet-lane-detection#156]
标注的多个json格式标签文件，每个json文件之间标注大小不一  但json文件中标注格式一样， 能否一起参与训练，

**Comment by MaybeShewill-CV** [comment]
@yinhai86924 没有明白你的意思:)

**Comment by MaybeShewill-CV** [comment]
@yinhai86924 图森的数据本身就是Y方向等距取样,只要你能按照样本制作的规则生成训练图像就可以正常训练,有关图森数据的问题你可以去图森的官网查看:)
