### ISSUE TITLE
why not Enet

### ISSUE THREAD

**Issue by fred0209** [MaybeShewill-CV/lanenet-lane-detection#157]
Why is the model implemented in the code not enet?

**Comment by MaybeShewill-CV** [comment]
@fred0209 Since the FCN module was already made in my another work:)

**Comment by fred0209** [comment]
ok,thanks,I am looking for another person's ENet implementation

**Comment by MaybeShewill-CV** [comment]
@fred0209 As far as I know there are lots enet implementation on GitHub you may use that as the backend of the lanenet model:)

**Comment by MurphyChengIsMe** [comment]
@MaybeShewill-CV 您好，我可以詢問一下您測試這個模型大約能達到多少FPS嗎? 我自己實驗感覺是有機會達到real-time水平的，但目前還尚未成功，希望能夠有個參考的數值，我所使用的運算資源是1080T，謝謝您。
