### ISSUE TITLE
关于模型速度

### ISSUE THREAD

**Issue by MurphyChengIsMe** [MaybeShewill-CV/lanenet-lane-detection#160]
您好，我可以询问一下您测试这个模型大约能到多少FPS吗? 我自己实验感觉是有机会达到real-time水平的，但目前还尚未成功达到，想知道您测试时一般都达到多少帧数的处理速度，希望做个参考，我所使用的运算资源是1080Ti，谢谢您。

**Comment by MaybeShewill-CV** [comment]
@MurphyChengIsMe 单纯的前向传播过程能达到35～45fps在我的1070上测试，你可以测试一下看看结果~

**Comment by MurphyChengIsMe** [comment]
我今天實驗有成功了，速度可以超過50fps,沒注意到是GPU資源分配的關係，非常謝謝您！也祝您新年快樂=)

**Comment by MaybeShewill-CV** [comment]
@MurphyChengIsMe 哈哈 谢谢哈:)

**Comment by MurphyChengIsMe** [comment]
@MaybeShewill-CV 你好，我有个部份可能还不是很明白，想请教你一下。关于模型分支的部份binary会输出一个二值化的结果，然后pixel-embedding分支输出一张特征图，特征图再根据binary的结果进行clustering最后输出，这边我的理解是这样。我比较好奇是pixel-embedding分支为什么最后输出的dimension为3，因为我印象中segmentation model输出的dimension值通常跟他要预测的class数量相同，所以为什么不是5条线涵盖背景总共6个class输出dimension为6而是3呢？谢谢你。

**Comment by MaybeShewill-CV** [comment]
@MurphyChengIsMe 3是指特征向量的维度,也就是特征个数和class数量没有关系

**Comment by MurphyChengIsMe** [comment]
@MaybeShewill-CV 我明白了，非常谢谢你。我想再请问一下你有尝试过以DenseNet作为特征提取的部份吗？在速度与准确度上会不会比使用VGG-16来的高？我目前有些测试还没完成，由于没使用过DenseNet之后想尝试看看，有点好奇结果，谢谢你。

**Comment by MurphyChengIsMe** [comment]
@MaybeShewill-CV 你好，我想再请教你一下有关于pixel-embedding分支的问题，这个分支在训练上是不是属于无监督式学习(Unsupervised Learning)，因为他有属于它的Loss Function，但看不太出来有使用Ground Truth参与训练，只有在Cluster运算结束后输出Instance才又有计算一次Loss，如果就单纯输出分群的特征图，感觉应该是无监督式学习。抱歉问题有点多，身边也没有人可以跟我讨论，所以上来询问，非常谢谢你。

**Comment by yinhai86924** [comment]
> 我今天實驗有成功了，速度可以超過50fps,沒注意到是GPU資源分配的關係，非常謝謝您！也祝您新年快樂=)

您好 怎么能够达到50的？  设置了哪些

**Comment by MurphyChengIsMe** [comment]
@yinhai86924 我没有做特别的设置，主要取决于你的GPU资源使用率是否足够，且我那时的FPS是目测的，有一部分的影像是有快过50，大部分都落在45上下，我猜也是取决于GPU当时的状态或影像的计算。

**Comment by yinhai86924** [comment]
> @yinhai86924 我没有做特别的设置，主要取决于你的GPU资源使用率是否足够，且我那时的FPS是目测的，有一部分的影像是有快过50，大部分都落在45上下，我猜也是取决于GPU当时的状态或影

我测试图像时候GPU利用率为7%，GPU内存占用率80% 然而测试每一张图像 所需时间太大（预处理时间+车道线预测时间+聚类时间） 如下图所示：
![QQ截图20190410092153](https://user-images.githubusercontent.com/45553479/55854831-69d16d00-5b98-11e9-95e9-dca46261c306.jpg)
主要问题出现在哪里？

**Comment by MurphyChengIsMe** [comment]
@yinhai86924 我這邊只測試模型向前傳播的時間，沒有包含預處理跟聚類運算，另一個可能是GPU本身不一樣也會影響處理速度，我與論文中是使用GTX 1080Ti。
