### ISSUE TITLE
generating label_data.json

### ISSUE THREAD

**Issue by masterLearning** [MaybeShewill-CV/lanenet-lane-detection#161]
Hello @MaybeShewill-CV 

I am currently trying to train the lanenet model with my own dataset but i missing some files.
My current status:

* I trained successfully the network with the 6 images which are in traning data example directory
  Now i need to train it with my own dataset (I generated images from a simulation program)
  In order to train the network i need additionaly the gt_images_instance and the gt_image_binary of each image.

For that i can use the generate_tusimple_dataset.py file in the tools directory and my files need to be structured as in the tuSimple directory, but my problem is i can not run the file because i dont have the label_data.json . How can i generate the json file with all all the attributes

* "lanes"
* "h_samples"
* "raw_file"
  and, am i doing something wrong or is there perhaps a better way to train the network ?

I thank you in advance for any answer.

**Comment by MaybeShewill-CV** [comment]
@masterLearning You may refer to Tusimple website for details about the dataset:)

**Comment by shank-gyrus** [comment]
@masterLearning did you find any way to generate binary and instance images?
