### ISSUE TITLE
Culane dataset

### ISSUE THREAD

**Issue by zguo008** [MaybeShewill-CV/lanenet-lane-detection#166]
Hi:)

I am trying to use CUlane dataset to train the network.

I have prepared the dataset into 3 folders as suggested. img, binary and instance.

I modified CUlane dataset label generator a bit so that it draws 1.In binary, 255 for white marking 2. in instance 20, 70, 120, 170 for 4 different instances.

However the training cannot start itself and saying:F ./tensorflow/core/util/cuda_launch_config.h:127] Check failed: work_element_count > 0 (0 vs. 0)

So i doubt whether I prepare the dataset in the right way. 

Any help will be appreciated!

Best regards,

Zx

**Comment by MaybeShewill-CV** [comment]
@zguo008 It seems there is something wrong with the cuda rather than the data preparation process:)

**Comment by zguo008** [comment]
I tried to start training using TUsimple dataset with the same machine and it can be trained sucessfully.
So I suppose the cuda is functioning properly?
Could u tell me whether I am labelling the data in the right way?
Thanks!

Best regards,
ZX

**Comment by MaybeShewill-CV** [comment]
@zguo008 You may check this https://github.com/MaybeShewill-CV/lanenet-lane-detection/blob/master/tools/generate_tusimple_dataset.py and see if you correctly labeled the data:)

**Comment by zguo008** [comment]
Issue solved, used tf version 1.80 which is incompatible.Solved by upgrade numpy version and tensorflow version.

thanks! ill close the issue now

**Comment by zacario-li** [comment]
I saw you convert CULane dataset into Tusimple dataset format. How did you generate the instance image? Did you simply let the lane to 20, 70, 120, 170 from the left to right?

**Comment by yinhai86924** [comment]
> Issue solved, used tf version 1.80 which is incompatible.Solved by upgrade numpy version and tensorflow version.
> 
> thanks! ill close the issue now

Can  you share your convert tools or code on github ?

**Comment by yinhai86924** [comment]
> Hi:)
> I am trying to use CUlane dataset to train the network.
> I have prepared the dataset into 3 folders as suggested. img, binary and instance.
> I modified CUlane dataset label generator a bit so that it draws 1.In binary, 255 for white marking 2. in instance 20, 70, 120, 170 for 4 different instances.
> However the training cannot start itself and saying:F ./tensorflow/core/util/cuda_launch_config.h:127] Check failed: work_element_count > 0 (0 vs. 0)
> So i doubt whether I prepare the dataset in the right way.
> Any help will be appreciated!
> Best regards,
> Zx

I really want to know how to translate Culane data to Tusmple Data。Can you provide some translate codes ？ becouse I also want to  train lanenet with Culane data！threrefor,  I really thank you！
