### ISSUE TITLE
pixel-embedding分支问题

### ISSUE THREAD

**Issue by MurphyChengIsMe** [MaybeShewill-CV/lanenet-lane-detection#167]
你好，我想请教你一下有关于pixel-embedding分支的问题，这个分支在训练上是不是属于无监督式学习(Unsupervised Learning)，因为他有属于它的Loss Function (Discriminative Loss)，但看不太出来有使用Ground Truth参与训练，只有在该分支输出特征图，并与Binary结果进行Cluster运算结束后输出Instance才有使用Ground Truth计算一次Loss，如果就单纯输出分群的特征图，感觉应该是无监督式学习，谢谢你。

**Comment by MaybeShewill-CV** [comment]
@MurphyChengIsMe instance label就是用来训练pixel embedding的label，你可以再仔细看下论文哈:)

**Comment by MurphyChengIsMe** [comment]
所以他的instance label是有直接参与到discriminative loss的计算对吗？感觉是决定loss里面C的参数。
我原先以为是pixel embedding输出一个特征图，再进行cluster运算结束后得到instance才有使用instance label计算loss，我刚刚有印论文出来再重看一次，有比较明白一些，非常谢谢你=)
