### ISSUE TITLE
training with culane dataset with empty image

### ISSUE THREAD

**Issue by zguo008** [MaybeShewill-CV/lanenet-lane-detection#168]
Hey:)
I have seen others using Culane dataset to train Lanenet.

I want to know the reason why if we input a completely black binary image(no lane) to the net will lead to the NAN error? (so far I have modified the l2 normalization to l1 normalization and remove the images with no lane included, and the training process is sucessful so far)

I believe it's some gradient overflow during backpropagation? 

Any help will be appreciated!

Best regards,

ZX

**Comment by MaybeShewill-CV** [comment]
@zguo008 The black binary label will lead to an unstable gradient you'd better remove all those kind of training examples:)

**Comment by zguo008** [comment]
No I mean I wonder which step in the model causes such kinda gradient overflow?

Best regards,

ZX

**Comment by MaybeShewill-CV** [comment]
@zguo008 The gradient overflow happened in the instance segmentation in most situation, you may test on your own dataset:)

**Comment by zguo008** [comment]
thanks and have a good day!
