### ISSUE TITLE
无法复现events.out.tfevents.1526872263.baidu-pc文件中记录的模型在Val_set上的表现。

### ISSUE THREAD

**Issue by EBlueQ** [MaybeShewill-CV/lanenet-lane-detection#171]
尝试从随机初始化的权重开始训练网络，Train_Accuracy达到**0.9**，Val_Accuracy达到**0.45**以后就不再上升，train_loss持续逼近**1.0**，val_loss在**4k**次迭代后不降反升。数据由代码作者提供的工具生成，按**7:3**比例划分train_set和val_set。

读取tboard文件夹下的`events.out.tfevents.1526872263.baidu-pc`日志文件，在Tensorboard中查看。注意到训练结束时Train和Validation的Accuracy都接近**1.0**。

直接读取训练好的参数进行训练，train_accuracy接近**1.0**，val_accuracy稳定在**0.8**。

**Comment by MaybeShewill-CV** [comment]
@EBlueQ 因为上传的tboard文件对应的模型和现在上传的模型在backbone上有一定不同哈:)

**Comment by EBlueQ** [comment]
谢谢答复！

可以指点一下为什么没有引用原论文的encoder结构吗？

另外，最新的模型参数是如何训练得到的呢？

是否还用了除tusimple benchmark以外的更多数据？

**Comment by MaybeShewill-CV** [comment]
@EBlueQ 因为和之前的工作有重叠，原来的网络结构和参数就直接拿来用了,没有用更多数据：）

**Comment by EBlueQ** [comment]
@MaybeShewill-CV 
从我目前的实验结果来看，如果没有在其他项目中训练过的参数，想要train from scratch (除了VGG-16 encoder是在ImageNet上预训练过的以外)，仅用tusimple的数据会出现比较严重的过拟合。

![image](https://user-images.githubusercontent.com/23174052/53681159-36412e80-3d20-11e9-816d-3e59aaeda975.png)

![image](https://user-images.githubusercontent.com/23174052/53681167-46590e00-3d20-11e9-8168-342e26679fc0.png)


因此猜想，采用VGG-16的模型要比原论文中ENet的模型表达能力更强，也就需要更多数据来对抗过拟合。

**Comment by MaybeShewill-CV** [comment]
@EBlueQ 你也可以尝试使用更少的共享参数 比如从更浅层开始分支成binary segmentation和pixel embedding:)

**Comment by EBlueQ** [comment]
@MaybeShewill-CV 好的，我继续尝试，谢谢您的建议！

**Comment by MaybeShewill-CV** [comment]
@EBlueQ 不客气:)

**Comment by coldsheephot** [comment]
> 尝试从随机初始化的权重开始训练网络，Train_Accuracy达到**0.9**，Val_Accuracy达到**0.45**以后就不再上升，train_loss持续逼近**1.0**，val_loss在**4k**次迭代后不降反升。数据由代码作者提供的工具生成，按**7:3**比例划分train_set和val_set。
> 
> 读取tboard文件夹下的`events.out.tfevents.1526872263.baidu-pc`日志文件，在Tensorboard中查看。注意到训练结束时Train和Validation的Accuracy都接近**1.0**。
> 
> 直接读取训练好的参数进行训练，train_accuracy接近**1.0**，val_accuracy稳定在**0.8**。

请问你现在的val精度是多少呢？我在测试的时候发现val_accuracy精度一直很跳跃
