### ISSUE TITLE
h-net integration 

### ISSUE THREAD

**Issue by singaporv** [MaybeShewill-CV/lanenet-lane-detection#174]
Hello,

Can you please tell if you have integrated Hnet with lanenet yet?

**Comment by MaybeShewill-CV** [comment]
@singaporv No I have not integrated with HNet. The ipm module is replaced with my own module. You can refer https://github.com/MaybeShewill-CV/Easy-Ipm-Client if you're interested with the ipm module:)

**Comment by singaporv** [comment]
@MaybeShewill-CV 
Thanks for the information, I'll look into it.

Also, one more thing - in file Lanenet_cluster.py
you have defined a function --> def _lane_fit(lane_pts):
But, in your implementation you are not calling it, to fit a line.

Can you please tell where to integrate this in our function call, or if not possible, can you please tell how can I fit a line on the points in mask_image?

**Comment by MaybeShewill-CV** [comment]
@singaporv The fit line function was not used. If you want to fit a line you need to cluster to determin which lane points belong to the same lane and then you can apply a ploy line fit function on those points:)
