### ISSUE TITLE
从更浅层开始分支成binary segmentation和pixel embedding

### ISSUE THREAD

**Issue by sc1234qwer** [MaybeShewill-CV/lanenet-lane-detection#175]
从更浅层开始分支成binary segmentation和pixel embedding,意思是比如可以decode_layer_list ['pool3' ,'pool2' ， 'pool1']  ?

**Comment by MaybeShewill-CV** [comment]
@MaybeShewill-CV 是的:)

**Comment by sc1234qwer** [comment]
> @MaybeShewill-CV 是的:)

那conv_4_1之后的卷积操作还有利用到嘛？我试了删掉也能训练

**Comment by MaybeShewill-CV** [comment]
@sc1234qwer 看你需要从哪一层开始分支,不需要CONV4就可以删除:)
