### ISSUE TITLE
Why not the E-Net?

### ISSUE THREAD

**Issue by kannidekan** [MaybeShewill-CV/lanenet-lane-detection#176]
Hello, thanks your public code. But here is a question. 
Why didn't you use E-Net as the based model on Encode-Decode architecture like the paper?

**Comment by MaybeShewill-CV** [comment]
@kannidekan The backbone net was inherited from another of my project. You may use enet as backbone net and It may promote the model's performance in my opinion:)

**Comment by kannidekan** [comment]
Ok, i got it, thanks!
