### ISSUE TITLE
how to restore densenet pre-trained weight?

### ISSUE THREAD

**Issue by zacario-li** [MaybeShewill-CV/lanenet-lane-detection#178]
I want ot use densenet rather than vgg16. how to restore densenet pre-trained weight? Which densenet do you use? 121?169?201?

**Comment by MaybeShewill-CV** [comment]
@zacario-li There's no pretrained weights with densenet. You may need train yourself:)

**Comment by yinhai86924** [comment]
如何训练密集网 得到权重？
