### ISSUE TITLE
请问实例分割结果这样合不合理。。

### ISSUE THREAD

**Issue by zijianzhang** [MaybeShewill-CV/lanenet-lane-detection#184]
![image](https://user-images.githubusercontent.com/16860630/54187797-4c51aa80-44e9-11e9-98a8-ff06bb5cecbc.png)

**Comment by MaybeShewill-CV** [comment]
@zijianzhang 这是embedding的特征图还是你聚类以后得到的结果?:)

**Comment by zijianzhang** [comment]
像是聚类之后的结果，embedding结果看着是正常的

**Comment by zijianzhang** [comment]
需要做相关图像处理吗

**Comment by MaybeShewill-CV** [comment]
@zijianzhang 如果是聚类结果那就是最终的instance segmentation结果 如果是embedding feature那就还需要聚类才能得到最后的instance segmentation结果:)

**Comment by zijianzhang** [comment]
@MaybeShewill-CV 是聚类之后的结果，embedding的特征图看着是正常的，所以感觉是聚类时候出了问题？

**Comment by MaybeShewill-CV** [comment]
@zijianzhang 这个结果好像没什么问题啊==!
