### ISSUE TITLE
关于instance_label

### ISSUE THREAD

**Issue by sc1234qwer** [MaybeShewill-CV/lanenet-lane-detection#185]
instance_label有三条车道线 而训练的时候只能显示一条或者两条是什么原因造成的？
![embedding](https://user-images.githubusercontent.com/32254819/54501348-b93cc880-495f-11e9-9dcf-90456e493c5e.png)
![instance_label](https://user-images.githubusercontent.com/32254819/54501349-b93cc880-495f-11e9-85bc-f1e1390236c3.png)

**Comment by sc1234qwer** [comment]
二值分割对应有三条，没有问题

**Comment by MaybeShewill-CV** [comment]
@sc1234qwer Train process failed. Adjust the hyper parameters yourself:)

**Comment by sc1234qwer** [comment]
> @sc1234qwer Train process failed. Adjust the hyper parameters yourself:)

仅仅调超参数就可以嘛   调的时候出现两种情况  一种是只显示左边的   一种是只显示右边的  就是不能全部显示对应上instance_label

**Comment by MaybeShewill-CV** [comment]
@sc1234qwer 这个需要你自己根据数据调整:)

**Comment by sc1234qwer** [comment]
> @sc1234qwer 这个需要你自己根据数据调整:)

如果增加了类别  需要更改discriminative loss么？

**Comment by MaybeShewill-CV** [comment]
@sc1234qwer 不需要:)
