### ISSUE TITLE
you may change input_tensor shape to [None,CFG.TRAIN.IMG_HEIGHT,CFG.TRAIN.IMG_WIDTH, 3] in "train_lanenet.py"

### ISSUE THREAD

**Issue by zacario-li** [MaybeShewill-CV/lanenet-lane-detection#188]
you may change input_tensor shape to [None,CFG.TRAIN.IMG_HEIGHT,CFG.TRAIN.IMG_WIDTH, 3] in "train_lanenet.py"
Cause this is more convenience for prediction

**Comment by MaybeShewill-CV** [comment]
@zacario-li The script is used for training:)
