### ISSUE TITLE
lanet网络问题

### ISSUE THREAD

**Issue by aisichonzi007** [MaybeShewill-CV/lanenet-lane-detection#189]
你好我想咨询下实例分割是在二值的语义分割的结果上进行的，还是不同的两个分支，最后在聚类的时候得到了结合。感觉看论文是前者，看图2是后者，有点糊涂。

**Comment by MaybeShewill-CV** [comment]
@aisichonzi007 不同分支,　二值分割做聚类的掩码.　细节内容可以仔细阅读论文:)

**Comment by aisichonzi007** [comment]
好的 ，多谢

 

发件人: MaybeShewill-CV <notifications@github.com> 
发送时间: 2019年3月27日 10:45
收件人: MaybeShewill-CV/lanenet-lane-detection <lanenet-lane-detection@noreply.github.com>
抄送: aisichonzi007 <zhangchong@chinamobile.com>; Mention <mention@noreply.github.com>
主题: Re: [MaybeShewill-CV/lanenet-lane-detection] lanet网络问题 (#189)

 

@aisichonzi007 <https://github.com/aisichonzi007>  不同分支,　二值分割做聚类的掩码.　细节内容可以仔细阅读论文:)
