### ISSUE TITLE
miss 'semantic_segmentation' in folder 'encoder_decoder_model' ?

### ISSUE THREAD

**Issue by AromaticJ** [MaybeShewill-CV/lanenet-lane-detection#19]
Hi 
I'd like to train lanenet mode on my own dataset, but found something seems wrong in 'train_encoder_deconder.py'
In line 28: 'from encoder_decoder_model import semantic_segmentation'
but no such file in folder 'encoder_decoder_model'
Do you miss something like this?

**Comment by MaybeShewill-CV** [comment]
@AromaticJ The scripts you used is not the lanenet training script you should use train_lanenet.py instead
