### ISSUE TITLE
Training not converge

### ISSUE THREAD

**Issue by eerobert** [MaybeShewill-CV/lanenet-lane-detection#190]
i am using tusimple dataset with --net dense to train
however, train up to 58k epoch still not converge to what you show 
i am still getting total_loss of 1.6-2.1

can you detail out the steps and command how you can coverge the training?

thanks

**Comment by MaybeShewill-CV** [comment]
@eerobert The figure in readme is trained with vgg. If you want to use densenet you'd better find a suitable pretrained weights:)
