### ISSUE TITLE
有关于maskimage结果

### ISSUE THREAD

**Issue by junxiaoge** [MaybeShewill-CV/lanenet-lane-detection#192]
最终的结果maskimage如何区分类别呢

![1553823376(1)](https://user-images.githubusercontent.com/28887820/55205019-1ceead80-520c-11e9-9aba-67856a5bcdd6.png)

**Comment by MaybeShewill-CV** [comment]
@junxiaoge mask image就是两个不同的车道线:)

**Comment by junxiaoge** [comment]
谢谢您的回答 我还有些疑问 也就是说mask image中一种颜色代表一种车道线吗？那么这个颜色如何让与标定的类别进行对应呢?我目前训练了10个类别，我想知道mask image中颜色对应哪一个类别

**Comment by junxiaoge** [comment]
@MaybeShewill-CV 谢谢您的回答我还有些疑问也就是说面具图片中一种颜色代表一种车道线吗？那么这个颜色如何让与标定的类别进行对应呢？我目前训练了10个类别，我想知道mask image中颜色对应哪一个类别

**Comment by junxiaoge** [comment]
@MaybeShewill-CV 谢谢您的回答,我还有些疑问,按照您上面的说法maskimage图片中一种颜色代表一种车道线吗？那么这个颜色如何让与标定的类别进行对应呢？我目前训练了10个类别，我想知道mask image中颜色对应哪一个类别

**Comment by MaybeShewill-CV** [comment]
@junxiaoge 那你需要自己去改代码让颜色和聚类出来的结果一一对应：）

**Comment by junxiaoge** [comment]
@MaybeShewill-CV 好的，谢谢您的回答，我先尝试修改下

**Comment by zhudt0314** [comment]
> @MaybeShewill-CV 好的，谢谢您的回答，我先尝试修改下
你好，看到您在问题中提到利用lanenet进行车道线分类，请问您实现这部分的功能了吗？
问题中提到训练了十个类别，是只需要在输入的groud truth中改正为分类的label就行，还是代码也需要做对应的修改呢？
如果方便的话能否回复一个更方便的联系方式，还有些问题想请教您，谢谢！

**Comment by GChenH** [comment]
您好，请问您实现这个 mask image 用于车道线分类的功能了吗？期待您的回复~
