### ISSUE TITLE
dataset label json

### ISSUE THREAD

**Issue by kkyiss** [MaybeShewill-CV/lanenet-lane-detection#194]
Hello @MaybeShewill-CV

According to TuSimple Label Data Format, it only labels the **20th** frame file to the json

>        {
>          'raw_file': str. 20th frame file path in a clip.
>        }

So how do you get the rest of the frame labels. (ex: 1to19th frame file)
Thanks for any replies!

**Comment by MaybeShewill-CV** [comment]
@kkyiss You may check the Tusimple lane dataset website for details of that:)
