### ISSUE TITLE
Testing on Videos

### ISSUE THREAD

**Issue by ashwin-phadke** [MaybeShewill-CV/lanenet-lane-detection#196]
How does one go about testing this model on videos?

**Comment by MaybeShewill-CV** [comment]
@ashwin-phadke You may capture the frame in your video yourself and put it into the network:)

**Comment by hellosher** [comment]
@ashwin-phadke Have you tested on videos, how is the result, how should I modify the code?

**Comment by ashwin-phadke** [comment]
I am testing it as we speak , I'll probably put a PR if I'm able to complete it soon .

**Comment by MaybeShewill-CV** [comment]
@ashwin-phadke Appreciate it for you to share your testing result with us. Looking forward to it:)

**Comment by hellosher** [comment]
@ashwin-phadke I hope that you can succeed as soon as possible. Appreciate it for you to share your testing result with us.

**Comment by ashwin-phadke** [comment]
@hellosher yes I am surely about to complete it will also update here.

@MaybeShewill-CV : What's the accuracy or expected accuracy you think that comes out from this model? I've hadsome hiccups in the processed video , also had to change the tensor shape to fit to videos, can you shed some light on parameters that can be changed to tweak accuracy.

**Comment by MaybeShewill-CV** [comment]
@ashwin-phadke The performance is related to the data fed into the net. Shouldn't the single frame of the video have the same image size as far as I know. Why does the image size need to be changed per frame? If the image size is the mainly problem that bothers you the multi scale inference may help but it's time consuming

**Comment by ashwin-phadke** [comment]
@MaybeShewill-CV I don't know but the input tensor doesn't accept value of the default one so had to change it to [x, y, w, z] instead of [none, y, w, z].
Thanks for sharing the multi scale inference , I was thinking maybe resizing before feeding it so that it matches to tensor value.
Also how does one go about multi scale inference? any reference you can suggest? that'd be really helpful.

**Comment by MaybeShewill-CV** [comment]
@ashwin-phadke You may feed a image pyramid into the net and merge the binary segmentation and instance segmentation result according to some strategy for example you may collect all the binary segmentation positive prediction result as your final binary segmentation output:)

**Comment by ashwin-phadke** [comment]
Hey @MaybeShewill-CV yeah that's a possibility , let me try it out and get back.

**Comment by ashwin-phadke** [comment]
What is the accuracy that you predict for the pre-trained model included in here?
Note : A PR here is due for videos to be almost ready now.

**Comment by MaybeShewill-CV** [comment]
@ashwin-phadke The trained model in my local machine can reach a mean acc around 94 in tusimple lane test dataset:)

**Comment by ashwin-phadke** [comment]
@MaybeShewill-CV , while final testing I found out that in some cases the bridges and buildings are detected as lanes and the lines just go crisscross on the processed image, can you say something as to what might be causing this. The model being used is the pre-trained model available from the repository.

**Comment by MaybeShewill-CV** [comment]
@ashwin-phadke Maybe you need a more accurate post process to threshold the false predictions.

**Comment by ashwin-phadke** [comment]
maybe `minarea_threshold` parameter ?

**Comment by MaybeShewill-CV** [comment]
@ashwin-phadke That's something I did not push here:)

**Comment by ashwin-phadke** [comment]
@MaybeShewill-CV  : Will check then if that param helps.

**Comment by ashwin-phadke** [comment]
Hey @MaybeShewill-CV , changing the `minarea-threshold` seems to have no effect on the accuracy, can you point out to the specific details of it.

**Comment by MaybeShewill-CV** [comment]
@ashwin-phadke The whole post process is a simple demo.You may need a more accurate post process method:)

**Comment by ashwin-phadke** [comment]
@MaybeShewill-CV thanks for clearing it out.

**Comment by ashwin-phadke** [comment]
@MaybeShewill-CV  : PR Sent #228 

Let us know the results @hellosher .
