### ISSUE TITLE
IPM模块

### ISSUE THREAD

**Issue by hellosher** [MaybeShewill-CV/lanenet-lane-detection#197]
您好，想请问一下，您的这份最新的代码里面有加入您自己的IPM模块吗？

**Comment by MaybeShewill-CV** [comment]
@hellosher 没有：）

**Comment by hellosher** [comment]
那现在程序里面拟合车道线是直接在原图片上进行操作的吗？

**Comment by hellosher** [comment]
那现在程序里面拟合车道线是直接在原图片上进行操作的吗？

**Comment by MaybeShewill-CV** [comment]
@hellosher 对

**Comment by hellosher** [comment]
好的，另外，还有一个问题想咨询您一下，如果将问题定位到雨天场景下检测车道线的话，您觉得可以从哪些方面来考虑改进对图片的处理呢，可以在这个模型的基础上进行哪些改进呢？蟹蟹♪(･ω･)ﾉ

**Comment by MaybeShewill-CV** [comment]
@hellosher 这个一方面从图像增强的方向增加原始图像的可辨识度　另一方面考虑多增加该类别的数据样本看模型是否能够fit．还有就是考虑多传感器融合吧．暂时就想到这些

**Comment by hellosher** [comment]
@MaybeShewill-CV 非常感谢٩('ω')و
