### ISSUE TITLE
测试模型速度过低问题！

### ISSUE THREAD

**Issue by yinhai86924** [MaybeShewill-CV/lanenet-lane-detection#198]
本人用1060显卡，显存6G，用lanenet训练与测试自己的数据集，但每帧图片测试平均时间是0.03s左右，1s才30多帧，不是论文说的50帧以上，有什么办法可以提高测试的速度？ 谢谢！

**Comment by MaybeShewill-CV** [comment]
@yinhai86924 首先看gpu使用率是否达到了100% 如果没有 实现效率更高的data feed pip line，如果gpu使用率达到了100你可以考虑使用论文中使用的gpu进行测试:)

**Comment by yinhai86924** [comment]
谢谢您的回复 我看了测试的时候GPU采利用7%，测试运行结果如下：
I0409 20:02:27.393360 13508 test_lanenet.py:155] 开始获取图像文件路径...
2019-04-09 20:02:30.187034: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-04-09 20:02:31.170888: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1405] Found device 0 with properties: 
name: GeForce GTX 1060 major: 6 minor: 1 memoryClockRate(GHz): 1.733
pciBusID: 0000:01:00.0
totalMemory: 6.00GiB freeMemory: 4.97GiB
2019-04-09 20:02:31.171213: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1484] Adding visible gpu devices: 0
2019-04-09 20:02:31.902007: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-04-09 20:02:31.902187: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:971]      0 
2019-04-09 20:02:31.902301: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:984] 0:   N 
2019-04-09 20:02:31.902502: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4915 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1060, pci bus id: 0000:01:00.0, compute capability: 6.1)
INFO:tensorflow:Restoring parameters from F:/new-Lanenet/lanenet-lane-detection-master/tools/model/tusimple_lanenet/tusimple_lanenet_vgg_2019-02-26-09-21-40.ckpt-48000
I0409 20:02:31.908002 13508 tf_logging.py:115] Restoring parameters from F:/new-Lanenet/lanenet-lane-detection-master/tools/model/tusimple_lanenet/tusimple_lanenet_vgg_2019-02-26-09-21-40.ckpt-48000
I0409 20:02:32.051414 13508 test_lanenet.py:189] [Epoch:0] 开始图像读取和预处理...
I0409 20:02:32.232635 13508 test_lanenet.py:199] [Epoch:0] 预处理2张图像, 共耗时: 0.18122s, 平均每张耗时: 0.09061
2019-04-09 20:02:33.159478: E T:\src\github\tensorflow\tensorflow\stream_executor\cuda\cuda_driver.cc:903] failed to allocate 2.54G (2728604416 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
I0409 20:02:33.854947 13508 test_lanenet.py:206] [Epoch:0] 预测2张图像车道线, 共耗时: 1.62231s, 平均每张耗时: 0.81116s
I0409 20:02:33.956189 13508 test_lanenet.py:236] [Epoch:0] 进行2张图像车道线聚类, 共耗时: 0.05615s, 平均每张耗时: 0.02807
I0409 20:02:33.956189 13508 test_lanenet.py:189] [Epoch:1] 开始图像读取和预处理...
I0409 20:02:34.095589 13508 test_lanenet.py:199] [Epoch:1] 预处理2张图像, 共耗时: 0.13940s, 平均每张耗时: 0.06970
I0409 20:02:34.149703 13508 test_lanenet.py:206] [Epoch:1] 预测2张图像车道线, 共耗时: 0.05411s, 平均每张耗时: 0.02706s
I0409 20:02:34.239943 13508 test_lanenet.py:236] [Epoch:1] 进行2张图像车道线聚类, 共耗时: 0.04512s, 平均每张耗时: 0.02256
I0409 20:02:34.239943 13508 test_lanenet.py:189] [Epoch:2] 开始图像读取和预处理...
I0409 20:02:34.293114 13508 test_lanenet.py:199] [Epoch:2] 预处理2张图像, 共耗时: 0.05317s, 平均每张耗时: 0.02659
I0409 20:02:34.348261 13508 test_lanenet.py:206] [Epoch:2] 预测2张图像车道线, 共耗时: 0.05414s, 平均每张耗时: 0.02707s
I0409 20:02:34.435495 13508 test_lanenet.py:236] [Epoch:2] 进行2张图像车道线聚类, 共耗时: 0.04211s, 平均每张耗时: 0.02106
I0409 20:02:34.435495 13508 test_lanenet.py:189] [Epoch:3] 开始图像读取和预处理...
I0409 20:02:34.472591 13508 test_lanenet.py:199] [Epoch:3] 预处理2张图像, 共耗时: 0.03710s, 平均每张耗时: 0.01855
I0409 20:02:34.527720 13508 test_lanenet.py:206] [Epoch:3] 预测2张图像车道线, 共耗时: 0.05513s, 平均每张耗时: 0.02756s
I0409 20:02:34.610961 13508 test_lanenet.py:236] [Epoch:3] 进行2张图像车道线聚类, 共耗时: 0.03810s, 平均每张耗时: 0.01905
I0409 20:02:34.610961 13508 test_lanenet.py:189] [Epoch:4] 开始图像读取和预处理...
I0409 20:02:34.659088 13508 test_lanenet.py:199] [Epoch:4] 预处理2张图像, 共耗时: 0.04813s, 平均每张耗时: 0.02406
I0409 20:02:34.714206 13508 test_lanenet.py:206] [Epoch:4] 预测2张图像车道线, 共耗时: 0.05411s, 平均每张耗时: 0.02706s
I0409 20:02:34.805480 13508 test_lanenet.py:236] [Epoch:4] 进行2张图像车道线聚类, 共耗时: 0.04513s, 平均每张耗时: 0.02256
I0409 20:02:34.805480 13508 test_lanenet.py:189] [Epoch:5] 开始图像读取和预处理...
I0409 20:02:34.855582 13508 test_lanenet.py:199] [Epoch:5] 预处理2张图像, 共耗时: 0.05010s, 平均每张耗时: 0.02505
I0409 20:02:34.909754 13508 test_lanenet.py:206] [Epoch:5] 预测2张图像车道线, 共耗时: 0.05417s, 平均每张耗时: 0.02709s
I0409 20:02:35.011025 13508 test_lanenet.py:236] [Epoch:5] 进行2张图像车道线聚类, 共耗时: 0.05412s, 平均每张耗时: 0.02706
I0409 20:02:35.011025 13508 test_lanenet.py:189] [Epoch:6] 开始图像读取和预处理...
I0409 20:02:35.062132 13508 test_lanenet.py:199] [Epoch:6] 预处理2张图像, 共耗时: 0.05111s, 平均每张耗时: 0.02555
I0409 20:02:35.117278 13508 test_lanenet.py:206] [Epoch:6] 预测2张图像车道线, 共耗时: 0.05515s, 平均每张耗时: 0.02757s
I0409 20:02:35.229606 13508 test_lanenet.py:236] [Epoch:6] 进行2张图像车道线聚类, 共耗时: 0.06518s, 平均每张耗时: 0.03259
I0409 20:02:35.229606 13508 test_lanenet.py:189] [Epoch:7] 开始图像读取和预处理...
I0409 20:02:35.267707 13508 test_lanenet.py:199] [Epoch:7] 预处理2张图像, 共耗时: 0.03810s, 平均每张耗时: 0.01905
I0409 20:02:35.323829 13508 test_lanenet.py:206] [Epoch:7] 预测2张图像车道线, 共耗时: 0.05612s, 平均每张耗时: 0.02806s
I0409 20:02:35.428134 13508 test_lanenet.py:236] [Epoch:7] 进行2张图像车道线聚类, 共耗时: 0.05817s, 平均每张耗时: 0.02909
I0409 20:02:35.428134 13508 test_lanenet.py:189] [Epoch:8] 开始图像读取和预处理...
I0409 20:02:35.467238 13508 test_lanenet.py:199] [Epoch:8] 预处理2张图像, 共耗时: 0.03910s, 平均每张耗时: 0.01955
I0409 20:02:35.523362 13508 test_lanenet.py:206] [Epoch:8] 预测2张图像车道线, 共耗时: 0.05612s, 平均每张耗时: 0.02806s
I0409 20:02:35.614631 13508 test_lanenet.py:236] [Epoch:8] 进行2张图像车道线聚类, 共耗时: 0.04414s, 平均每张耗时: 0.02207
I0409 20:02:35.614631 13508 test_lanenet.py:189] [Epoch:9] 开始图像读取和预处理...
I0409 20:02:35.664764 13508 test_lanenet.py:199] [Epoch:9] 预处理2张图像, 共耗时: 0.05013s, 平均每张耗时: 0.02507
I0409 20:02:35.719882 13508 test_lanenet.py:206] [Epoch:9] 预测2张图像车道线, 共耗时: 0.05512s, 平均每张耗时: 0.02756s
I0409 20:02:35.839228 13508 test_lanenet.py:236] [Epoch:9] 进行2张图像车道线聚类, 共耗时: 0.07222s, 平均每张耗时: 0.03611
I0409 20:02:35.839228 13508 test_lanenet.py:189] [Epoch:10] 开始图像读取和预处理...
I0409 20:02:35.887356 13508 test_lanenet.py:199] [Epoch:10] 预处理2张图像, 共耗时: 0.04813s, 平均每张耗时: 0.02406
I0409 20:02:35.942475 13508 test_lanenet.py:206] [Epoch:10] 预测2张图像车道线, 共耗时: 0.05512s, 平均每张耗时: 0.02756s
I0409 20:02:36.038759 13508 test_lanenet.py:236] [Epoch:10] 进行2张图像车道线聚类, 共耗时: 0.05013s, 平均每张耗时: 0.02507
I0409 20:02:36.038759 13508 test_lanenet.py:189] [Epoch:11] 开始图像读取和预处理...
I0409 20:02:36.099924 13508 test_lanenet.py:199] [Epoch:11] 预处理2张图像, 共耗时: 0.06116s, 平均每张耗时: 0.03058
I0409 20:02:36.156042 13508 test_lanenet.py:206] [Epoch:11] 预测2张图像车道线, 共耗时: 0.05612s, 平均每张耗时: 0.02806s
I0409 20:02:36.267367 13508 test_lanenet.py:236] [Epoch:11] 进行2张图像车道线聚类, 共耗时: 0.06620s, 平均每张耗时: 0.03310
I0409 20:02:36.268369 13508 test_lanenet.py:189] [Epoch:12] 开始图像读取和预处理...
I0409 20:02:36.302461 13508 test_lanenet.py:199] [Epoch:12] 预处理2张图像, 共耗时: 0.03409s, 平均每张耗时: 0.01705
I0409 20:02:36.357581 13508 test_lanenet.py:206] [Epoch:12] 预测2张图像车道线, 共耗时: 0.05512s, 平均每张耗时: 0.02756s
I0409 20:02:36.451829 13508 test_lanenet.py:236] [Epoch:12] 进行2张图像车道线聚类, 共耗时: 0.05016s, 平均每张耗时: 0.02508
I0409 20:02:36.451829 13508 test_lanenet.py:189] [Epoch:13] 开始图像读取和预处理...
I0409 20:02:36.522045 13508 test_lanenet.py:199] [Epoch:13] 预处理2张图像, 共耗时: 0.07022s, 平均每张耗时: 0.03511
I0409 20:02:36.577192 13508 test_lanenet.py:206] [Epoch:13] 预测2张图像车道线, 共耗时: 0.05414s, 平均每张耗时: 0.02707s
I0409 20:02:36.670439 13508 test_lanenet.py:236] [Epoch:13] 进行2张图像车道线聚类, 共耗时: 0.05013s, 平均每张耗时: 0.02507
I0409 20:02:36.670439 13508 test_lanenet.py:189] [Epoch:14] 开始图像读取和预处理...
I0409 20:02:36.739623 13508 test_lanenet.py:199] [Epoch:14] 预处理2张图像, 共耗时: 0.06918s, 平均每张耗时: 0.03459
I0409 20:02:36.794742 13508 test_lanenet.py:206] [Epoch:14] 预测2张图像车道线, 共耗时: 0.05512s, 平均每张耗时: 0.02756s
I0409 20:02:36.899047 13508 test_lanenet.py:236] [Epoch:14] 进行2张图像车道线聚类, 共耗时: 0.06016s, 平均每张耗时: 0.03008
I0409 20:02:36.899047 13508 test_lanenet.py:189] [Epoch:15] 开始图像读取和预处理...
I0409 20:02:36.946173 13508 test_lanenet.py:199] [Epoch:15] 预处理2张图像, 共耗时: 0.04612s, 平均每张耗时: 0.02306
I0409 20:02:37.001293 13508 test_lanenet.py:206] [Epoch:15] 预测2张图像车道线, 共耗时: 0.05512s, 平均每张耗时: 0.02756s
I0409 20:02:37.083510 13508 test_lanenet.py:236] [Epoch:15] 进行2张图像车道线聚类, 共耗时: 0.03813s, 平均每张耗时: 0.01906
I0409 20:02:37.083510 13508 test_lanenet.py:189] [Epoch:16] 开始图像读取和预处理...
I0409 20:02:37.124648 13508 test_lanenet.py:199] [Epoch:16] 预处理2张图像, 共耗时: 0.04114s, 平均每张耗时: 0.02057
I0409 20:02:37.179767 13508 test_lanenet.py:206] [Epoch:16] 预测2张图像车道线, 共耗时: 0.05512s, 平均每张耗时: 0.02756s
I0409 20:02:37.261012 13508 test_lanenet.py:236] [Epoch:16] 进行2张图像车道线聚类, 共耗时: 0.03612s, 平均每张耗时: 0.01806
I0409 20:02:37.261012 13508 test_lanenet.py:189] [Epoch:17] 开始图像读取和预处理...
I0409 20:02:37.328336 13508 test_lanenet.py:199] [Epoch:17] 预处理2张图像, 共耗时: 0.06632s, 平均每张耗时: 0.03316
I0409 20:02:37.383455 13508 test_lanenet.py:206] [Epoch:17] 预测2张图像车道线, 共耗时: 0.05512s, 平均每张耗时: 0.02756s
I0409 20:02:37.482719 13508 test_lanenet.py:236] [Epoch:17] 进行2张图像车道线聚类, 共耗时: 0.05414s, 平均每张耗时: 0.02707
I0409 20:02:37.482719 13508 test_lanenet.py:189] [Epoch:18] 开始图像读取和预处理...
I0409 20:02:37.558151 13508 test_lanenet.py:199] [Epoch:18] 预处理2张图像, 共耗时: 0.07543s, 平均每张耗时: 0.03772
I0409 20:02:37.613269 13508 test_lanenet.py:206] [Epoch:18] 预测2张图像车道线, 共耗时: 0.05512s, 平均每张耗时: 0.02756s
I0409 20:02:37.715569 13508 test_lanenet.py:236] [Epoch:18] 进行2张图像车道线聚类, 共耗时: 0.05815s, 平均每张耗时: 0.02908
I0409 20:02:37.715569 13508 test_lanenet.py:189] [Epoch:19] 开始图像读取和预处理...
I0409 20:02:37.763753 13508 test_lanenet.py:199] [Epoch:19] 预处理2张图像, 共耗时: 0.04818s, 平均每张耗时: 0.02409
I0409 20:02:37.819878 13508 test_lanenet.py:206] [Epoch:19] 预测2张图像车道线, 共耗时: 0.05512s, 平均每张耗时: 0.02756s
I0409 20:02:37.919142 13508 test_lanenet.py:236] [Epoch:19] 进行2张图像车道线聚类, 共耗时: 0.05317s, 平均每张耗时: 0.02658
I0409 20:02:37.919142 13508 test_lanenet.py:189] [Epoch:20] 开始图像读取和预处理...
I0409 20:02:37.958705 13508 test_lanenet.py:199] [Epoch:20] 预处理2张图像, 共耗时: 0.03956s, 平均每张耗时: 0.01978
I0409 20:02:38.013828 13508 test_lanenet.py:206] [Epoch:20] 预测2张图像车道线, 共耗时: 0.05512s, 平均每张耗时: 0.02756s
I0409 20:02:38.115097 13508 test_lanenet.py:236] [Epoch:20] 进行2张图像车道线聚类, 共耗时: 0.05517s, 平均每张耗时: 0.02759
I0409 20:02:38.115097 13508 test_lanenet.py:189] [Epoch:21] 开始图像读取和预处理...
I0409 20:02:38.159073 13508 test_lanenet.py:199] [Epoch:21] 预处理2张图像, 共耗时: 0.04294s, 平均每张耗时: 0.02147
I0409 20:02:38.213188 13508 test_lanenet.py:206] [Epoch:21] 预测2张图像车道线, 共耗时: 0.05412s, 平均每张耗时: 0.02706s
I0409 20:02:38.341559 13508 test_lanenet.py:236] [Epoch:21] 进行2张图像车道线聚类, 共耗时: 0.08425s, 平均每张耗时: 0.04213
I0409 20:02:38.341559 13508 test_lanenet.py:189] [Epoch:22] 开始图像读取和预处理...
I0409 20:02:38.392642 13508 test_lanenet.py:199] [Epoch:22] 预处理2张图像, 共耗时: 0.05108s, 平均每张耗时: 0.02554
I0409 20:02:38.447801 13508 test_lanenet.py:206] [Epoch:22] 预测2张图像车道线, 共耗时: 0.05516s, 平均每张耗时: 0.02758s
I0409 20:02:38.554073 13508 test_lanenet.py:236] [Epoch:22] 进行2张图像车道线聚类, 共耗时: 0.06116s, 平均每张耗时: 0.03058
I0409 20:02:38.554073 13508 test_lanenet.py:189] [Epoch:23] 开始图像读取和预处理...
I0409 20:02:38.591522 13508 test_lanenet.py:199] [Epoch:23] 预处理2张图像, 共耗时: 0.03745s, 平均每张耗时: 0.01872
I0409 20:02:38.645633 13508 test_lanenet.py:206] [Epoch:23] 预测2张图像车道线, 共耗时: 0.05411s, 平均每张耗时: 0.02706s
I0409 20:02:38.759966 13508 test_lanenet.py:236] [Epoch:23] 进行2张图像车道线聚类, 共耗时: 0.07019s, 平均每张耗时: 0.03509
I0409 20:02:38.759966 13508 test_lanenet.py:189] [Epoch:24] 开始图像读取和预处理...
I0409 20:02:38.798122 13508 test_lanenet.py:199] [Epoch:24] 预处理2张图像, 共耗时: 0.03816s, 平均每张耗时: 0.01908
I0409 20:02:38.854247 13508 test_lanenet.py:206] [Epoch:24] 预测2张图像车道线, 共耗时: 0.05612s, 平均每张耗时: 0.02806s
I0409 20:02:38.970607 13508 test_lanenet.py:236] [Epoch:24] 进行2张图像车道线聚类, 共耗时: 0.07216s, 平均每张耗时: 0.03608
I0409 20:02:38.970607 13508 test_lanenet.py:189] [Epoch:25] 开始图像读取和预处理...
I0409 20:02:39.023586 13508 test_lanenet.py:199] [Epoch:25] 预处理2张图像, 共耗时: 0.05298s, 平均每张耗时: 0.02649
I0409 20:02:39.078733 13508 test_lanenet.py:206] [Epoch:25] 预测2张图像车道线, 共耗时: 0.05414s, 平均每张耗时: 0.02707s
I0409 20:02:39.170005 13508 test_lanenet.py:236] [Epoch:25] 进行2张图像车道线聚类, 共耗时: 0.04615s, 平均每张耗时: 0.02308
I0409 20:02:39.170005 13508 test_lanenet.py:189] [Epoch:26] 开始图像读取和预处理...
I0409 20:02:39.258668 13508 test_lanenet.py:199] [Epoch:26] 预处理2张图像, 共耗时: 0.08866s, 平均每张耗时: 0.04433
I0409 20:02:39.312809 13508 test_lanenet.py:206] [Epoch:26] 预测2张图像车道线, 共耗时: 0.05414s, 平均每张耗时: 0.02707s
I0409 20:02:39.410071 13508 test_lanenet.py:236] [Epoch:26] 进行2张图像车道线聚类, 共耗时: 0.05216s, 平均每张耗时: 0.02608
I0409 20:02:39.410071 13508 test_lanenet.py:189] [Epoch:27] 开始图像读取和预处理...
I0409 20:02:39.457681 13508 test_lanenet.py:199] [Epoch:27] 预处理2张图像, 共耗时: 0.04761s, 平均每张耗时: 0.02380
I0409 20:02:39.512829 13508 test_lanenet.py:206] [Epoch:27] 预测2张图像车道线, 共耗时: 0.05515s, 平均每张耗时: 0.02757s
I0409 20:02:39.628135 13508 test_lanenet.py:236] [Epoch:27] 进行2张图像车道线聚类, 共耗时: 0.06818s, 平均每张耗时: 0.03409
I0409 20:02:39.628135 13508 test_lanenet.py:189] [Epoch:28] 开始图像读取和预处理...
I0409 20:02:39.712212 13508 test_lanenet.py:199] [Epoch:28] 预处理2张图像, 共耗时: 0.08408s, 平均每张耗时: 0.04204
I0409 20:02:39.767359 13508 test_lanenet.py:206] [Epoch:28] 预测2张图像车道线, 共耗时: 0.05414s, 平均每张耗时: 0.02707s
I0409 20:02:39.886676 13508 test_lanenet.py:236] [Epoch:28] 进行2张图像车道线聚类, 共耗时: 0.06718s, 平均每张耗时: 0.03359
I0409 20:02:39.886676 13508 test_lanenet.py:189] [Epoch:29] 开始图像读取和预处理...
I0409 20:02:39.954859 13508 test_lanenet.py:199] [Epoch:29] 预处理2张图像, 共耗时: 0.06818s, 平均每张耗时: 0.03409
I0409 20:02:40.012010 13508 test_lanenet.py:206] [Epoch:29] 预测2张图像车道线, 共耗时: 0.05715s, 平均每张耗时: 0.02858s
I0409 20:02:40.126453 13508 test_lanenet.py:236] [Epoch:29] 进行2张图像车道线聚类, 共耗时: 0.05214s, 平均每张耗时: 0.02607
I0409 20:02:40.126453 13508 test_lanenet.py:189] [Epoch:30] 开始图像读取和预处理...
I0409 20:02:40.178592 13508 test_lanenet.py:199] [Epoch:30] 预处理2张图像, 共耗时: 0.05214s, 平均每张耗时: 0.02607
I0409 20:02:40.236747 13508 test_lanenet.py:206] [Epoch:30] 预测2张图像车道线, 共耗时: 0.05715s, 平均每张耗时: 0.02858s
I0409 20:02:40.324981 13508 test_lanenet.py:236] [Epoch:30] 进行2张图像车道线聚类, 共耗时: 0.04111s, 平均每张耗时: 0.02056
I0409 20:02:40.324981 13508 test_lanenet.py:189] [Epoch:31] 开始图像读取和预处理...
I0409 20:02:40.384908 13508 test_lanenet.py:199] [Epoch:31] 预处理2张图像, 共耗时: 0.05993s, 平均每张耗时: 0.02996
I0409 20:02:40.441025 13508 test_lanenet.py:206] [Epoch:31] 预测2张图像车道线, 共耗时: 0.05612s, 平均每张耗时: 0.02806s
I0409 20:02:40.549314 13508 test_lanenet.py:236] [Epoch:31] 进行2张图像车道线聚类, 共耗时: 0.05612s, 平均每张耗时: 0.02806
I0409 20:02:40.549314 13508 test_lanenet.py:189] [Epoch:32] 开始图像读取和预处理...
I0409 20:02:40.623512 13508 test_lanenet.py:199] [Epoch:32] 预处理2张图像, 共耗时: 0.07420s, 平均每张耗时: 0.03710
I0409 20:02:40.685676 13508 test_lanenet.py:206] [Epoch:32] 预测2张图像车道线, 共耗时: 0.06216s, 平均每张耗时: 0.03108s
I0409 20:02:40.847108 13508 test_lanenet.py:236] [Epoch:32] 进行2张图像车道线聚类, 共耗时: 0.05715s, 平均每张耗时: 0.02858
I0409 20:02:40.847108 13508 test_lanenet.py:189] [Epoch:33] 开始图像读取和预处理...
I0409 20:02:40.988482 13508 test_lanenet.py:199] [Epoch:33] 预处理2张图像, 共耗时: 0.14137s, 平均每张耗时: 0.07069
I0409 20:02:41.048642 13508 test_lanenet.py:206] [Epoch:33] 预测2张图像车道线, 共耗时: 0.06016s, 平均每张耗时: 0.03008s
I0409 20:02:41.154954 13508 test_lanenet.py:236] [Epoch:33] 进行2张图像车道线聚类, 共耗时: 0.05819s, 平均每张耗时: 0.02910
I0409 20:02:41.155955 13508 test_lanenet.py:189] [Epoch:34] 开始图像读取和预处理...
I0409 20:02:41.206108 13508 test_lanenet.py:199] [Epoch:34] 预处理2张图像, 共耗时: 0.05015s, 平均每张耗时: 0.02508
I0409 20:02:41.265280 13508 test_lanenet.py:206] [Epoch:34] 预测2张图像车道线, 共耗时: 0.05917s, 平均每张耗时: 0.02959s
I0409 20:02:41.361543 13508 test_lanenet.py:236] [Epoch:34] 进行2张图像车道线聚类, 共耗时: 0.04815s, 平均每张耗时: 0.02407
I0409 20:02:41.361543 13508 test_lanenet.py:189] [Epoch:35] 开始图像读取和预处理...
I0409 20:02:41.403638 13508 test_lanenet.py:199] [Epoch:35] 预处理2张图像, 共耗时: 0.04210s, 平均每张耗时: 0.02105
I0409 20:02:41.463798 13508 test_lanenet.py:206] [Epoch:35] 预测2张图像车道线, 共耗时: 0.06016s, 平均每张耗时: 0.03008s
I0409 20:02:41.548023 13508 test_lanenet.py:236] [Epoch:35] 进行2张图像车道线聚类, 共耗时: 0.03613s, 平均每张耗时: 0.01806
I0409 20:02:41.548023 13508 test_lanenet.py:189] [Epoch:36] 开始图像读取和预处理...
I0409 20:02:41.629521 13508 test_lanenet.py:199] [Epoch:36] 预处理2张图像, 共耗时: 0.08150s, 平均每张耗时: 0.04075
I0409 20:02:41.688649 13508 test_lanenet.py:206] [Epoch:36] 预测2张图像车道线, 共耗时: 0.05913s, 平均每张耗时: 0.02956s
I0409 20:02:41.832062 13508 test_lanenet.py:236] [Epoch:36] 进行2张图像车道线聚类, 共耗时: 0.09531s, 平均每张耗时: 0.04765
I0409 20:02:41.832062 13508 test_lanenet.py:189] [Epoch:37] 开始图像读取和预处理...
I0409 20:02:41.872166 13508 test_lanenet.py:199] [Epoch:37] 预处理2张图像, 共耗时: 0.04010s, 平均每张耗时: 0.02005
I0409 20:02:41.931294 13508 test_lanenet.py:206] [Epoch:37] 预测2张图像车道线, 共耗时: 0.05913s, 平均每张耗时: 0.02956s
I0409 20:02:42.012540 13508 test_lanenet.py:236] [Epoch:37] 进行2张图像车道线聚类, 共耗时: 0.03509s, 平均每张耗时: 0.01755
I0409 20:02:42.012540 13508 test_lanenet.py:189] [Epoch:38] 开始图像读取和预处理...
I0409 20:02:42.064390 13508 test_lanenet.py:199] [Epoch:38] 预处理2张图像, 共耗时: 0.05185s, 平均每张耗时: 0.02593
I0409 20:02:42.124522 13508 test_lanenet.py:206] [Epoch:38] 预测2张图像车道线, 共耗时: 0.05913s, 平均每张耗时: 0.02956s
I0409 20:02:42.220955 13508 test_lanenet.py:236] [Epoch:38] 进行2张图像车道线聚类, 共耗时: 0.03512s, 平均每张耗时: 0.01756
I0409 20:02:42.220955 13508 test_lanenet.py:189] [Epoch:39] 开始图像读取和预处理...
I0409 20:02:42.298160 13508 test_lanenet.py:199] [Epoch:39] 预处理2张图像, 共耗时: 0.07721s, 平均每张耗时: 0.03860
I0409 20:02:42.358328 13508 test_lanenet.py:206] [Epoch:39] 预测2张图像车道线, 共耗时: 0.05916s, 平均每张耗时: 0.02958s
I0409 20:02:42.436528 13508 test_lanenet.py:236] [Epoch:39] 进行2张图像车道线聚类, 共耗时: 0.02810s, 平均每张耗时: 0.01405
I0409 20:02:42.436528 13508 test_lanenet.py:189] [Epoch:40] 开始图像读取和预处理...
I0409 20:02:42.458887 13508 test_lanenet.py:199] [Epoch:40] 预处理1张图像, 共耗时: 0.02136s, 平均每张耗时: 0.02136
I0409 20:02:43.065484 13508 test_lanenet.py:206] [Epoch:40] 预测1张图像车道线, 共耗时: 0.60660s, 平均每张耗时: 0.60660s
I0409 20:02:43.100593 13508 test_lanenet.py:236] [Epoch:40] 进行1张图像车道线聚类, 共耗时: 0.01004s, 平均每张耗时: 0.01004
上面我不是很明白，一张图片处理完到底是怎么算的总时间，是不是等于预测处理一张图像+预测一张车道线+进行一张车道线聚类 ，那么这样的话，测试一张图片时间更长了！有点困惑，谢谢您的答复！

**Comment by MaybeShewill-CV** [comment]
@yinhai86924 是的 聚类和图像预处理比较费时:)

**Comment by yinhai86924** [comment]
> @yinhai86924 是的 聚类和图像预处理比较费时:)

论文说每帧图片能够达到50帧以上，然而我测试时候每帧都要0.06s 我观测到测试时候GPU才利用7%，速度慢是不是出在这个问题上。

**Comment by yinhai86924** [comment]
论文说每帧图片能够达到50帧以上，然而我测试时候每帧都要0.06s 我观测到测试时候GPU才利用7%，速度慢是不是出在这个问题上。可能要data feed pip line？

**Comment by MaybeShewill-CV** [comment]
@yinhai86924 GPU使用率低说明ＧＰＵ一直在等待数据传入，所以需要你实现更有效的数据传入方法．然后需要你自己实现效率更高的聚类方法应为这个过程比较耗时．还有就是换一个好的显卡，１０６０太老了：）
