### ISSUE TITLE
请问只用二分类分割提取车道线是否可行，实际项目中能这样用吗？

### ISSUE THREAD

**Issue by 92ypli** [MaybeShewill-CV/lanenet-lane-detection#199]

**Comment by MaybeShewill-CV** [comment]
@92ypli 二分类可以，这样你就不需要instance segmentation分支.实际项目可以自己尝试:)

**Comment by 92ypli** [comment]
因为刚接触车道线，所以再请较下后处理问题，就是分割得到车道线后，怎么利用分割结果提取车道线？

**Comment by MaybeShewill-CV** [comment]
@92ypli 你得到分割结果后 需要进行车道线拟合:)

**Comment by yinhai86924** [comment]
直接用二值分割，还需要对车道线聚类吗 还是要通过每条车道线聚类，然后再做拟合？谢谢！
