### ISSUE TITLE
accuracy较低问题

### ISSUE THREAD

**Issue by hellosher** [MaybeShewill-CV/lanenet-lane-detection#204]
按照代码中给出的参数，使用Tusimple数据集进行训练，在训练了几万个epoch之后，准确率都没有超过0.7，请问这可能是哪方面的问题呢，需要怎么调整呢？

**Comment by MaybeShewill-CV** [comment]
@hellosher １．检查样本是否正确 2.数据增强 3.调节学习率等超参数
