### ISSUE TITLE
评估指标

### ISSUE THREAD

**Issue by hellosher** [MaybeShewill-CV/lanenet-lane-detection#205]
您好，冒昧问一下，结果的评估指标是什么呢，训练过程中的准确率指的是什么呢，非常感谢

**Comment by MaybeShewill-CV** [comment]
@hellosher 可以参照train_net.py文件中的100~109行, accuracy = correct_prediction / prediction_total_count

**Comment by MaybeShewill-CV** [comment]
@hellosher 可以参照train_net.py文件中的100~109行, accuracy = correct_prediction / ground_truth_nums

**Comment by yinhai86924** [comment]
> @hellosher 可以参照train_net.py文件中的100~109行, accuracy = correct_prediction / ground_truth_nums
您好，语义分割的评价指标 具体是怎么算的   miou吗 还是 其他指标  还有一个问题， 文中指的每帧能到60FPS， 没有包括后处理聚类哪些嘛  还是只有inference？

**Comment by yinhai86924** [comment]
您好，语义分割的评价指标 具体是怎么算的 miou吗 还是 其他指标 还有一个问题， 文中指的每帧能到60FPS， 没有包括后处理聚类哪些嘛 还是只有inference？
