### ISSUE TITLE
请教一下 用CUlane数据集如何转换成图森格式的数据集？ 用于训练lanenet网络

### ISSUE THREAD

**Issue by yinhai86924** [MaybeShewill-CV/lanenet-lane-detection#206]
CUlane数据集好像没有实例分割标签，请各位大佬能够分享一下转换代码？

**Comment by MaybeShewill-CV** [comment]
@yinhai86924 这个你自己转换一下就好了 很容易:)

**Comment by yinhai86924** [comment]
我看了CUlane数据集 很图森的一点都不一样 ，如下是标注text文件中的内容
-20.5165 500 15.3997 490 50.0491 480 85.661 470 121.273 460 156.885 450 192.497 440 228.108 430 263.72 420 298.718 410 334.33 400 369.942 390 405.554 380 440.203 370 475.815 360 511.427 350 547.039 340 
331 590 345.832 580 359.839 570 374.671 560 389.502 550 403.51 540 418.341 530 433.173 520 447.181 510 462.012 500 476.02 490 490.851 480 505.683 470 519.828 460 534.66 450 549.492 440 563.499 430 578.331 420 593.162 410 607.17 400 622.001 390 636.009 380 650.841 370 665.672 360 679.68 350 694.511 340 
1284.33 590 1268.26 580 1253.04 570 1236.98 560 1220.91 550 1204.84 540 1189.62 530 1173.56 520 1157.49 510 1141.42 500 1126.2 490 1110.14 480 1094.07 470 1078.13 460 1062.91 450 1046.84 440 1030.77 430 1014.71 420 999.488 410 983.422 400 967.355 390 951.289 380 936.069 370 920.002 360 903.936 350 888.715 340 
1640 430 1587.83 420 1531.73 410 1476.61 400 1420.51 390 1365.2 380 1309.1 370 1253.98 360 1197.88 350 1142.76 340 

上面点的坐标已经超出了原图像，且存在负数，改写图森特别麻烦！-20.5165 500 这个点就是负数 怎么处理呢

**Comment by MaybeShewill-CV** [comment]
@yinhai86924 这个你自己转一下吧 不难的:)

**Comment by yinhai86924** [comment]
自己写了代码，终于搞定了！谢谢您哈
![0001](https://user-images.githubusercontent.com/45553479/57756933-f4246800-7726-11e9-92b5-2b1e7ffe34d3.png)
![0001](https://user-images.githubusercontent.com/45553479/57756947-f8508580-7726-11e9-804b-86355ffea530.png)
![0001](https://user-images.githubusercontent.com/45553479/57756959-fc7ca300-7726-11e9-85a7-df7cfee65c56.png)

**Comment by MaybeShewill-CV** [comment]
@yinhai86924 赞～

**Comment by zhangyuelong** [comment]
> 自己写了代码，终于搞定了！谢谢您哈
> ![0001](https://user-images.githubusercontent.com/45553479/57756933-f4246800-7726-11e9-92b5-2b1e7ffe34d3.png)
> ![0001](https://user-images.githubusercontent.com/45553479/57756947-f8508580-7726-11e9-804b-86355ffea530.png)
> ![0001](https://user-images.githubusercontent.com/45553479/57756959-fc7ca300-7726-11e9-85a7-df7cfee65c56.png)

您好，您能提供一下转化脚本吗？我也想用CULane数据集跑laneNet

**Comment by TommyTang930** [comment]
@yinhai86924 
@zhangyuelong 
您好，请问可否分享一下CULane数据集转成TuSimple数据集的代码呢？非常感谢各位大佬们 ～

**Comment by 850977164** [comment]
@yinhai86924 @zhangyuelong 
Can you share the code CULane converted into the TuSimple dataset?Thank you very much

**Comment by jiguanglu** [comment]
> 自己写了代码，终于搞定了！谢谢您哈
> ![0001](https://user-images.githubusercontent.com/45553479/57756933-f4246800-7726-11e9-92b5-2b1e7ffe34d3.png)
> ![0001](https://user-images.githubusercontent.com/45553479/57756947-f8508580-7726-11e9-804b-86355ffea530.png)
> ![0001](https://user-images.githubusercontent.com/45553479/57756959-fc7ca300-7726-11e9-85a7-df7cfee65c56.png)
帅哥，求一份转化数据集的代码。。。
