### ISSUE TITLE
Question about VGG16 weights

### ISSUE THREAD

**Issue by david-bernstein** [MaybeShewill-CV/lanenet-lane-detection#207]
Hi, I have a question about the training, in particular if I run the training script with --net vgg are the VGG weights frozen during training or are they updated by the optimizer? If they're frozen what part of the code controls that?

Thanks,
Dave

**Comment by MaybeShewill-CV** [comment]
@david-bernstein The weights are updated during training process:)

**Comment by david-bernstein** [comment]
Ok, thanks for the quick response!
