### ISSUE TITLE
Getting the inference graph

### ISSUE THREAD

**Issue by jackofall96** [MaybeShewill-CV/lanenet-lane-detection#208]
I tried to obtain the inference graph on terminal in the following way:

`python -m tensorflow.python.tools.optimize_for_inference --input '/frozen_graph.pb' --output '/optimized_inference.pb' --input_names 'input_tensor,net_phase' --output_names 'lanenet_model/inference/decode/score_final/score_final,lanenet_model/pix_embedding_relu' --placeholder_type_enum '1,7'`

Tried to load the model in the following way:

```
with tf.gfile.GFile('/optimized_inference.pb', "rb") as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())

with tf.Graph().as_default() as graph:
    tf.import_graph_def(graph_def, name="")
```

I get the following error:

5 with tf.Graph().as_default() as graph:
----> 6     tf.import_graph_def(graph_def, name="")

~/anaconda3/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py in new_func(*args, **kwargs)
    505                 'in a future version' if date is None else ('after %s' % date),
    506                 instructions)
--> 507       return func(*args, **kwargs)
    508 
    509     doc = _add_deprecated_arg_notice_to_docstring(

~/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/importer.py in import_graph_def(graph_def, input_map, return_elements, name, op_dict, producer_op_list)
    428       except errors.InvalidArgumentError as e:
    429         # Convert to ValueError for backwards compatibility.
--> 430         raise ValueError(str(e))
    431 
    432     # Create _DefinedFunctions for any imported functions.

ValueError: NodeDef expected inputs '' do not match 1 inputs specified; Op<name=Const; signature= -> output:dtype; attr=value:tensor; attr=dtype:type>; NodeDef: {{node lanenet_model/inference/encode/conv1_1/bn/cond/Const}}

**Comment by MaybeShewill-CV** [comment]
@jackofall96 I think you may use the tensorFlow saved model for inference and you may convert the ckpt model weights into tf saved model. I will release a tf saved model in the future:)
