### ISSUE TITLE
train_instance_seg_loss感觉不收敛

### ISSUE THREAD

**Issue by hellosher** [MaybeShewill-CV/lanenet-lane-detection#209]
您好，我在训练了80000多个epoch，train_accuracy达到了90%以上，但是val_accuracy不到60%且波动较大，而且train_instance_seg_loss震荡幅度很大，使用的都是代码里的参数没有修改，出现这种情况是正常的吗，值得继续训练吗还是需要怎样调整呢？

**Comment by MaybeShewill-CV** [comment]
@hellosher 这种情况需要你调参数,正常情况train和val都可以达到90以上:)

**Comment by MaybeShewill-CV** [comment]
@hellosher eg.
/home/baidu/Desktop/1.png

**Comment by MaybeShewill-CV** [comment]
@hellosher 这种情况需要你调参数,正常情况train和val都可以达到90以上:)
![1](https://user-images.githubusercontent.com/15725187/57222744-459d6a80-7036-11e9-99e4-4fa587d6f2b9.png)

**Comment by hellosher** [comment]
@MaybeShewill-CV  调整学习率等超参数吗，请问您在参数调整方面有什么指导吗？

**Comment by MaybeShewill-CV** [comment]
@hellosher 经验就是多实验 hh

**Comment by hellosher** [comment]
@MaybeShewill-CV您就是使用的给出代码中的参数吗，为什么您的结果这么平稳呢，包括训练部分我也是这样，60000多个epoch之后准确率才刚到达90%，val_accuracy更是波动非常大

**Comment by MaybeShewill-CV** [comment]
@hellosher 这个图用的参数和模型我进行了一定的修改和现在上传的repo不是完全一致,不过现在这个repo也完全可以达到这个效果,可能需要你自己多实验调整了．也欢迎你分享调整的经验和结果：）

**Comment by hellosher** [comment]
@MaybeShewill-CV ok!!!

**Comment by hellosher** [comment]
@MaybeShewill-CV 博主，有个问题想咨询你一下啊，如果我按照图森的这种方法标注了一些雨天或者夜间的数据，能用Lanenent论文的模型结构得到一个还可以的效果吗，就是这个论文的模型，你觉得它在雨天/夜间的检测还能适用吗，鲁棒吗，或者您觉得有哪些比较新的成果可以使用吗，非常感谢您了^_^?

**Comment by MaybeShewill-CV** [comment]
@hellosher 这个你可以自己实验下:)
