### ISSUE TITLE
Bus error (core dump)

### ISSUE THREAD

**Issue by weweus** [MaybeShewill-CV/lanenet-lane-detection#210]
调用了 python /root/lanenet-lane-detection/tools/test_lanenet.py --is_batch False --batch_size 1 --weights_path /root/lanenet-lane-detection/model/tusimple_lanenet/tusimple_lanenet_vgg_2018-10-19-13-33-56.ckpt-200000.meta --image_path /root/lanenet-lane-detection/data/tusimple_test_image/0.jpg
但报错Bus error (core dump)，请问这是因为我的磁盘满了的原因么？

**Comment by MaybeShewill-CV** [comment]
@weweus 这个不太清楚, 你可以百度一下:)

**Comment by weweus** [comment]
这个错误原因比较广，我是因为硬盘空间不够导致的，所以找了空间重新安装，就没再报这个错了

**Comment by MaybeShewill-CV** [comment]
@weweus 解决了就好 也感谢分享：）
