### ISSUE TITLE
some variables are not used in global_config.py

### ISSUE THREAD

**Issue by zoeveryday** [MaybeShewill-CV/lanenet-lane-detection#213]
Thanks for the awesome project!

One question regarding the training configs. Are the following variables used for the training? I couldn't find them been used in your code. If not used, does this mean the `LEARNING_RATE` is always set to 0.0005 for all epochs?

```
# Set the learning rate decay steps
__C.TRAIN.LR_DECAY_STEPS = 410000
# Set the learning rate decay rate
__C.TRAIN.LR_DECAY_RATE = 0.1
```

Thanks in advance.

**Comment by MaybeShewill-CV** [comment]
@zoeveryday Yep not all the vars in config is used:)
