### ISSUE TITLE
这种情况是什么原因造成？

### ISSUE THREAD

**Issue by yinhai86924** [MaybeShewill-CV/lanenet-lane-detection#214]
![QQ截图20190510195749](https://user-images.githubusercontent.com/45553479/57525687-ebfeae00-735d-11e9-88bd-97bbbaf7a855.jpg)
![1812](https://user-images.githubusercontent.com/45553479/57526504-22d5c380-7360-11e9-9b6e-b24674f693d2.jpg)

经过训练，准确率达到93左右，但测试出现问题，前面几帧正常，突然出现这种情况 连续的几帧。需要调整哪些网络参数，多出现几条浅蓝色车道线 原因？

**Comment by MaybeShewill-CV** [comment]
@yinhai86924 需要调整的就是聚类那里的参数 关于dbscan和meanshift你可以看sklearn的相关文档.然后也可以通过后处理的时候截断最远端的输出认为最远端的输出不可靠:)

**Comment by yinhai86924** [comment]
好的！我查看一下聚类，还想请教你一个问题 如图：
![QQ截图20190510204347](https://user-images.githubusercontent.com/45553479/57528339-b01b1700-7364-11e9-8a33-3789b329f99f.jpg)
![QQ截图20190510204436](https://user-images.githubusercontent.com/45553479/57528340-b01b1700-7364-11e9-87bf-36e7a7eb93ae.jpg)
这是我设置的训练参数，学习率0.00005， batch_size为4，我是分布训练的 总共训练了7万左右eporchs，但是训练时候发现准确率波动太大，验证精度也一样 才83左右，是否还可以进一步增加训练总次数，提高验证精度？这应该不是训练最好的权重参数，我认为是导致测试出现问题的一部分原因吧， 后处理也有一定原因， 我可以这样理解吗？

**Comment by MaybeShewill-CV** [comment]
@yinhai86924 你可以试试:)

**Comment by yinhai86924** [comment]
> @yinhai86924 你可以试试:)

问一个基础知识，从训练集里面选出来的验证集 是不参与训练吧?

**Comment by yinhai86924** [comment]
谢谢你！ 我试试 问一个基础知识，从训练集里面选出来的验证集 是不参与训练吧?

**Comment by MaybeShewill-CV** [comment]
@yinhai86924 是的 而且感觉你的学习率设置的太小了 可以尝试大一点的值:)

**Comment by yinhai86924** [comment]
因为发现训练精度波动较大，我设置小了学习率，设置大点可能波动厉害！对结果有没有影响？

**Comment by MaybeShewill-CV** [comment]
@yinhai86924 大学习率可以配合adam优化方法 一般会收敛的比SGD快速但是一般来说没有精细调参的SGD泛化能力强。多自己实验吧：）

**Comment by yinhai86924** [comment]
好的！ 谢谢了！ 想请问一下，提高语义分割效率，还可以考虑哪些方法？

**Comment by MaybeShewill-CV** [comment]
@yinhai86924 有这时间 多看论文吧:)

**Comment by yinhai86924** [comment]
打算用CUlane数据集来训练Lanenet网络，主要问题在于 您的训练集与验证集 设置的数量比例 一般为多少？

**Comment by hellosher** [comment]
@yinhai86924 想问一下，您用mobilenet v2替换基础网络成功了了吗，训练的模型有变小吗^_^

**Comment by TommyTang930** [comment]
@yinhai86924 
请问是否还在研究LaneNet呢？可否加Q？有几个问题，向大佬请教一下～
