### ISSUE TITLE
Paper Sources

### ISSUE THREAD

**Issue by LukasProgram** [MaybeShewill-CV/lanenet-lane-detection#215]
Hi @MaybeShewill-CV 

I used your network and train my own data on it. It worked pretty well. Now I want some more information about LaneNet. I found a paper from Ze Wang, Weiqiang Ren, and Qiang Qiu -> "LaneNet: Real-Time Lane Detection Networks for Autonomous Driving" is it the same LaneNet, or is it related to the LaneNet described in "Towards End-to-End Lane Detection: an Instance Segmentation Approach"? 

Can you help me to understand it because I want to know how it works?  They are a lot of LaneNet papers but I cannot distinguish between the LaneNet used in your Implementation from the other LaneNet described in other papers.

I want to cite your work and I thank you in advance for any answer.

**Comment by MaybeShewill-CV** [comment]
@LukasProgram The repo implements the paper "Towards End-to-End Lane Detection: an Instance Segmentation Approach". As for method details you may refer to the paper for details:). Btw could you please share some test result on your own dataset here if possible? :)

**Comment by LukasProgram** [comment]
Hi @MaybeShewill-CV  
I can share the results from tensorboard if you want. I also did the validation step.

I am trying now to run the model on a smartphone, so I need to run the python3 export_inference_graph.py \
    --input_type
    --pipeline_config_path 
    --trained_checkpoint_prefix 
    --output_directory 

I don't know what argument should I use for pipeline_config_path. Can you help me?

**Comment by MaybeShewill-CV** [comment]
@LukasProgram Sorry I do not know what is it:)

**Comment by MaybeShewill-CV** [comment]
@LukasProgram Sorry I do not know what it is:)

**Comment by LukasProgram** [comment]
Ok, and what output nodes have the model or graph?

I try to run the script in 
https://stackoverflow.com/questions/45864363/tensorflow-how-to-convert-meta-data-and-index-model-files-into-one-graph-pb

**Comment by MaybeShewill-CV** [comment]
@LukasProgram You may find the node you need in the LaneNet model script:)

**Comment by LukasProgram** [comment]
@MaybeShewill-CV i think the name of the input node is "input_tensor" and the output node is "lanenet_model" am I right ?

**Comment by MaybeShewill-CV** [comment]
@LukasProgram No you may print all the variable in the compute graph and select what you need by yourself:)

**Comment by mbrv** [comment]
@LukasProgram Hi ,

You mentioned your trying to run the code on a smartphone but the reported run-time on NVIDIA 1080 TI is 52 FPS which sounds not very "mobile" friendly. can you elaborate how you plan to use this network on a mobile platform ?

**Comment by MasschineeMe** [comment]
@mbrv 
 I am trying also to run the network on a mobile phone. 
After I get the values from the output nodes I need to make the clustering in android. I don't know how the performance will be but let's find out.

Do you have experience with the integration of a network in Android? Do you think it will perform badly?
