### ISSUE TITLE
How can I test it with cpu?

### ISSUE THREAD

**Issue by JWei-D** [MaybeShewill-CV/lanenet-lane-detection#217]
When I set the use_gpu to 0, I get an error like this:(test an image)
tensorflow.python.framework.errors_impl.NotFoundError: No CPU devices are available in this process

**Comment by JWei-D** [comment]
if use_gpu:
        sess_config = tf.ConfigProto(device_count={'GPU': 1})
    else:
        sess_config = tf.ConfigProto(device_count={'CPU': 0})
I think it‘s ’GPU‘ instead of ’CPU'?

**Comment by MaybeShewill-CV** [comment]
@JWei-D Sorry only gpu support now. You may change the code yourself if you want to use cpu:)

**Comment by ashwin-phadke** [comment]
It works on CPU and GPU both for me though.

**Comment by MaybeShewill-CV** [comment]
@JWei-D You may ask @ashwin-phadke  for help:)
