### ISSUE TITLE
Missing ckpt.data on new model weights 

### ISSUE THREAD

**Issue by gmbonini** [MaybeShewill-CV/lanenet-lane-detection#219]
Hi, thanks for sharing the code. I was trying to load the model weights and was getting the error:
./model/tusimple_lanenet_vgg/tusimple_lanenet.ckpt.data-00000-of-00001; No such file or directory
which really is missing from the new download link, I believe that the .data is necessary to load the model weights. Can you please check it? 
Thanks

**Comment by TaeHoonKK** [comment]
me too, and this problem happens when i trained the model too,

**Comment by hicaonmb** [comment]
rename tusimple_lanenet.ckpt to tusimple_lanenet.ckpt.data-00000-of-00001

**Comment by gmbonini** [comment]
That worked thanks!

**Comment by MaybeShewill-CV** [comment]
@gmbonini It's my bad. I've pushed the wrong weights file and I have corrected it and you may test it again:)
