### ISSUE TITLE
output nodes

### ISSUE THREAD

**Issue by klnsz** [MaybeShewill-CV/lanenet-lane-detection#22]
Hi, I am trying the convert the model into frozen graph. But i could not found the output node names on the internet or the paper. Can you help me to find it?

**Comment by MaybeShewill-CV** [comment]
@klnsz You can check the code for details

**Comment by jackofall96** [comment]
> Found it. thank you

Are the input and output nodes the following?

input nodes = 'input_tensor', 'net_phase'
output nodes = 'lanenet_model/inference/decode/score_final/score_final', 'lanenet_model/pix_embedding_relu'

**Comment by zhangyuelong** [comment]
> Found it. thank you

can you share your found results about the output nodes about lanenet for tensorflowslite's tflite

**Comment by jackofall96** [comment]
> > Found it. thank you
> 
> can you share your found results about the output nodes about lanenet for tensorflowslite's tflite

Load checkpoints into test_lanenet.py and inside the session, convert it into a frozen graph.
Save the graph as a .pb file.
Then you can try the following and see if it works:
input nodes = 'input_tensor'
output nodes = 'lanenet_model/pix_embedding_relu' (binary branch output);
                           'lanenet_model/ArgMax' (instance branch output to be used for clustering)

**Comment by ArtlyStyles** [comment]
@klnsz I want to convert it to freeze_graph as well so I can change it to uff. Could you please let me know how you run freeze_graph?
