### ISSUE TITLE
训练CUlane数据集 instance loss 出现nan

### ISSUE THREAD

**Issue by yinhai86924** [MaybeShewill-CV/lanenet-lane-detection#220]
![QQ截图20190519132427](https://user-images.githubusercontent.com/45553479/57978144-98652200-7a39-11e9-8b36-6bc8473ae047.jpg)
请问一下，需要调整哪里参数设置，

**Comment by hellosher** [comment]
@yinhai86924 我想问一下，你是用CULane数据集训练的时候怎么生成训练数据啊？

**Comment by MaybeShewill-CV** [comment]
@yinhai86924 You may refer to #33 .

**Comment by yinhai86924** [comment]
> @yinhai86924 我想问一下，你是用CULane数据集训练的时候怎么生成训练数据啊？

有相应的标签文件 ， 自己转换就可以了

**Comment by yinhai86924** [comment]
训练到eporch=500时候出现问题 ：
![QQ截图20190519183915](https://user-images.githubusercontent.com/45553479/57981076-93b66300-7a65-11e9-863a-da14369aa842.jpg)

**Comment by MaybeShewill-CV** [comment]
@yinhai86924 调小BATCH SIZE

**Comment by yinhai86924** [comment]
> @yinhai86924 调小BATCH SIZE
可以正常训练了， 总共训练了11000次，是分阶段训练了 3000 + 5000 + 3000  学习率= 0.001 batch_size =2 结果如下：
![QQ截图20190520111102](https://user-images.githubusercontent.com/45553479/57994532-34e9fb80-7af0-11e9-94b6-732db36cdbc4.jpg)
![QQ截图20190520111122](https://user-images.githubusercontent.com/45553479/57994533-34e9fb80-7af0-11e9-9e07-5787eac46a54.jpg)
![QQ截图20190520111139](https://user-images.githubusercontent.com/45553479/57994534-35829200-7af0-11e9-880d-affa9ce1482c.jpg)
![QQ截图20190520111200](https://user-images.githubusercontent.com/45553479/57994535-35829200-7af0-11e9-9a78-b897f707d613.jpg)

**Comment by MaybeShewill-CV** [comment]
@yinhai86924 你这个实例分割的loss太大了 建议修改instance loss相关参数:)

**Comment by yinhai86924** [comment]
我尝试修改了基础网络 encoder-decoder 部分， 但是训练的时候出现nan， 找了很久找不到原因。我怀疑是不是样本数量太少 只有150张图像，学习率为0.0001 训练到2500左右出现nan
![QQ截图20190521120856](https://user-images.githubusercontent.com/45553479/58067923-ec9b0e00-7bc1-11e9-9f39-68346946463f.jpg)
![QQ截图20190521120906](https://user-images.githubusercontent.com/45553479/58067924-ec9b0e00-7bc1-11e9-895e-3f792feb290f.jpg)
![QQ截图20190521120939](https://user-images.githubusercontent.com/45553479/58067926-ed33a480-7bc1-11e9-9d75-6cd3fcecab27.jpg)

**Comment by MaybeShewill-CV** [comment]
@yinhai86924 样本少一般也不会导致nan:)

**Comment by yinhai86924** [comment]
> @yinhai86924 样本少一般也不会导致nan:)
将学习修改为0.00005 正常训练了7万次，训练精度达到92.5%，观察还有上升的可能，inference时间大大提高，语义分割效果也很好。但在训练的验证精度上却不高 50%左右。测试效果不理想。

**Comment by MaybeShewill-CV** [comment]
@yinhai86924 样本太少很容易过拟合:)

**Comment by hellosher** [comment]
@yinhai86924 您使用SCNN作者提供的工具转化的标签吗？

**Comment by hellosher** [comment]
@yinhai86924 您是用SCNN作者提供的工具生成的标签吗，或者是您自己制作的工具的话，方便分享吗，非常感谢^_^

**Comment by yinhai86924** [comment]
没有用SCNN的转换工具 自己写了一个------------------ 原始邮件 ------------------
发件人: "sher"<notifications@github.com>
发送时间: 2019年6月18日(星期二) 下午5:14
收件人: "MaybeShewill-CV/lanenet-lane-detection"<lanenet-lane-detection@noreply.github.com>;
抄送: "yinhai86924"<454960553@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [MaybeShewill-CV/lanenet-lane-detection] 训练CUlane数据集 instance loss 出现nan (#220)



@yinhai86924 您使用SCNN作者提供的工具转化的标签吗？
 
&mdash;

**Comment by hellosher** [comment]
@yinhai86924 方便分享或指导一下转换工具吗？

**Comment by TommyTang930** [comment]
@yinhai86924 
您好，可否分享一下将CULane的train数据集转换成TuSimple格式的代码呢？非常感谢大佬 ～

**Comment by jiguanglu** [comment]
> 我尝试修改了基础网络 encoder-decoder 部分， 但是训练的时候出现nan， 找了很久找不到原因。我怀疑是不是样本数量太少 只有150张图像，学习率为0.0001 训练到2500左右出现nan，我重新训练的，感觉收敛比较快。

楼主您好，请问你最后训练的效果怎么样？我这里那CUlane数据的2万张图片，是按照MaybeShewill-CV 大佬的代码，一步一步生成的，我只是把没有车道线的图片剔除掉了。Batch-Size=8
训练了大概10万次了，准确率在90%以上，但是测试的效果真的不太理想啊，您可以给点意见吗？

**Comment by TommyTang930** [comment]
Sorry, 很抱歉，我已经不接触这个领域了。具体也不了解，很长时间没有学习这个了。

lujiguang <notifications@github.com> 于2020年5月18日周一 上午8:45写道：
