### ISSUE TITLE
数据集制作中车道线不是4条的话，代码修改请教

### ISSUE THREAD

**Issue by hustcc19860606** [MaybeShewill-CV/lanenet-lane-detection#221]
您好，请问下如果数据集中的车道线条数不是4条，而是6条或者更多，是不是要对feature_dim进行修改吧。我的数据集车道线数目不确定，binary结果很好但是embed效果不行。

**Comment by MaybeShewill-CV** [comment]
@hustcc19860606 不需要修改 feature_dim和车道线个数无关:)

**Comment by hustcc19860606** [comment]
那就只能修改delta_v, delta_d这两个参数提高embed效果对吧

> @hustcc19860606 不需要修改 feature_dim和车道线个数无关:)

**Comment by MaybeShewill-CV** [comment]
@hustcc19860606 Yep instance segmentation主要受这个影响:)
