### ISSUE TITLE
请问随便找一张含车道线的图片，为什么效果很差？

### ISSUE THREAD

**Issue by hicaonmb** [MaybeShewill-CV/lanenet-lane-detection#222]
需要对图片进行什么预处理么？

**Comment by MaybeShewill-CV** [comment]
@hicaonmb 可以参考tools里面的test_lanenet.py:)

**Comment by hicaonmb** [comment]
用你dropbox里面提供的模型，测试0、1、2、3这几个jpg文件，识别效果很好
但是我在网上随便下载一张含车道线的图片，识别效果很差，这个和不同照片拍摄时摄像头的角度不一致有关系么？还是和照片的光照有关系

**Comment by MaybeShewill-CV** [comment]
@hicaonmb 都有关系:)
