### ISSUE TITLE
训练出来的ckpt 无法转pb模型

### ISSUE THREAD

**Issue by SentimentSongs** [MaybeShewill-CV/lanenet-lane-detection#224]
训练出来的ckpt 无法转pb模型。。
转换方法 按照官网的说明
https://github.com/tensorflow/models/tree/master/research/slim

python export_inference_graph.py \
  --alsologtostderr \
  --model_name=vgg16 \
  --image_size=224 \
  --output_file=/tmp/vgg16.pb

bazel build tensorflow/python/tools:freeze_graph
bazel-bin/tensorflow/python/tools/freeze_graph \
  --input_graph=/tmp/vgg16.pb \
  --input_checkpoint=/tmp/checkpoints/tusimple_lanenet_vgg_2018-05-21-11-11-03..ckpt \
  --input_binary=true --output_graph=/tmp/frozen_vgg16.pb \
  --output_node_names=vgg16/Predictions/Reshape_1

转出来的pb 无法使用，没有办法在提取vgg16的pool层

**Comment by MaybeShewill-CV** [comment]
@SentimentSongs 这个你自己百度一下怎么解决吧：）

**Comment by SentimentSongs** [comment]
要做分类 没有全连接层。这个添加上去了，计算的loss 都不对了
