### ISSUE TITLE
test a simple image

### ISSUE THREAD

**Issue by zhangtiantian12311** [MaybeShewill-CV/lanenet-lane-detection#227]
cv2.error: OpenCV(3.4.5) /io/opencv/modules/imgproc/src/imgwarp.cpp:1708: error: (-215:Assertion failed) !_map1.empty() in function 'remap'?thanks

**Comment by MaybeShewill-CV** [comment]
@zhangtiantian12311 检查文件路径:)

**Comment by zhangtiantian12311** [comment]
文件的路径是没有问题的

**Comment by MaybeShewill-CV** [comment]
@zhangtiantian12311 remap为空肯定是没有正确读入文件 你可以在相关的地方设置断点自行查看:)

**Comment by zhangtiantian12311** [comment]
谢谢，根据你的提示，我已经找到了错误，

**Comment by hellosher** [comment]
@zhangtiantian12311 请问这个错误在哪里啊，我还没有找到:)
