### ISSUE TITLE
train time

### ISSUE THREAD

**Issue by kannidekan** [MaybeShewill-CV/lanenet-lane-detection#230]
Hello, I'm trying to implement this code to Pytorch. But it seems to be too slow for one epoch, about 90s. Here is my information: Nvidia 1080 * 3 
Could you tell me how long you train one epoch? And the total time of 80K epoch?
:)

**Comment by MaybeShewill-CV** [comment]
@kannidekan Around 1s:)

**Comment by kannidekan** [comment]
ok, thanks :)
