### ISSUE TITLE
run test_lanenet.py 

### ISSUE THREAD

**Issue by zhangtiantian12311** [MaybeShewill-CV/lanenet-lane-detection#231]
![image](https://user-images.githubusercontent.com/43676340/58382724-46f00080-8000-11e9-88ec-49c1de1ca62d.png) how to generate similar images? thank you very much!

**Comment by MaybeShewill-CV** [comment]
@zhangtiantian12311 merge binary segmentation and instance segmentation result as mask and add to the origin image. You may checkout to older version and find out some useful codes:)
