### ISSUE TITLE
测试时最左边与最右边的车道线存在相同id的问题

### ISSUE THREAD

**Issue by Yc174** [MaybeShewill-CV/lanenet-lane-detection#234]
您好！
       我测试了一些图片，发现最左边的车道线与最右边的，在某些情况下聚类导致的id相同。请问作者发现有类似的情况么？我猜这种情况可能是1）loss中区分不同车道线的问题，2）聚类时的聚类器的问题。请问作者您怎么看？ @MaybeShewill-CV 谢谢！

**Comment by MaybeShewill-CV** [comment]
@Yc174 是会有这样的问题出现. 出现这样的问题考虑前段的话应该是instance segmentation分支还没有很好的收敛考虑后端的话可能是聚类器的性能还不够导致的.其实一般也只会用到当前行驶车道附近的车道线,如果只需要附近的车道的话可以减少dbscan的搜索半径来消除你上面提到的问题:)
