### ISSUE TITLE
语义分割时，车道线像素占少，背景多，是否用了类平衡？

### ISSUE THREAD

**Issue by yinhai86924** [MaybeShewill-CV/lanenet-lane-detection#235]
如题

**Comment by MaybeShewill-CV** [comment]
@yinhai86924 是的

**Comment by yinhai86924** [comment]
你的类权重是怎么取值的？ 谢谢回复！

**Comment by MaybeShewill-CV** [comment]
@yinhai86924 按照enet的方式 ennet相关自己查下论文:)

**Comment by yinhai86924** [comment]
您好，有几个问题不是很明白， （1） 关于postprocessor的作用，是对二值分割做什么处理？（2）binery_seg_image[0]  代表什么意思？ 为什么要取[0]
