### ISSUE TITLE
Output nodes to mask Image

### ISSUE THREAD

**Issue by MasschineeMe** [MaybeShewill-CV/lanenet-lane-detection#236]
Hi @MaybeShewill-CV 

I generate a .pb file according to this site. 
https://stackoverflow.com/questions/45864363/tensorflow-how-to-convert-meta-data-and-index-model-files-into-one-graph-pb

For now i need the optimized inference graph because i want to run the network on a mobile phone. Can you tell me which output nodes i need in order to print the final lanes?

I looked in the model code but i am not sure if i am right. Please help me.

**Comment by MaybeShewill-CV** [comment]
@MasschineeMe You may find them in https://github.com/MaybeShewill-CV/lanenet-lane-detection/blob/master/tools/test_lanenet.py. I believe the binary_seg_ret and instance_seg_ret node are what you need, you may get their node name in your pb file yourself:)

**Comment by MasschineeMe** [comment]
@MaybeShewill-CV   Thank you very much for answering. That was my thought too with binary_seg_ret and  instance_seg_ret i will try it in short, but I was unsure because in the train file there are also the  lanenet_cluster and lanenet_postprocess code used.

If i want to create the mask image on the phone do i need also the cluster and postprocess code an my android phone ? this is confusing me and i want to understand it, can you please explain it. 

Thank you very very much in advance.

**Comment by MaybeShewill-CV** [comment]
@MasschineeMe Yep you need the cluster procedure:)

**Comment by MasschineeMe** [comment]
@MaybeShewill-CV  Ok

Can you tell what values are inside  binary_seg_ret, instance_seg_ret ??
My first thought was that these are coordinates indicating the position of a line. Then a simple polyline function would do the job, but i see the output value are much more complex.

**Comment by MaybeShewill-CV** [comment]
@MasschineeMe Those are binary segmentation result and instance segmentation result. You may refer to the origin paper for details:)

**Comment by MasschineeMe** [comment]
@MaybeShewill-CV  am i doing something wrong?

i ran  
`       #all nodes name
        #output_node_names =[n.name for n in tf.get_default_graph().as_graph_def().node]

        #desired nodes for mask image
        output_node_names = ['binary_seg_ret','instance_seg_ret']

        print(' '.join(output_node_names))
        frozen_graph = tf.graph_util.convert_variables_to_constants(sess, sess.graph_def, output_node_names)
        with open('output_graph.pb', 'wb') as f:
          f.write(frozen_graph.SerializeToString())`

and i got

`binary_seg_ret instance_seg_ret
Traceback (most recent call last):
  File "tools/test_lanenet_with_pb_extraction.py", line 256, in <module>
    test_lanenet(args.image_path, args.weights_path, args.use_gpu)
  File "tools/test_lanenet_with_pb_extraction.py", line 122, in test_lanenet
    frozen_graph = tf.graph_util.convert_variables_to_constants(sess, sess.graph_def, output_node_names)
  File "/home/foegelle/.local/lib/python3.5/site-packages/tensorflow/python/framework/graph_util_impl.py", line 232, in convert_variables_to_constants
    inference_graph = extract_sub_graph(input_graph_def, output_node_names)
  File "/home/foegelle/.local/lib/python3.5/site-packages/tensorflow/python/framework/graph_util_impl.py", line 174, in extract_sub_graph
    _assert_nodes_are_present(name_to_node, dest_nodes)
  File "/home/foegelle/.local/lib/python3.5/site-packages/tensorflow/python/framework/graph_util_impl.py", line 133, in _assert_nodes_are_present
    assert d in name_to_node, "%s is not in graph" % d
AssertionError: binary_seg_ret is not in graph
`


when i  print all nodes name the nodes 'binary_seg_ret','instance_seg_ret' are not in the list. Which nodes do i need or am i doing something wrong? Can you please help me ?

**Comment by MasschineeMe** [comment]
@MaybeShewill-CV  am i doing something wrong?

i ran  
`       #all nodes name
        #output_node_names =[n.name for n in tf.get_default_graph().as_graph_def().node]

        #desired nodes for mask image
        output_node_names = ['binary_seg_ret','instance_seg_ret']

        print(' '.join(output_node_names))
        frozen_graph = tf.graph_util.convert_variables_to_constants(sess, sess.graph_def, output_node_names)
        with open('output_graph.pb', 'wb') as f:
          f.write(frozen_graph.SerializeToString())`

and i got

`   File "/home/user/.local/lib/python3.5/site-packages/tensorflow/python/framework/graph_util_impl.py",         line 133, in _assert_nodes_are_present
    assert d in name_to_node, "%s is not in graph" % d
    AssertionError: binary_seg_ret is not in graph
`

when i  print all nodes name the nodes 'binary_seg_ret','instance_seg_ret' are not in the list. Which nodes do i need or am i doing something wrong? Can you please help me ?

**Comment by MaybeShewill-CV** [comment]
@MasschineeMe You need the node's name in the compute graph rather than the variable name in the code. You may print all the node in your compute graph and find what you need then:)

**Comment by LukasProgram** [comment]
@MaybeShewill-CV 
I ran tensorboard and study the graph. 
are my required outputs:
- binary segmentation - lanenet_model/inference/decode/score_final/score_fina
- instance segamentation - lanenet_model/pix_embedding_relu
??

Please tell me that I am right or tell me the right answer.

**Comment by MaybeShewill-CV** [comment]
@LukasProgram Srr I didn't remember the exact node name of that two element ==!

**Comment by ArtlyStyles** [comment]
@LukasProgram Did you find the correct names?

**Comment by nikhilbv** [comment]
+1
