### ISSUE TITLE
大佬，有篇新论文，可以看看

### ISSUE THREAD

**Issue by hellosher** [MaybeShewill-CV/lanenet-lane-detection#238]
FastDraw: Addressing the Long Tail of Lane Detection by Adapting a Sequential Prediction Network      https://arxiv.org/abs/1905.04354

**Comment by MaybeShewill-CV** [comment]
@hellosher 哈哈 感谢哈 已经看过了:)

**Comment by hellosher** [comment]
@MaybeShewill-CV 那大佬有空可以考虑一下这个的实现，嘻嘻嘻嘻

**Comment by MaybeShewill-CV** [comment]
@hellosher :)
