### ISSUE TITLE
 复现的LaneNet代码，是否用了最小二乘法拟合？

### ISSUE THREAD

**Issue by yinhai86924** [MaybeShewill-CV/lanenet-lane-detection#239]
您好！是否用了俯视图变换 和 最小二乘拟合

**Comment by MaybeShewill-CV** [comment]
@yinhai86924 你可以参考后处理的部分：）

**Comment by yinhai86924** [comment]
H-NET 这个网络您用了吗？

**Comment by zacario-li** [comment]
> H-NET 这个网络您用了吗？
下面链接的代码，使用了H-Net
[https://github.com/stesha2016/lanenet](url)
