### ISSUE TITLE
fix readme

### ISSUE THREAD

**Issue by e-yi** [MaybeShewill-CV/lanenet-lane-detection#241]
former:
>You can download the model and put them in folder model/tusimple_lanenet/
You can test a single image on the trained model as follows
>>python tools/test_lanenet.py --weights_path ./model/tusimple_lanenet_vgg/tusimple_lanenet.ckpt 
--image_path ./data/tusimple_test_image/0.jpg

better change it to：
>You can download the model and put them in folder model/tusimple_lanenet_vgg/
You can test a single image on the trained model as follows
>>python tools/test_lanenet.py --weights_path ./model/tusimple_lanenet_vgg/tusimple_lanenet_vgg.ckpt 
--image_path ./data/tusimple_test_image/0.jpg

beacause of some changes in the pretrained model provided?

**Comment by MaybeShewill-CV** [comment]
@e-yi Thanks a lot. I will change it quickly:)

**Comment by ashwin-phadke** [comment]
@MaybeShewill-CV  : 
Can you help out here : ValueError: The passed save_path is not a valid checkpoint: C:\\lanenet-lane-detection-master\\model\\tusimple_lanenet_vgg\\tusimple_lanenet_vgg.ckpt

**Comment by MaybeShewill-CV** [comment]
@ashwin-phadke You may check if you've downloaded the right model weights file:)

**Comment by ashwin-phadke** [comment]
@MaybeShewill-CV  : I have them exactly as the readme says.

**Comment by e-yi** [comment]
@ashwin-phadke well,put model weights in `model/tusimple_lanenet_vgg/` instead of `model/tusimple_lanenet/`.

**Comment by ashwin-phadke** [comment]
@e-yi : 
my current structure is 
```C:\\lanenet\\model\\tusimple_lanenet_vgg``` where I have the following files : 

```tusimple_lanenet_vgg.ckpt.data-00000-of-00001```
```checkpoint```
```tusimple_lanenet_vgg.ckpt.index```
```tusimple_lanenet_vgg.ckpt.meta```

**Comment by MaybeShewill-CV** [comment]
@ashwin-phadke Nothing wrong happened when I test the model in my local machine. That is exactly what you need:)

**Comment by ashwin-phadke** [comment]
So which of the above files should I use, coz it seems whichever I use it is giving me the same error.

**Comment by MaybeShewill-CV** [comment]
@ashwin-phadke tusimple_lanenet_vgg.ckpt :)

**Comment by ashwin-phadke** [comment]
@MaybeShewill-CV  : If I go by the exact filename, there ain't such file in the dropbox link you shared. So I suppose one of these two ```tusimple_lanenet_vgg.ckpt.index```  ```tusimple_lanenet_vgg.ckpt.meta``` .

**Comment by ashwin-phadke** [comment]
> @ashwin-phadke tusimple_lanenet_vgg.ckpt :)

@MaybeShewill-CV It seems that the above notation for file description works on Linux platforms and not on Windows.


> @MaybeShewill-CV : If I go by the exact filename, there ain't such file in the dropbox link you shared. So I suppose one of these two `tusimple_lanenet_vgg.ckpt.index` `tusimple_lanenet_vgg.ckpt.meta` .
> 
> Also I remember having the same issue with the previous version of code, which I was able to solve by some question on a Chinese forum csdn something wherein the checkpoint file named `tusimple_lanenet_vgg.ckpt.data-00000-of-00001` was to be used to restore the session.

I.E tusimple_lanenet_vgg.ckpt works in Linux but not in Windows. As you have mentioned in the readme, however previous codes change in checkpoint file worked in Windows as mentioned in the previous comment.

**Comment by ashwin-phadke** [comment]
@MaybeShewill-CV Have you figured out why it only works on Linux and not on Windows platform?

**Comment by MaybeShewill-CV** [comment]
@ashwin-phadke No. Sorry do not have enough time for windows recently:)

**Comment by kk52099** [comment]
@ashwin-phadke can u  send  me  the model file "tusimple_lanenet_vgg.ckpt"? I have been unable to download it at the link provided by the author .  Thank you  very much !    my email: 1045342540@qq.com,
