### ISSUE TITLE
Clarification on Encoder-Decoder

### ISSUE THREAD

**Issue by jackofall96** [MaybeShewill-CV/lanenet-lane-detection#242]
Why are we using layers 3, 4 and 5 of the vgg encoder to the decoder input??
I'm trying to understand why these layers in particular would help in this problem.

**Comment by MaybeShewill-CV** [comment]
@jackofall96 lower features remain more details and higher features catpure more semantic information. You may refer some semantic segmentation papers for your question:)

**Comment by jackofall96** [comment]
Okay, thanks. I'll take a look at them.
