### ISSUE TITLE
问个网络结构问题

### ISSUE THREAD

**Issue by hustcc19860606** [MaybeShewill-CV/lanenet-lane-detection#243]
您好，看了您的代码后有个疑问：
我感觉整个decode过程类似fcn，binary和instance一起decode一直到恢复到原图288X800的大小才开始做了一次分支，分别做conv合成所需的维度图片。似乎和论文结构和代码说明里面的结构不太一样，分支结构简单得多（或者说decode过程有很大一部分binary和instance是一起decode的，只在最后做了个简单的分支），不知道理解的对不对。
再次对您的工作表示感谢。

**Comment by MaybeShewill-CV** [comment]
@hustcc19860606 论文里使用的backbone net是enet. Enet的结构和我现在使用的encoder decoder结构不一样,enet模型更轻量更适合对实时性有需求的任务,不过enet结构本身也并不复杂,替换backbone网络在我现在的代码结构里也很简单，感兴趣的话可以自己尝试一下. 也欢迎分享测试结果：）
