### ISSUE TITLE
FailedPreconditionError (see above for traceback): Attempting to use uninitialized value

### ISSUE THREAD

**Issue by jackofall96** [MaybeShewill-CV/lanenet-lane-detection#244]
Getting the following error while running tf.global_initializer() from the latest commit:

**FailedPreconditionError (see above for traceback): Attempting to use uninitialized value lanenet_model/vgg_frontend/vgg16_encode_module/conv5_3_instance/conv/W
	 [[node lanenet_model/vgg_frontend/vgg16_encode_module/conv5_3_instance/conv/W/read (defined at /cosmosHD/lanenet-lane-detection-master/semantic_segmentation_zoo/cnn_basenet.py:70) ]]**

After debugging the code, it was found that the following nodes were not being initialized:

'lanenet_model/vgg_frontend/vgg16_decode_module/binary_seg_decode/decode_stage_4_fuse/deconv/deconv/kernel'
'lanenet_model/vgg_frontend/vgg16_decode_module/binary_seg_decode/decode_stage_3_fuse/deconv/deconv/kernel'
'lanenet_model/vgg_frontend/vgg16_decode_module/binary_seg_decode/decode_stage_2_fuse/deconv/deconv/kernel'
'lanenet_model/vgg_frontend/vgg16_decode_module/binary_seg_decode/decode_stage_1_fuse/deconv/deconv/kernel'
'lanenet_model/vgg_frontend/vgg16_decode_module/binary_seg_decode/binary_final_logits/W'
'lanenet_model/vgg_frontend/vgg16_decode_module/instance_seg_decode/decode_stage_4_fuse/deconv/deconv/kernel'
'lanenet_model/vgg_frontend/vgg16_decode_module/instance_seg_decode/decode_stage_3_fuse/deconv/deconv/kernel'
'lanenet_model/vgg_frontend/vgg16_decode_module/instance_seg_decode/decode_stage_2_fuse/deconv/deconv/kernel'
'lanenet_model/vgg_frontend/vgg16_decode_module/instance_seg_decode/decode_stage_1_fuse/deconv/deconv/kernel'

Tried to assign zeros of same shape for all global variables but still facing the same error.

Any help would be appreciated, thanks.

**Comment by MaybeShewill-CV** [comment]
@jackofall96 Check if your tensorflow version is not the same as mine:)

**Comment by jackofall96** [comment]
I have tried with the same version as yours, 1.10.0. I have also tried 1.9, 1.11 and 1.13.1. Still facing the same error. Anything else that could be the problem?

**Comment by MaybeShewill-CV** [comment]
@jackofall96 Some of your kernel is not correctly initialized. You may check if there is something different with README file.I have not met this kind of error ever:)

**Comment by jackofall96** [comment]
Changing dataset loading from tfrecords to loading from dataset directory fixed the issue for me. I do not why the initializing would get affected with that but, it worked for me.
