### ISSUE TITLE
关于backbone用SCNN替换的问题

### ISSUE THREAD

**Issue by Yc174** [MaybeShewill-CV/lanenet-lane-detection#245]
您好！
      lanenet模型目前用的backbone是用VGG16搭建的FCN,请问 @MaybeShewill-CV 有试过SCNN作为backbone么？SCNN据说在检测'线特征'上有优势。谢谢！

**Comment by MaybeShewill-CV** [comment]
@Yc174 scnn可以直接输出车道线 为什么不直接使用SCNN呢 哈哈：）

**Comment by Yc174** [comment]
SCNN不是在提升线特征上有优势么，但是他的后端将线数定死了。如果用SCNN做前端，实例分割做后端，不就能够融合二者的优势了么。 @MaybeShewill-CV

**Comment by MaybeShewill-CV** [comment]
@Yc174 是的 你可以尝试下 也欢迎分享结果：）
