### ISSUE TITLE
Anaconda虚拟环境中安装requirements.txt，找不到合适的opencv版本

### ISSUE THREAD

**Issue by U-cifer** [MaybeShewill-CV/lanenet-lane-detection#246]
执行pip3 install -r requirements.txt时，提示以下错误，请问有什么可以解决的方法吗
Could not find a version that satisfies the requirement opencv==4.0.0 (from -r requirements.txt (line 7)) (from versions: )
No matching distribution found for opencv==4.0.0 (from -r requirements.txt (line 7))

**Comment by MaybeShewill-CV** [comment]
@U-cifer Opencv不一定非要这个版本的 用的都是基础的opencv功能 只是pipreqs生成这个文件的时候带着版本号：）

**Comment by U-cifer** [comment]
谢谢！

**Comment by deeprun** [comment]
I have the same problem. Should I change requirements.txt? Which version of opencv should I use?
