### ISSUE TITLE
关于训练误差和accuracy的问题

### ISSUE THREAD

**Issue by LoveMIssY** [MaybeShewill-CV/lanenet-lane-detection#247]
问一下大佬，我看你给出的图片中，初始误差只有0.08左右，最后收敛到0.01附近，准确率最开始就有0.982，最后收敛到0.998附近，可是我的训练了90000个epoch，最终误差还是很大，还有2点几，好像也没有继续下降的趋势，准确率最开始就很低，最终达到0.93附近，数据集同样是使用的图森数据集，这是什么原因呢，希望大佬百忙之中回复一下，谢谢！

**Comment by MaybeShewill-CV** [comment]
@LoveMIssY 如果你完全按照README上的配置跑完了实验得到的结果基本和我在README中陈述的一致，只会有一点微小的差别,因为有些参数是随机初始化的无法保证每次参数都是完全相同.如果得到的结果不一致,首先检查你自己的样本是否有问题,其次查看tensorflow版本问题.
