### ISSUE TITLE
关于instance_seg_image部分的损失函数的一点疑问，

### ISSUE THREAD

**Issue by LoveMIssY** [MaybeShewill-CV/lanenet-lane-detection#248]
原始论文中说，经过instance_seg_image的损失函数之后，论文中是说会将相同的车道线聚在一起，不同的分开，但是最后测试的时候，代码中显示出来的两张图片，一个是instance_image和我的binary_image基本上是重合的，也就是说并没有将相同的车道线聚在一起，不同的车道线分开，这样会导致后面在使用DBSCAN聚类的时候出现一些问题，可能会将几根车道线聚为一类，希望大佬告知

**Comment by MaybeShewill-CV** [comment]
@LoveMIssY Instance seg分支做的是让mebedding出来的特征以不同车道线为类别区分开来.也就是同一个车道线的embedding feats更相近然后不同的车道线的feats距离更远:)

**Comment by LoveMIssY** [comment]
您的意思我明白，因为这个是将像素进行了4维嵌入，所以我也没办法画图查看不同车道线是否确实分开了，但是通过后面的DBSCAN对嵌入向量聚类的时候，发现有很多车道线没有了  跟binary里面的显示的不一样了，这是否意味着嵌入的向量没有分开呢？再就是DBSCAN算法的两个超参数 ，您是根据什么确定的，在tusimple的数据集上积累没有问题，但是测试我自己的图片的时候，常常聚类不出我想要的结果，这是怎么回事呢？麻烦大佬百忙之中解答，谢谢

**Comment by MaybeShewill-CV** [comment]
@LoveMIssY 1.超参数是经验值. 2.如果你想很直观的可视化instance seg的值 你可以设置embeding为三维然后可视化或者你自己把4维数据降维,或者你就按照四通道数据可视化也是能看出来聚类效果的，这些中间过程在训练的过程中都可以可视化看到 你可以自行查看. 3.你在tusimple上训练的数据怎么可能在所有不同的场景中都表现良好,想解决这个问题 最直接的方法自己标数据集 或者尝试迁移学习的方法:)

**Comment by LoveMIssY** [comment]
再向大佬请教一下几个问题，后处理中有一个 tusimple_ipm_remap.yml 文件，这个文件是怎么得来的？我的理解是他将1280x720的图片重映射到640x640，为什么要进行这样的处理呢？整个代码里面是不是没有实现透视变换这一步操作？麻烦大佬百忙之中解答，谢谢！

**Comment by MaybeShewill-CV** [comment]
@LoveMIssY 车道线检测结果后处理的时候将前视图转换成俯视图会用到这个文件. 这个相关算法可以参考https://github.com/MaybeShewill-CV/Easy-Ipm-Client和其中提到的文献,就是用这个算法实现的:)

**Comment by LoveMIssY** [comment]
tmp_ipm_mask = cv2.remap( 
                tmp_mask,       # 这是原图像
                self._remap_to_ipm_x, # （640,640） # 这个和下面的remap_to_ipm_y是没有变化的
                self._remap_to_ipm_y,
                interpolation=cv2.INTER_NEAREST  # 近邻插值 ,这个 tmp_mask的形状是（640,640）
            ) 
这个地方不太明白，原来的图片是1280x720，变换之后我看这个tmp_ipm_mask是640x640，这个重映射是先经过了透视变换，然后再经过逆透视变换得到的吗？

**Comment by MaybeShewill-CV** [comment]
@LoveMIssY 这个remap矩阵可以认为就是实现了透视变化:)

**Comment by LoveMIssY** [comment]
可视我将这个remap之后得到的640x640的图片显示出来，发现里面的车道线不是平行的啊  也就是没有实现透视变换，是不是相当于先经过了透视变换，然后再进行了逆透视变换得到这个640x640的图片

**Comment by MaybeShewill-CV** [comment]
@LoveMIssY 不是：）

**Comment by LoveMIssY** [comment]
大佬方便详解一下这个remap的功能吗，这个地方我硬是没搞懂，纠结好久了，谢谢大佬！

**Comment by MaybeShewill-CV** [comment]
@LoveMIssY 就是实现类似透视变换的功能,为了能更好的用二次曲线描述车道线.效果和你选取控制点做cv2.perspectiveWarp一样：）

**Comment by xiang1107** [comment]
我想请问一下，自己数据集车道线标注的话，标线还是标点呢？

**Comment by MaybeShewill-CV** [comment]
@xiang1107 标线 和一般语以分割标注一样:)
