### ISSUE TITLE
Output on own dataset

### ISSUE THREAD

**Issue by nathannzw** [MaybeShewill-CV/lanenet-lane-detection#250]
Hi when i trained my own model and tested on an image the binary and segmentation shows proper lines drawn but the masking only had 2/4 of the lines. may i know the possible reasons for this? and how is the masking formed from binary and instance segmentation? thanks

**Comment by MaybeShewill-CV** [comment]
@nathannzw Binary seg result is used as cluster mask on the instance seg result. The reason why use binary seg result as mask is to speed up cluster process. You may refer the code for details:)

**Comment by shank-gyrus** [comment]
@nathannzw  can you please explain how did you annotate your custom dataset?
