### ISSUE TITLE
Cutting off lane lines at horizon

### ISSUE THREAD

**Issue by nathannzw** [MaybeShewill-CV/lanenet-lane-detection#251]
Hi is there anyway to remove lane lines before a certain y value? the current tested output of my model has lines being extended more than wanted so I would like to cut extra lane lines at a certain horizon. Thanks

**Comment by MaybeShewill-CV** [comment]
@nathannzw You should check the postprocess procedure code and you will find what you want:)

**Comment by nathannzw** [comment]
Yup found it, thanks!
