### ISSUE TITLE
测试时间

### ISSUE THREAD

**Issue by MMY1994** [MaybeShewill-CV/lanenet-lane-detection#252]
您好，请问我现在测试一张图片大概需要将近1秒，我了解可能GPU需要预热一下，但目前的test文件的batch_size只能为1，是否需要用老版本中可设置batch_size的test文件。

**Comment by MaybeShewill-CV** [comment]
@MMY1994 1.你可以修改place holder里面的batch size 2.placeholder这种方式传入数据效率会比较低但是比较直观，你可以直接使用tensorflow的io api来批量读取数据,这样效率会高一点:)

**Comment by MMY1994** [comment]
好的非常感谢
