### ISSUE TITLE
Instance mask not showing anything

### ISSUE THREAD

**Issue by danieladea** [MaybeShewill-CV/lanenet-lane-detection#253]
Hi, thank you for posting your lane detection software! I'm trying to test the model on my own data set and the binary is showing clear lanes, but the instance mask does not show anything for most of my data. Is there a threshold I should be changing or is there another reason that the segmentation branch isn't catching any of my lanes? 
![binary_mask_image](https://user-images.githubusercontent.com/35434955/60537244-ea49ca80-9cbc-11e9-9b7b-9a3577f0f57c.png)
![Test1dimension](https://user-images.githubusercontent.com/35434955/60537263-fd5c9a80-9cbc-11e9-9fe3-1c7d96716b61.jpg)
![instance_mask_image](https://user-images.githubusercontent.com/35434955/60537278-0483a880-9cbd-11e9-9394-2ea0fab27838.png)

**Comment by MaybeShewill-CV** [comment]
@danieladea Adjust threshold used in dbscan cluster method:)

**Comment by danieladea** [comment]
The instance segmentation now shows predictions, but they're not mapping correctly. If my dataset is using different dimensions, can't I just change the mask dimensions in postprocess.py? The mask lines aren't lining up with my image lanes even after adjusting mask shape dimension.

**Comment by MaybeShewill-CV** [comment]
@danieladea What do you mean different dimensions?

**Comment by danieladea** [comment]
The images I want to use are 1920x1200, but your images are 1280x720

**Comment by MaybeShewill-CV** [comment]
@danieladea You need to resize the image if you use the origin config or you can modify the config file:)

**Comment by danieladea** [comment]
Technically, the issue question has been answered. I'll open up a new issue

**Comment by iltertaha** [comment]
> The instance segmentation now shows predictions, but they're not mapping correctly. If my dataset is using different dimensions, can't I just change the mask dimensions in postprocess.py? The mask lines aren't lining up with my image lanes even after adjusting mask shape dimension.

Hi, I have the same problem. However I couldn't figure out that which parameter in the lanenet_postprocess.py should I modify?
