### ISSUE TITLE
__C.TRAIN.EMBEDDING_FEATS_DIMS这个的含义是什么？

### ISSUE THREAD

**Issue by RanKevin** [MaybeShewill-CV/lanenet-lane-detection#254]
感谢您的分享
下面这个参数看到是用在实例分割的输出通道数，但是没有理解为什么要设置为4。向您请教一下，谢谢

# Set the embedding features dims
__C.TRAIN.EMBEDDING_FEATS_DIMS = 4

**Comment by MaybeShewill-CV** [comment]
@RanKevin 特征维数:)

**Comment by MaybeShewill-CV** [comment]
@RanKevin 特征维数:)

**Comment by RanKevin** [comment]
嗯嗯，这个了解。但是没有理解为什么是4维呢？我理解比如分割10类，会有10维。但是图中车道线也不止4条，也许会有5条，而且后面有聚类处理，我想这个维数的意义也不是车道线数量。所以不太理解这个特征维数4具体指的是什么。还请指点一下，谢谢

**Comment by MaybeShewill-CV** [comment]
@RanKevin 特征维数和车道线数量没有关系 你理解错了 建议再多看看原文哈：）
