### ISSUE TITLE
Lanes not lining up correctly on image

### ISSUE THREAD

**Issue by danieladea** [MaybeShewill-CV/lanenet-lane-detection#256]
I'm trying to test on a data set with1920x1200 images, but the lanes don't show up on the correct place in the images. I don't see a dimension variable in the config file that I can change. Is there a way to fix this? Simply cropping/resizing still doesn't give accurate results:

Original image 1920x1200
![MalibuD2v2 png_result](https://user-images.githubusercontent.com/35434955/60742357-f5e9fb00-9f21-11e9-98d0-fd06e67ebf7a.jpg)

Cropped 1280x720
![MalibuD2v2cropped png_result](https://user-images.githubusercontent.com/35434955/60742360-f5e9fb00-9f21-11e9-9bb4-8c67cf3feb04.jpg)

Resize 1280x720
![MalibuD2v2resize png_result](https://user-images.githubusercontent.com/35434955/60742361-f5e9fb00-9f21-11e9-8c6d-aa17868dc212.jpg)

**Comment by MaybeShewill-CV** [comment]
@danieladea The post process part is used in tusimple dataset. You can check if the binary segmentation and instance segmentation result are correctly generated by the model. Then you could implement your own post process module to get what you want:)

**Comment by danieladea** [comment]
Hi, do you have any ideas why the far right lane would have its path changed? The instance segmentation is correct and lines up with the picture, but the final result has the right line drastically changing slope. I returned. This is using the original postprocess code you have provided. 
![3 jpg_result](https://user-images.githubusercontent.com/35434955/60906324-b8d87e00-a22b-11e9-9ee4-691714428b3c.jpg)

**Comment by MaybeShewill-CV** [comment]
@danieladea That's not a bug. That is due to the dbscan cluster's wrong clustering result:)

**Comment by danieladea** [comment]
Yes, looking at the instance mask, I see that you're right. Why does dbscan cluster lines on the right side of the screen with the left side of the screen? Is there a way to fix that?

**Comment by MaybeShewill-CV** [comment]
@danieladea You need to adjust the dbscan cluster threshold or add some post process rules to avoid this:)

**Comment by danieladea** [comment]
I'm confused. With the inverse perspective mapping, why would the clustering cluster the left side of the image with the right side of the image? The distance between these points should be very large since they're on opposite sides of the image

**Comment by danieladea** [comment]
Is there a way I to save the ipm image so I can see why the clustering would cluster two lines far away from each other?

**Comment by MaybeShewill-CV** [comment]
@danieladea You may convert the image into bird view via the remap file:)
