### ISSUE TITLE
Nan and inf cost

### ISSUE THREAD

**Issue by nathannzw** [MaybeShewill-CV/lanenet-lane-detection#258]
![image](https://user-images.githubusercontent.com/51075642/60941371-86a14c00-a311-11e9-9765-f93f9b4528fc.jpg)

Hi how do i go about fixing this?

**Comment by nathannzw** [comment]
It’s training with my dataset. The training worked for smaller batches but now with a larger dataset with different conditions i get this...

**Comment by MaybeShewill-CV** [comment]
@nathannzw Maybe you should adjust the threshold of the instance segmentation loss function:)

**Comment by hustcc19860606** [comment]
@MaybeShewill-CV 我也在大样本数据集上碰到了同样的问题，请问您说的阈值在哪啊？之前看您说instance segmentation的时候需要确定的阈值 你可以查看lanenet_merge_model.py文件的114-118行。
            print("pix_embedding:",pix_embedding.get_shape().as_list())
            pix_embedding = self.relu(inputdata=pix_embedding, name='pix_embedding_relu')
            print("pix_embedding:",pix_embedding.get_shape().as_list())
            # 计算discriminative loss
            image_shape = (pix_embedding.get_shape().as_list()[1], pix_embedding.get_shape().as_list()[2])

**Comment by MaybeShewill-CV** [comment]
@hustcc19860606 就是在计算discriminative loss的地方:)

**Comment by hustcc19860606** [comment]
@MaybeShewill-CV 您的意思是delta_v, delta_d, param_var, param_dist, param_reg这些参数吧，有调整建议么？

**Comment by MaybeShewill-CV** [comment]
@hustcc19860606 这个和数据相关了 你自己实验下吧:)

**Comment by AmmarSaqib** [comment]
Hi,
I am having similar issue cost is coming out to be 'nan'. How can i resolve this? How to adjust the threshold of the instance segmentation loss function?

**Comment by MaybeShewill-CV** [comment]
@AmmarSaqib That's dataset relevant you may test yourself:)
