### ISSUE TITLE
ENet-Label-Torch is available now (a light-weight and effective lane detection model)

### ISSUE THREAD

**Issue by cardwing** [MaybeShewill-CV/lanenet-lane-detection#261]
Our **ENet-Label-Torch** has been released. More details can be found in [my repo](https://github.com/cardwing/Codes-for-Lane-Detection).

Key features:

(1) ENet-label is a **light-weight** lane detection model based on [ENet](https://arxiv.org/abs/1606.02147) and adopts **self attention distillation** (more details can be found in our paper which will be published soon).

(2) It has **20** × fewer parameters and runs **10** × faster compared to the state-of-the-art SCNN, and achieves **72.0** (F1-measure) on CULane testing set (better than SCNN which achieves 71.6).

(**Do not hesitate to try our model!!!**)

Performance on CULane testing set (F1-measure):

|Category|[SCNN-Torch](https://github.com/XingangPan/SCNN)|SCNN-Tensorflow|[ENet-Label-Torch](https://github.com/cardwing/Codes-for-Lane-Detection)|
|:---:|:---:|:---:|:---:|
|Normal|90.6|90.2|**90.7**|
|Crowded|69.7|71.9|70.8|
|Night|66.1|64.6|65.9|
|No line|43.4|45.8|44.7|
|Shadow|66.9|73.8|70.6|
|Arrow|84.1|83.8|**85.8**|
|Dazzle light|58.5|59.5|**64.4**|
|Curve|64.4|63.4|**65.4**|
|Crossroad|1990|4137|2729|
|Total|71.6|71.3|**72.0**|
|Runtime(ms)|133.5|--|**13.4**|
|Parameter(M)|20.72|--|**0.98**|

**Comment by MaybeShewill-CV** [comment]
@cardwing It will be very nice if you have time for a tensorflow version of your model:)

**Comment by cardwing** [comment]
@MaybeShewill-CV I will try to implement one when I am free. ^_^

**Comment by MaybeShewill-CV** [comment]
@cardwing That's very kind:)
