### ISSUE TITLE
nan

### ISSUE THREAD

**Issue by zhangtiantian12311** [MaybeShewill-CV/lanenet-lane-detection#262]
我在训练culane数据集的时候，尝试了将学习率降低; 图片改成png格式; 没有车道线的标签删除，甚至将图片大小都改成1280×720, 都出现了nan的情况，请问还有改进方法吗？谢谢

**Comment by MaybeShewill-CV** [comment]
@zhangtiantian12311 看下 #258 #183 #116

**Comment by TommyTang930** [comment]
@zhangtiantian12311 
您好，可否分享一下将CULane的train数据集转换成TuSimple格式的代码呢？非常感谢大佬 ～

**Comment by 850977164** [comment]
@MaybeShewill-CV @zhangtiantian12311 I would appreciate it if you could provide me with the code to convert the CULane dataset into the TuSimple dataset. Thank you
