### ISSUE TITLE
Run Lanenet on Jetson TX2

### ISSUE THREAD

**Issue by deeprun** [MaybeShewill-CV/lanenet-lane-detection#263]
Have you tried to run this on jetson TX2?

**Comment by MaybeShewill-CV** [comment]
@deeprun Sorry I have not tested it before:)

**Comment by ashwin-phadke** [comment]
@deeprun @MaybeShewill-CV : Tested the code on TX2, gives decent results as compared to the hardware it houses and the task it is given.

**Comment by MaybeShewill-CV** [comment]
@ashwin-phadke If you have tested it on TX2 you may post some details here and give some advice:)

**Comment by ashwin-phadke** [comment]
Sure, anything one needs @MaybeShewill-CV 
TX2 inference is slower than GTX 1080 which is obvious , however to make it real time, I/O operations need to be optimized.
It gives decent enough FPS and with some changes to memory allocation a double digit FPS sometimes. However TX2 may quickly run out of memory while loading the model and while doing the inference so the TX2 shared memory should be really available for the model to perform well.

**Comment by deeprun** [comment]
Why did it run out of memory? Is there memory leak?

**Comment by deeprun** [comment]
@ashwin-phadke which version of L4T os and cuda did you use on Tx2? Did you use Jetpack to flush the TX2? Which version of Jetpack?

**Comment by ashwin-phadke** [comment]
L4T : 32.2
Jetpack : 4.2
Cuda I currently don't have the device with me right now.


> Why did it run out of memory? Is there memory leak?

Even I am guessing it is the same reason , I am trying to debug it . Do you have any leads on it?

**Comment by ArtlyStyles** [comment]
@ashwin-phadke There are two ways to run this lanenet:

1. Convert the author's tensorflow model to TensorRT and then run it on Jetson TX2
2. Install this repo and run the author's tools/test_lanenet.py script. 

Which one did you used? Did you train your own model?

**Comment by ashwin-phadke** [comment]
@ArtlyStyles  : I made certain changes to author's script and used the second method to check what inference does existing model provide.
