### ISSUE TITLE
Detect path borders

### ISSUE THREAD

**Issue by deeprun** [MaybeShewill-CV/lanenet-lane-detection#264]
Can I use this network to detect the borders of path as show in this picture [http://artlystyles.com/tmp/sp_path.JPG](url) Or there is some other DL network can do this?

**Comment by MaybeShewill-CV** [comment]
@deeprun can not see your picture here:)

**Comment by ArtlyStyles** [comment]
You can copy the address to browser address bar and then you can see it

**Comment by MaybeShewill-CV** [comment]
@deeprun Any image segmentation model can do your task theoretically
