### ISSUE TITLE
Lanenet with Python 2.7

### ISSUE THREAD

**Issue by ArtlyStyles** [MaybeShewill-CV/lanenet-lane-detection#266]
Do you have a version of code for Python 2.7?

**Comment by ashwin-phadke** [comment]
Most of the code works in Python 2.7 , you need to however change few attributes(like CPU , GPU setup) and remove some variables in the function call(like recursive in glob and the way you import your model.).

**Comment by MaybeShewill-CV** [comment]
@ArtlyStyles No:)
