### ISSUE TITLE
Convert the trained model to UFF

### ISSUE THREAD

**Issue by ArtlyStyles** [MaybeShewill-CV/lanenet-lane-detection#268]
Hi @MaybeShewill-CV. Could you please convert your trained model to TensorRT UFF mode? That way, we can use the model to run inference directly on Jetson TX2. 

Thank you very much

**Comment by MaybeShewill-CV** [comment]
@ArtlyStyles Sorry have no spare for this recently. Welcome to share your converted model here if you are willing to:)

**Comment by shortstheory** [comment]
Hi @ArtlyStyles, could you share the UFF model you were able to generate for LaneNet? I am looking for a way to get a pretrained TensorRT model for the Jetson and NVIDIA desktop GPUs, so I would really appreciate it if you could share the UFF or ONNX model with me!

**Comment by MaybeShewill-CV** [comment]
@shortstheory For tensorrt you check https://github.com/MaybeShewill-CV/bisenetv2-tensorflow/blob/master/tools/cityscapes/timeprofile_cityscapes_bisenetv2.py which may help:)

**Comment by shortstheory** [comment]
Thank you @MaybeShewill-CV . Could you tell me the names of the input and output nodes of the lanenet model so I can convert it to ONNX using tf2onnx?

**Comment by MaybeShewill-CV** [comment]
@shortstheory I do not remember the exact name of those node. You may print the tensor to fetch their names:)

**Comment by ArtlyStyles** [comment]
@shortstheory What's the issue when you convert it to UFF? My model is trained with my own images, also I do not know where to put them.

**Comment by ArtlyStyles** [comment]
Also, check my GitHub

**Comment by shortstheory** [comment]
I figured it out. In case anyone else needs help with doing this, the ONNX model I was able to generate is here: [https://www.dropbox.com/s/w9bkty2drm005aj/lanenet_model.onnx?dl=0](https://www.dropbox.com/s/w9bkty2drm005aj/lanenet_model.onnx?dl=0)

**Comment by MaybeShewill-CV** [comment]
@shortstheory Good job:)
