### ISSUE TITLE
How to deal with tf.gather bug?

### ISSUE THREAD

**Issue by lsjws2008** [MaybeShewill-CV/lanenet-lane-detection#27]
I can't train lanenet with batch =3 , 1080 ti, because of this function.

> ''UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. ''

**Comment by MaybeShewill-CV** [comment]
@lsjws2008 Is it a warning or an error?

**Comment by lsjws2008** [comment]
因为这个问题, 会导致gpu 内存溢出,[https://stackoverflow.com/questions/35892412/tensorflow-dense-gradient-explanation](详细错误, 请参考). 目前我个人的解决方案是将`tf.gather()` 和 `tf.gather_nd()` 之上增加一行`with tf.device('/cpu:0')`, 交由cpu计算.

**Comment by MaybeShewill-CV** [comment]
@lsjws2008 你训练的图像数据大小?

**Comment by lsjws2008** [comment]
与源代码一样, 未修改 resize到 512 * 256, resize之前是 1640 * 590.

**Comment by MaybeShewill-CV** [comment]
@lsjws2008 我的模型batch size为４也没有出现显存不够的问题

**Comment by lsjws2008** [comment]
@MaybeShewill-CV  不好意思...我也不知道为什么,可能和显卡体质有关系. 还是非常感谢你!

**Comment by MaybeShewill-CV** [comment]
@lsjws2008 我的是1070ti 你可以看下是不是有别的任务占用了你的显卡

**Comment by y11203090135** [comment]
请问训练数据集可以使用TuSimple的车道线检测数据集吗？ 如何转换成训练数据集的二值分割图呢？
