### ISSUE TITLE
实例分割和H-net的必要性

### ISSUE THREAD

**Issue by andeyeluguo** [MaybeShewill-CV/lanenet-lane-detection#270]
首先膜拜大神。我是车道线检测的初学者，这里有几个疑惑。我感觉只要enet完成语义分割把背景和线面给分割出来就差不多了，为啥还要实例分割和车道线拟合？用图像处理的方法对二值图像做一个区域分割（具体还没想起怎么弄），车就在当前区域中跑就完事了。可能问题比较低级，见谅哈，能加一下微信吗，探讨一下。wechat:15711325055

**Comment by andeyeluguo** [comment]
我的想法是二值图像出来之后直接用图像处理的一些方法得出结论

**Comment by andeyeluguo** [comment]
比如膨胀和腐蚀之类的

**Comment by fyqqyf** [comment]
In this project, we should cluster these lines. So it's necessary to do these things. : D

**Comment by MaybeShewill-CV** [comment]
@andeyeluguo 实例分割是为了区分不同的车道线 车道线拟合是为了给车道线建模:)

**Comment by andeyeluguo** [comment]
车道线建模是啥意思

**Comment by fyqqyf** [comment]
你好，实例分割是为了找出属于同一条车道线的像素点，变换建模（如一个三次多项式）是为了给出一个函数便于车辆选择行驶方向😁

**Comment by MaybeShewill-CV** [comment]
@andeyeluguo 简单理解就是给个方程:)
