### ISSUE TITLE
Tools to generate training dataset

### ISSUE THREAD

**Issue by ArtlyStyles** [MaybeShewill-CV/lanenet-lane-detection#274]
I would like to train the network with my own images. I wondering if there are some tools I can use to easily label the lane in the image?

**Comment by MaybeShewill-CV** [comment]
@ArtlyStyles Try labelimg or labelme:)

**Comment by xxzcxb1314** [comment]
请问可以加我的QQ吗？我这里遇到一些问题 qq 2627084603

**Comment by xxzcxb1314** [comment]
在generate_tusimple_dataset.py模块，我这里只生成了目录，目录里面没有东西，train.txt里也是空的
