### ISSUE TITLE
What is the output_node_names

### ISSUE THREAD

**Issue by ArtlyStyles** [MaybeShewill-CV/lanenet-lane-detection#275]
I want to run Lanenet inference with TensorRT and the input is the original image, output are the segmented binary image, segmented instance image, lane points, and ideally, lane instance fitted by polynomial. I am trying to convert the lanenet trained model to freeze_graph and eventually UFF model. I found a lot of code to do this on the web. However, one parameter to run these code is the "output node names". What output names should I use? I printed out all tensors in the model, as shown below, nothing seems to be what I needed. Could anyone help?Momentum

**Comment by ArtlyStyles** [comment]
I am surprised no one news the ouput node?

**Comment by VasinPA** [comment]
> I am surprised no one news the ouput node?
According to Tensorboard scheme, output nodes is "lanenet_model/vgg_backend/instance_seg/pix_embedding_conv/pix_embedding_conv" for instance segmentation result and "lanenet_model/vgg_backend/binary_seg/ArgMax" for binary segmentation

**Comment by ArtlyStyles** [comment]
@VasinPA Thank you very much. 

"lanenet_model/vgg_backend/instance_seg/pix_embedding_conv/pix_embedding_conv" worked.
But it complained there was no  "lanenet_model/vgg_backend/binary_seg/ArgMax". Actually, as I printed out above, there is no "vgg_backend/binary_seg/..." at all. 

How do we get the binary seg?

**Comment by ArtlyStyles** [comment]
@VasinPA Could you please show Tensorboard scheme?

**Comment by VasinPA** [comment]
@ArtlyStyles, There is two dead-end nodes on scheme, ArgMax and pix_embedding_conv, i suppose they are is output nodes. For now i tested only pix_embedding_conv, and it output really ressembling instance segmentation
![Screenshot from 2019-08-20 08-30-09](https://user-images.githubusercontent.com/25569949/63320075-209ee000-c325-11e9-9b17-ae215eae814d.png)
![Screenshot from 2019-08-20 08-32-35](https://user-images.githubusercontent.com/25569949/63320076-209ee000-c325-11e9-97ab-488cd83f778f.png)

**Comment by ArtlyStyles** [comment]
Which model file (checkpoint files) did you use?

**Comment by VasinPA** [comment]
@ArtlyStyles I use model provided by MaybeShewill, link in README.md:
https://www.dropbox.com/sh/tnsf0lw6psszvy4/AAA81r53jpUI3wLsRW6TiPCya?dl=0

**Comment by ArtlyStyles** [comment]
That's strange. I used the same...

**Comment by VasinPA** [comment]
@ArtlyStyles I created fork of this repo with crude scripts for freezeng model and running frozen model, maybe it can help:
https://github.com/VasinPA/lanenet-lane-detection/tree/master/tools
There are two new scripts: test_lanenet_and_freeze.py, and load-n-run-graph.py try them

**Comment by ArtlyStyles** [comment]
@VasinPA Thanks. However, seems you load-n-run-graph only generate one output image, correct? I need two output image, binary and instance. 

Also, you did not use "lanenet_model/vgg_backend/binary_seg/ArgMax" in test_lanenet_and_freeze.py. Why?

**Comment by VasinPA** [comment]
@ArtlyStyles It is only a crude test of freezing and running this model, you can add ArgMax to output_node_names and it will calculate binary segmentation too.

**Comment by ArtlyStyles** [comment]
@VasinPA Yes, that worked. Thanks a lot. 
However, when I convert the freeze grapha to uff, it complained the node was not inside the graph. Do you know why? Below is the code

`import uff

frozen_filename ='./model-native.pb'
#output_node_names = ['lanenet_model/vgg_backend/instance_seg/pix_embedding_conv/pix_embedding_conv,lanenet_model/vgg_frontend/vgg16_decode_mo
dule/binary_seg_decode/binary_final_logits/binary_final_logits']
output_node_names = ['lanenet_model/vgg_backend/instance_seg/pix_embedding_conv/pix_embedding_conv']
output_uff_filename = './model.uff'

uff_mode = uff.from_tensorflow_frozen_model(frozen_file=frozen_filename, output_nodes=output_node_names, output_filename=output_uff_filename,
text=True)

`

**Comment by VasinPA** [comment]
# @ArtlyStyles sorry for long response, it is "ArgMax" for lanenet_model/vgg_backend/binary_seg/ArgMax, and "Identity" for lanenet_model/vgg_backend/instance_seg/pix_embedding_conv/pix_embedding_conv, as you can see on Tensorboard schemes

**Comment by ArtlyStyles** [comment]
Thanks @VasinPA "identify" means it is the same as previous node. So we should use the node before it. Looks like it is conv2D. What it's the type of "conv2D"?

**Comment by ArtlyStyles** [comment]
I was able to convert the tensorflow checkpoint to uff. But I need to know the input node name of the network. What is the input nodename of Lanenet?

**Comment by MaybeShewill-CV** [comment]
@ArtlyStyles Suggest you use tensorboard to find it:)
