### ISSUE TITLE
测试模型准确性

### ISSUE THREAD

**Issue by whz1994** [MaybeShewill-CV/lanenet-lane-detection#278]
您好，请问模型训练出来怎么去评估它的性能啊？

**Comment by xxzcxb1314** [comment]
> 您好，请问模型训练出来怎么去评估它的性能啊？

不是有曲线变化图吗？准确率和损失   可以加qq 2627084603聊一下

**Comment by whz1994** [comment]
那是训练的准确率和损失，我需要的是测试的准确性这些评价指标




发自网易邮箱大师
在2019年08月12日 16:07，xxzcxb1314 写道：

您好，请问模型训练出来怎么去评估它的性能啊？

不是有曲线变化图吗？准确率和损失 可以加qq 2627084603聊一下

**Comment by MaybeShewill-CV** [comment]
@whz1994 可以参考tusimple和culane数据集的评价指标 github上都能搜到:)

**Comment by whz1994** [comment]
好的，谢谢




发自网易邮箱大师
在2019年08月13日 10:30，MaybeShewill-CV 写道：

@whz1994 可以参考tusimple和culane数据集的评价指标 github上都能搜到:)

**Comment by whz1994** [comment]
您好，可以请您说一下具体怎么在tusimple数据集上评估模型准确性吗？我水平有限实在不知道怎么操作，麻烦您了，谢谢！




发自网易邮箱大师
在2019年08月13日 14:58，MaybeShewill-CV 写道：

Closed #278.

**Comment by MaybeShewill-CV** [comment]
@whz1994 閱讀一下tusimple的eval代碼你就知道了哈:)

**Comment by TommyTang930** [comment]
@whz1994 
您好，请问你是否实现了将CULane的train数据集转换成TuSimple格式的代码呢？

**Comment by whz1994** [comment]
没有，我现在已经不做这个了




发自网易邮箱大师
在2019年10月22日 17:03，唐国梁 Tommy 写道：

@whz1994
您好，请问你是否实现了将CULane的train数据集转换成TuSimple格式的代码呢？
