### ISSUE TITLE
consistency with the original paper

### ISSUE THREAD

**Issue by tabrisweapon** [MaybeShewill-CV/lanenet-lane-detection#28]
我想问下，你的实现是不是和原文有区别的，比如网络结构，后处理的方法等等。如果是，能不能说下具体改了哪些。我完全按照原文实现了一遍，但效果不够好。

**Comment by MaybeShewill-CV** [comment]
@tabrisweapon 就是按照原文实现的, 基础网络不一样,然后我的hnet实现还有点问题最近还没时间修改.你的hnet有效的话也欢迎分享一哈
