### ISSUE TITLE
How do get prediction JSON 

### ISSUE THREAD

**Issue by nikhilbv** [MaybeShewill-CV/lanenet-lane-detection#286]
Hi @MaybeShewill-CV, first of all, great work!! 
I have trained a lanenet model on a custom dataset. Now to find out the acc, fp and fn of a model, I have ground-truth but no prediction JSON file. Is the code missing?

**Comment by cardwing** [comment]
@nikhilbv You can have a look at [my repo](https://github.com/cardwing/Codes-for-Lane-Detection/tree/master/ENet-TuSimple-Torch/evaluate).

**Comment by nikhilbv** [comment]
Hi @cardwing, thank you for replying. I went through your repo. I got to know that lane.py takes two arguments i.e pred_file and gt_file. I have a gt_file and I am looking at how to generate a pred_file. Or correct me if I am missing something

**Comment by cardwing** [comment]
You can generate JSON files using `pred_json.py` in my repo. However, it is intended for ENet-SAD model not LaneNet. You may need to modify some codes in `pred_json.py`.

**Comment by nikhilbv** [comment]
@cardwing, I get it now. Thanks for replying so soon.

**Comment by whz1994** [comment]
> 你

Could you please share how you generate pred_file? I don't know how to modify pred_json.py, thanks

**Comment by whz1994** [comment]
Can you share an assessment of how the lanenet model generates pred_file?I don't know how to modify pred_json.py, thanks

**Comment by whz1994** [comment]
Can you share how lanenet generates pred_file?I don't know how to modify pred_json.py, thanks

**Comment by MaybeShewill-CV** [comment]
@nikhilbv @whz1994 No such script sorry:)

**Comment by whz1994** [comment]
Ok, thank you, have you evaluated lanenet on the tusimple data set?

**Comment by whz1994** [comment]
Ok, thank you, have you evaluated lanenet on the tusimple data set?




At 2019-09-03 18:35:40, "MaybeShewill-CV" <notifications@github.com> wrote:


@nikhilbv@whz1994 No such script sorry:)

**Comment by MaybeShewill-CV** [comment]
@whz1994 Yep. You may check tusimple benchmark and generate the pred.json file according to their requests:)

**Comment by whz1994** [comment]
Can you tell me how to generate the pred.json?







At 2019-09-03 18:46:20, "MaybeShewill-CV" <notifications@github.com> wrote:


@whz1994 Yep. You may check tusimple benchmark and generate the pred.json file according to their requests:)

**Comment by whz1994** [comment]
Can you send me the modified file to generate the pred.json file? whz_1226@163.com, this is my email, thank you





At 2019-09-03 18:46:20, "MaybeShewill-CV" <notifications@github.com> wrote:


@whz1994 Yep. You may check tusimple benchmark and generate the pred.json file according to their requests:)

**Comment by MaybeShewill-CV** [comment]
@whz1994 The script was missing or I will post it here:)

**Comment by whz1994** [comment]
Hope to see your release soon






At 2019-09-03 19:19:09, "MaybeShewill-CV" <notifications@github.com> wrote:


@whz1994 The script was missing or I will post it here:)
