### ISSUE TITLE
About DataSet

### ISSUE THREAD

**Issue by ABexit** [MaybeShewill-CV/lanenet-lane-detection#287]
Hello, thx for sharing, best wishes .
But I have a question about the dataset, Whether it's necessary to generate binary segmentation label images and instance segmentation label images or there're other ways to do it ?
Thx a lot.

**Comment by MaybeShewill-CV** [comment]
@ABexit It's necessary:)

**Comment by ABexit** [comment]
OH, BIg Bro, CAN U SHARE IT WITH ME? <CRYING> BAIDU Forever

**Comment by ABexit** [comment]
> @ABexit It's necessary:)

OH, BIg Bro, CAN U SHARE IT WITH ME? BAIDU Forever AGAIN

**Comment by MaybeShewill-CV** [comment]
@ABexit You may download the dataset via Baidu.com :)

**Comment by ABexit** [comment]
> @ABexit You may download the dataset via Baidu.com :)

I believe in U a ghost   >_<

**Comment by MaybeShewill-CV** [comment]
@ABexit 嘻嘻嘻嘻：）

**Comment by ABexit** [comment]
> @ABexit You may download the dataset via Baidu.com :)

Thx, it's real. Thx sincerely
