### ISSUE TITLE
How to make own model?

### ISSUE THREAD

**Issue by 94JuHo** [MaybeShewill-CV/lanenet-lane-detection#289]
Hi, I'm grateful for your code.
I have a question.
I want to make a model using my data.
But, I don't know how to make a gt_image_binary and gt_image_instance.
Do you need help for me? Thank you.

**Comment by MaybeShewill-CV** [comment]
@94JuHo You may refer to tools/generate_tusimple_dataset.py file:)

**Comment by 94JuHo** [comment]
Thank you for your answer.
However, the intention I asked you is to assign a ground true label to my data, but I don't know which tools to use. Do you know any programs?

**Comment by MaybeShewill-CV** [comment]
@94JuHo check labelme or labelimg tools:)

**Comment by 94JuHo** [comment]
> @94JuHo check labelme or labelimg tools:)

Thank you. i will try it.
