### ISSUE TITLE
inference time

### ISSUE THREAD

**Issue by klnsz** [MaybeShewill-CV/lanenet-lane-detection#29]
Hi. I am using the pretrained model on jetson tx2 and the speed is too slow. It took 3.5 second to process only one image. Do you know what causing is this problem or is this normal speed time? Thank you

**Comment by MaybeShewill-CV** [comment]
@klnsz Most time may be caused during the mean shift clustering process

**Comment by ktr-hubrt** [comment]
> @klnsz Most time may be caused during the mean shift clustering process

Thank you for your amazing work ,however ,when i test the pretrain model on my dataset, i found the preprocess time is around 0.15s , postprocess time is around 0.2s, the most time consume is the network predict time, which is up to 3s,
emm...,may you tell me your test time and your GPU type?

**Comment by ktr-hubrt** [comment]
作者你好，我发现把一张图片放在不同batch中验证，都到的测试结果都不同？，网络的bn有问题？

**Comment by ktr-hubrt** [comment]
> 作者你好，我发现把一张图片放在不同batch中验证，都到的测试结果都不同？，网络的bn有问题？

@MaybeShewill-CV

**Comment by ArtlyStyles** [comment]
Hi @klnsz, could you please let me know if anything special is needed to install this on TX2? Which version of L4T and cuda you are using on Tx2?
