### ISSUE TITLE
Output nodes types

### ISSUE THREAD

**Issue by ArtlyStyles** [MaybeShewill-CV/lanenet-lane-detection#290]
I am trying to convert the trained model to Tensorflow uff so I can run efficiently on Nvidia Jetson TX2. My output nodes are:

lanenet_model/vgg_backend/instance_seg/pix_embedding_conv/pix_embedding_conv
lanenet_model/vgg_backend/binary_seg/ArgMax

However, these two node may not be supported by tensorRT, since when I converted the model to uff, it complained the nodes could not be found in the graph.

Does anyone know the exact type of these two node? What are their tensorflow layer type or name?

**Comment by shortstheory** [comment]
Hey, were you able to find the names of these output nodes?
