### ISSUE TITLE
运行test_lanenet.py，为什么instance_mask_image.png是一张全黑图，没有结果？

### ISSUE THREAD

**Issue by github-luffy** [MaybeShewill-CV/lanenet-lane-detection#291]

**Comment by MaybeShewill-CV** [comment]
@github-luffy 测试数据是demo里面的数据么:)

**Comment by github-luffy** [comment]
是我自己的数据，但是instance_image.png，binary_mask_image.png是有结果的，但postprocess_result['mask_image']与postprocess_result['src_image']都没有结果。

**Comment by MaybeShewill-CV** [comment]
@github-luffy 那可能是后处理的时候有一些超参数不适合你的数据 需要你自己调整:)

**Comment by penglongluan** [comment]
@github-luffy 请问你解决这个问题了吗？怎么解决的

**Comment by github-luffy** [comment]
@penglongluan 在看源码，还没解决呢

**Comment by guoyong-yours** [comment]
@MaybeShewill-CV 大佬，后处理哪些超参数需要调整，我的也是instance_image.png，binary_mask_image.png有结果，但postprocess_result['mask_image']与postprocess_result['src_image']都没有结果

**Comment by guoyong-yours** [comment]
@MaybeShewill-CV 我的也是用的自己的数据

**Comment by guoyong-yours** [comment]
@github-luffy大哥，请问解决了吗

**Comment by MaybeShewill-CV** [comment]
@guoyong-yours 比如dbscan聚類的參數 轉換俯視圖使用的remap矩陣 這些都是需要根據你自己的數據進行調整的參數:)

**Comment by dongwenqi6619** [comment]
请问 生成的文件会再tool目录下吗，为什么我没有生成任何 图片？也没有显示任何图片？

**Comment by huangqianfirst** [comment]
mask_image 全黑和DBSACN方法的参数有关，可能是DBSCAN_MIN_SAMPLES太大了，导致聚类把所有的数都聚到一个类别了。
可以调整config/global_config.py中两个参数：
__C.POSTPROCESS.DBSCAN_EPS = 0.35
# Set the post process dbscan min samples threshold
#__C.POSTPROCESS.DBSCAN_MIN_SAMPLES = 1000
比如我这里把参数调小
__C.POSTPROCESS.DBSCAN_MIN_SAMPLES = 300
就能正确的聚类出三个类别的车道线了。
![image](https://user-images.githubusercontent.com/11473038/68197564-6fd7e100-fff5-11e9-8564-2285c39384f6.png)

**Comment by jiguanglu** [comment]
您好，我虽然显示出这三个车道线，但是在原图上，这三条线就扭曲的厉害，完全不在车道线上。
请问您遇到过类似的情况吗？

**Comment by jiguanglu** [comment]
> mask_image 全黑和DBSACN方法的参数有关，可能是DBSCAN_MIN_SAMPLES太大了，导致聚类把所有的数都聚到一个类别了。
> 可以调整config/global_config.py中两个参数：
> __C.POSTPROCESS.DBSCAN_EPS = 0.35
> __C.POSTPROCESS.DBSCAN_MIN_SAMPLES = 1000
> 比如我这里把参数调小
> __C.POSTPROCESS.DBSCAN_MIN_SAMPLES = 300
> 就能正确的聚类出三个类别的车道线了。
> ![image](https://user-images.githubusercontent.com/11473038/68197564-6fd7e100-fff5-11e9-8564-2285c39384f6.png)
您好，我虽然显示出这三个车道线，但是在原图上，这三条线就扭曲的厉害，完全不在车道线上。
请问您遇到过类似的情况吗？

**Comment by MaybeShewill-CV** [comment]
@jiguanglu 现在的remap.yml只适合用在tusimple数据集上。自己的数据的话需要你自己写后处理过程:)

**Comment by jiguanglu** [comment]
> @jiguanglu 现在的remap.yml只适合用在tusimple数据集上。自己的数据的话需要你自己写后处理过程:)

您好，大佬，现在就是不太清楚如何操作后处理的过程，才向您提问的，如果方便的话，可以加个微信吗？23124264  我有偿求助。

**Comment by china56321** [comment]
> > @jiguanglu 现在的remap.yml只适合用在tusimple数据集上。自己的数据的话需要你自己写后处理过程:)
> 
> 您好，大佬，现在就是不太清楚如何操作后处理的过程，才向您提问的，如果方便的话，可以加个微信吗？23124264 我有偿求助。

请问你解决了吗？我也遇到了这个问题，识别的车道线扭曲的厉害

**Comment by jiguanglu** [comment]
这么没弄好，一直在使用作者提供的yml文件。其实
Jiguang Lu
图形图像算法工程师-北京聚光绘影
AI Engineer at ILLUMINA
Phone: +8613521568943


china56321 <notifications@github.com> 于2020年6月4日周四 下午4:30写道：

**Comment by Jerry-LMB** [comment]
我也在复现你的代码 但在图片上的划线完全没有在车道线上，直接是乱画，请问remap.yaml的如何修改

**Comment by zhsanxiansheng** [comment]
@jiguanglu 

> Reference in new issue
您好，我现在跟你是一样的问题，请问测试的最后一张图车道线扭曲乱飞的问题您解决了吗，.yml文件您是怎么处理的呢
