### ISSUE TITLE
The error about cannot import name 'global_config'

### ISSUE THREAD

**Issue by JeremyCKT** [MaybeShewill-CV/lanenet-lane-detection#292]
When I run the order as follows
python tools/test_lanenet.py --weights_path ./model/tusimple_lanenet_vgg/tusimple_lanenet_vgg.ckpt  --image_path ./data/tusimple_test_image/0.jpg

Then a error occurs
File "tools/test_lanenet.py", line 22, in <module>
    from config import global_config
ImportError: cannot import name 'global_config'

I tried to add config folder in pythonpath but didn't solve it
How to solve the problem about 'global_config' ?
Thanks!!

**Comment by MaybeShewill-CV** [comment]
@JeremyCKT config your PYTHONPATH

**Comment by JeremyCKT** [comment]
@MaybeShewill-CV  I did this but dosen't work
export PYTHONPATH="${PYTHONPATH}:my_path/lanenet-lane-detection-master/config"

**Comment by JeremyCKT** [comment]
I already try to put these in .bashrc but not works

# virtualenv and virtualenvwrapper
export WORKON_HOME=/home/jeremydl/.virtualenvs
export PROJECT_HOME=/home/jeremydl/Devel
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
export VIRTUALENVWRAPPER_VIRTUALENV=/usr/local/bin/virtualenv
export PYTHONPATH="${PYTHONPATH}:home/jeremydl/Downloads/lanenet-lane-detection-master/lanenet_model"
export PYTHONPATH="${PYTHONPATH}:home/jeremydl/Downloads/lanenet-lane-detection-master/config"
source /usr/local/bin/virtualenvwrapper.sh

**Comment by hahakid** [comment]
@JeremyCKT 
1) try to manage the project with pycharm or other IDE
2) add __init__.py to ./config/

**Comment by Angel0003** [comment]
> @JeremyCKT
> 
> 1. try to manage the project with pycharm or other IDE
> 2. add `__init__.py` to ./config/

之前加进去之后可以啦，现在又不行了，咋回事，`__init__.py` 在 ./config/下面呢

**Comment by psd10110** [comment]
> > @JeremyCKT
> > 
> > 1. try to manage the project with pycharm or other IDE
> > 2. add `__init__.py` to ./config/
> 
> 之前加进去之后可以啦，现在又不行了，咋回事，`__init__.py` 在 ./config/下面呢

你解决了吗现在，我也是这个问题

**Comment by anna-1209** [comment]
> > > @JeremyCKT
> > > 
> > > 1. try to manage the project with pycharm or other IDE
> > > 2. add `__init__.py` to ./config/
> > 
> > 
> > 之前加进去之后可以啦，现在又不行了，咋回事，`__init__.py` 在 ./config/下面呢
> 
> 你解决了吗现在，我也是这个问题

我遇到了同样的问题，请问您解决了吗

**Comment by byq-luo** [comment]
> > > > @JeremyCKT
> > > > 
> > > > 1. try to manage the project with pycharm or other IDE
> > > > 2. add `__init__.py` to ./config/
> > > 
> > > 
> > > 之前加进去之后可以啦，现在又不行了，咋回事，`__init__.py` 在 ./config/下面呢
> > 
> > 
> > 你解决了吗现在，我也是这个问题
> 
> 我遇到了同样的问题，请问您解决了吗

遇到同样的问题，不知道怎么解决了

**Comment by weihao-ysgs** [comment]
because the python have the package named config
use the commit : pip uninstall config, 
to uninstall the config, then is OK!
