### ISSUE TITLE
About retraining

### ISSUE THREAD

**Issue by JeremyCKT** [MaybeShewill-CV/lanenet-lane-detection#294]
I'm trying to retrain with new data, as I modified the train.txt and val.txt into correct directories, 

train.txt
/home/jeremydl/Downloads/lanenet-lane-detection-master/data/training_data_example/image/0000.png /home/jeremydl/Downloads/lanenet-lane-detection-master/data/training_data_example/gt_image_binary/0000.png /home/jeremydl/Downloads/lanenet-lane-detection-master/data/training_data_example/gt_image_instance/0000.png
/home/jeremydl/Downloads/lanenet-lane-detection-master/data/training_data_example/image/0001.png /home/jeremydl/Downloads/lanenet-lane-detection-master/data/training_data_example/gt_image_binary/0001.png /home/jeremydl/Downloads/lanenet-lane-detection-master/data/training_data_example/gt_image_instance/0001.png
/home/jeremydl/Downloads/lanenet-lane-detection-master/data/training_data_example/image/0002.png /home/jeremydl/Downloads/lanenet-lane-detection-master/data/training_data_example/gt_image_binary/0002.png /home/jeremydl/Downloads/lanenet-lane-detection-master/data/training_data_example/gt_image_instance/0002.png
/home/jeremydl/Downloads/lanenet-lane-detection-master/data/training_data_example/image/0003.png /home/jeremydl/Downloads/lanenet-lane-detection-master/data/training_data_example/gt_image_binary/0000.png /home/jeremydl/Downloads/lanenet-lane-detection-master/data/training_data_example/gt_image_instance/0003.png

val.txt
/home/jeremydl/Downloads/lanenet-lane-detection-master/data/training_data_example/image/0004.png /home/jeremydl/Downloads/lanenet-lane-detection-master/data/training_data_example/gt_image_binary/0004.png /home/jeremydl/Downloads/lanenet-lane-detection-master/data/training_data_example/gt_image_instance/0004.png
/home/jeremydl/Downloads/lanenet-lane-detection-master/data/training_data_example/image/0005.png /home/jeremydl/Downloads/lanenet-lane-detection-master/data/training_data_example/gt_image_binary/0005.png /home/jeremydl/Downloads/lanenet-lane-detection-master/data/training_data_example/gt_image_instance/0005.png

But after I entered the code
python3 data_provider/lanenet_data_feed_pipline.py --dataset_dir ./data/training_data_example --tfrecords_dir ./data/training_data_example/tfrecords
Then the error still happens
ValueError: Source image data is not complete, please check if one of the image folder is not exist

How to fix the problem?

By the way, when I entered the code
python3 tools/train_lanenet.py --net vgg --dataset_dir ./data/training_data_example -m 0
Then an error occurs
AssertionError: ./data/vgg16.npy not exist
Seems that a file vgg16.npy is missing, where can I download it?

**Comment by JeremyCKT** [comment]
> @JeremyCKT You can google it and you may find it somewhere:)

Thank you! I finally found the vgg16.npy and downloaded it.
But when I entered the code again.
Another error occured.

OutOfRangeError (see above for traceback): End of sequence
	 [[node train_IteratorGetNext (defined at /home/jeremydl/Downloads/lanenet-lane-detection-master/data_provider/lanenet_data_feed_pipline.py:365)  = IteratorGetNext[output_shapes=[[4,256,512,3], [4,256,512,1], [4,256,512,1]], output_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](input_tensor/OneShotIterator)]]
	 [[{{node lanenet_model/vgg_backend/instance_seg/while/UniqueWithCounts/_79}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_623_lanenet_model/vgg_backend/instance_seg/while/UniqueWithCounts", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](^_clooplanenet_model/vgg_backend/instance_seg/while/Cast/_42)]]

Is there anything wrong about the data?

**Comment by JeremyCKT** [comment]
The full error shows that

Caused by op 'train_IteratorGetNext', defined at:
  File "tools/train_lanenet.py", line 710, in <module>
    train_lanenet(args.dataset_dir, args.weights_path, net_flag=args.net_flag)
  File "tools/train_lanenet.py", line 235, in train_lanenet
    CFG.TRAIN.BATCH_SIZE, 1
  File "/home/jeremydl/Downloads/lanenet-lane-detection-master/data_provider/lanenet_data_feed_pipline.py", line 365, in inputs
    return iterator.get_next(name='{:s}_IteratorGetNext'.format(self._dataset_flags))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 421, in get_next
    name=name)), self._output_types,
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_dataset_ops.py", line 2069, in iterator_get_next
    output_shapes=output_shapes, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

OutOfRangeError (see above for traceback): End of sequence
	 [[node train_IteratorGetNext (defined at /home/jeremydl/Downloads/lanenet-lane-detection-master/data_provider/lanenet_data_feed_pipline.py:365)  = IteratorGetNext[output_shapes=[[4,256,512,3], [4,256,512,1], [4,256,512,1]], output_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](input_tensor/OneShotIterator)]]
	 [[{{node lanenet_model/vgg_backend/instance_seg/while/UniqueWithCounts/_79}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_623_lanenet_model/vgg_backend/instance_seg/while/UniqueWithCounts", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](^_clooplanenet_model/vgg_backend/instance_seg/while/Cast/_42)]]

**Comment by MaybeShewill-CV** [comment]
@JeremyCKT Which version of Tensorflow did you use:)

**Comment by pkadams** [comment]
Hi, I also get the issue -> 
ValueError: Source image data is not complete, please check if one of the image folder is not exist

How did JeremyCKT fix that issue? Any help would be amazing.

**Comment by pkadams** [comment]
I figured it out! 

The folders in the data/training_data_example should be named gt_image, gt_binary_image and gt_instance_image. 

In the repo, they are named slightly differently

**Comment by JeremyCKT** [comment]
> @JeremyCKT Which version of Tensorflow did you use:)

@MaybeShewill-CV  My TensorFlow gpu version is 1.12.0

**Comment by JeremyCKT** [comment]
> I figured it out!
> 
> The folders in the data/training_data_example should be named gt_image, gt_binary_image and gt_instance_image.
> 
> In the repo, they are named slightly differently

I didn't fixed.
By the way, when I changed the folder "image" name into "gt_image" ,
then another error occured.

Traceback (most recent call last):
  File "data_provider/lanenet_data_feed_pipline.py", line 372, in <module>
    assert ops.exists(args.dataset_dir), '{:s} not exist'.format(args.dataset_dir)
AssertionError: ./data/training_data_example/image not exist

**Comment by MaybeShewill-CV** [comment]
@JeremyCKT Your input data was not correctly supplied. Reprepare the training samples according the code in data_provider/lanenet_data_feed_pipline.py:)

**Comment by JeremyCKT** [comment]
> I figured it out!
> 
> The folders in the data/training_data_example should be named gt_image, gt_binary_image and gt_instance_image.
> 
> In the repo, they are named slightly differently

@pkadams 

I finally fixed by renamed these folders in data/training_data_example, and successfully generate the tensorflow records file. Thanks a lot!!

But when training model by insert the code
python tools/train_lanenet.py --net vgg --dataset_dir ./data/training_data_example -m 0

Same error still occurs.

W0930 17:11:22.336742 15173 gradients_impl.py:112] /usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gradients_impl.py:112: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "

2019-09-30 17:11:25.273111: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-09-30 17:11:25.920245: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-09-30 17:11:25.920667: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.607
pciBusID: 0000:01:00.0
totalMemory: 10.91GiB freeMemory: 10.75GiB
2019-09-30 17:11:25.920681: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-09-30 17:11:26.106014: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-09-30 17:11:26.106035: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2019-09-30 17:11:26.106040: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2019-09-30 17:11:26.106189: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10613 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
I0930 17:11:26.794609 15173 train_lanenet.py:405] Global configuration is as follows:
I0930 17:11:26.794828 15173 train_lanenet.py:406] {'TEST': {'TF_ALLOW_GROWTH': True, 'GPU_MEMORY_FRACTION': 0.8, 'BATCH_SIZE': 2}, 'TRAIN': {'EPOCHS': 80010, 'LEARNING_RATE': 0.0005, 'CLASSES_NUMS': 2, 'VAL_DISPLAY_STEP': 1000, 'EMBEDDING_FEATS_DIMS': 4, 'TF_ALLOW_GROWTH': True, 'GPU_MEMORY_FRACTION': 0.95, 'MOMENTUM': 0.9, 'CPU_MULTI_PROCESS_NUMS': 6, 'VAL_BATCH_SIZE': 4, 'IMG_WIDTH': 512, 'MOVING_AVERAGE_DECAY': 0.9999, 'CROP_PAD_SIZE': 32, 'GPU_NUM': 2, 'DISPLAY_STEP': 1, 'IMG_HEIGHT': 256, 'BATCH_SIZE': 4}, 'POSTPROCESS': {'DBSCAN_EPS': 0.35, 'DBSCAN_MIN_SAMPLES': 1000, 'MIN_AREA_THRESHOLD': 100}}
I0930 17:11:26.795816 15173 train_lanenet.py:411] Training from scratch
W0930 17:11:47.338188 15173 _methods.py:65] /usr/local/lib/python3.5/dist-packages/numpy/core/fromnumeric.py:2920: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)

W0930 17:11:47.338571 15173 _methods.py:85] /usr/local/lib/python3.5/dist-packages/numpy/core/_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)

I0930 17:11:47.338638 15173 train_lanenet.py:454] Epoch: 1 total_loss= 35.357826 binary_seg_loss= 1.430907 instance_seg_loss= 30.797335 accuracy= 0.559711 fp= 0.980064 fn= 0.440289 lr= 0.000500 mean_cost_time=   nans 
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.OutOfRangeError: End of sequence
	 [[{{node val_IteratorGetNext}} = IteratorGetNext[output_shapes=[[4,256,512,3], [4,256,512,1], [4,256,512,1]], output_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](input_tensor_1/OneShotIterator)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train_lanenet.py", line 710, in <module>
    train_lanenet(args.dataset_dir, args.weights_path, net_flag=args.net_flag)
  File "tools/train_lanenet.py", line 465, in train_lanenet
    val_images, val_binary_labels, val_instance_labels])
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: End of sequence
	 [[node val_IteratorGetNext (defined at /home/jeremydl/Downloads/lanenet-lane-detection-master/data_provider/lanenet_data_feed_pipline.py:365)  = IteratorGetNext[output_shapes=[[4,256,512,3], [4,256,512,1], [4,256,512,1]], output_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](input_tensor_1/OneShotIterator)]]

Caused by op 'val_IteratorGetNext', defined at:
  File "tools/train_lanenet.py", line 710, in <module>
    train_lanenet(args.dataset_dir, args.weights_path, net_flag=args.net_flag)
  File "tools/train_lanenet.py", line 299, in train_lanenet
    CFG.TRAIN.VAL_BATCH_SIZE, 1
  File "/home/jeremydl/Downloads/lanenet-lane-detection-master/data_provider/lanenet_data_feed_pipline.py", line 365, in inputs
    return iterator.get_next(name='{:s}_IteratorGetNext'.format(self._dataset_flags))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 421, in get_next
    name=name)), self._output_types,
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_dataset_ops.py", line 2069, in iterator_get_next
    output_shapes=output_shapes, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

OutOfRangeError (see above for traceback): End of sequence
	 [[node val_IteratorGetNext (defined at /home/jeremydl/Downloads/lanenet-lane-detection-master/data_provider/lanenet_data_feed_pipline.py:365)  = IteratorGetNext[output_shapes=[[4,256,512,3], [4,256,512,1], [4,256,512,1]], output_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](input_tensor_1/OneShotIterator)]]

**Comment by MaybeShewill-CV** [comment]
@JeremyCKT Maybe your tfrecords was not correctly generated:)

**Comment by JeremyCKT** [comment]
> @JeremyCKT Maybe your tfrecords was not correctly generated:)

@MaybeShewill-CV  How to make sure my tfrecords was generated correctly or not??

**Comment by monilshah1988** [comment]
@JeremyCKT How did you generate tf records. When I tried to generate it, it keeps showing me error of local utils . What do we need to change in config/yaml file? Can you help me?

<img width="1657" alt="Screen Shot 2020-08-28 at 1 48 07 PM" src="https://user-images.githubusercontent.com/22041656/91613973-74c7a180-e935-11ea-8ba0-a57c54a24da8.png">

**Comment by yuanqiyin** [comment]
@JeremyCKT Has your problem been solved? I also encountered the same problem. Could you please give me some suggestions? Thank you 

> 
> 
> > I figured it out!
> > The folders in the data/training_data_example should be named gt_image, gt_binary_image and gt_instance_image.
> > In the repo, they are named slightly differently
> 
> @pkadams
> 
> I finally fixed by renamed these folders in data/training_data_example, and successfully generate the tensorflow records file. Thanks a lot!!
> 
> But when training model by insert the code
> python3 tools/train_lanenet.py --net vgg --dataset_dir ./data/training_data_example -m 0
> 
> Same error still occurs.
> 
> W0930 17:11:22.336742 15173 gradients_impl.py:112] /usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gradients_impl.py:112: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
> "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
> 
> 2019-09-30 17:11:25.273111: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
> 2019-09-30 17:11:25.920245: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2019-09-30 17:11:25.920667: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties:
> name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.607
> pciBusID: 0000:01:00.0
> totalMemory: 10.91GiB freeMemory: 10.75GiB
> 2019-09-30 17:11:25.920681: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
> 2019-09-30 17:11:26.106014: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
> 2019-09-30 17:11:26.106035: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988] 0
> 2019-09-30 17:11:26.106040: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0: N
> 2019-09-30 17:11:26.106189: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10613 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
> I0930 17:11:26.794609 15173 train_lanenet.py:405] Global configuration is as follows:
> I0930 17:11:26.794828 15173 train_lanenet.py:406] {'TEST': {'TF_ALLOW_GROWTH': True, 'GPU_MEMORY_FRACTION': 0.8, 'BATCH_SIZE': 2}, 'TRAIN': {'EPOCHS': 80010, 'LEARNING_RATE': 0.0005, 'CLASSES_NUMS': 2, 'VAL_DISPLAY_STEP': 1000, 'EMBEDDING_FEATS_DIMS': 4, 'TF_ALLOW_GROWTH': True, 'GPU_MEMORY_FRACTION': 0.95, 'MOMENTUM': 0.9, 'CPU_MULTI_PROCESS_NUMS': 6, 'VAL_BATCH_SIZE': 4, 'IMG_WIDTH': 512, 'MOVING_AVERAGE_DECAY': 0.9999, 'CROP_PAD_SIZE': 32, 'GPU_NUM': 2, 'DISPLAY_STEP': 1, 'IMG_HEIGHT': 256, 'BATCH_SIZE': 4}, 'POSTPROCESS': {'DBSCAN_EPS': 0.35, 'DBSCAN_MIN_SAMPLES': 1000, 'MIN_AREA_THRESHOLD': 100}}
> I0930 17:11:26.795816 15173 train_lanenet.py:411] Training from scratch
> W0930 17:11:47.338188 15173 _methods.py:65] /usr/local/lib/python3.5/dist-packages/numpy/core/fromnumeric.py:2920: RuntimeWarning: Mean of empty slice.
> out=out, **kwargs)
> 
> W0930 17:11:47.338571 15173 _methods.py:85] /usr/local/lib/python3.5/dist-packages/numpy/core/_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
> ret = ret.dtype.type(ret / rcount)
> 
> I0930 17:11:47.338638 15173 train_lanenet.py:454] Epoch: 1 total_loss= 35.357826 binary_seg_loss= 1.430907 instance_seg_loss= 30.797335 accuracy= 0.559711 fp= 0.980064 fn= 0.440289 lr= 0.000500 mean_cost_time= nans
> Traceback (most recent call last):
> File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1334, in _do_call
> return fn(*args)
> File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
> options, feed_dict, fetch_list, target_list, run_metadata)
> File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
> run_metadata)
> tensorflow.python.framework.errors_impl.OutOfRangeError: End of sequence
> [[{{node val_IteratorGetNext}} = IteratorGetNext[output_shapes=[[4,256,512,3], [4,256,512,1], [4,256,512,1]], output_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](input_tensor_1/OneShotIterator)]]
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "tools/train_lanenet.py", line 710, in
> train_lanenet(args.dataset_dir, args.weights_path, net_flag=args.net_flag)
> File "tools/train_lanenet.py", line 465, in train_lanenet
> val_images, val_binary_labels, val_instance_labels])
> File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 929, in run
> run_metadata_ptr)
> File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1152, in _run
> feed_dict_tensor, options, run_metadata)
> File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1328, in _do_run
> run_metadata)
> File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1348, in _do_call
> raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.OutOfRangeError: End of sequence
> [[node val_IteratorGetNext (defined at /home/jeremydl/Downloads/lanenet-lane-detection-master/data_provider/lanenet_data_feed_pipline.py:365) = IteratorGetNext[output_shapes=[[4,256,512,3], [4,256,512,1], [4,256,512,1]], output_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](input_tensor_1/OneShotIterator)]]
> 
> Caused by op 'val_IteratorGetNext', defined at:
> File "tools/train_lanenet.py", line 710, in
> train_lanenet(args.dataset_dir, args.weights_path, net_flag=args.net_flag)
> File "tools/train_lanenet.py", line 299, in train_lanenet
> CFG.TRAIN.VAL_BATCH_SIZE, 1
> File "/home/jeremydl/Downloads/lanenet-lane-detection-master/data_provider/lanenet_data_feed_pipline.py", line 365, in inputs
> return iterator.get_next(name='{:s}_IteratorGetNext'.format(self._dataset_flags))
> File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 421, in get_next
> name=name)), self._output_types,
> File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_dataset_ops.py", line 2069, in iterator_get_next
> output_shapes=output_shapes, name=name)
> File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
> op_def=op_def)
> File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
> return func(*args, **kwargs)
> File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
> op_def=op_def)
> File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1770, in **init**
> self._traceback = tf_stack.extract_stack()
> 
> OutOfRangeError (see above for traceback): End of sequence
> [[node val_IteratorGetNext (defined at /home/jeremydl/Downloads/lanenet-lane-detection-master/data_provider/lanenet_data_feed_pipline.py:365) = IteratorGetNext[output_shapes=[[4,256,512,3], [4,256,512,1], [4,256,512,1]], output_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](input_tensor_1/OneShotIterator)]]
