### ISSUE TITLE
Can I train with different angles of photography?

### ISSUE THREAD

**Issue by BBeomH** [MaybeShewill-CV/lanenet-lane-detection#295]
I want to create a model that extracts lanes from cctv footage.
The angle you see from above, and the direction is not constant.I think I need a lot of data and learning amount.
Have you tried this? Or is it worth the attempt?

**Comment by MaybeShewill-CV** [comment]
@BBeomH Worth attempt:)

**Comment by BBeomH** [comment]
Thank you for the reply.
The training data includes original photos, binary photos, and instance photos. Did you have any tools to help you generate them?
If not, letting us know how you created the training data.

Finally, I wonder how many photos were used on the current model and how long it took.

I hope I will get good results from this attempt.

Thank you.

**Comment by MaybeShewill-CV** [comment]
@BBeomH You may search Lableme or Labeling tools to generate the training samples:)
