### ISSUE TITLE
About the speed

### ISSUE THREAD

**Issue by ashergaga** [MaybeShewill-CV/lanenet-lane-detection#297]
Excuse me, when I test the model, the mean inference time every single image is about 1 second. But you said it could achieve 50fps. Do you know what's the problem? Thanks.

**Comment by MaybeShewill-CV** [comment]
@ashergaga 1.That's not my paper. 2.Origin paper use Enet as backbone net but I use vgg16 as backbone net so speed will not get as fast as that. 3.Gpu need a short time to warm up and you can adjust your batch size to test the speed again:)

**Comment by ashergaga** [comment]
@MaybeShewill-CV I didn't find where to adjust the batch size, can you tell me?

**Comment by MaybeShewill-CV** [comment]
@ashergaga You need to modified the code yourself:)
