### ISSUE TITLE
About training the binary segmentation branch

### ISSUE THREAD

**Issue by monsterlyg** [MaybeShewill-CV/lanenet-lane-detection#299]
我仅仅对binary segmentation分支进行了训练 但是训练效果很差 最后损失稳定在0.3左右 实际上网络的输出可以说也很不好 检测出的车道线会非常宽 而且有很多的漏检和误检 。两个分支同时训练 ，第二个pixel embedding分支，是不是会对第一个分支也有积极作用 ？您在文件里提供的binary损失最后已经很低；
（图上传不了 算了。。。）

**Comment by MaybeShewill-CV** [comment]
@monsterlyg 我在tusimple数据集上也训练过这个binary segmentation,训练结果也挺好的啊==!
