### ISSUE TITLE
Can I get a model trained on tusimple lane dataset?

### ISSUE THREAD

**Issue by Seanbbbb** [MaybeShewill-CV/lanenet-lane-detection#300]
Because the link that you posted is not correct  so I can't get accessed to the dataset.

So.. could you please re-upload tusimple lane dataset?

**Comment by MaybeShewill-CV** [comment]
@Seanbbbb The dataset was not available now:)

**Comment by Seanbbbb** [comment]
and... Could I use quote your reports on my paper working?

**Comment by Seanbbbb** [comment]
and... Could I use quote your reports on my paper working?

**Comment by MaybeShewill-CV** [comment]
@Seanbbbb My reports?
