### ISSUE TITLE
 index of lanes that are not predicted by lanenet

### ISSUE THREAD

**Issue by nikhilbv** [MaybeShewill-CV/lanenet-lane-detection#304]
Hi! I am facing trouble in identifing the index of lanes that are not predicted by lanenet in the preprocessing stage. I am assuming that the prediction json has to be sequenced like the tusimple training data inorder to calculate the accuracy. Thanks in advance

**Comment by MaybeShewill-CV** [comment]
@nikhilbv If you want to evaluate your model using the tusimple dataset test scripts you need to generate the pred.json file yourself which is not supplied here:)

**Comment by nikhilbv** [comment]
Thank you for replying real soon. I have trained the lanenet on my own dataset using a tusimple dataset specification. Is there any other way to evaluate the model without using the tusimple dataset test scripts?

**Comment by MaybeShewill-CV** [comment]
@nikhilbv Eg. Simply calculate the precision and recall value in pixel level:)

**Comment by nikhilbv** [comment]
@MaybeShewill-CV Thank you for the suggestion
