### ISSUE TITLE
CULane Training

### ISSUE THREAD

**Issue by TommyTang930** [MaybeShewill-CV/lanenet-lane-detection#307]
Sorry to ask you that how to set up CULane datasets for training ? 

I have already read all of issues concerning with CULane, but didn't find the suggestions how to set up CULane datasets. Hope you offer some suggestions. Thank you :)

**Comment by MaybeShewill-CV** [comment]
@TommyTang930 Write a simple tools to generate the gt_image gt_bianry_image and gt_instance_image yourself:)

**Comment by MaybeShewill-CV** [comment]
@TommyTang930 Sorry. Do not have that kind of link:)
