### ISSUE TITLE
Old models needed for the ROS-friendly version

### ISSUE THREAD

**Issue by Asylbeck** [MaybeShewill-CV/lanenet-lane-detection#311]
Hello Can you provide the models that work with this ROS-version [ROS_LANE_NET](https://github.com/AbangLZU/LaneNetRos)?  I believe it is the original model that worked with these requirements:
easydict==1.6
opencv_python==3.4.1.15
glog==0.3.1
tensorflow_gpu==1.10.0
numpy==1.13.1
matplotlib==2.0.2
scikit_learn==0.19.1
tensorflow==1.10.0

**Comment by MaybeShewill-CV** [comment]
@Asylbeck Sorry can not find the old ckpt weights file:)
