### ISSUE TITLE
ValueError: The passed save_path is not a valid checkpoint

### ISSUE THREAD

**Issue by sam0983** [MaybeShewill-CV/lanenet-lane-detection#312]
Hi,

when I use your model for test_lanenet.py, it works fine, but when I try it with evaluate_lanenet_on_tusimple.py, the following error occurs:
ValueError: The passed save_path is not a valid checkpoint: ./model/tusimple_lanenet_vgg/tusimple_lanenet.ckpt
what's the problem here? Thank you.

**Comment by MaybeShewill-CV** [comment]
@sam0983 Check your kept file path:)

**Comment by sam0983** [comment]
thank you
