### ISSUE TITLE
cannot import name 'global_config' from 'config'

### ISSUE THREAD

**Issue by dongwenqi6619** [MaybeShewill-CV/lanenet-lane-detection#313]
when i do python tools/test_lanenet.py --is_batch False --batch_size 1 --weights_path ./model tusimple_lanenet_vgg_2018-10-19-13-33-56.ckpt-200000.data-00000-of-00001 --image_path data/tusimple_test_image/0.jpg, it doest work and reply  

cannot import name 'global_config' from 'config'

python tools/test_lanenet.py --weights_path ./model/tusimple_lanenet_vgg/tusimple_lanenet_vgg.ckpt 
--image_path ./data/tusimple_test_image/0.jpg    the same ~~~~~

**Comment by dongwenqi6619** [comment]
help me thanks

**Comment by MaybeShewill-CV** [comment]
@dongwenqi6619 Add Project root dir to your PYTHONPATH
