### ISSUE TITLE
Not found: Key lanenet_model/vgg_backend/instance_seg/pix_bn/beta not found in checkpoint

### ISSUE THREAD

**Issue by dongwenqi6619** [MaybeShewill-CV/lanenet-lane-detection#314]
Not found: Key lanenet_model/vgg_backend/instance_seg/pix_bn/beta not found in checkpoint 

how to solve this question？？！！！

**Comment by dongwenqi6619** [comment]
help！

**Comment by MaybeShewill-CV** [comment]
@dongwenqi6619 Make sure you have downloaded the right ckpt weights file:)

**Comment by dongwenqi6619** [comment]
> @dongwenqi6619 Make sure you have downloaded the right ckpt weights file:)

i down 5files    : 
 checkpoint  
lanenet_model.pb
tusimple_lanenet_vgg_2018-10-19-13-33-56.ckpt-200000.data-00000-of-00001
tusimple_lanenet_vgg_2018-10-19-13-33-56.ckpt-200000.index 
tusimple_lanenet_vgg_2018-10-19-13-33-56.ckpt-200000.meta

and i have put them in the right place (\model\tusimple_lanenet_vgg)

the wrong said  lanenet_model/vgg_backend/instance_seg/pix_bn/beta not found in checkpoint 
README.md dont Mention this object .......

**Comment by MaybeShewill-CV** [comment]
@dongwenqi6619 This happened mainly due to the mismatch between your local code and the ckpt weights file. Weights file can be found here https://www.dropbox.com/sh/tnsf0lw6psszvy4/AAA81r53jpUI3wLsRW6TiPCya?dl=0. You may refer to README file for details:)
