### ISSUE TITLE
How to use the network output

### ISSUE THREAD

**Issue by ArtlyStyles** [MaybeShewill-CV/lanenet-lane-detection#315]
I have successfully install and tested the repo on Jetson Xaiver. However, how can I use this network?

Suppose I am running this network on live video feed on my car, I would like to find the lane my car is driving and then find the middle point of the lane in front of the car, and use that to autonomously driving the car. How can I achieve that?

**Comment by MaybeShewill-CV** [comment]
@ArtlyStyles This network can only tell you how many lanes are there in your image and where they   are placed in. You need to find out your own way to get what you want:)
