### ISSUE TITLE
Real Time

### ISSUE THREAD

**Issue by sieuwe1** [MaybeShewill-CV/lanenet-lane-detection#316]
Hi 

Is there a implementation available to run this model real time on a video stream. 

Thanks

Sieuwe

**Comment by cardwing** [comment]
The ENet-SAD model can run in real-time but is different from the lanenet model. More details can be found [here](https://github.com/cardwing/Codes-for-Lane-Detection).

**Comment by MaybeShewill-CV** [comment]
@sieuwe1 Not have tools to implement that yet:)

**Comment by sieuwe1** [comment]
@MaybeShewill-CV  thanks for your reply. I did try to make it real time by adding a while loop that loops over the frames of a video and then runs your model on every frame. But this was really slow! Something like 1 frame per 5 seconds.

@cardwing  is there an python implementation for this model?

Greetings Sieuwe
