### ISSUE TITLE
Any updates on releasing lanenet model trained on culane dataset? <eom>

### ISSUE THREAD

**Issue by nikhilbv** [MaybeShewill-CV/lanenet-lane-detection#317]

**Comment by MaybeShewill-CV** [comment]
@nikhilbv Sorry for that:)

**Comment by nikhilbv** [comment]
@MaybeShewill-CV I am curious about it as it is mentioned in `Recently updates 2018.11.10` of README

**Comment by MaybeShewill-CV** [comment]
@nikhilbv I have trained the model on culane dataset on myself:)

**Comment by nikhilbv** [comment]
@MaybeShewill-CV Are you releasing the model anytime soon?

**Comment by MaybeShewill-CV** [comment]
@nikhilbv No plan for this recently:)

**Comment by nikhilbv** [comment]
@MaybeShewill-CV Thank you for replying so soon

**Comment by sam0983** [comment]
Hi, just out of curiosity, was the accuracy of training on CULane similar to Tusimple? Thank you.
