### ISSUE TITLE
Test without training will cause low accuracy

### ISSUE THREAD

**Issue by zouzhenhong98** [MaybeShewill-CV/lanenet-lane-detection#318]
I simply test your code using .jpg file directly as indicated in your readme.md file and my record is shown below:
[1] test tusimple image from the test folder, it works pretty good.
[2] test my own image from mobilephone shot, didn't work.
[3] test on culane, kitti, caltech-lanes image, none worked.
![kitti](https://user-images.githubusercontent.com/26429253/68755326-3c521380-0600-11ea-84ee-8a50dee57982.jpg)
![kitti_binary_mask_image](https://user-images.githubusercontent.com/26429253/68755358-4bd15c80-0600-11ea-8f18-a38500e22900.png)
[4] test on another tusimple image, worked well again.
[5] test on the same tusimple image in [4], with half of the image masked in black, works well again,
[6] test on the tusimple in [4] and kitti in [3], I combine two images to make each one occupying half of the image, one on left side and another right, it works!
![test++_source_image](https://user-images.githubusercontent.com/26429253/68755092-e1b8b780-05ff-11ea-977d-126c9220a1c4.png)
[7] test on the tusimple in [4], I mask the right side, them do reversion of the left side to obtain a symmetry image, it worked again.
![test+++_source_image](https://user-images.githubusercontent.com/26429253/68755128-f1380080-05ff-11ea-8906-1768fb187734.png)
[8] do the same thing in [7] on the kitti in [3], it worked!
![test++++_source_image](https://user-images.githubusercontent.com/26429253/68755151-f7c67800-05ff-11ea-8283-88d50b4837f9.png)

Error reported:
in [2][3][4], model returned binary_mask_image but not instance_mask_image, and no detected lane shown in the source_image.
in [5][6][7][8], model returned both binary_mask_image and instance_mask_image, but failed to located detected lanes on the correct place on the source_image, always on the 'sky'.

**Comment by zouzhenhong98** [comment]
The masked tusimple image
![test_source_image](https://user-images.githubusercontent.com/26429253/68757009-1c701f00-0603-11ea-9b29-8e620c83d4e6.png)
![test_instance_mask_image](https://user-images.githubusercontent.com/26429253/68757034-25f98700-0603-11ea-9742-8ffc7709df79.png)

**Comment by MaybeShewill-CV** [comment]
@zouzhenhong98 1.模型是在tusimple上训练的 在别的数据集上表现不佳也是正常现象 2.repo里面的后处理过程包括但不限于dbscan聚类，ipm转换，车道线方程拟合相关的参数都是根据tusimple数据集定制的，所以在别的数据上无法有效泛化 3.如果要在别的数据上测试效果，建议只观察binary segmentation的掩码结果和pixel embedding结果，pixel embedding结果既可以通过归一化到[0-255]以四维图像的数据形式观察，也可以自行调节聚类参数或者替换自己的聚类方法得到聚类的instance segmentation掩码结果。后处理部分在别的数据集上无法直接使用：）

**Comment by tareeqav** [comment]
I had the exact same experience @zouzhenhong98 just now.  The google translate of the above is


1. The model is trained on tusimple and it is normal in other data sets. 
2. The post-processing process in repo includes but not limited to dbscan clustering, ipm conversion, lane line equation fitting related parameters are According to the tusimple data set customization, it can not be effectively generalized on other data. 
3. If you want to test the effect on other data, it is recommended to observe only the binary segmentation mask result and pixel embedding result. The pixel embedding result can be passed back. Once it is observed in [0-255] in the form of data of four-dimensional images, it is also possible to adjust the clustering parameters or replace its own clustering method to obtain the instance segmentation mask result of the cluster. The post-processing part cannot be used directly on other data sets :)
I have to try out the post-processing differently.  @zouzhenhong98 have you accomplished this already?

**Comment by luyuliu** [comment]
I have the same issue here. Most of the pictures won't give a result and some working pictures are not quite good. I assume the working pictures' binary segmentation is right, but perhaps the final step to merge results and raw pictures have something wrong, or compatible issues.

**Comment by MaybeShewill-CV** [comment]
@luyuliu The potprocess process is not a common procedure it's dataset related:)
