### ISSUE TITLE
channel qusetion?

### ISSUE THREAD

**Issue by y11203090135** [MaybeShewill-CV/lanenet-lane-detection#32]
请问：为什么训练您的数据集时，在图片预处理
label_img = cv2.imread(gt_label_path, cv2.IMREAD_UNCHANGED)时，可以将
(720, 1280, 3)变为(720, 1280)
我用自己的训练集，处理之后
(720, 1280, 3)还是(720, 1280，3)
这是什么原因呢？

**Comment by MaybeShewill-CV** [comment]
@y11203090135 imread不会改变通道数的

**Comment by y11203090135** [comment]
但是我用您的训练样例
在图片预处理
label_img = cv2.imread(gt_label_path, cv2.IMREAD_UNCHANGED)时，将
(720, 1280, 3)变为(720, 1280)

**Comment by MaybeShewill-CV** [comment]
@y11203090135 因为我保存的时候就是一通道的啊＝＝！

**Comment by y11203090135** [comment]
@MaybeShewill-CV 可以了，thank you!
