### ISSUE TITLE
testing on my own data and get lane coordinates

### ISSUE THREAD

**Issue by jingw0129** [MaybeShewill-CV/lanenet-lane-detection#320]
您好，想问一下，如果用此模型跑自己的数据集并得到坐标，要做什么改动呢？目前在自己录制的视频得到的帧上看效果不是特别好。
希望得到回复，
谢谢

**Comment by MaybeShewill-CV** [comment]
@jingw0129 需要看后处理过程的代码然后改成适合自己数据集的处理过程。repo里的后处理过程只适合tusimple数据集:)

**Comment by jingw0129** [comment]
您好，谢谢回复。
如果车道线空白部分不想检测（例如虚线车道线，只标注白色部分），要做什么处理，您有什么建议吗？

**Comment by MaybeShewill-CV** [comment]
@jingw0129 不需要特殊处理 就只标注虚线部分就可以了:)

**Comment by jingw0129** [comment]
那在您的源代码上可以做这样的修改吗？目前想快速标记一些样本。

**Comment by MaybeShewill-CV** [comment]
@jingw0129 你只需要标注你自己的样本文件就可以了

**Comment by jingw0129** [comment]
不好意思  可能我没说清楚。
是想用我的数据集做测试集，加上现有的代码程序跑出车道线不包括虚线的坐标
现在我输出的图像是这样的。
![00074](https://user-images.githubusercontent.com/22219702/69604809-6fad8d00-1059-11ea-97dd-cff828a6b90b.png)

**Comment by MaybeShewill-CV** [comment]
@jingw0129 tusimple数据集中是不区分实线和虚线的。所以现在模型没有实线和虚线的区分能力。不过你可以试试现有模型训练的embedding features是不是被使用为分类器的输入进而得到你想要的分类结果。比如你拿到不同车道线上点的embedding feature你可以将他们放入类似svm之类分类器看看分类效果如何，不过这个样本需要你自己标注:)

**Comment by jingw0129** [comment]
知道了   非常感谢

**Comment by MaybeShewill-CV** [comment]
@jingw0129 没事儿:)
