### ISSUE TITLE
lanenet_postprocess.py里知道两车道点插值中间点计算为何是这样的？

### ISSUE THREAD

**Issue by rocinant** [MaybeShewill-CV/lanenet-lane-detection#321]
https://github.com/MaybeShewill-CV/lanenet-lane-detection/blob/bb5e9c8bc538f1bc8409edd0f1f816fb2075d8ea/lanenet_model/lanenet_postprocess.py#L305
这里的interpolation_src_pt_x和interpolation_src_pt_y为何是这么计算的，而不是直接用plot_y线性插值[previous_src_pt_x, previous_src_pt_y]和[last_src_pt_x, last_src_pt_y]呢?谢谢

**Comment by MaybeShewill-CV** [comment]
@rocinant 这里的插值方法你可以扩展成任何一种你想要的方法:)

**Comment by rocinant** [comment]
@MaybeShewill-CV 谢谢答复，主要是这里的插值我没太看明白，照理来说[previous_src_pt_x, previous_src_pt_y]和[last_src_pt_x, last_src_pt_y]分别是plot_y在高度方向上的上下两个点，plot_y是隔10个像素取一个采样的y坐标，那么为了估计该采样的x坐标，第一反应是上下点连直线插值plot_y。您插值出的[interpolation_src_pt_x, interpolation_src_pt_y]几何上我不太理解，还要向您求教。

**Comment by MaybeShewill-CV** [comment]
@rocinant 当时是考虑到插值点不一定位于前后两个点连接的直线上，比如这里转弯处曲率较大的点:)

**Comment by rocinant** [comment]
@MaybeShewill-CV 目前这种插值叫什么方法呢？想看看相应的资料。看起来似乎是以到plot_y的y轴距离比例进行上下两坐标加权的平均。反过来看又像在找一个不规则四边形的y轴plot_y质心点。这种插值方法如何适应大曲率转弯呢？

**Comment by MaybeShewill-CV** [comment]
@rocinant 就是按照y比例进行加权的做法:)
