### ISSUE TITLE
mask image has bad result

### ISSUE THREAD

**Issue by Philip035** [MaybeShewill-CV/lanenet-lane-detection#322]
在自己的图片上，二值化图像和实例分割图像效果都还不错，但是mask image效果很差，请问有知道如何改进一下的吗

**Comment by MaybeShewill-CV** [comment]
@Philip035 后处理过程只适合tusimple数据集 如果要处理自己的数据需要你自己根据自己的数据修改后处理过程:)

**Comment by Philip035** [comment]
请问H-net的训练过程在哪里，或者说得到的H矩阵在哪？

**Comment by MaybeShewill-CV** [comment]
@Philip035 Hnet的训练这里不提供了，我本地也没有得到很好的实验结果，换方法了：）

**Comment by jiguanglu** [comment]
> @Philip035 后处理过程只适合tusimple数据集 如果要处理自己的数据需要你自己根据自己的数据修改后处理过程:)

您好，你知道如何修改后处理自己的数据吗？
