### ISSUE TITLE
How the instance image was transferred to embedding image during training

### ISSUE THREAD

**Issue by deeprun** [MaybeShewill-CV/lanenet-lane-detection#323]
The network has two output, binary_seg_ret and instance_seg_ret. binary_set_ret is single channel image, the same as training image under gt_binary_image. However, instance_seg_ret has four channels, and they are very different from the training image under gt_instance_image. That means somewhere in the training code, the gt_instance_image was transferred to other format before training. Could you point the code to do this?

**Comment by MaybeShewill-CV** [comment]
@deeprun instance_seg_ret which you mention above is the visualization result of the embedding features:)
