### ISSUE TITLE
How to make this amazing project a semantic segmentation model?

### ISSUE THREAD

**Issue by meanmee** [MaybeShewill-CV/lanenet-lane-detection#326]
If I want to segment yellow lane, white lane, zebra. How could I modify this model? Does anyone have any ideas? Thank you.

**Comment by MaybeShewill-CV** [comment]
@meanmee 不明白你的意思

**Comment by meanmee** [comment]
这个模型是做实例分割的，一条线当做一个类别。现在我想要改成做予语义分割的，类别是确定的，比如黄实线，白实线，斑马线分别为不同类。

**Comment by MaybeShewill-CV** [comment]
@meanmee 那你只要binary segmentation就好了 然后自己改类别从二分类到多分类:)

**Comment by meanmee** [comment]
是这样的，之前我在自己数据集上是直接训练的多分类分割模型，但是由于黄实线和白实线数据量差距太大，黄实线很容易被当成白实线，尝试过加权，但效果不理想。
然后用你的模型测了一下，发现可以很好地区分黄实线，白实线。所以在想能不能在你模型的基础上改动（我觉得聚类部分是关键）

**Comment by MaybeShewill-CV** [comment]
@meanmee 那你可以尝试下:)

**Comment by gabaebae123** [comment]
请问你有做出来吗？我现在也做了自己的数据集，在检测的基础上需要区分虚线和实现，请问要怎么修改呢？ @meanmee
