### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by Zuojianhao** [MaybeShewill-CV/lanenet-lane-detection#327]
非常感谢您的分享，请问我在使用您提供的权重进行测试时，报错
Key lanenet_model/inference/decode/deconv_1/deconv_1/kernel not found in checkpoint
请问是tfb版本不对还是什么其他问题？

**Comment by MaybeShewill-CV** [comment]
@Zuojianhao 代码和权重文件不匹配:)

**Comment by MaybeShewill-CV** [comment]
@Zuojianhao 是我之前上传mnn版本权重的时候把文件搞错了 现在重新上传了 你可以重新下载试试

**Comment by Zuojianhao** [comment]
@MaybeShewill-CV 测试成功，非常感谢您的工作和热心帮助！

**Comment by MaybeShewill-CV** [comment]
@Zuojianhao 不客气
