### ISSUE TITLE
关于训练自己制作的数据集

### ISSUE THREAD

**Issue by Zuojianhao** [MaybeShewill-CV/lanenet-lane-detection#328]
您好，请问我想训练自己的数据集的话，使用labelme进行标注，是将所有车道当作一类(lane)，还是每条车道分类为lane1,lane2...，恳请您能帮我解答一下疑惑，非常感谢！

**Comment by Zuojianhao** [comment]
我标注了165张图片，在您提供的权重基础上训练了两万轮，最终的结果并不是很理想，binary_mask图像基本能将车道线分开来，但是instance图像很不理想，请问您是否能给我提点建议，怎样能够训练的算法的性能

**Comment by MaybeShewill-CV** [comment]
@Zuojianhao 语义分割标注只需要区分车道线和非车道线。实例分割标注需要区分每个不同的车道线:)

**Comment by Zuojianhao** [comment]
嗯，这点我明白，我现在制作的数据集只对车道一类进行标注，然后通过转化脚本生成类似于tusimple数据集中的，gt_binary和gt_instance，这部分我比较我生成的和您代码中的示例相同，但是最终训练完效果不理想，二分类的mask图效果非常好，但instance结果很差，所以我想请教一下您，我可能哪个环节出现了问题，希望您能抽空回复一下我。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"MaybeShewill-CV"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月11日(星期三) 下午3:42
收件人:&nbsp;"MaybeShewill-CV/lanenet-lane-detection"<lanenet-lane-detection@noreply.github.com&gt;;
抄送:&nbsp;"1536578707"<1536578707@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [MaybeShewill-CV/lanenet-lane-detection] 关于训练自己制作的数据集 (#328)




@Zuojianhao 语义分割标注只需要区分车道线和非车道线。实例分割标注需要区分每个不同的车道线:)

**Comment by MaybeShewill-CV** [comment]
@Zuojianhao 需要针对你自己的数据集 调整instance segmentation loss的值

**Comment by MaybeShewill-CV** [comment]
@Zuojianhao 需要你自己根据你的数据集 调整instance segmentation loss相关的距离阈值:)

**Comment by Zuojianhao** [comment]
@MaybeShewill-CV 好的，非常感谢您的指导

**Comment by xiang1107** [comment]
> 需要你自己根据你的数据集 调整instance segmentation loss相关的距离阈值:)

请问这个是怎么操作的？
