### ISSUE TITLE
remap - 640x640 matrix 

### ISSUE THREAD

**Issue by kmsgnnew** [MaybeShewill-CV/lanenet-lane-detection#330]
https://github.com/MaybeShewill-CV/lanenet-lane-detection/blob/master/lanenet_model/lanenet_postprocess.py#L357
1) how was the 640x640 matrix used for remapping generated??
2) why is remap necessary ??? (is  it an alternate to H-NET ??). 
3) if you avoid remap what was the  polyfit behaviour??

**Comment by MaybeShewill-CV** [comment]
@kmsgnnew 1. Remap matrix was generated via https://github.com/MaybeShewill-CV/Easy-Ipm-Client
2. Lane fitting will be easier if ipm image is used.
3. You may also fit the lane in front view image.
