### ISSUE TITLE
Prediction Probabilities

### ISSUE THREAD

**Issue by smcl2** [MaybeShewill-CV/lanenet-lane-detection#332]
is it possible to see the prediction probabilities for the lane instances using the code in its current form? thanks

**Comment by MaybeShewill-CV** [comment]
@smcl2 Not possible now:)

**Comment by smcl2** [comment]
Any idea why not?

**Comment by MaybeShewill-CV** [comment]
@smcl2 Instance segmentation branch's output was a feature map rather a prob map. You may refer the origin paper for details:)

**Comment by smcl2** [comment]
Ok thanks
