### ISSUE TITLE
train.txt and test.txt

### ISSUE THREAD

**Issue by xxzcpsmemeda** [MaybeShewill-CV/lanenet-lane-detection#333]
How to generate the directory of train.txt and test.txt files? Can you send me the code of image catalog?

**Comment by MaybeShewill-CV** [comment]
@xxzcpsmemeda 可以参考 https://github.com/MaybeShewill-CV/lanenet-lane-detection/blob/master/data/training_data_example/train.txt 生成. 文件每一行记录了1.原始数据路径 2.二值分割掩码图 3.实例分割掩码图。中间空格分隔:)
