### ISSUE TITLE
model/tusimple_lanenet/

### ISSUE THREAD

**Issue by usman-mcs** [MaybeShewill-CV/lanenet-lane-detection#335]
this folder does not exsit in this repo  what should i do now

**Comment by MaybeShewill-CV** [comment]
@usman-mcs Download the pretrained model and mkdir on your own:)

**Comment by usman-mcs** [comment]
just weight files only weight files are available on the link you provided

**Comment by MaybeShewill-CV** [comment]
@usman-mcs That's exactly what you need:)
