### ISSUE TITLE
Trainning with my own images got "cost is nan"

### ISSUE THREAD

**Issue by deeprun** [MaybeShewill-CV/lanenet-lane-detection#336]
I have been continously training the lanenet with my own images. I first trained the network with some images, and then ran inference on a larger set. If I did not get good inference results on some of the images, I added them to the training set and train the network on top of the trained model. Keep doing this, I have trained the network for about 300K epoch. Now, I found if I added more images and trained again on top of the existing model, I kept getting the following error message:

cost is: nan
binary cost is: 1.8876
instance cost is: inf

Why? How can I fix this?

**Comment by MaybeShewill-CV** [comment]
@deeprun refer to #116
