### ISSUE TITLE
Error encountered when change IMAGE_HEIGHT and IMAGE_WIDTH

### ISSUE THREAD

**Issue by DonaldRR** [MaybeShewill-CV/lanenet-lane-detection#337]
(0) Invalid argument: Input to reshape is a tensor with 156672 values, but the requested shape has 574464
	 [[{{node Reshape_2}}]]
	 [[train_IteratorGetNext]]
  (1) Invalid argument: Input to reshape is a tensor with 156672 values, but the requested shape has 574464
	 [[{{node Reshape_2}}]]
	 [[train_IteratorGetNext]]
	 [[lanenet_model/vgg_frontend/vgg16_encode_module/conv3_3/bn/gamma/read/_1711]]

It seems the model's node shape was not changed according to input shape leading such a shape incompatible problem. 

Where is the bug?

**Comment by DonaldRR** [comment]
I surmised the problem was the pretrained vgg16's input was 256*512 which accounts for the shape mismatch problem

**Comment by MaybeShewill-CV** [comment]
@DonaldRR Did you train the model from scratch or from pretrained snapshot?

**Comment by DonaldRR** [comment]
> @DonaldRR Did you train the model from scratch or from pretrained snapshot?

No. Even I skipped the process of loading pretrained model, the problem still exist.

**Comment by DonaldRR** [comment]
@MaybeShewill-CV 
No. Even I skipped the process of loading pretrained model, the problem still exist.

**Comment by MaybeShewill-CV** [comment]
@DonaldRR The problem was not caused by the pertained vgg16 model weights. You're supposed to check your test image size.

**Comment by sainisanjay** [comment]
Hi @DonaldRR did you able to solve the problem? i am getting exactly same issue. I am trying to train the model on Tusimple dataset.
