### ISSUE TITLE
How can we get the image in `lanenet-lane-detection/data/source_image/lanenet_instance_seg.png`?

### ISSUE THREAD

**Issue by masouduut94** [MaybeShewill-CV/lanenet-lane-detection#339]
Can you tell us how we can get output image in this directory : 
`lanenet-lane-detection/data/source_image/lanenet_instance_seg.png`?

I want to map it on the image. Can you help me how to get this done, please?

**Comment by MaybeShewill-CV** [comment]
@masouduut94 Do dimension reduction on instance segmentation result and rescale the value into [0, 255]:)

**Comment by masouduut94** [comment]
I did not go through code deep, but I was able to figure out this code for drawing binary segmentation for lanes on the source image:

# drawing the road lanes
    ht, wd = binary_seg_result.shape
    src_ht, src_wd, _ = source_image.shape
    source_image = cv2.resize(source_image, (wd, ht))

    # splitting color channels
    B = source_image[:, :, 0] | binary_seg_result
    G = source_image[:, :, 1] | binary_seg_result
    R = source_image[:, :, 2] | binary_seg_result

    # prepare it for output
    src_with_lanes = cv2.merge((B, G, R))
    src_with_lanes = cv2.resize(src_with_lanes, (src_wd, src_ht))

    ret = {
        'mask_image': mask_image,
        'fit_params': fit_params,
        'source_image': source_image,
        'src_with_lanes': src_with_lanes,
    }

But I still did not spend time to do the same thing for the colorful one.
Can you help me with code plz?

**Comment by MaybeShewill-CV** [comment]
@masouduut94 check https://github.com/MaybeShewill-CV/lanenet-lane-detection/blob/master/tools/test_lanenet.py line 122~124
