### ISSUE TITLE
Hello, can I replace the VGG model with Squeeze?

### ISSUE THREAD

**Issue by d123456ddq** [MaybeShewill-CV/lanenet-lane-detection#34]
Hello, can I replace the VGGNet with SqueezeNet or some other model?
I need a model with fewer parameters for lane detection. Do you have any good suggestions? Thanks.

**Comment by MaybeShewill-CV** [comment]
@d123456ddq You can implement your own feature extraction base net and replace vgg feature before generate the binary segmentation result and pix embedding.

**Comment by d123456ddq** [comment]
OK，I will try. Thanks !
