### ISSUE TITLE
Anybody sucessully able to install and run on Ubuntu 18.04?

### ISSUE THREAD

**Issue by amarsaroj** [MaybeShewill-CV/lanenet-lane-detection#340]

**Comment by 850977164** [comment]
Theoretically,It is best to run on the specified version

**Comment by amarsaroj** [comment]
> Theoretically,It is best to run on the specified version

The specified version is Ubuntu 16.04?

**Comment by farazBhatti** [comment]
yes, it runs after adding config to pythonpath:
export PYTHONPATH=$PYTHONPATH:/home/***/Desktop/***/projects/***/lanenet-lane-detection

**Comment by Aya-S** [comment]
I'm trying to run on 18.04 as well, Having some issues
but can't even download the model at this point. did you face a similar issue ?

**Comment by Aya-S** [comment]
@amarsaroj  did things work out for you. i'm also trying to run on 18.04 but having issues

**Comment by amarsaroj** [comment]
> @amarsaroj did things work out for you. i'm also trying to run on 18.04 but having issues

I reinstalled Ubuntu 16.04 and now its working for me. Able to test and train example dataset. 

regarding the model, just download the dropbox files and use the model path command as described. I had to change paths in train.txt and val.txt files though.
