### ISSUE TITLE
Can you provide the code to call the pb interface

### ISSUE THREAD

**Issue by 850977164** [MaybeShewill-CV/lanenet-lane-detection#342]
I tried calling the pb file with the freeze_lanenet_model folder,but didn't succeed
Can you provide the code to call the pb interface

**Comment by MaybeShewill-CV** [comment]
@850977164 where did you get stuck off?:)

**Comment by 850977164** [comment]
I want to call the lanenet.pb file to detect the training effect, not the tusimple_lanenet_vgg.ckpt file

**Comment by 850977164** [comment]
@MaybeShewill-CV 调用到ARM板子中，您有没有可以提供的参考

**Comment by MaybeShewill-CV** [comment]
@850977164 可以考虑mnn-lanenet https://github.com/MaybeShewill-CV/MNN-LaneNet

**Comment by 850977164** [comment]
@MaybeShewill-CV 我按照您的提示，编译了MNN0.2.1.0,确没有生成MNNConvert可执行文件，MNN0.2.1.7生成了这个文件，用MNN0.2.1.7版本，出现了这个问题，我该如何解决呢
![image](https://user-images.githubusercontent.com/39330916/72588915-bf5f5500-3934-11ea-8ceb-32ae2c74b49e.png)

**Comment by MaybeShewill-CV** [comment]
@850977164 MNN0.2.1.0的模型转换工具需要单独编译. 别的版本的mnn转换工具没有测试过 可以去mnn那里提个issue:)

**Comment by 850977164** [comment]
好的，多谢了

**Comment by 850977164** [comment]
@MaybeShewill-CV 参考 https://github.com/alibaba/MNN/issues/569，
python source/backend/metal/MetalCodeGen.py source/backend/metal/ source/backend/metal/MetalOPRegister.mm方案，MNN0.2.1.7可以执行，MNN0.2.1.0确无法执行，您能提供一下模型转换工具编译方法吗，谢谢

![image](https://user-images.githubusercontent.com/39330916/72592915-a0fe5700-393e-11ea-84d3-a49000511b33.png)

**Comment by MaybeShewill-CV** [comment]
@850977164 cd tools/convert && mkdir build && cd build && cmake .. && make -j

**Comment by 850977164** [comment]
谢谢

**Comment by 850977164** [comment]
@MaybeShewill-CV 
![image](https://user-images.githubusercontent.com/39330916/72673958-1fc4d280-3aac-11ea-8764-8a1c49988d0c.png)
您好，我在执行上面第二步命令时出现了如下错误，glog我确定已经安装成功了，确仍出现这样的问题，应该怎么解决呢，谢谢
![image](https://user-images.githubusercontent.com/39330916/72673953-fad05f80-3aab-11ea-9301-84764c4e3d07.png)

**Comment by MaybeShewill-CV** [comment]
@850977164 不是报错很清楚么 不是你没有装glog而是cmake找不到glog-config.cmake文件。你百度一下这个问题就知道了:)
