### ISSUE TITLE
custom data training

### ISSUE THREAD

**Issue by aacmi** [MaybeShewill-CV/lanenet-lane-detection#343]
Hi,
I'm trying to train with my own dataset and got this error, Any suggestion would be helpful

Traceback (most recent call last):
File "tools/train_lanenet.py", line 719, in <module>
train_lanenet(args.dataset_dir, args.weights_path, net_flag=args.net_flag)
File "tools/train_lanenet.py", line 442, in train_lanenet
train_images, train_binary_labels, train_instance_labels])
File "/home/pcific/anaconda3/envs/tf_gpu/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 950, in run
run_metadata_ptr)
File "/home/pcific/anaconda3/envs/tf_gpu/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1173, in _run
feed_dict_tensor, options, run_metadata)
File "/home/pcific/anaconda3/envs/tf_gpu/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
run_metadata)
File "/home/pcific/anaconda3/envs/tf_gpu/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 470016 values, but the requested shape has 156672
[[{{node Reshape_2}}]]
[[train_IteratorGetNext]]

**Comment by MaybeShewill-CV** [comment]
@aacmi Seems your tensor size is not matched with your input image data:)

**Comment by aacmi** [comment]
Thanks for your reply.
we solved this error but we are getting error due to some reasons.
Image size - 300 x 300
number of classes - 5
single gpu configuration
vgg16 network

tensorflow.python.framework.errors_impl.AlreadyExistsError: Resource __per_step_18/lanenet_model/vgg_backend/instance_seg/while/ArithmeticOptimizer/AddOpsRewrite_add_3/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
	 [[{{node lanenet_model/vgg_backend/instance_seg/while/ArithmeticOptimizer/AddOpsRewrite_add_3/tmp_var}}]]

any ideas and suggestion would be helpful.

**Comment by aacmi** [comment]
If i execute with this command:
python3 tools/train_lanenet.py -d ./data/training_data_example/ -m 1 --net_flag vgg

Image size - 300 x 300
number of classes - 5
single gpu configuration
vgg16 network

I'm getting the follwoing error,
ValueError: Dimensions must be equal, but are 37 and 36 for 'tower_0/lanenet_model/vgg_frontend/vgg16_decode_module/binary_seg_decode/decode_stage_4_fuse/fuse_feats' (op: 'Add') with input shapes: [4,37,37,512], [4,36,36,512].

**Comment by MaybeShewill-CV** [comment]
@aacmi rescale your image size:)

**Comment by aacmi** [comment]
you mean all the image size should be 256 x 512 ?

**Comment by aacmi** [comment]
ok i have managed to start train but after two epochs i m getting error
2020-01-16 23:51:35.510442: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set. If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU. To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
I0116 23:52:17.068542 7399 train_lanenet.py:685] Epoch_Train: 1 total_loss= 38.303520 lr= 0.003000 mean_cost_time= 33.687111s 
I0116 23:52:17.068787 7399 train_lanenet.py:694] Epoch_Val: 1 total_loss= nan mean_cost_time= 7.424681s 
E0116 23:52:43.995813 7399 train_lanenet.py:660] Train loss is nan

**Comment by MaybeShewill-CV** [comment]
@aacmi remove those input image with no lane on it:)

**Comment by aacmi** [comment]
Thank you so much. How to increase the number of classes from 2 to 5 ?

**Comment by MaybeShewill-CV** [comment]
@aacmi modified the config file:)

**Comment by aacmi** [comment]
I did but i m getting the following error,

Traceback (most recent call last):
File "/home/pcific/anaconda3/envs/tf_gpu/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
return fn(*args)
File "/home/pcific/anaconda3/envs/tf_gpu/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
options, feed_dict, fetch_list, target_list, run_metadata)
File "/home/pcific/anaconda3/envs/tf_gpu/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [4,256,512,5] vs. [2]
[[{{node tower_1/lanenet_model/vgg_backend/binary_seg/Mul}}]]

**Comment by MaybeShewill-CV** [comment]
@aacmi check your label image:)

**Comment by pkraison** [comment]
we've two folders for labels(binary, instance), as it's directed through example. training works with 2 classes but we've five classes in our data. when we're modifying class no. in the config, we're getting the above errors. shall we create five folders with images and labels or any other way?

**Comment by MaybeShewill-CV** [comment]
@pkraison make sure your binary seg label image have unique label id from [0, 4] if you have 5 classes before you put them into the network:)

**Comment by yingluoxiao** [comment]
> Hi,
> I'm trying to train with my own dataset and got this error, Any suggestion would be helpful
> 
> Traceback (most recent call last):
> File "tools/train_lanenet.py", line 719, in
> train_lanenet(args.dataset_dir, args.weights_path, net_flag=args.net_flag)
> File "tools/train_lanenet.py", line 442, in train_lanenet
> train_images, train_binary_labels, train_instance_labels])
> File "/home/pcific/anaconda3/envs/tf_gpu/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 950, in run
> run_metadata_ptr)
> File "/home/pcific/anaconda3/envs/tf_gpu/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1173, in _run
> feed_dict_tensor, options, run_metadata)
> File "/home/pcific/anaconda3/envs/tf_gpu/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
> run_metadata)
> File "/home/pcific/anaconda3/envs/tf_gpu/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
> raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 470016 values, but the requested shape has 156672
> [[{{node Reshape_2}}]]
> [[train_IteratorGetNext]]

May I ask how do you solve this problem?

**Comment by MaybeShewill-CV** [comment]
@yingluoxiao check if your label image's size is matched with the input tensor shape:)

**Comment by 810541195** [comment]
the tusimple_ipm_remap don't fit custom data, How to train the H-net?

**Comment by MaybeShewill-CV** [comment]
@810541195 hnet was not used here:)

**Comment by Aya-S** [comment]
thank you @MaybeShewill-CV  for providing much needed support.
I have a relevant question what is the function of tusimple_ipm_remap and do we need to provide a similar matrix for any dataset that we are trying to use with your implementation.
Can you shed some light on why the pretrained model you provided would only work on tusimple data?

**Comment by shauryad15** [comment]
@aacmi how you solved this error?

470016 values, but the requested shape has 156672

**Comment by MaybeShewill-CV** [comment]
@Aya-S ipm_remap was used to generate bird view image for lane detection:)

**Comment by shauryad15** [comment]
@MaybeShewill-CV  ok so i've resized my images to 512*256 as ,mentioned in the config file but i'm still getiing the same error.

(0) Invalid argument: Input to reshape is a tensor with 470016 values, but the requested shape has 156672

any pointers will be helpful.

**Comment by shauryad15** [comment]
I don't how to check it then. I have resized my data to 256*512 as mentioned in config file. What else can I do after it?

**Comment by shauryad15** [comment]
@MaybeShewill-CV any help?

**Comment by MaybeShewill-CV** [comment]
@shauryad15 Which command did you use or paste some useful information here. Can not help without any useful information. Like I said you may check your data shape, channel number is one element of data shape.

**Comment by shauryad15** [comment]
ok so you mean to say that the binary and instance sample image size should be (256*512*1) instead of (256*512*3)?

**Comment by MaybeShewill-CV** [comment]
@shauryad15 You may check the script which is used to generate tusimple training examples by yourself:)

**Comment by shauryad15** [comment]
training started. The issue was because of the color channels. Make the image single channel and it'll start working.

Thanks @MaybeShewill-CV for the support.

**Comment by MaybeShewill-CV** [comment]
@shauryad15 welcome

**Comment by enginbaglayici** [comment]
@pythonmjs Its a bit late but I saw your comments in a couple of places, I hope you solved your problem. If you didn't, for you and those who have this question, here is the answer: use `generate_tusimple_dataset.py` file and manipulate it to generate binary-instance images from your custom dataset.

**Comment by zoombinis** [comment]
@enginbaglayici does this mean for each and every image file we need to figure out the x,y points where the lanes exist and enter them into the json file manually?

For training thousands of images, how are folks reliably detecting the x,y coordinates of each lane in order to enter them into the json file?

**Comment by enginbaglayici** [comment]
@zoombinis yes, you need to write labels (x,y pixel coordinates of each line) into json file just like in the tusimple dataset. 

There are some tools for labeling (e.g Matlab Labeling Tool), in which you can annotate a couple of points from a lane line, then you can fit a line between those points. That's how you can reliably get labels.

**Comment by zoombinis** [comment]
@enginbaglayici this surprises me because the Lanenet paper that Duke published made no mention of manually annotating all the points. Instead the ground truth was just the number of lanes:

> Considering
the large cost of annotating each lane in an image using a
quadratic function, and any inaccurate annotations affecting
the training result, we design a weakly supervised training
method for the lane line localization network, which only
requires the number of lanes in a image as ground truth, we
call this form of loss the min-distance loss. When using
min-distance loss, the loss function is computed by the sum
of the distance of each input point to its nearest estimated
line.


So is annotating all points yielding better results or is it just a simpler, brute force method?

**Comment by shank-gyrus** [comment]
@enginbaglayici Can you please explain how you created JSON file with lane coordinates for your custom dataset?

**Comment by enginbaglayici** [comment]
> 
> 
> @enginbaglayici Can you please explain how you created JSON file with lane coordinates for your custom dataset?

As I explained before, there is a matlab tool that extracts x,y coordinates from annotated images. The rest is writing a matlab script that generates the json file from the image and coordinates information, just like in the TuSimple dataset. So the hard part is annotating, rather than producing the json :)
