### ISSUE TITLE
Can I modify algotihm to use it for my realsense camera data?

### ISSUE THREAD

**Issue by polatoguzhan40** [MaybeShewill-CV/lanenet-lane-detection#347]
Can you help me to use this code for the data comes from camera. I'm newbie on this topic sorry for awkward question?

**Comment by MaybeShewill-CV** [comment]
@polatoguzhan40 You need feed the single frame from your camera into the network:)

**Comment by polatoguzhan40** [comment]
Can you give me little bit detail please :) Is there a way to feed network from camera? Should I change any code or something. I just could run demo examples today.
