### ISSUE TITLE
some questions about the training dataset

### ISSUE THREAD

**Issue by south-ocean** [MaybeShewill-CV/lanenet-lane-detection#35]
你好，我现在想用自己的数据集训练。看到代码里给的训练集样本图片，里面的二值图像和实例分割图像都是3通道的，但是我按照3通道产生的数据集，报错维度应该为1通道。报错如下所示，谢谢
ValueError: Cannot feed value of shape (4, 512, 1024, 3) for Tensor 'instance_input_label:0', which has shape '(4, 512, 1024).

**Comment by sunmiaozju** [comment]
@south-ocean 作者给的数据集参考样例里面，标签都是一通道的

**Comment by MaybeShewill-CV** [comment]
@south-ocean labels images are single channel
