### ISSUE TITLE
测试图片结果的问题

### ISSUE THREAD

**Issue by TOM-tym** [MaybeShewill-CV/lanenet-lane-detection#351]
首先要感谢作者的模型！
我在测试非Tusimple数据集中的图片的时候，遇到了下面的情况。
输出的图片分别为：
![source_image](https://user-images.githubusercontent.com/38480329/75090332-c5cc9680-559c-11ea-8121-853d496514a4.png)
![instance_mask_image](https://user-images.githubusercontent.com/38480329/75090333-c6fdc380-559c-11ea-9bd5-1129690d0b9f.png)
![binary_mask_image](https://user-images.githubusercontent.com/38480329/75090334-c82ef080-559c-11ea-90a5-3130e97fad3a.png)
检测结果比较差。

我使用的命令是
`python tools/test_lanenet.py --weights_path ./model/tusimple_lanenet_vgg/tusimple_lanenet_vgg.ckpt 
--image_path ./data/tusimple_test_image/10.png`
使用的权重是作者提供的权重。

请问这是什么原因呢？谢谢！

**Comment by TOM-tym** [comment]
已找到相关issue。问题已解决。
issue[#291](https://github.com/MaybeShewill-CV/lanenet-lane-detection/issues/291)

**Comment by china56321** [comment]
> 已找到相关issue。问题已解决。
> issue[#291](https://github.com/MaybeShewill-CV/lanenet-lane-detection/issues/291)

你好，我用作者提供的模型检测自己的图片，检测车道线是弯曲的，请问你遇到了这种情况了吗？是怎么解决的？
