### ISSUE TITLE
Some questions about the lanenet model trained with CULane Dataset

### ISSUE THREAD

**Issue by Baiwenjing** [MaybeShewill-CV/lanenet-lane-detection#352]
Hi,   
I have trained the lanenet model on CULane dataset. When I test the model with test dataset, I found some pictures with bad results(most picture can get a good result), as shown in the figure. 
The think the reasons are as follows:
1) First, a wrong segment result is provide by the  binary segmentation branch, I think it's inevitable in practice;
2) Second, the clustering branches do not distinguish the road and surface very well. I think there is a logic error in the discriminative loss. As in discriminative loss, although the background is taken into account in the calculation of var_loss and distance_loss, as the pixel number of background is too big, even some pixels's embedding results are wrong, the mean var_loss of background class will always be small. So, after training, the model doesn't work well when the binary segmentation branch provide a wrong result.

I don't know if my analysis is correct, If there is any mistake, please correct me.
Could you please give me some advice or suggestions to solve the problem?

![00360_instance-feat](https://user-images.githubusercontent.com/12594258/75133848-46af9d80-5717-11ea-9fd3-39a91fee3070.jpg)

![00360_binary](https://user-images.githubusercontent.com/12594258/75135087-59c46c80-571b-11ea-8a0f-61badc9ce7dc.jpg)

**Comment by MaybeShewill-CV** [comment]
@Baiwenjing 后处理的过程中 其实路面背景上的embedding features是不参与最后的聚类的 参与后处理聚类过程的是靠binary segmentation掩码取出来的那些embedding features:)
