### ISSUE TITLE
Model load error.

### ISSUE THREAD

**Issue by shauryad15** [MaybeShewill-CV/lanenet-lane-detection#353]
@MaybeShewill-CV What --net you have used? I'm trying to load your trained model and want to perform transfer learning on your model but i'm getting an error stating that "The passed save_path is not a valid checkpoint. Any pointers?

**Comment by MaybeShewill-CV** [comment]
@shauryad15 Check your input ckpt file path:)

**Comment by shauryad15** [comment]
getting new error now...

(0) Invalid argument: Input to reshape is a tensor with 470016 values, but the requested shape has 156672
	 [[{{node Reshape_2}}]]
	 [[train_IteratorGetNext]]
	 [[train_IteratorGetNext/_515]]
  (1) Invalid argument: Input to reshape is a tensor with 470016 values, but the requested shape has 156672
	 [[{{node Reshape_2}}]]
	 [[train_IteratorGetNext]]
1 successful operations.
0 derived errors ignored.

What should I change?

**Comment by MaybeShewill-CV** [comment]
@shauryad15 tensor shape not qualified:)

**Comment by shauryad15** [comment]
what's the workaround? I mean should i resize all the images before feeding to the network? If yes, then what should be the image dimension for the network.

BTW, thanks for the quick replies. :) @MaybeShewill-CV

**Comment by MaybeShewill-CV** [comment]
@shauryad15 You may check related issues:)
