### ISSUE TITLE
@yingluoxiao check if your label image's size is matched with the input tensor shape:)

### ISSUE THREAD

**Issue by lch666** [MaybeShewill-CV/lanenet-lane-detection#354]
@yingluoxiao check if your label image's size is matched with the input tensor shape:)

_Originally posted by @MaybeShewill-CV in https://github.com/MaybeShewill-CV/lanenet-lane-detection/issues/343#issuecomment-576663021_
您好，我也遇到相同的问题，训练的是CULane数据集，这个数据集的图片训练前需要修改尺寸么

**Comment by shauryad15** [comment]
make the image single channel. refer script of tusimple data conversion.

**Comment by lch666** [comment]
> make the image single channel. refer script of tusimple data conversion.
the binary and instance label is single channels, the picture in gt_image is RGB png picture ，how are solve the problem

**Comment by MaybeShewill-CV** [comment]
@lch666 看下前面的issue:)
