### ISSUE TITLE
模型推理速度

### ISSUE THREAD

**Issue by sdu2011** [MaybeShewill-CV/lanenet-lane-detection#357]
作者你好,我在LaneNet类的inference方法里加了时间统计,
```
            # first extract image features
            t_start = time.time()
            extract_feats_result = self._frontend.build_model(
                input_tensor=input_tensor,
                name='{:s}_frontend'.format(self._net_flag),
                reuse=self._reuse
            )
            t_cost = time.time() - t_start
            glog.info('*********extract image features cost time: {:.5f}s'.format(t_cost))

            # second apply backend process
            t_start = time.time()
            binary_seg_prediction, instance_seg_prediction = self._backend.inference(
                binary_seg_logits=extract_feats_result['binary_segment_logits']['data'],
                instance_seg_logits=extract_feats_result['instance_segment_logits']['data'],
                name='{:s}_backend'.format(self._net_flag),
                reuse=self._reuse
            )
            t_cost = time.time() - t_start
            glog.info('backend process cost time: {:.5f}s'.format(t_cost))
```
想看下模型的推理到底在哪部分耗时比较久.

问题1:
对于input为单张图片即(1, 256, 512, 3)统计如下
```
extract image features cost time: 1.27622s
backend process cost time: 0.02468s
Single imgae inference cost time: 2.20125s
```
**imgae inference cost time统计的是sess.run的时间,extract image features cost time + backend process cost time可以认为是inference函数执行的时间**,我以前的理解,这两个时间应该非常接近相等才对,但是实验差距似乎挺大的,差出来的0.9s是哪里去了？

第二个问题:
我稍微改了一下代码,测试输入是多张图片时候的性能.
```
    image_path_list = glob.glob('{:s}/**/*.jpg'.format(image_dir), recursive=True) + \
                      glob.glob('{:s}/**/*.png'.format(image_dir), recursive=True) + \
                      glob.glob('{:s}/**/*.jpeg'.format(image_dir), recursive=True)
    
    log.info('Start reading image and preprocessing')
    t_start = time.time()
    # image_list_input = []
    image_list_epoch = [cv2.imread(tmp, cv2.IMREAD_COLOR) for tmp in image_path_list]
    image_list_epoch = [cv2.resize(tmp, (512, 256), interpolation=cv2.INTER_LINEAR)
                        for tmp in image_list_epoch]
    image_list_input = [tmp/127.5 - 1.0 for tmp in image_list_epoch]
```
测出来的结果如下:
输入为４张图片时,imgae inference cost time: 2.58794s,平均一张0.6s
输入为32张时,imgae inference cost time: 4.31036s,平均一张为0.13s
我不是很理解,这种巨大差异的根源是什么?是什么造成了这种类似"吞吐量大,延迟高"的现象?

问题3:
测试输入为32张图的时候,有个奇怪的问题
```
Iextract image features cost time: 6.04508s
backend process cost time: 0.02409s

imgae inference cost time: 3.38117s
```
怎么会出现sess.run统计出来的时间比extract image features cost time时间短的问题呢?

我的环境:
4张titan xp,tensorflow版本1.15.2

**Comment by MaybeShewill-CV** [comment]
@sdu2011 1.你第一个图里添加的计时函数实际统计的是tensorflow的建图时间 而不是最后的运行计算时间 tensorflow的静态图设计就是如此 2.sess.run方法的调用才是整个静态图真的运行计算的过程， gpu是会出现随着batch size的增大 运行时间会出现先上升后下降的趋势 这个应该和gpu的设计有关系 具体我也不是很懂 所以只能描述现象不能分析原因 3.gpu一般会有一段时间的warm up 所以会出现同样batch size=32的时候 前期耗时长 中后期耗时变短并稳定下来的情况

**Comment by sdu2011** [comment]
> @sdu2011 1.你第一个图里添加的计时函数实际统计的是tensorflow的建图时间 而不是最后的运行计算时间 tensorflow的静态图设计就是如此 2.sess.run方法的调用才是整个静态图真的运行计算的过程， gpu是会出现随着batch size的增大 运行时间会出现先上升后下降的趋势 这个应该和gpu的设计有关系 具体我也不是很懂 所以只能描述现象不能分析原因 3.gpu一般会有一段时间的warm up 所以会出现同样batch size=32的时候 前期耗时长 中后期耗时变短并稳定下来的情况

多谢作者的回复!如果我想统计具体的每个计算环节的时间　应该怎么做呢？
比如,我想统计sess.run所耗费的时间中有多久是耗费在了extract image features,有多久是耗费在了生成binary_seg_prediction, instance_seg_prediction？

**Comment by sdu2011** [comment]
还有就是你们有真正的把lanenet应用于实际环境吗？实际环境中比如自动驾驶,应该是要求很低的延迟,至少要在100ms以下吧.　从我的测试数据来看,lanenet的延迟似乎没法用于生产啊

**Comment by MaybeShewill-CV** [comment]
@sdu2011 1.具体业务层面的东西不方便讲 2.如果你想看每个op的耗时的话可以查询tf.RunOptions tf.RunMetadata() 相关的用法:)

**Comment by sdu2011** [comment]
> @sdu2011 1.具体业务层面的东西不方便讲 2.如果你想看每个op的耗时的话可以查询tf.RunOptions tf.RunMetadata() 相关的用法:)

多谢指点!
