### ISSUE TITLE
what is the output of the network?

### ISSUE THREAD

**Issue by shauryad15** [MaybeShewill-CV/lanenet-lane-detection#358]
@MaybeShewill-CV Hi,

I was wondering what is the output of the network? Does it produces the mask as output? If yes, then where can I find it. I've explored the network but unable to get it. 

Reason why i'm doing this to annotate the data. I'm getting false positives, thus to generate more data i'm trying to use the output of the network and then filter out the false positives to generate more data.

**Comment by MaybeShewill-CV** [comment]
@shauryad15 Check this https://github.com/MaybeShewill-CV/lanenet-lane-detection/blob/master/tools/test_lanenet.py you may get binary segmentation mask:)

**Comment by shauryad15** [comment]
@MaybeShewill-CV  ok, so i was exploring this file only. 
Here,

"binary_seg_ret" is the tensor and "binary_seg_image" is the  is the image itself. The only part which I'm missing is the binary mask :P

**Comment by MaybeShewill-CV** [comment]
@shauryad15 。。。。。。。 binary seg image is what you need as I know ==!

**Comment by shauryad15** [comment]
also, while training, my instance segmentation loss isn't going down. binary has reached to a satisfactory level though.

**Comment by MaybeShewill-CV** [comment]
@shauryad15 You may adjust some of your params to fine-tune the model:)

**Comment by shauryad15** [comment]
@MaybeShewill-CV have you tried to run in using tflite on android devices? If no, can you please provide me some pointers?

**Comment by MaybeShewill-CV** [comment]
@shauryad15 Have not use trite yet. You may try MNN for mobile devices. https://github.com/MaybeShewill-CV/MNN-LaneNet
