### ISSUE TITLE
车道线属性

### ISSUE THREAD

**Issue by ryan1051** [MaybeShewill-CV/lanenet-lane-detection#360]
请问按论文的方法是不是得不到车道线的属性（虚实、黄白），只能得到车道线的曲线方程。

**Comment by MaybeShewill-CV** [comment]
@ryan1051 要得到属性需要修改语意分割输出和增加后处理，现有模型不能得到:)

**Comment by ryan1051** [comment]
@MaybeShewill-CV ok，谢谢
