### ISSUE TITLE
关于车道线拟合的问题

### ISSUE THREAD

**Issue by liuyanglab** [MaybeShewill-CV/lanenet-lane-detection#361]
您好，我看您在postprocess文件里，加载了ipm_remap文件，您是把原图转换成俯视图再做车道线拟合吗？是这样的，我在学习摩托车车道偏离预警，相机参数一直在变化，所以想在原图上直接拟合车道线，不知道行不行的通，如果直接拟合的话，应该用什么函数呢？

**Comment by MaybeShewill-CV** [comment]
@liuyanglab 俯视图上一般都是二次函数 原图拟合你可以尝试二次和三次函数：）
