### ISSUE TITLE
Lane / road marking / vanishing point dataset

### ISSUE THREAD

**Issue by SeokjuLee** [MaybeShewill-CV/lanenet-lane-detection#362]
[VPGNet](https://arxiv.org/abs/1710.06288) dataset is available.
It contains around 21K images with human-annotated lane, road markings, and vanishing point labels.
For more details, please check our project [page](https://github.com/SeokjuLee/VPGNet#vpgnet-dataset).

**Comment by MaybeShewill-CV** [comment]
@SeokjuLee Thanks:)
