### ISSUE TITLE
关于车道线拟合部分的疑问

### ISSUE THREAD

**Issue by zy1817104** [MaybeShewill-CV/lanenet-lane-detection#363]
您好，我想请问下i'pm_remap.yml文件是怎么得到的？并且里面的数值代表什么意思？
十分感谢、期待您的回复！

**Comment by MaybeShewill-CV** [comment]
@zy1817104 ipm remap矩阵是存放了将图像转换为俯视图的remap矩阵 具体生成可以参考 https://github.com/MaybeShewill-CV/Easy-Ipm-Client 中提到的方法
