### ISSUE TITLE
关于postprocess部分的提问

### ISSUE THREAD

**Issue by liuyanglab** [MaybeShewill-CV/lanenet-lane-detection#364]
您好，在详细看了代码后有几点搞不太懂，想问下您，麻烦您了
问题一：在test_lanenet.py中line129，postprocess函数传入的参数是instance_seg_image[0]，instance_seg_image有四个维度[batch,width,height,channel],这里instance_seg_image[0]是指一个batch中的第一张图吗?
问题二：输出mask图像时，test_lanenet.py中line133   mask_image[:, :, (2, 1, 0)]不太明白，（2，1，0）是指rgb三通道吗？
问题三：想请教您，如果要识别出当前正在行驶的车道应该怎么做？是在制作label时只标记当前两条车道，还是在后处理部分进行操作

**Comment by MaybeShewill-CV** [comment]
@liuyanglab 1. 对 2.是指把opencv的[b, g, r]顺序换成[r, g, b]顺序 3.可以尝试制作label的时候只标注ego lane:)

**Comment by liuyanglab** [comment]
@MaybeShewill-CV 感谢您的回答，可不可以先不要close 这个问题，我再看看代码，麻烦您了！

**Comment by MaybeShewill-CV** [comment]
@liuyanglab ok

**Comment by liuyanglab** [comment]
@MaybeShewill-CV 您好，我在做检测视频时，一帧图片的检测时间大概是Single imgae inference cost time: 0.20143s，整个视频的检测速度是2-3fps,数据集用的是我自己的，请问这样的速度正常吗，您当时一张图片的检测速度是多少呢？

**Comment by MaybeShewill-CV** [comment]
@liuyanglab 经过部分优化之后能达到12fps左右：）

**Comment by liuyanglab** [comment]
您好，感谢您的回答，请问部分优化具体是指什么呢？
发自我的iPhone

------------------ 原始邮件 ------------------
发件人: MaybeShewill-CV <notifications@github.com&gt;
发送时间: 2020年4月9日 00:40
收件人: MaybeShewill-CV/lanenet-lane-detection <lanenet-lane-detection@noreply.github.com&gt;
抄送: liuyanglab <509840123@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[MaybeShewill-CV/lanenet-lane-detection] 关于postprocess部分的提问 (#364)





 
@liuyanglab 经过部分优化之后能达到12fps左右：）

**Comment by MaybeShewill-CV** [comment]
@liuyanglab 1.优化feed pipline 2.更换网络front end部分：）

**Comment by liuyanglab** [comment]
好的，多谢您的回答


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: MaybeShewill-CV <notifications@github.com&gt;
发送时间: 2020年4月9日 00:46
收件人: MaybeShewill-CV/lanenet-lane-detection <lanenet-lane-detection@noreply.github.com&gt;
抄送: liuyanglab <509840123@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[MaybeShewill-CV/lanenet-lane-detection] 关于postprocess部分的提问 (#364)





 
@liuyanglab 1.优化feed pipline 2.更换网络front end部分：）
