### ISSUE TITLE
纯小白的提问，执行generate_tusimple_dataset.py未生成val.txt文件

### ISSUE THREAD

**Issue by FlyingSharp** [MaybeShewill-CV/lanenet-lane-detection#365]
大佬你好，我是一个纯小白，我在运行tools/generate_tusimple_dataset.py 的时候，training文件夹中只生成了三个文件夹：gt_binary_image；gt_image；gt_instance_image + 三个label的json文件 + train.txt。 testing文件夹中只有test_label.json这一个文件，请问为什么没有val.txt呀？
我是把train_set.zip和test_set.zip解压出来再运行tools/generate_tusimple_dataset.py 的。因为我试着直接将路径写到train_set.zip、test_set.zip、test_label.json所在的目录，结果只会在train_set.zip所在的目录生成training和testing文件夹，里面也没有val.txt，train.txt也是空的，testing文件夹里只有test_label.json文件。我在generate_tusimple_dataset.py的代码里面也没看可以生成val.txt文件的代码段。所以val.txt文件到底要怎么样才能生成啊？（我把zip解压好之后，倒是可以生成相关的png文件，train.txt也不是空的）可能这个问题对大佬们来说来说太简单了，我在网上找不到问题的原因。折腾了好长时间。只能向大佬求救了。

**Comment by MaybeShewill-CV** [comment]
@FlyingSharp 自己手动剪出来一部分train.txt到val.txt就可以了:)

**Comment by FlyingSharp** [comment]
@MaybeShewill-CV 谢谢大佬，突然感觉自己的这个问题好傻哈哈哈

**Comment by MaybeShewill-CV** [comment]
@FlyingSharp 没关系 是我偷懒 没有主动生成val.txt文件

**Comment by FlyingSharp** [comment]
@MaybeShewill-CV 老哥你也太随和了，我能说i了i了吗？（手动滑稽）

**Comment by MaybeShewill-CV** [comment]
@FlyingSharp ==! (狗头保命)
