### ISSUE TITLE
如何用训练好的lanenet模型测试自己的图片？

### ISSUE THREAD

**Issue by WangHeHe008** [MaybeShewill-CV/lanenet-lane-detection#367]
我按照步骤训练好lanenet模型，（只想做车道线检测，不需要做拟合），现在用tools/test_lanenet.py做测试,报各种错误，请指点!
python test_lanenet.py
 --weights_path /home/wanghe/lane/lanenet-lane-detection-master/tools/model/tusimple_lanenet_vgg/tusimple_lanenet_vgg_2020-03-26-21-30-47.ckpt-80001
 --image_path /home/wanghe/1.jpg

**Comment by WangHeHe008** [comment]
AssertionError: /home/wanghe/lane/lanenet-lane-detection-master/data/tusimple_ipm_remap.yml not exist

**Comment by MaybeShewill-CV** [comment]
@WangHeHe008 下载remap文件到指定的位置 你可以仔细看下readme。

**Comment by WangHeHe008** [comment]
您那边可以提供一个remap文件吗？网上找不到，我只是用来跑通测试，做检测不拟合

**Comment by MaybeShewill-CV** [comment]
@WangHeHe008 data文件夹里就有啊 ==! 麻烦你仔细看看
