### ISSUE TITLE
What is the minimum number of elements to train?

### ISSUE THREAD

**Issue by dpramirez** [MaybeShewill-CV/lanenet-lane-detection#369]
In addition to the doubt of the title, are you creating the training images with any specific program?

**Comment by MaybeShewill-CV** [comment]
@dpramirez The tusimple dataset was used in this program and you may refer to their website to check out the detailed description about it. Also the model can be trained on culane dataset and you're welcomed to do such a experiment:)

**Comment by dpramirez** [comment]
@MaybeShewill-CV  I understand and it is quite clear to me, my problem is how I generate the binary image and the instance, I generated it manually occupying gimp but when adding it, the training falls. Also I just wanted to add a couple more images that interested me and Culane is more information than I need.

**Comment by MaybeShewill-CV** [comment]
@dpramirez You may look at this https://github.com/MaybeShewill-CV/lanenet-lane-detection/blob/master/tools/generate_tusimple_dataset.py which will guide you to generate the training samples:)

**Comment by dpramirez** [comment]
I saw it, I appreciate the answer. But what I do not understand is where I get the json and how I produce it, I saw in other doubts that there is another repository that generates them but there must be a simpler way.
If you can give me a guide or help I would be very grateful. my image is as follows:
![0006](https://user-images.githubusercontent.com/39503441/78747090-94ced800-7936-11ea-8906-3116666922f9.png)
Quiero detectar las siguientes lineas:
![0006_a](https://user-images.githubusercontent.com/39503441/78747459-73bab700-7937-11ea-9edc-22a6fe079cb6.png)

Sorry I'm still a novice, I don't want to cause you trouble.

**Comment by MaybeShewill-CV** [comment]
@dpramirez Google the usage of labelme which should help you to annotate such a image segmentation task:)

**Comment by dpramirez** [comment]
some example of the json that you use for the generate_tusimple

**Comment by MaybeShewill-CV** [comment]
@dpramirez Seems that the dataset are not available now on Tusimple website. You'd better to google it yourself:)

**Comment by monilshah1988** [comment]
@MaybeShewill-CV @dpramirez , Do we need to make binary images and instance images from labelme tool for like 1000 images?
