### ISSUE TITLE
problem about train own model

### ISSUE THREAD

**Issue by cuicuizhang1989** [MaybeShewill-CV/lanenet-lane-detection#37]
thanks for your great work, but I wonder why I trained model using tusimple traindata (the number is 3626) 
 following the readme in this project, cannot achieve looks well result. The train loss looks well , but the trained model cannot achieve a  effective result.

**Comment by MaybeShewill-CV** [comment]
@cuicuizhang1989 Sorry i can not figure it out because i am not well informed

**Comment by cuicuizhang1989** [comment]
@MaybeShewill-CV 请问您使用的训练样本的数量是多少呢？ 是只使用了3626张tusimple的训练数据吗？

**Comment by MaybeShewill-CV** [comment]
@cuicuizhang1989 就是tusimple数据集

**Comment by cuicuizhang1989** [comment]
I have solved my problem, thanks.
