### ISSUE TITLE
车道线像素集合再哪个变量里？

### ISSUE THREAD

**Issue by WangHeHe008** [MaybeShewill-CV/lanenet-lane-detection#370]
你好，我想知道检测到的每个车道线的像素集合及其id在哪个变量里，感谢～

**Comment by MaybeShewill-CV** [comment]
@WangHeHe008 看下这个https://github.com/MaybeShewill-CV/lanenet-lane-detection/blob/master/lanenet_model/lanenet_postprocess.py 模块里的postprocess函数吧：）
