### ISSUE TITLE
关于 remap 文件

### ISSUE THREAD

**Issue by Steve-Mr** [MaybeShewill-CV/lanenet-lane-detection#371]
你好，关于 remap 文件我有几个问题：

1. 按照我的理解，要生成 remap 文件需要有相机相关的参数（相机离地高度，俯仰角，偏向角等），但是 tusimple 数据集有 “We do not have a calibration file for Lane Detection Challenge.” 的说明。我想知道你是如何得到这些参数的，或者说是我的理解有误或是有一些公开的参数我没有找到，还请您指出。

2. remap 文件的生成是根据 _Adaptive Inverse Perspective Mapping for Lane Map Generation with SLAM_ 这篇论文的算法实现的，但是这篇论文中将原 IPM 方法中的 θ0 替换为了 θ0 + θp，我的理解是 θ0 （原文中称为 "a tilt angle of a camera"）已经是相机的俯仰角，那么再添加的 θp 是指地面的坡度或者说是汽车的俯仰角？（并以此来应对坡度的变化？）
![Adaptive IPM 中最终的侧视图](https://user-images.githubusercontent.com/24504742/79071466-7558f600-7d0e-11ea-9d6f-a81abc500fb6.png)

最后如果对你造成打扰还请我在这里提前抱歉。

**Comment by MaybeShewill-CV** [comment]
@Steve-Mr theta p是相平面上某个点相对于通过像平面中心的z轴的偏角, 这个图上应该话的挺清楚。然后这个地平面是你指的汽车行驶当下的地平面：）

**Comment by Steve-Mr** [comment]
谢谢解答！
另外不知道你是否方便说明一下如何在 tusimple 没有给出校定文件和相机姿态等参数情况下进行IPM转换的，谢谢！

**Comment by MaybeShewill-CV** [comment]
@Steve-Mr 我是自己测试不同的pitch角 然后看实验效果决定的:)

**Comment by Steve-Mr** [comment]
谢谢解答 非常感谢！
