### ISSUE TITLE
Using Fast Scnn as for segmentation

### ISSUE THREAD

**Issue by sieuwe1** [MaybeShewill-CV/lanenet-lane-detection#373]
Hi @MaybeShewill-CV 

I believe lanenet uses the vgg16 architecture for segmentatic segmentation? If so would it be possible to use some of the later more successful architectures like Fast scnn which have much better real time performance. I am working on a project where I am making a self driving vehicle and thus my computational power is limited to a gtx1080. I would still like to reach the highest FPS possible. 

Is it possible to change the segmentation model architecture to Fast scnn? 
And what FPS would you expect on the implementation you already have with a gtx1080?

Greetings

Sieuwe

**Comment by MaybeShewill-CV** [comment]
@sieuwe1 fastscnn can be modified as the backbone net of lanenet model. Pure inference time without the time consuming of postprocess would at least reach above 50fps if you use some more effective segmentation backbone (eg. fast scnn、bisenet).
