### ISSUE TITLE
Error when testing on other highway images

### ISSUE THREAD

**Issue by yoga-0125** [MaybeShewill-CV/lanenet-lane-detection#376]
Hello, I tried running the test_lanenet.py for other highway images (not TuSimple data). The results are attached. Why the pre-trained network cannot fit lines on the image and how to solve it? 

Thank you for your help. 

![test image](https://user-images.githubusercontent.com/57866841/79938226-0411f500-842a-11ea-8b90-f094ae2ee06a.jpg)
![result](https://user-images.githubusercontent.com/57866841/79938231-08d6a900-842a-11ea-84b5-52e0ea8219f3.PNG)

**Comment by MaybeShewill-CV** [comment]
@yoga-0125 The post process module can not be used on other data directly due to the remap file. You may fetch the binary segmentation and instance segmentation result and do the post process yourself:)

**Comment by yoga-0125** [comment]
Thanks for your reply. 

And can the pre-trained model weights be used for transfer learning?

**Comment by MaybeShewill-CV** [comment]
@yoga-0125  They're supposed to work:)
