### ISSUE TITLE
not run on GPU

### ISSUE THREAD

**Issue by diennv** [MaybeShewill-CV/lanenet-lane-detection#377]
Hi @MaybeShewill-CV,
Thank you for your great work,

I am trying to run your works on C++ by using mnn-lanenet project.

By MNN convert cpkt --> pb--> *.mnn file. My host PC has GPU card GTX2070 and i run with *.mnn model on Docker. I got only 2 fps. 

After checking GPU load, i found that model was not load on GPU (Used GPU RAM memory did not change) , lanenet seem run on CPU.  I used pre-traied model provided by you.

How to check and setting to  run lanenet on GPU ?

Thank you so much.

**Comment by MaybeShewill-CV** [comment]
@diennv MNN project was used to run on mobile devices. Use origin tf tools to run the model on gpu. README file will guide you there:)

**Comment by diennv** [comment]
@MaybeShewill-CV , i got it.
Thank for your support
