### ISSUE TITLE
inference time too slow

### ISSUE THREAD

**Issue by LeRoii** [MaybeShewill-CV/lanenet-lane-detection#379]
hello,
I tried your code on 2080 Ti, I got a single image inference time about 6s, it seems weird, any suggestion about this?
thanks

**Comment by MaybeShewill-CV** [comment]
@LeRoii Check if your gpu works normally:)

**Comment by LeRoii** [comment]
> @LeRoii Check if your gpu works normally:)
thanks for your reply, but I'm not very clear about where should I look into,
I added CUDA_VISIBLE_DEVICES=1 does that mean the gpu was used during the inference

**Comment by LeRoii** [comment]
> > @LeRoii Check if your gpu works normally:)
> > thanks for your reply, but I'm not very clear about where should I look into,
> > I added CUDA_VISIBLE_DEVICES=1 does that mean the gpu was used during the inference

it's quite weird when I set CUDA_VISIBLE_DEVICES=-1, the inference time was 1s, why it becomes slower when I use gpu

**Comment by MaybeShewill-CV** [comment]
@LeRoii Maybe your TensorFlow-gpu was not correctly installed:)
