### ISSUE TITLE
sth. about embedding branch

### ISSUE THREAD

**Issue by RudolfLiu** [MaybeShewill-CV/lanenet-lane-detection#38]
作者您好，非常感谢您的工作。我有个问题想请教您：
1）对于embedding分支我们是否真的需要？这样的分支加聚类无疑也是一笔开销，那么能否直接e2e的方式输出每条车道线。若是不可以，麻烦指教下原因？
2）延申：关于车道线我们无非关注是当前车道和非当前车辆行驶车道，这种情况是否可以e2e？

**Comment by MaybeShewill-CV** [comment]
@RudolfLiu embedding主要是为了instance segmentation服务的,如果没有这个需求可以不需要
