### ISSUE TITLE
如何在自己训练好的权重上恢复训练？

### ISSUE THREAD

**Issue by WangHeHe008** [MaybeShewill-CV/lanenet-lane-detection#380]
因为训练生成的结果包含.meta，.data，.index，改如何恢复训练呢？请提供一下运行指令，谢谢

**Comment by MaybeShewill-CV** [comment]
@WangHeHe008 参考https://github.com/MaybeShewill-CV/lanenet-lane-detection/blob/9154c1497291276f03fb70a33149b152aa74cda3/tools/train_lanenet.py#L410-L416
