### ISSUE TITLE
discriminative loss

### ISSUE THREAD

**Issue by liuyanglab** [MaybeShewill-CV/lanenet-lane-detection#381]
对比您以前版本的代码，请问嵌入分支损失函数中距离的计算是之前用的是L2范数，现在用的L1范数吗？那参数delta_v和delta_d不用改吗？

**Comment by MaybeShewill-CV** [comment]
@liuyanglab 这个参数我没改 你也可以调整试试看：）

**Comment by liuyanglab** [comment]
多谢您的回答，我再调调参数

**Comment by MaybeShewill-CV** [comment]
@liuyanglab 好滴:)
