### ISSUE TITLE
Testing the model on another image type

### ISSUE THREAD

**Issue by AN-Ahmed** [MaybeShewill-CV/lanenet-lane-detection#382]
I would like to test your model on another image that have different resolution (attached below) I would like were can I find the parameters in the post process to adjust for it to view the lane markings on this image. 

EDIT:: I have been through other issues in this repo , and I found that I need to edit the post process , I'm a quite new to deep learning and CV , it would be great if someone can advise me on what parts exactly to look on and change in the post process

PS. I have resized the image to suit the resolution of the TuSimple test images , the model runs , but it views the src image the same as the image I inserted and the detected lanes are not added, and the masked image shows a black image.

![frame_1](https://user-images.githubusercontent.com/42812987/81006967-ab425380-8e50-11ea-9d5a-84c8da2deb9f.png)

![binary](https://user-images.githubusercontent.com/42812987/81006986-b2696180-8e50-11ea-8f9e-f09930759f8d.png)

![instance](https://user-images.githubusercontent.com/42812987/81006998-b8f7d900-8e50-11ea-830b-6bb5f30b774c.png)

![src](https://user-images.githubusercontent.com/42812987/81007014-c0b77d80-8e50-11ea-9853-37b3b2e80359.png)

![mask](https://user-images.githubusercontent.com/42812987/81007039-cca33f80-8e50-11ea-9f3a-8744123fcaf5.png)

**Comment by MaybeShewill-CV** [comment]
@AN-Ahmed You need a new remap.yml which is used to convert the source image from front view into bird view. You can read the post process module for details:)

**Comment by AN-Ahmed** [comment]
Thanks for your swift reply and time, I have seen another closed issue linking to on of your repo on how to generate remap.yml files :)

My qestion regarding the remap.yml file , do I need to make it for all test images from the same distribution , or making it for only one image will be enough?

**Comment by MaybeShewill-CV** [comment]
@AN-Ahmed One is enough. The remap.yml for Tusimple dataset was generated via one of the testing image in the dataset:)

**Comment by AN-Ahmed** [comment]
Thanks alot :)

**Comment by MankaranSingh** [comment]
@MaybeShewill-CV Can you point to a good way of making a custom remap.yml file ?

**Comment by MaybeShewill-CV** [comment]
@MankaranSingh 1.For ipm image you may simply do a perspective transformation to get it. You may google how to do it. 2.Actually you can do your own post process procedure instead of using my version here:)
