### ISSUE TITLE
lanenet_postprocess

### ISSUE THREAD

**Issue by AN-Ahmed** [MaybeShewill-CV/lanenet-lane-detection#384]
I was wondering why you are diving the image height by 256 and the width by 512 , what does these values represent?

https://github.com/MaybeShewill-CV/lanenet-lane-detection/blob/9154c1497291276f03fb70a33149b152aa74cda3/lanenet_model/lanenet_postprocess.py#L351

Thanks :)

**Comment by MaybeShewill-CV** [comment]
@AN-Ahmed The origin image size is (1280, 720). The rescaled image size is (512, 256). :)

**Comment by AN-Ahmed** [comment]
Thanks for your time :)
