### ISSUE TITLE
Error in tensor mismatching

### ISSUE THREAD

**Issue by arvindhbti** [MaybeShewill-CV/lanenet-lane-detection#385]
Hi,

when i am running the script, i got the error.

input to reshape is a tensor with 470016 values, but the requested shape has 156672.

how can i solve this error.

**Comment by MaybeShewill-CV** [comment]
@arvindhbti Check if you load a binary image with color mode:)

**Comment by arvindhbti** [comment]
Hi @MaybeShewill-CV  thanks a lot for your quick reply.
My Binary images and instance images are 3 channel images.
so can we change this in code or we have to take care of this during data preparation?
Thanks in advance.

**Comment by MaybeShewill-CV** [comment]
@arvindhbti Binary and instance image should be 1 channel:)

**Comment by him009verma** [comment]
hi @MaybeShewill-CV  I am also facing the same issue however i corrected the binary and instance segmented image single channel and regenerated the tfrecords but still I am getting the same error although tensor numbers have changed only, please suggest

**Comment by MaybeShewill-CV** [comment]
@him009verma Simplest way is to diff the image dataset between yours and tusimple's:)

**Comment by MaybeShewill-CV** [comment]
@him009verma @arvindhbti The gt_image should have shape [512, 256, 3] and binary image should have shape [512, 256]. You may check the way I generate tusimple training images:)

https://github.com/MaybeShewill-CV/lanenet-lane-detection/blob/9154c1497291276f03fb70a33149b152aa74cda3/tools/generate_tusimple_dataset.py#L61-L65

**Comment by him009verma** [comment]
@MaybeShewill-CV thanks :) will try this too but just one doubt that if we convert the instance image to greyscale image then colors will disappear, is this something i am doing wrong ??

**Comment by MaybeShewill-CV** [comment]
@him009verma instance label image are not supposed to have color:)

**Comment by him009verma** [comment]
@MaybeShewill-CV i am taking about the colors of lanes in instance image i think in your dataset  you have given different colors to the lanes in instance images

**Comment by MaybeShewill-CV** [comment]
@him009verma The instance label image are not supposed to have color. Each pixel value in that label image is the intance id. The color image you see is the visualization result of instance segmentation output. You'd better read the origin paper carefully:)

**Comment by him009verma** [comment]
@MaybeShewill-CV thanks for the help :)

**Comment by MaybeShewill-CV** [comment]
@him009verma welcome:)
