### ISSUE TITLE
Why could this be a mistake during training?

### ISSUE THREAD

**Issue by dpramirez** [MaybeShewill-CV/lanenet-lane-detection#386]
![Train](https://user-images.githubusercontent.com/39503441/81954569-030e5680-95d7-11ea-87a5-afb3563d46c6.PNG)
I have a question about how the training works, I don't know why this error happens.
It could be an error in the tfrecord preparation buffer or the GPU.

**Comment by MaybeShewill-CV** [comment]
@dpramirez You may google it:)

**Comment by MaybeShewill-CV** [comment]
@dpramirez I have not met this ever. First make sure you have correctly generated tensorflow records:)

**Comment by him009verma** [comment]
@dpramirez i can see your training gets started, I am facing issue in the training code, error is Input tensor mismatch, can you please help me, can u please tell if you are training on your custom data if yes please let me know what dimensions you have written in config/global_config file.

Note: I have tried training on my own dataset and even on provided dataset by maybeshewill I am getting the same error, input tensor mismatch, I really want to understand where its wrong

**Comment by dpramirez** [comment]
@him009verma  try to check the tfrecord, in general my problems at first when trying to use these were due to not generating the good ones.  it works for me with Custom datasets.  The problems I have now with my data.

**Comment by him009verma** [comment]
@dpramirez thanks, I am new to tfrecords, however i generated them successfully by the script but what do you mean by not generating good ones, how can i check if these are ok or not, a little hint can help me

**Comment by dpramirez** [comment]
@him009verma  take my mail, let's talk through that means! dpramirez@miuandes.cl

**Comment by him009verma** [comment]
@dpramirez  thanks buddy the issue was with tfrecord, now i am able to train it, anyways will connect with you :)

**Comment by AN-Ahmed** [comment]
@him009verma , I think I have similar issue as you , can you please share with me how did you fix the tfrecord. Thanks

**Comment by him009verma** [comment]
@AN-Ahmed first try by clearing the tfrecords folder and rerun code

**Comment by dpramirez** [comment]
@MaybeShewill-CV  the question is whether the images in the dataset should have any characteristics or types. You should be a little clearer the exemplification to be able to train with more images.

**Comment by MaybeShewill-CV** [comment]
@dpramirez Maybe you're supposed to learn more about the tusimple dataset or other semantic segmentation dataset like this by yourself. The repo was not pushed here to process the dataset relatives problems:)
