### ISSUE TITLE
Training using the provided examples

### ISSUE THREAD

**Issue by AN-Ahmed** [MaybeShewill-CV/lanenet-lane-detection#387]
I'm training the model using the training examples available in this repo, and I'm using vgg16.npy available in this repo(https://github.com/machrisaa/tensorflow-vgg).

When I run the training I get this error ,and what causes it.

Thanks in advance :)

![Selection_060](https://user-images.githubusercontent.com/42812987/81989490-9d08ea00-963d-11ea-8925-fd8678218626.png)

**Comment by MaybeShewill-CV** [comment]
@AN-Ahmed You may google how to solve cause that's not a problem relative to this model:)
