### ISSUE TITLE
关于训练问题，instance_seg_loss收敛特别慢，导致total_loss收敛很慢，怎么办

### ISSUE THREAD

**Issue by lvxuanxuan123** [MaybeShewill-CV/lanenet-lane-detection#389]

**Comment by MaybeShewill-CV** [comment]
@lvxuanxuan123 可以尝试增大instance segmentation分支的学习率:)

**Comment by lvxuanxuan123** [comment]
博主，您好，我只知道可以在config文件里面设置学习率，该如何分开设置

**Comment by MaybeShewill-CV** [comment]
@lvxuanxuan123 需要你自己改代码实现。

**Comment by lvxuanxuan123** [comment]
您好，我使用labelme标注数据集（自己使用摄像头采集的城市道路，用线段标注的方法标注车道线），首先使用20张图片训练（epoch=30000, learning_rate=0.01），所有的loss差不多都降到了0.01，效果不错（也有效果差的图片），后来加大图片数量到500张，（epoch=200000, learning_rate=0.0005，0.001，0.01，0.005），效果全部都很差，这有没有可能是我的数据集的问题，或者是我标注方法的问题。效果较差的照片如图
![0078](https://user-images.githubusercontent.com/32082480/82171348-a0c89500-98f9-11ea-9905-5ea0c5b5219e.jpg)
![2020-05-18 11-12-35 的屏幕截图](https://user-images.githubusercontent.com/32082480/82171359-ab832a00-98f9-11ea-8669-130bf9fe4384.png)

**Comment by lvxuanxuan123** [comment]
![2020-05-18 11-12-35 的屏幕截图](https://user-images.githubusercontent.com/32082480/82171415-d2d9f700-98f9-11ea-96c1-b7f659edc7f6.png)

**Comment by MaybeShewill-CV** [comment]
@lvxuanxuan123 你自己的数据要根据你自己的数据调整后处理过程中的一些超参数。 比如DBSCAN聚类相关的参数 直接使用tusimple对应的参数肯定不行的。 你上面那个效果差的图像其实就是dbscan聚类错误导致把两条不同的车道线聚类成了同一条:)

**Comment by lvxuanxuan123** [comment]
谢谢博主指导
