### ISSUE TITLE
fp过高

### ISSUE THREAD

**Issue by liuyanglab** [MaybeShewill-CV/lanenet-lane-detection#391]
想问一下，训练结果中fp(误检率)一直很高，大概有0.55，但是我看二值图像，并没有检测到多余的车道线，请问这可能是什么原因？，感谢博主！

**Comment by MaybeShewill-CV** [comment]
@liuyanglab 生成label的时候车道线是按照固定宽度生成的 很可能生成的label中的车道线比实际地面上的车道线宽。还是关注最终的结果能不能满足你的实际需求，要刷点的话，这个不行的.

**Comment by liuyanglab** [comment]
明白了，谢谢您
