### ISSUE TITLE
运行train_lanenet.py出现 AssertionError: ./data/vgg16.npy not exist

### ISSUE THREAD

**Issue by lygmsy123** [MaybeShewill-CV/lanenet-lane-detection#392]
在google colab上运行出现AssertionError: ./data/vgg16.npy not exist，我在原始./data下没有发现这个文件，请问该文件怎么获取或生成

**Comment by MaybeShewill-CV** [comment]
@lygmsy123 上网搜索一下 可以下载的到：）

**Comment by lygmsy123** [comment]
@MaybeShewill-CV 你好，可以再问一下如何启动tensorboard来查看训练过程中正确率等变化，新手，不会使用

**Comment by MaybeShewill-CV** [comment]
@lygmsy123 终端里输入tensorboard --logdir ./日志存储路径 https://www.jianshu.com/p/d8f9b0dfacdb

**Comment by lygmsy123** [comment]
@MaybeShewill-CV 您好，我在./tboard/tusimple_lanenet_vgg/下找到日志，但显示的只有网络的graphs，没有acc，fp，fn等变化的曲线图，请问是我找的日志地址不对吗？
还可以询问下为什么fp在训练过程中为什么一直保持在0.7几，这是什么原因造成的呢？

**Comment by MaybeShewill-CV** [comment]
@lygmsy123 1.检查你的summary相关的代码有没有问题吧 2.fp一直在0.7几 不知道你的数据什么样　所以我也不太清楚。建议还是多关注模型处理的结果能不能满足你的生产需求。

**Comment by weijian555** [comment]
> @ MaybeShewill-CV您好，我在./tboard/tusimple_lanenet_vgg/下查找日志，但显示的只有网络的图，没有acc，fp，fn等变化的曲线图，请问是我找的日志地址不对吗？
@lygmsy123 你好，请问如何生成acc、fp、fn这些曲线图呢？
