### ISSUE TITLE
evaluation

### ISSUE THREAD

**Issue by chenyiman** [MaybeShewill-CV/lanenet-lane-detection#393]
I have trained the model, but I have to compare it with the ground truth of the testing data  when I evaluate it, that is, every line should be correspond to each other. How can I know which lines are predicted? For example, one graph has four lane lines, but the network only predicts three of them. How can I know which three of the four lines are predicted?

**Comment by MaybeShewill-CV** [comment]
@chenyiman Maybe you should make some rules (eg. Pixel distance with label or something) to identify it:)
