### ISSUE TITLE
using lanenet in opencv 

### ISSUE THREAD

**Issue by naserpiltan** [MaybeShewill-CV/lanenet-lane-detection#395]
Hello
Im tying to use this model in opencv c++. I froze saved checkpoints with the name of lanenet.pb succesfully.But when i import this model in the opencv readNet module ,  i have this issue :
`OpenCV(4.2.0) /home/eagle-soft/opencv/modules/dnn/src/tensorflow/tf_importer.cpp:544: error: 
(-2:Unspecified error) Input layer not found: lanenet_model/vgg_frontend/vgg16_decode_module/instance_seg_decode/decode_stage_1_fuse/deconv/deconv/Shape in function 'connect'
`
can anybody help me ? is there an other way to use lanenet in c++ ?I know that in mnn_project there is some c++ source codes but i don't know how to use them.

**Comment by MaybeShewill-CV** [comment]
@naserpiltan 1.Seems you have used the wrong input layer. You may check again. 2. MNN usage can be found here https://github.com/MaybeShewill-CV/MNN-LaneNet

**Comment by naserpiltan** [comment]
@MaybeShewill-CV  thank you so much for link. 
what is the correct input layer name? i used the mnn_project/freeze_lanenet_model.py script to freeze the checkpoints. do i have to change some lines in freeze_lanenet_model.py script ?
Thanks in advance

**Comment by MaybeShewill-CV** [comment]
@naserpiltan I have not used opencv to deploy the tf model so I have no idea what's going on here. The mnn_project/freeze_lanenet_model.py script doesn't need to be corrected:)

**Comment by naserpiltan** [comment]
@MaybeShewill-CV  thank you for your answer.
Sir can you guid me to compile MNNConverter ? I am reading the docs but there is no any information about that.

**Comment by MaybeShewill-CV** [comment]
@naserpiltan Just modify the cmakelist.txt file and open the BUILD_MNN_CONVERTER option. You may raise an issue in MNN project if you have any problem when build the project:)

**Comment by naserpiltan** [comment]
@MaybeShewill-CV finally I converted tensorflow checkpoints to MNN model and can do inference with anenet_detector.out with your solution. thank you so much sir. 
This is my output :
`detect, 144, cost time: 18.373001 ms
detect, 151, cost time: 878.525024 ms
detect, 202, cost time: 330.006012 ms
detect, 209, cost time: 86.454002 ms`

Now i have 2 questions :
1 - Does this model use GPU or it is just running on my CPU ?
2- I am developing an road segmentation app in Qt c++ and wanna use lanenet-mnn in my app. I don't know which libraries are needed to build lanenet successfully  in Qt. can you give some information about essential libraries ?
Thanks in advance

**Comment by naserpiltan** [comment]
@MaybeShewill-CV  sir i solved my second question.i can run MNN project and do inference in my Qt app but it is too slow. so i have my first question yet.
Im woundering about using MNN with cuda support to accelerate inference operation.
Do you have any idea about that ?

**Comment by MaybeShewill-CV** [comment]
@naserpiltan I suggest you to raise an relative issue in MNN project where you can get more useful guidance than here:)
