### ISSUE TITLE
acc,fp,fn反复振荡，不收敛,求教该调整哪些参数

### ISSUE THREAD

**Issue by lygmsy123** [MaybeShewill-CV/lanenet-lane-detection#397]
@MaybeShewill-CV 您好，我使用的是tuSimple数据集，用您提供的代码生成train.txt，val.txt，test.txt和数据集和tfrecords文件，在google colab上，使用tensorflow-gpu=1.15.2版本训练模型，初始学习率=0.0005，但评估模型用的acc、fp、fn初期能正常下降，但训练到10000次以后，三者均出现反复振荡现象，尤其是fp，保持在0.75左右振荡，想向您请教，对原代码哪些参数进行处理可能有效，如果您能解答我的疑惑，我将不胜感激，谢谢！

**Comment by MaybeShewill-CV** [comment]
@lygmsy123 主要还是学习率相关的参数。比如可是尝试cosine decay降低学习率 尝试加入warmup策略 加入ohem都可能改善模型效果:)

**Comment by lygmsy123** [comment]
@MaybeShewill-CV 谢谢您，我会进行尝试，同时，由于我是初次接触tensorflow，使用的是单gpu服务器，发现summary_writer.add_summary(summary=train_summary, global_step=epoch)并没有将acc，loss等的scalar写入文件，我不清楚怎么调整代码，请问该如何解决？

**Comment by MaybeShewill-CV** [comment]
@lygmsy123 单gpu也不影响。统计数据会写入到tensorboard日志中，你可以使用tensorboard查看:)
