### ISSUE TITLE
Problem Restricted training

### ISSUE THREAD

**Issue by dpramirez** [MaybeShewill-CV/lanenet-lane-detection#398]
Hello, how are you? I have a problem, I was able to prepare my data set but if I try with a high batch number, it falls due to lack of memory. Currently I have managed to train only one batch taking a time of 10 hours, which seems very strange to me since I have a RTX2080 graphics card. Here is an image that shows the consumption of the card with a batch. If you can help me or give me some advice it would be ideal.
regards
![gpu](https://user-images.githubusercontent.com/39503441/82842761-bc5b0f00-9ea8-11ea-8713-c46e74d71b5a.png)

**Comment by MaybeShewill-CV** [comment]
@dpramirez Can not figure out what's going wrong here. Everything seems normal here ==!

**Comment by dpramirez** [comment]
@MaybeShewill-CV  what I don't find normal is the amount of gpu memory that is occupying only training with a batch.

**Comment by MaybeShewill-CV** [comment]
@dpramirez The gpu memory are allocated during graph construction process. So it's normal that all of your cpu memo are allocated during training process:)

**Comment by dpramirez** [comment]
then there is no problem that only one batch occupies?, I mean because you can generate local kittens etc.

**Comment by MaybeShewill-CV** [comment]
@dpramirez I do not get your meaning of "one batch occupies" ==!

**Comment by dpramirez** [comment]
@MaybeShewill-CV I mean, using a batch of 1 doesn't produce local minima in the results.

**Comment by MaybeShewill-CV** [comment]
@dpramirez You mean batch size equals 1?

**Comment by dpramirez** [comment]
@MaybeShewill-CV  yes

**Comment by MaybeShewill-CV** [comment]
@dpramirez Batch size larger than 1 will cause out of gpu memory problem? If so you'd better raise an issue in TensorFlow repo. I have not met such a problem before:)
