### ISSUE TITLE
转化为Instance label时遇到的问题

### ISSUE THREAD

**Issue by zhangcheng999** [MaybeShewill-CV/lanenet-lane-detection#40]
你好，首先谢谢您分享代码，我在把图森数据转化为Instance label时遇到这样的问题，我看您给出的训练样例中是左=20，自车左=70，自车右=120，右=170，第五条=220，但是图森数据保存的lanes的顺序有的不是按照自车左，自车右，左，右，这样的顺序，因此会导致如下的情况
![2929](https://user-images.githubusercontent.com/26853693/43505854-c67a9d7a-959a-11e8-93e9-634a3f6457f5.png)
这是原图下面是instance图，因为原始label是按照从左至右的顺序，因此处理后就出现了自车左=20的情况
![2929](https://user-images.githubusercontent.com/26853693/43506014-54c48fe6-959b-11e8-8d61-4ed52fab6dcf.png)
请问您是如何处理这种情况的?还有一个问题想请教您就是图森的数据每个clip都有20张图，只有最后一张有label，那其他的图的作用是？小白一枚，百忙之后希望收到您的答疑十分感谢。

**Comment by MaybeShewill-CV** [comment]
@zhangcheng999 图森数据集的问题你可以去他们官网查看写的很详细. Instance Label制作只需要保证每个instance所给的标签不一致， 顺序没有关系

**Comment by zhangcheng999** [comment]
好的，谢谢
