### ISSUE TITLE
Tensor board

### ISSUE THREAD

**Issue by AN-Ahmed** [MaybeShewill-CV/lanenet-lane-detection#400]
Update:
I have found a way to run event file, but the url generated does not work, am I doing something wrong?

![tboard](https://user-images.githubusercontent.com/42812987/83069995-0f7cbf80-a06b-11ea-976d-b810e4467ebc.png)

I have also tried with adding --port6006 , but still the generated url is not working
![tboard2](https://user-images.githubusercontent.com/42812987/83070657-135d1180-a06c-11ea-863d-8e938f882e28.png)

Thanks

**Comment by MaybeShewill-CV** [comment]
@AN-Ahmed logdir is a directory path rather than a event file path. You may google how to use tensor board to solve it:)
