### ISSUE TITLE
CULane训练问题

### ISSUE THREAD

**Issue by nolovenolife** [MaybeShewill-CV/lanenet-lane-detection#401]
请问大神贴出来的最新的model只是使用了tusimple训练吗？是否有用到CULane

**Comment by MaybeShewill-CV** [comment]
@ffddlihong 只用到tusimple

**Comment by ffddlihong** [comment]
最近在尝试调整lanenet_discriminative_loss.discriminative_loss(
                        pix_embedding, instance_label, CFG.TRAIN.EMBEDDING_FEATS_DIMS,
                        pix_image_shape, 0.5, 3.0, 1.0, 1.0, 0.001
                    )
的参数，因为训练CULane数据集的过程中不定时出现
![image](https://user-images.githubusercontent.com/10968289/83498288-47ae5300-a4ee-11ea-9fe6-5e52027d4d01.png)
项目的其他issue都看过了，但是还没有解决。想请教下，看您有没有好的方法。

**Comment by MaybeShewill-CV** [comment]
@ffddlihong culane中没有车道线的标注图像过滤掉 应该就没有这个问题了

**Comment by ffddlihong** [comment]
已经过滤掉了的。line.txt文件为空的话，我不会去生成gt_binary_image和gt_instance_image。
前面看到您在一个issue里面说需要调整lanenet_discriminative_loss.discriminative_loss(
pix_embedding, instance_label, CFG.TRAIN.EMBEDDING_FEATS_DIMS,
pix_image_shape, 0.5, 3.0, 1.0, 1.0, 0.001
)
里面的0.5, 3.0, 1.0, 1.0, 0.001  这几个参数

**Comment by MaybeShewill-CV** [comment]
@ffddlihong 现在这个版本的程序搭配现在的这个参数是不会在culane上nan的 出现nan大概率还是你的数据有问题:)

**Comment by ffddlihong** [comment]
![015876](https://user-images.githubusercontent.com/10968289/83500098-e936a400-a4f0-11ea-8574-1504f10a9476.png)
我生成的数据中有这种，请问正常吗？

**Comment by ffddlihong** [comment]
就是读取的lines.txt然后画线

**Comment by MaybeShewill-CV** [comment]
@ffddlihong 你可以做个彩色的掩码叠加在原图上检查:)

**Comment by ffddlihong** [comment]
好的，我再试试。感谢~   不行我把这种一条线的全部干掉

**Comment by MaybeShewill-CV** [comment]
@ffddlihong 嗯 你可以试试看。而且这种很短很短的单根线本身的价值我觉得就不是很大:)

**Comment by ffddlihong** [comment]
因为图片中有的是lines.txt里面是 883.533 310 869.624 300 855.165 290 
所以画出来就是上面这个样子。其他的为空的我都过滤掉了的。

**Comment by ffddlihong** [comment]
想请教下，您在处理数据的时候是只按他这个标注来的还是有做过优化？

**Comment by MaybeShewill-CV** [comment]
@ffddlihong 做过筛选 有一部分我觉得不是很合适的我就人工删除了:)

**Comment by ffddlihong** [comment]
好的  谢谢  我下来试试。有结果了过来告诉您

**Comment by MaybeShewill-CV** [comment]
@nolovenolife ok :)

**Comment by nolovenolife** [comment]
我设置了个条件就是把y方向上长度不足100px的图片干掉后再生成tfrecords跑了一晚上没出现nan。感谢指导

**Comment by nolovenolife** [comment]
expoch 5w了 但是精度还上不去
![image](https://user-images.githubusercontent.com/10968289/83585116-9524d180-a57b-11ea-8cc9-8c0b451f2036.png)
请问这个正常吗？

**Comment by MaybeShewill-CV** [comment]
@nolovenolife 我也不记得我之前跑的日志了 还是你自己训练完了自己测试调整吧:)

**Comment by nolovenolife** [comment]
@MaybeShewill-CV 好的 谢谢

**Comment by nolovenolife** [comment]
![image](https://user-images.githubusercontent.com/10968289/83710158-a42a8300-a652-11ea-87aa-74a99cf691de.png)
还想请教下，如果像这种第一条和第二条线连起来的样本。如何通过DBSCAN区分开？

**Comment by MaybeShewill-CV** [comment]
@nolovenolife 通过instance segmentation的embedding features。这个你可以看下论文上的这部分内容哈:)

**Comment by nolovenolife** [comment]
@MaybeShewill-CV 好的 谢谢

**Comment by nolovenolife** [comment]
@MaybeShewill-CV 我这边看 用culane数据集训练后，用culane的测试集跑的话，城市道路场景下识别率还不错，和SCNN差别不大，并且要快。culane数据集就没有做交叉路口的标注，想问下楼主有没有做过交叉路口的实验？

**Comment by MaybeShewill-CV** [comment]
@nolovenolife 交叉路口的数据 你可以看看我司的apollo scope数据集 看看能不能满足你的需求哈：）

**Comment by nolovenolife** [comment]
@MaybeShewill-CV 好的 多谢~

**Comment by vanilla000** [comment]
> 
> 
> @MaybeShewill-CV 我这边看 用culane数据集训练后，用culane的测试集跑的话，城市道路场景下识别率还不错，和SCNN差别不大，并且要快。culane数据集就没有做交叉路口的标注，想问下楼主有没有做过交叉路口的实验？

你好，culane的数据集是怎么训练的，能指点一二吗？
