### ISSUE TITLE
请问一下 嵌入分支网络训练用的什么网络框架

### ISSUE THREAD

**Issue by yinhai86924** [MaybeShewill-CV/lanenet-lane-detection#402]
是否还是语义分割网络FCN8，只是把损失函数和训练标签变了？还是其他网络来训练？

**Comment by MaybeShewill-CV** [comment]
@yinhai86924 嵌入分支就是在原有的encoder-decoder backbone上新开了一个分支，这个你可以仔细看下论文，写的很清楚了：）
