### ISSUE TITLE
instance output value

### ISSUE THREAD

**Issue by ArtlyStyles** [MaybeShewill-CV/lanenet-lane-detection#405]
When we make the instance image for training, it has only one change, and the value for each lane is 100, 150, 200, 250, etc. But from the network, the instance image has 4 channels. Each channel has the lanes. What is the targeted value for the lanes in the 4 channels?

**Comment by MaybeShewill-CV** [comment]
@ArtlyStyles The channels nums represent the embedding feature dims rather than the lane nums instead:)
