### ISSUE TITLE
consistent lane numbers

### ISSUE THREAD

**Issue by ArtlyStyles** [MaybeShewill-CV/lanenet-lane-detection#406]
I have made my own training dataset and for each image, I have only one lane. Therefore, in the output binary image, I have two lines for the left and right border of the lane. The network worked well and can detect the two lines successfully. My problem is two label the left and right line consistently. Is there any way I can identify the left and right line?

**Comment by MaybeShewill-CV** [comment]
@ArtlyStyles The instance segmentation was used to tell you the different instance of lane line:)
