### ISSUE TITLE
vgg_lanenet with own dataset

### ISSUE THREAD

**Issue by naserpiltan** [MaybeShewill-CV/lanenet-lane-detection#409]
@MaybeShewill-CV  hello sir.
I am planning to train the lanenet with the vgg backbone on my own dataset.
I converted my dataset to tfrecords and can start training succesfully.
But just it saves bisenetv2 checkpoints , not vgg.
You have mentioned that  : **You can switch --net argument to change the base encoder stage. If you choose --net vgg then the vgg16 will be used as the base encoder stage and a pretrained parameters will be loaded** , But there is no any --net argument int the tools/train_lanenet_tusimple.py file.
Though i tried this command : **python tools/train_lanenet_tusimple.py --net vgg**
, but nothing changed and bisenetv2 checkpoints are saved.
What is my problem ? 
Thank you.

**Comment by MaybeShewill-CV** [comment]
@naserpiltan Modify this file https://github.com/MaybeShewill-CV/lanenet-lane-detection/blob/7cee4840588f2d1c80fa5ee594552fc5ae9018f4/config/tusimple_lanenet.yaml#L41-L48 FRONT_END should be "vgg"

**Comment by naserpiltan** [comment]
@MaybeShewill-CV  Thanks , i got it .
I have an other question.
Can we train the lanenet for more classes like roadside curbs ?
I want to segment not only the lines , roadside curbs too.

**Comment by MaybeShewill-CV** [comment]
@naserpiltan You need to modified the seg head by yourself. This repo's model was nothing different with other general image scene segmentation model:)

**Comment by naserpiltan** [comment]
@MaybeShewill-CV thank you for your answer.
I don't know what is seg head .sorry am newbie in this field.
Do you mean the output of lanenet (last layer) or it's some configurations in the config/tusimple_lanenet.yaml file ? 
Sorry for my dumb question.

**Comment by MaybeShewill-CV** [comment]
@naserpiltan The last several layers in the model. eg. https://github.com/MaybeShewill-CV/lanenet-lane-detection/blob/7cee4840588f2d1c80fa5ee594552fc5ae9018f4/semantic_segmentation_zoo/bisenet_v2.py#L999-L1042

**Comment by naserpiltan** [comment]
@MaybeShewill-CV Thanks , Im going to try it.

**Comment by MaybeShewill-CV** [comment]
@naserpiltan Welcome:)

**Comment by ArtlyStyles** [comment]
@naserpiltan check my curb detection with this repo https://twitter.com/SmallpixelCar

**Comment by naserpiltan** [comment]
@ArtlyStyles  Thanks for your reply. wow what a great work ! 
I tried @MaybeShewill-CV  solution for multiclass segmentation with Lanenet.
My classes are curbs and road and lines. 
But unfortunately couldn't modify the lenenet source code for more than one class . im noob in lanenet.
Do you  have any idea about that ?

**Comment by monilshah1988** [comment]
@naserpiltan Hey, I am also doing with my own dataset. How did you generate the tfrecord file?  I only have RGB images of lane(highway). It doesn't contain the binary and instance images of those lanes. Can you guide me on how did you generate those binary and instance images? I am having hard time with it.

**Comment by MaybeShewill-CV** [comment]
@ArtlyStyles Great work at https://twitter.com/SmallpixelCar:)

**Comment by naserpiltan** [comment]
@monilshah1988  Hi , You can use pixel annotation tool. you can find it in this link :[https://github.com/abreheret/PixelAnnotationTool](https://github.com/abreheret/PixelAnnotationTool).
It generates binary and colored mask for any image.then you can use them in lanenet easily.

**Comment by ArtlyStyles** [comment]
@pythonmjs you can generate a text file and the run the python program in this repo to generate the binary and instance images. I wrote a simple windows program to generate this text file. You can check here: https://twitter.com/SmallpixelCar/status/1200268567498805248

**Comment by enginbaglayici** [comment]
If you use your custom dataset and have your GT images and labels in Tusimple format, you can easily modify and use `generate_tusimple_dataset.py` and generate binary-instance segmentation images for training. No need to do anything else...

**Comment by Petros626** [comment]
@enginbaglayici did you run a whole training on custom data succesfully? I thought you won't need GT labels, because the raw images were processed through embedding und segmentation?
