### ISSUE TITLE
test model key value errror

### ISSUE THREAD

**Issue by zwyzwy** [MaybeShewill-CV/lanenet-lane-detection#410]
I try to test the model download from https://www.dropbox.com/sh/tnsf0lw6psszvy4/AAA81r53jpUI3wLsRW6TiPCya?dl=0 , and change the config file line 43 "FRONT_END: 'vgg' ",but there seems to be error named model key error below:

tensorflow.python.framework.errors_impl.NotFoundError: Key LaneNet/vgg_backend/instance_seg/pix_bn/beta not found in checkpoint

I  doubt if the model provided is deprecated?

**Comment by MaybeShewill-CV** [comment]
@zwyzwy If you want to test old model you need to roll back the repo to old version now. I will release a mode trained with vgg front end when enough spare time was supplied in the future:)
