### ISSUE TITLE
不是什么issue,就是想问点经验...

### ISSUE THREAD

**Issue by hellosummer8850** [MaybeShewill-CV/lanenet-lane-detection#412]
大佬好, 我在训练自己的数据时候,训完测试发现网络输出的 instance_seg_image 里把所有的道路线(或者误以为道路线的东西)都画为了同一种颜色, 后面类聚的时候unique_label里只有一个标签[-1],没法类聚, 于是输出的 mask_image 就只是个黑色的图相当于没结果, 我训练的参数除了次数80010 改成了 8000,其它都没动,在你tusimplevgg16模型上做的微调,我的数据比较少500张图左右,感觉明明训练的log里已经显示val_accruacy在90左右波动了, fn 都在0.02左右了, fp却降不下来一直都是 0.6左右, 效果也像上面说的那样比较差, 我有是个小白找不到问题的头绪, 请大佬给点建议呗.
感谢

**Comment by MaybeShewill-CV** [comment]
@hellosummer8850 需要你自己调整instance seg的参数，你的instance seg分支训练出来的embedding features区分度不好导致dbscan无法有效聚类从而导致unique_label里只有一个标签[-1]

**Comment by hellosummer8850** [comment]
@MaybeShewill-CV 是指训练instance seg分支的loss函数吗还是哪些?多谢大佬了~

**Comment by MaybeShewill-CV** [comment]
@hellosummer8850 https://github.com/MaybeShewill-CV/lanenet-lane-detection/blob/7cee4840588f2d1c80fa5ee594552fc5ae9018f4/lanenet_model/lanenet_back_end.py#L126-L131 看下这里吧

**Comment by hellosummer8850** [comment]
@MaybeShewill-CV  Nice, 感谢!

**Comment by pauperonway** [comment]
[图片][图片]
我的测试结果也有一些过度色（如上图），调整
        “delta_v,
        delta_d,
        param_var,
        param_dist,
        param_reg”可能会有改善吗？或者是我的训练数据有脏数据？

**Comment by MaybeShewill-CV** [comment]
@pauperonway 调整dbscan的阈值如果无法解决的话说明是embedding的特征不好 需要调整instance seg分支的参数再训练

**Comment by gabaebae123** [comment]
请问这些参数调整有什么技巧吗？
