### ISSUE TITLE
Can't restore model

### ISSUE THREAD

**Issue by tsubu01** [MaybeShewill-CV/lanenet-lane-detection#413]
Hi,
I cloned the project and downloaded the checkpoint files to a path as in the README, but when I run from command line:
python tools/test_lanenet.py --weights_path model/tusimple_lanenet_vgg/tusimple_lanenet_vgg.ckpt.data-00000-of-00001 --image_path ./data/tusimple_test_image/0.jpg

I get
DataLossError (see above for traceback): Unable to open table file model/tusimple_lanenet_vgg/checkpoint: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
         [[node save/RestoreV2 (defined at tools/test_lanenet.py:114) ]]

Help would be greatly appreciated.
Thanks
Tsubu

**Comment by SamSelvan09** [comment]
Can you try with  

python tools/test_lanenet.py --weights_path model/tusimple_lanenet_vgg/tusimple_lanenet_vgg.ckpt --image_path ./data/tusimple_test_image/0.jpg

**Comment by MaybeShewill-CV** [comment]
@tsubu01 Google the usage of tensorflow ckpt file:)

**Comment by tsubu01** [comment]
SamSelvan09  Tried your suggestion and got the same results.
