### ISSUE TITLE
Can't restore model

### ISSUE THREAD

**Issue by tsubu01** [MaybeShewill-CV/lanenet-lane-detection#414]
Hi,

Still not able to restore the model. Tried all combinations of model path, including calling tf.train.latest_checkpoint() .
I keep getting messages that the variable names don't match the checkpoint. 
I should mention that I am using tf 1.13, because if I use the default line pip3 install -r requirements.txt I get tf version 2.2.0, and when I try to run with it I get error messages about placeholders, so I figured a lower version is required.

Thanks
Tsubu

**Comment by MaybeShewill-CV** [comment]
@tsubu01 1. git pull update the code repo 2. Download new pretrained model here https://www.dropbox.com/sh/0b6r0ljqi76kyg9/AADedYWO3bnx4PhK1BmbJkJKa?dl=0 3. Make sure you have use the right way to restore model from ckpt file:)

**Comment by tsubu01** [comment]
Thanks @MaybeShewill-CV ! Now it works! (with TF1.13.1, doesn't work with TF2.2.0).

Tsubu

**Comment by MaybeShewill-CV** [comment]
@tsubu01 Welcome:)
