### ISSUE TITLE
similar issue to #413 #414 #411 "key X not found in checkpoint" when restoring model, only when using single GPU trainer

### ISSUE THREAD

**Issue by malawada** [MaybeShewill-CV/lanenet-lane-detection#416]
I saw the suggestions for fixing the issues with checkpoint restoration in the other issue threads and it worked for me as well. However, this issue is only resolved for the multi GPU trainer; when using the single GPU trainer the issue still occurs.

**Comment by malawada** [comment]
I would like to note that, if you are only using a single GPU and need a fix for the issue, you can enable multi GPU training and just change the GPU list to ['0']. maybe a better fix can be implemented in the repository?

**Comment by MaybeShewill-CV** [comment]
@malawada Multi gpu trainner use moving avg op which was not used in single gpu trainner. You may delete these lines https://github.com/MaybeShewill-CV/lanenet-lane-detection/blob/e1a553a6f3d00474b412d8cfef217987bd6cf77f/tools/test_lanenet.py#L103-L106 and modify https://github.com/MaybeShewill-CV/lanenet-lane-detection/blob/e1a553a6f3d00474b412d8cfef217987bd6cf77f/tools/test_lanenet.py#L109 into saver = tf.train.Saver() to get over this problem:)
