### ISSUE TITLE
strange checkpoint file name

### ISSUE THREAD

**Issue by ArtlyStyles** [MaybeShewill-CV/lanenet-lane-detection#417]
Why the checkpoint filename is like this?

-rw-r--r--. 1 root root    36719 Jun 27 15:26 'tusimple_val_miou=0.5917.ckpt-344.index'
-rw-r--r--. 1 root root 27938248 Jun 27 15:26 'tusimple_val_miou=0.5917.ckpt-344.data-00000-of-00001'
-rw-r--r--. 1 root root 11495934 Jun 27 15:26 'tusimple_val_miou=0.5917.ckpt-344.meta'
-rw-r--r--. 1 root root 27938248 Jun 27 15:27 'tusimple_val_miou=0.5923.ckpt-352.data-00000-of-00001'
-rw-r--r--. 1 root root    36719 Jun 27 15:27 'tusimple_val_miou=0.5923.ckpt-352.index'

**Comment by MaybeShewill-CV** [comment]
@ArtlyStyles Nothing strange here:)
