### ISSUE TITLE
weights的路径应该怎么设置？

### ISSUE THREAD

**Issue by minnib578** [MaybeShewill-CV/lanenet-lane-detection#418]
你好
我根据你的教程，已经将weights文件（model/tusimple_lanenet_vgg/）存到model/tusimple_lanenet_vgg/上面了
但是跑
python tools/test_lanenet.py  --weights_path /PATH/TO/YOUT/CKPT_FILE_PATH  --image_path ./data/tusimple_test_image/0.jpg
的时候，还是会报错找不到weights的路径
tensorflow.python.framework.errors_impl.NotFoundError: /PATH/TO/YOUT; No such file or directory
我是在google colab上运行，用的python3.5和tensorflow1.15
谢谢

**Comment by MaybeShewill-CV** [comment]
@minnib578 --weights_path ./model/tusimple_lanenet_vgg/xxxx.ckpt

**Comment by MaybeShewill-CV** [comment]
@minnib578 同时建议更新代码使用新的预训练模型　旧的基于vgg的预训练模型可能和新代码不适配　并且未来不打算继续适配工作:)
