### ISSUE TITLE
accuracy, epoch, training time of bisenetv2 based lanenet

### ISSUE THREAD

**Issue by nikhilbv** [MaybeShewill-CV/lanenet-lane-detection#419]
Hi,
Great work on using bisenetv2 based frontend and glad to know that it will reach up to 78 FPS in the single image inference process. I have a few questions which I was wondering about
1. Is the accuracy same as 96.4% on using bisenetv2 frontend as mentioned in `https://paperswithcode.com/sota/lane-detection-on-tusimple`?
2. The epoch used to train bisenetv2 based lanenet is 905 as mentioned in config/tusimple_lanenet.yaml or 80010 as mentioned in the old config?
3. I experienced that bisenetv2 based lanenet took 200x times more than vgg16 based lanenet to train. I enabled MULTI_GPU and set the GPU_DEVICES:['0'] to train on a single GPU. Please shed some light here.

**Comment by MaybeShewill-CV** [comment]
1.The precision was not tested on tusimple lancet.
2.The training epoch is 905 mentioned in tusimple_lanenet.yaml config file.
3.You may reduce the epoch nums and see if the model performs well on your dataset if you feel the training process was too long:)

**Comment by nikhilbv** [comment]
@MaybeShewill-CV Thank you for replying in such a short time
