### ISSUE TITLE
Tusimple weight 在一般路况场景的问题

### ISSUE THREAD

**Issue by yupei3030** [MaybeShewill-CV/lanenet-lane-detection#420]
我用tusimple的weight跑别的图，binary segmentation效果很差，mask 全是黑的。
以为是perspective 转换的问题，用opencv warp改了post processing
debugging发现好像不是lane fitting的问题。mask_image 是出在之前的，跟lane fitting没关系

是不是CNN inference 的binary本来就不好，DBSCAN clustering 后没有mask的结果？
有没有可能lanenet binary part在美国高速路上overtrain了, 导致不能generlize。

![123](https://user-images.githubusercontent.com/40482975/86535613-21783a80-bf14-11ea-8bbb-0ba1f80f0873.jpg)

**Comment by pauperonway** [comment]
最好找一个没有箭头和车距确认线的图片测试，针对地面的斑马线和箭头，可以把二值分割的参数改为多类别，增加自己的数据集训练应该会有改善。我瞎说的···

**Comment by MaybeShewill-CV** [comment]
@yupei3030 根据实际使用经验来说 如果你要在自己的数据集上获得比较好的效果 需要你自己准备训练数据重新训练模型才可以:)
