### ISSUE TITLE
'LaneNet' object has no attribute 'Summary'

### ISSUE THREAD

**Issue by bcrevath** [MaybeShewill-CV/lanenet-lane-detection#423]
Hi, I am trying to load model LaneNet and visualize summary of layers.
code:

import keras
import math
import os.path as ops
import os
import time
import sys
import cv2
import glog as log
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
from config import global_config
import collections

CFG = global_config.cfg

from semantic_segmentation_zoo import cnn_basenet
from semantic_segmentation_zoo import vgg16_based_fcn
from semantic_segmentation_zoo.vgg16_based_fcn import VGG16FCN
from lanenet_model import lanenet

model = lanenet.LaneNet(phase = 'test')
model.summary()**

output:
AttributeErrorTraceback (most recent call last)
<ipython-input-18-051ca4accdd3> in <module>
     21 
     22 model = lanenet.LaneNet(phase = 'test')
---> 23 model.summary()
     24 
     25 

AttributeError: 'LaneNet' object has no attribute 'summary'

![image](https://user-images.githubusercontent.com/43743070/86994558-50b4d300-c1c4-11ea-8444-e1de90d87385.png)

**Comment by MaybeShewill-CV** [comment]
@bcrevath The repo has beec updated. You may check the new code. Old repo was not intended to be maintained any more:)

**Comment by akshatbhutra** [comment]
@MaybeShewill-CV is it now possible to print the summary of layers?
