### ISSUE TITLE
No output for Model.summary() : I have updated your code modifications

### ISSUE THREAD

**Issue by bcrevath** [MaybeShewill-CV/lanenet-lane-detection#426]
Hi,
I updated all the config files and others changes you have made. Yet, I am unable to obtain model.summary() to visualize conv layers. Please help me.

![image](https://user-images.githubusercontent.com/43743070/87008383-4bb24c80-c1e1-11ea-963e-d439c68631dd.png)

Just no output at all

**Comment by MaybeShewill-CV** [comment]
@bcrevath The LaneNet class do not have member function called summary at all. I did not use keras:)
