### ISSUE TITLE
 Generate binary and instance graphs

### ISSUE THREAD

**Issue by ShangJP** [MaybeShewill-CV/lanenet-lane-detection#43]
请问您数据处理成二进制图和实例图是如何完成的啊，

**Comment by MaybeShewill-CV** [comment]
@ShangJP 可以根据tusimple dataset提供的json文件制作

**Comment by ShangJP** [comment]
我尝试了一下，把json数据读出来了，发现是车道线的点，怎么把这个变成二值化图，和实例图就不会弄了，能指点一下么，
