### ISSUE TITLE
Model Missing

### ISSUE THREAD

**Issue by canozcivelek** [MaybeShewill-CV/lanenet-lane-detection#430]
Hi, thanks for the repo. I'm trying to implement this on my device however the link you provided leads to nowhere. Where can I find the trained lanenet model? Thanks!

**Comment by Luishfs** [comment]
https://www.dropbox.com/sh/0b6r0ljqi76kyg9/AADedYWO3bnx4PhK1BmbJkJKa?dl=0

**Comment by MaybeShewill-CV** [comment]
@canozcivelek Try this https://www.dropbox.com/sh/0b6r0ljqi76kyg9/AADedYWO3bnx4PhK1BmbJkJKa?dl=0
