### ISSUE TITLE
ValueError: Source image data is not complete, please check if one of the image folder is not exist

### ISSUE THREAD

**Issue by xukaiyan** [MaybeShewill-CV/lanenet-lane-detection#433]
when i was run  "python tools/make_tusimple_tfrecords.py ",I meet ValueError: Source image data is not complete, please check if one of the image folder is not exist

  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "tools/make_tusimple_tfrecords.py", line 32, in <module>
    generate_tfrecords()
  File "tools/make_tusimple_tfrecords.py", line 22, in generate_tfrecords
    producer = lanenet_data_feed_pipline.LaneNetDataProducer()
  File "/data-input/lanenet-lane-detection/data_provider/lanenet_data_feed_pipline.py", line 48, in __init__
    raise ValueError('Source image data is not complete, '
ValueError: Source image data is not complete, please check if one of the image folder is not exist

**Comment by MaybeShewill-CV** [comment]
@xukaiyan 按照https://github.com/MaybeShewill-CV/lanenet-lane-detection/tree/master/data/training_data_example 文件结构重新组织你的训练集数据.

**Comment by xukaiyan** [comment]
解决了，谢谢

**Comment by frozenbird07** [comment]
请问一下是怎么解决的，我刚刚下载项目，现在不知道怎么操作
