### ISSUE TITLE
Issue about lane fitting result

### ISSUE THREAD

**Issue by radeonwu** [MaybeShewill-CV/lanenet-lane-detection#435]
Thanks for sharing this excellent code repo.

After I trained lanenet with some customized data, the inference testing shows some issue on lane fitting result. A typical example is illustrated as the picture below.

From the picture, the binary result is still good, but in the mask result the left and right most lanes are categorized into the same instance, which leads to wild lane fitting result which, I guess, as it tries to fit these two lines together.  

Any hints to improve this, e.g., data preparation or fine tune the line fitting post processing step?
Thanks

![image](https://user-images.githubusercontent.com/2787410/90210151-cfcea400-de1f-11ea-9c3a-c54958847055.png)

**Comment by MaybeShewill-CV** [comment]
@radeonwu 1. Retrain the model to improve the instance segmentation branch 2. adjust dbscan params to get better cluster result:)

**Comment by radeonwu** [comment]
> @radeonwu 1. Retrain the model to improve the instance segmentation branch 2. adjust dbscan params to get better cluster result:)

thank you for your prompt reply.
For point 1, are you suggesting to train the instance segmentation branch exclusively while freezing the rest of branch(es)? 
For point 2, yes that's also what I plan to try.

**Comment by MaybeShewill-CV** [comment]
@radeonwu 1. adjust params in instance loss function to make the instance segmentation perform better 2. Switch backbone to get better image feature for intansce segmentation

**Comment by radeonwu** [comment]
@MaybeShewill-CV 
I adjusted the DBSCAN control params, and can get some better result now. An updated picture is attached below.
![image](https://user-images.githubusercontent.com/2787410/90335210-c737c280-e005-11ea-8453-630ae652b912.png)

One more question, in the above picture, the lane lines fitted seems beyond the binary result at horizontal direction. Should I look into the post processing code to limit the line fitting length? 
Thanks

**Comment by MaybeShewill-CV** [comment]
@radeonwu Yep you should change some code in post proceossing:)

**Comment by radeonwu** [comment]
@MaybeShewill-CV 
I modified a bit the post processing code to limit the lane length, and here is the new visual effect.
![image](https://user-images.githubusercontent.com/2787410/90713924-094c5700-e2d9-11ea-8ce5-dd00f508d295.png)

Two more issues for discussion.
Regarding instance embedding feature, from the config file, it's set as 4 dimensional. Wondering if set it to 3 dimensional, corresponding to RGB image channels, and change the network accordingly, will that make sense?

So far my trying result of LaneNet on highway dataset is pretty ok, yet coming to urban scenario, the performance is quite struggling, e.g., at traffic junctions where there are lanes along various direction, junction boxes whose pattern are quite different from parallel lanes on highway. Any ideas/suggestions to handle such situations?

**Comment by MaybeShewill-CV** [comment]
@radeonwu 1. 3 channel embedding features will make sense and easier to visualize. I have tried it myself. If the environment is complicated such as urban scenario i will suggest not to reduce embedding feature's dimension. Large dimension may encode more information but harder to train at the same time. 2. As for model's performance. Use some large backbone net model such as hrnet or deeplabv3 may boost the model's performance when coming to urban scenario.

**Comment by monilshah1988** [comment]
@radeonwu Hey, I got the same output as you get in instance image. but I didn't get the output as src_image. Have you tried on your own dataset? Actually I have some questions if you tried on your dataset...
How did you convert json data to tusimple dataset?
<img width="1677" alt="Screen Shot 2020-08-27 at 11 12 37 AM" src="https://user-images.githubusercontent.com/22041656/91479540-71111d80-e856-11ea-8b71-d7b3a835aed9.png">

So in the "images" directory, I have 1.json,2.json ... files and img.png, label.png, label_name.txt,label_viz.png.
When I run this I am not able to get any images in gt_binary and gt_instance directory.
