### ISSUE TITLE
TuSimple数据集---->Tfrecords  （使用的自己数据）

### ISSUE THREAD

**Issue by weijian555** [MaybeShewill-CV/lanenet-lane-detection#436]
![image](https://user-images.githubusercontent.com/54135879/90390415-e003af00-e0bd-11ea-83b9-cb6a9e44dee0.png)
使用自己的数据生成了上面文件，在使用python tools/make_tusimple_tfrecords.py  进行Tfrecords 格式转换的时候，出现错误：git-hub-lanenet\lanenet-lane-detection-master\tools\data_provider\lanenet_data_feed_pipline.py", line 48, in __init__
    raise ValueError('Source image data is not complete, '
ValueError: Source image data is not complete, please check if one of the image folder is not exist

显示文件不完整，请问是哪里出现问题了呢？

**Comment by radeonwu** [comment]
yaml 配置文件里面相应的文件目录有没有更新？

**Comment by weijian555** [comment]
我更新一下看看，非常感谢回复！😊------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;radeonwu&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年8月17日(星期一) 晚上10:34
收件人:&nbsp;&quot;MaybeShewill-CV/lanenet-lane-detection&quot;<lanenet-lane-detection@noreply.github.com&gt;;
抄送:&nbsp;&quot;weijian555&quot;<764643510@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [MaybeShewill-CV/lanenet-lane-detection] TuSimple数据集----&gt;Tfrecords  （使用的自己数据） (#436)

**Comment by MaybeShewill-CV** [comment]
@weijian555 配置文件里路径都自己检查下:)

**Comment by weijian555** [comment]
通过修改yaml中文件路径，已解决。：）

**Comment by monilshah1988** [comment]
@weijian555, can you help me with what did you modify in yml file.? I'm training on my own dataset

**Comment by weijian555** [comment]
I have encountered the following problems.
ValueError: Source image data is not complete, please check if one of the image folder is not exist
The reason is that I didn't update the tusimple_lanenet.yaml file path.
So I changed the path of my own project.
![image](https://user-images.githubusercontent.com/54135879/91241672-10abae80-e778-11ea-807e-ea48fe0e659d.png)

**Comment by monilshah1988** [comment]
<img width="1680" alt="Screen Shot 2020-08-25 at 10 19 47 PM" src="https://user-images.githubusercontent.com/22041656/91258555-7751ad80-e721-11ea-9891-07ede52b3fbb.png">


@weijian555  Thanks for the reply. I already changed that path. In that directory, I only have RGB images of lane(highway). It doesn't contain the binary and instance images of those lanes. Can you guide me on how did you generate those binary and instance images? I am having hard time with it.

Help would be appreciated . Thank you.

**Comment by weijian555** [comment]
There's some information on how to generate the Tusimple data set on the Web, you can check it out.
Such as:
https://blog.csdn.net/Hellow_RMB/article/details/107201309?utm_medium=distribute.pc_relevant.none-task-blog-BlogCommendFromMachineLearnPai2-1.channel_param&depth_1-utm_source=distribute.pc_relevant.none-task-blog-BlogCommendFromMachineLearnPai2-1.channel_param
https://www.jianshu.com/p/db49837b019a

**Comment by monilshah1988** [comment]
@weijian555 Thanks a lot. It really helps me. I converted JSON to tf records. but when I run this command

python tools/generate_tusimple_dataset.py --src_dir tools/data/training_data_example/images/1_json,
 
it just creates training and testing folder in that path.
I'm still wondering how the gt_binary, gt_instance image directory is created?
can you help me with it?
Help would be appreciated. You are so helpful.

<img width="407" alt="Screen Shot 2020-08-26 at 11 16 19 AM" src="https://user-images.githubusercontent.com/22041656/91341067-d51bdf00-e78d-11ea-8ddb-e4293b24234c.png">

**Comment by weijian555** [comment]
In this blog post：https://blog.csdn.net/Hellow_RMB/article/details/107201309?utm_medium=distribute.pc_relevant.none-task-blog-BlogCommendFromMachineLearnPai2-1.channel_param&depth_1-utm_source=distribute.pc_relevant.none-task-blog-BlogCommendFromMachineLearnPai2-1.channel_param

steps（3.3）Data set processing：json---->TuSimple  data set

I used the second method to get gt_binary, gt_instance image directory.
The first method is not tried. It is better suited to the official data set.

**Comment by monilshah1988** [comment]
<img width="1677" alt="Screen Shot 2020-08-27 at 11 12 37 AM" src="https://user-images.githubusercontent.com/22041656/91479540-71111d80-e856-11ea-8b71-d7b3a835aed9.png">

So in the "images" directory, I have 1.json,2.json ... files and img.png, label.png, label_name.txt,label_viz.png.
When I run this I am not able to get any images in gt_binary and gt_instance directory.
Help would be appreciated. Thanks.

**Comment by monilshah1988** [comment]
Thanks for helping.
But it didn't convert it to tfrecords yet. Can you help what changes do we have to make in ./config/yaml? 
It still keeps showing error.

<img width="1680" alt="Screen Shot 2020-08-27 at 4 38 31 PM" src="https://user-images.githubusercontent.com/22041656/91509024-f95ee500-e88d-11ea-9102-968e71ec3b1a.png">

**Comment by monilshah1988** [comment]
hey, I have a quick question 
 _python tools/make_tusimple_tfrecords.py_
when I run it, it calls generate_tusimple_dataset but generate_tusimple_dataset.py asks src file. so, how can we give the src dir for tfrecords?

**Comment by weijian555** [comment]
In the directory  'lanenet-lane-detection-master\data\training_data_example',
You need to create three folders (gt_image gt_binary_image  gt_instance_image) and it has your data in it.( image ->gt_image )
You also need to create train.txt test.txt val.txt .

**Comment by monilshah1988** [comment]
@weijian555 Hey, Thanks for the reply. Yes, I already created 3 files and train.txt and val.txt as per the @MaybeShewill-CV 's project's directory training_data_example.
I got an error in local_utils with no module error.
I tried this.
my pwd:/content/drive/My Drive/Colab Notebooks/lanenet-lane-detection-master
import sys,os
sys.path.append(os.path.dirname('local_utils') + os.sep + '/content/drive/My Drive/Colab Notebooks/lanenet-lane-detection-master')

<img width="1651" alt="Screen Shot 2020-08-30 at 11 02 38 AM" src="https://user-images.githubusercontent.com/22041656/91666295-723d8700-eab0-11ea-8d91-40311766d5b5.png">
