### ISSUE TITLE
使用tensorflow c API 加载 pb模型，同一张图片推理结果不一致......

### ISSUE THREAD

**Issue by pauperonway** [MaybeShewill-CV/lanenet-lane-detection#437]
使用tensorflow c API 加载固化的pb模型，加载一张图片30次，总用一两次没有结果，如图（增加了箭头识别）
第一张为正常输出；
第二张只有少数灰度点，不正常：
![0_0](https://user-images.githubusercontent.com/3377021/90479086-b780c100-e160-11ea-8d5b-e2e8348520fc.jpg)
![0_1](https://user-images.githubusercontent.com/3377021/90479096-ba7bb180-e160-11ea-9ce0-74759a057676.jpg)
@MaybeShewill-CV 求想法，哈哈哈

**Comment by MaybeShewill-CV** [comment]
@pauperonway 这个我感觉还是从输入数据检查吧 30次的输入数据之间有没有diff

**Comment by pauperonway** [comment]
导出TF_Tensor结果的时候维度shape获取有问题，导致有随机输出。已改正o(╥﹏╥)o
