### ISSUE TITLE
生成的线的位置错误

### ISSUE THREAD

**Issue by xukaiyan** [MaybeShewill-CV/lanenet-lane-detection#439]
生成的mark image
![1](https://user-images.githubusercontent.com/35806085/90951121-4c016100-e48a-11ea-87eb-c0c960ec7179.jpg)，效果不错
但是src_image中线的位置不对，请问这是什么原因
![2](https://user-images.githubusercontent.com/35806085/90951359-c92dd580-e48c-11ea-8723-1ee7261d4189.jpg)

**Comment by iltertaha** [comment]
> @xukaiyan 后处理过程是适配tusimple数据集的 不能直接用在自己的数据集上，需要你自己根据自己的数据修改：）

Hi,
I have a similar problem with a slight difference.
As far as I understand with the help of the translate,  we have to modify outputs. How can we do this?
I have a problem when I test the pretrained model with my custom image (.jpg format). Instance image shows without problem however, mask image appears full black and there is no colored lane on the src image. My custom image should perform better. What parameters or functions should I pay attention to solve this problem.

Thanks

**Comment by monilshah1988** [comment]
Hey @iltertaha and @MaybeShewill-CV @pauperonway ,
I am doing it on my custom dataset. when I run this file generate_tusimple_dataset.py, it only generates the directory called testing and training. Can you tell me how can we do generate binary and instance images?
I placed my dataset in ./data/training_data_example/DATASET/images/. here in .png format and these are just frames converted from a video. How can I generate  generate binary and instance images?

**Comment by xukaiyan** [comment]
好的，我去看看

**Comment by MaybeShewill-CV** [comment]
@iltertaha You may check postprocess module for details:)
