### ISSUE TITLE
how to evaluate?

### ISSUE THREAD

**Issue by y11203090135** [MaybeShewill-CV/lanenet-lane-detection#44]
在评估训练的模型时，需要将测试的图片转换成test_label.json文件的格式，请问具体怎样做了？

**Comment by y11203090135** [comment]
tusimple官网并没有给出测试数据的真实label，如何进行evaluate?

**Comment by MaybeShewill-CV** [comment]
@y11203090135 你可以看看这个eval文件https://github.com/TuSimple/tusimple-benchmark/blob/master/evaluate/lane.py

**Comment by y11203090135** [comment]
@MaybeShewill-CV 好的，谢谢

**Comment by y11203090135** [comment]
请问如何得到pre_file.json 文件

**Comment by MaybeShewill-CV** [comment]
@y11203090135 我没提交过这个结果 所以具体的细节你需要看tusimple lane dataset的说明

**Comment by y11203090135** [comment]
好的，谢谢啦！

**Comment by hristo-vrigazov** [comment]
How to generate the json file needed for evaluation?
