### ISSUE TITLE
How to generate our custom remap_ipm.yml file

### ISSUE THREAD

**Issue by Pari-singh** [MaybeShewill-CV/lanenet-lane-detection#442]
Hello @MaybeShewill-CV,

Thank you for your brilliant repository. I read other issues regarding remap_ipm yaml file generation, where you pointed to your **https://github.com/MaybeShewill-CV/Easy-Ipm-Client** repository. The repository only has the platform to convert image to BEV. I wanted to know if you could share with us how you got the data matrix in your tusimple_remap_ipm.yml file from the BEV generated there or any other way of obtaining those numbers for our custom data? 

Thanks once again

**Comment by MaybeShewill-CV** [comment]
@Pari-singh You may how to use opencv perspective transofrom to convert an image from front view into bird view:)

**Comment by Pari-singh** [comment]
@MaybeShewill-CV Thanks for the answer, although my question was pertaining more towards your repository Easy-Ipm-Client and if getting the numpy array from it could be added as a feature instead of just image, as just image could also be obtained from other sources like Opencv, as you mentioned. But thanks nonetheless! :)

**Comment by MaybeShewill-CV** [comment]
@Pari-singh 1. You may modified the Easy-Ipm-Client repo's source code to save your own remap file. 2. Some of the source code in that repo won't be released. 3. Opencv perspective transofrom was a efficient for you to get a ipm image in my view:)
