### ISSUE TITLE
error in local_utils

### ISSUE THREAD

**Issue by pythonmjs** [MaybeShewill-CV/lanenet-lane-detection#443]
@MaybeShewill-CV Thanks for wonderful work.
I have doubts.

I have changed in ./config/__.yml file:
DATASET:
    DATA_DIR: 'tools/data/training_data_example/'

I got an error in local_utils with no module error.
I tried this.
my pwd:/content/drive/My Drive/Colab Notebooks/lanenet-lane-detection-master
import sys,os
sys.path.append(os.path.dirname('local_utils') + os.sep + '/content/drive/My Drive/Colab Notebooks/lanenet-lane-detection-master')

<img width="1651" alt="Screen Shot 2020-08-30 at 11 02 38 AM" src="https://user-images.githubusercontent.com/22041656/91666295-723d8700-eab0-11ea-8d91-40311766d5b5.png">

**Comment by MaybeShewill-CV** [comment]
@monilshah1988 add repo's root path to your PYTHONPATH env variables:)

**Comment by iltertaha** [comment]
@monilshah1988 Hi,  as an alternative solution, I'm using absolute path's in config file. ( for DATA_DIR etc.)
I've also added:

`import sys  `
`sys.path.append('absolute_path_to/lanenet-lane-detection') `

By doing so, I am able to run without any error. Hope that helps.

**Comment by monilshah1988** [comment]
@MaybeShewill-CV Thanks for your reply in a short time. I did that. However, it keeps showing error in google colab.

@iltertaha Thanks for the reply. I did it as you mentioned.

Can you find err in image where did it go wrong? Maybe it should work in the local idle.
Thanks in advance!

<img width="1680" alt="Screen Shot 2020-09-02 at 1 38 56 PM" src="https://user-images.githubusercontent.com/22041656/92034434-137f4400-ed22-11ea-94e8-92a464758378.png">

**Comment by MaybeShewill-CV** [comment]
@monilshah1988 use this script to generate Tensorflow records https://github.com/MaybeShewill-CV/lanenet-lane-detection/blob/master/tools/make_tusimple_tfrecords.py
