### ISSUE TITLE
mask_image is black when testing my own picture?

### ISSUE THREAD

**Issue by Keyird** [MaybeShewill-CV/lanenet-lane-detection#444]
Thank you for your great share! when I tested the net on my own picture, I found that the mask_image was black , so how should I do?

**Comment by MaybeShewill-CV** [comment]
@Keyird The post process can only be used to process tusimple data. You need to modify the post process code to fit your dataset or you could simply add instance segmentation mask on source image:)

**Comment by iltertaha** [comment]
> Thank you for your great share! when I tested the net on my own picture, I found that the mask_image was black , so how should I do?

I've solved by changing the variables related to postprocessing in the .yaml file under config folder.

**Comment by Keyird** [comment]
> @Keyird The post process can only be used to process tusimple data. You need to modify the post process code to fit your dataset or you could simply add instance segmentation mask on source image:)

Thank you for your reply

**Comment by Keyird** [comment]
> > Thank you for your great share! when I tested the net on my own picture, I found that the mask_image was black , so how should I do?
> 
> I've solved the same problem by changing the variables related to postprocessing in the .yaml file under config folder.

Thank you for your reply!

**Comment by BernardinD** [comment]
> > Thank you for your great share! when I tested the net on my own picture, I found that the mask_image was black , so how should I do?
> 
> I've solved the same problem by changing the variables related to postprocessing in the .yaml file under config folder.

What procedure did you use in order to determine what parameters work for your dataset? And what parameters did you change? Thanks

**Comment by iltertaha** [comment]
> > > Thank you for your great share! when I tested the net on my own picture, I found that the mask_image was black , so how should I do?
> > 
> > 
> > I've solved the same problem by changing the variables related to postprocessing in the .yaml file under config folder.
> 
> What procedure did you use in order to determine what parameters work for your dataset? And what parameters did you change? Thanks

Hi,
Sorry for really late reply. If you still didn't solve the problem, I have changed the values in

> POSTPROCESS:
    MIN_AREA_THRESHOLD: 100
    DBSCAN_EPS: 0.35
    DBSCAN_MIN_SAMPLES: 1000

 part. I've read past open and closed issues. I don't remember exact values, but I've set for my own images by trial and error.

Best
