### ISSUE TITLE
dbscan elapsed time is 30~40ms on local server ?

### ISSUE THREAD

**Issue by pauperonway** [MaybeShewill-CV/lanenet-lane-detection#445]
I am using  mnn dbscan, but it is too slow. Any advice to optimize it?  Now Kd-tree has been opened.

**Comment by pauperonway** [comment]
调节参数后有改善。

**Comment by SHANK885** [comment]
@pauperonway I am also having the same issue. In my case, it's even worse and goes around 300~400 ms. Can you please let me know what modifications you have made to the parameter?

**Comment by pauperonway** [comment]
@SHANK885 you can Sparse sampling， and then do dbscan.
