### ISSUE TITLE
测试结果也有一些过度色

### ISSUE THREAD

**Issue by pauperonway** [MaybeShewill-CV/lanenet-lane-detection#446]
![image](https://user-images.githubusercontent.com/3377021/92551337-5300df80-f290-11ea-830b-8bc99f7b3020.png)

我的测试结果也有一些过度色（如上图），调整 lanenet_discriminative_loss.py 的
        “delta_v,
        delta_d,
        param_var,
        param_dist,
        param_reg”可能会有改善吗？或者是我的训练数据有脏数据？@MaybeShewill-CV

_Originally posted by @pauperonway in https://github.com/MaybeShewill-CV/lanenet-lane-detection/issues/412#issuecomment-689278410_

**Comment by MaybeShewill-CV** [comment]
@pauperonway 那个问题下面回你了
