### ISSUE TITLE
No semantic_segmentation in the encoder_decoder_model

### ISSUE THREAD

**Issue by WeiG1210** [MaybeShewill-CV/lanenet-lane-detection#45]
你好，在train_encoder_decoder.py 前面有 from encoder_decoder_model import semantic_segmentation 
但是在encoder_decoder_model里面没有找到semantic_segmentation啊。pycharm里面也有报错。
先谢谢你啦><

**Comment by MaybeShewill-CV** [comment]
@WeiG1210 那不是这个模型里用到的东西

**Comment by WeiG1210** [comment]
好的啊，我看到之前也有相关提问了，谢谢！



在 2018年8月7日，上午10:37，MaybeShewill-CV <notifications@github.com<mailto:notifications@github.com>> 写道：


@WeiG1210<https://github.com/WeiG1210> 那不是这个模型里用到的东西
