### ISSUE TITLE
How to Configure Python Path or Add Module Root Dir to Your PYTHONPATH

### ISSUE THREAD

**Issue by NaeemKhan333** [MaybeShewill-CV/lanenet-lane-detection#451]
Thanks for such a nice work. I am running the testing script, but I am facing following error

Traceback (most recent call last):
File "tools/test_lanenet.py", line 20, in
from lanenet_model import lanenet
ModuleNotFoundError: No module named 'lanenet_model'

I tried to setup the Module directory to python path but I could not run the testing script.
Can you guide me How I can add the Module Directory to my python path. Thanks

**Comment by MaybeShewill-CV** [comment]
@NaeemKhan333 export PYTHONPATH=repo_root_dir:$PYTHONPATH
