### ISSUE TITLE
the pretrained model file shows been deleted

### ISSUE THREAD

**Issue by Tartisan** [MaybeShewill-CV/lanenet-lane-detection#452]
dropbox shows the item was deleted, is there something with my network, or can you please upload the model again to dropbox or baidu netdisk?
thanks!

**Comment by MaybeShewill-CV** [comment]
@Tartisan You must have visited the wrong url. Try this https://www.dropbox.com/home/BiseNetV2_LaneNet_Tusimple_Model_Weights
