### ISSUE TITLE
tusimple数据库转换tfrecords错误

### ISSUE THREAD

**Issue by NeilKuo** [MaybeShewill-CV/lanenet-lane-detection#453]
您好！
我在执行python data_provider/lanenet_data_feed_pipline.py --dataset_dir./data/training_data_example/training --tfrecords_dir./data/training_data_example/training/tfrecords 这段时会出现以下错误
数据库资料位置 tfrecords 资料夹是我自行设置的
![1](https://user-images.githubusercontent.com/71683366/93842370-38cff400-fcc9-11ea-9051-33f48e3f4e48.png)

![2](https://user-images.githubusercontent.com/71683366/93842236-bc3d1580-fcc8-11ea-81bb-d3321d489412.png)

![3](https://user-images.githubusercontent.com/71683366/93842237-bc3d1580-fcc8-11ea-90f7-15891c377486.png)
期待您的回覆 谢谢！ ！

**Comment by MaybeShewill-CV** [comment]
@NeilKuo 旧代码不维护了。 新代码生成tfrecords参考readme. 你这个八成是在csdn上看到的基于旧代码某教程吧。 生成tfrecords看这个 https://github.com/MaybeShewill-CV/lanenet-lane-detection/blob/master/tools/make_tusimple_tfrecords.py

**Comment by NeilKuo** [comment]
您好！
tfrecords转换成功了
![2](https://user-images.githubusercontent.com/71683366/93977207-b6b8fb80-fdac-11ea-8702-297db4123432.png)

但在执行python tools/train_lanenet_tusimple.py --net vgg 時出現错误
![1](https://user-images.githubusercontent.com/71683366/93976763-119e2300-fdac-11ea-8700-1eed9627020c.png)
训练到2%时会中断 且训练时未使用gpu

**Comment by MaybeShewill-CV** [comment]
@NeilKuo 1.使用新代码 看下readme train脚本现在不需要指定参数-net 2.训练不使用gpu是你的tensorflow的问题,查询tensorflow或者cuda相关的问题.

**Comment by NeilKuo** [comment]
@MaybeShewill-CV 
![2020-09-23 16-44-42 的螢幕擷圖](https://user-images.githubusercontent.com/71683366/93989127-1f5ba480-fdbc-11ea-82ce-ebf819dc6b16.png)
![2020-09-23 16-44-34 的螢幕擷圖](https://user-images.githubusercontent.com/71683366/93989135-21256800-fdbc-11ea-8a42-aed806ac1f18.png)
执行 python tools/train_lanenet_tusimple.py 代码出現以上错误

**Comment by MaybeShewill-CV** [comment]
@NeilKuo reduce batch size

**Comment by NeilKuo** [comment]
@MaybeShewill-CV 
您好
调整后已可正常训练
但在评估模型遇到了问题
![3](https://user-images.githubusercontent.com/71683366/94095712-e0c5f880-fe54-11ea-952a-612ef6313305.png)
抱歉刚踏入这块 问题有点多

**Comment by MaybeShewill-CV** [comment]
@NeilKuo 代码更新下

**Comment by MaybeShewill-CV** [comment]
@NeilKuo 更新下代码

**Comment by NeilKuo** [comment]
您好
还是有出现了错误
似乎是权重档的问题
python tools/evaluate_lanenet_on_tusimple.py 
--image_dir ROOT_DIR/TUSIMPLE_DATASET/test_set/clips 
--weights_path /PATH/TO/YOUT/CKPT_FILE_PATH 
--save_dir ROOT_DIR/TUSIMPLE_DATASET/test_set/test_output
weights_path /PATH/TO/YOUT/CKPT_FILE_PATH这行指令是指下图的资料夹吧
![4](https://user-images.githubusercontent.com/71683366/94098633-a449cb00-fe5b-11ea-8bfb-5fed450e54e7.png)
谢谢！！

**Comment by MaybeShewill-CV** [comment]
@NeilKuo 你可以先看下怎么从tensorflow ckpt文件恢复模型。 --weights_path xxxx.ckpt
