### ISSUE TITLE
freeze_lanenet_model

### ISSUE THREAD

**Issue by git-chenjiqing** [MaybeShewill-CV/lanenet-lane-detection#454]
Key lanenet_model/bisenetv2_backend/instance_seg/pix_bn/beta not found in checkpoint

**Comment by MaybeShewill-CV** [comment]
@git-chenjiqing Paste the command you used here:)

**Comment by git-chenjiqing** [comment]
I'm trying:
Freeze your tensorflow ckpt model weights file
python mnn_project/freeze_lanenet_model.py -w lanenet.ckpt -s lanenet.pb

**Comment by git-chenjiqing** [comment]
I tried to freeze the tensorflow CKPT model weight file

**Comment by git-chenjiqing** [comment]
I used a new lanenet model based on bisenetv2 training

**Comment by MaybeShewill-CV** [comment]
@git-chenjiqing The code in mnn_project/freeze_lanenet_model.py was written for old code which is not match with new repo. You need to modified that code.

**Comment by MaybeShewill-CV** [comment]
@git-chenjiqing 这个问题已经修复了 重新更新下代码就好了:)

**Comment by git-chenjiqing** [comment]
好的，谢谢
