### ISSUE TITLE
accuracy

### ISSUE THREAD

**Issue by longtong-system** [MaybeShewill-CV/lanenet-lane-detection#456]
您好，我有两个问题：
1.我在您更新后的代码中找不到在tool下的calculate_model_precision函数以及fn、fp的计算函数的调用位置，请问您是在代码中去除了这部分的调用吗？您可以给例子或者将之前未去除这部分的代码公开一下吗？
2.我通过对tusimple_lanenet_multi_gpu_trainner.py中代码的理解以及对tensorboard的调用，发现在tensorboard中所显示的图像一共9张，分别为训练集与验证集的二值分割损失、实例分割损失、总体损失、miou（2×4个图）以及学习率变化曲线图，其中并没有val_accuracy以及train_accuracy的曲线图，请问您能告诉我如何进行显示或者将之前的代码以云盘方式进行公开吗？

**Comment by MaybeShewill-CV** [comment]
@longtong-system 1.看下这个文件 https://github.com/MaybeShewill-CV/lanenet-lane-detection/blob/master/tools/evaluate_model_utils.py 2. accuracy曲线你可以调用 tf.metrics.accuracy函数自己计算一下:)

**Comment by longtong-system** [comment]
> @longtong-system 1.看下这个文件 https://github.com/MaybeShewill-CV/lanenet-lane-detection/blob/master/tools/evaluate_model_utils.py 2. accuracy曲线你可以调用 tf.metrics.accuracy函数自己计算一下:)

感谢您回复的这么快，我用tensorflow用的不多，所以在一些语法和命令上有些不清晰，我已经看过您指出的这个py文件，但是我不知道如何进行调用它所对应的input_tensor, label_tensor的格式，我看您之前的代码应该是调用过accuracy的使用和tensorboard显示的，请问您可以分享它的使用例子吗？

**Comment by MaybeShewill-CV** [comment]
@longtong-system 旧代码已经不维护了 计算指标的例子网上很多 你可以搜搜看哈:)

**Comment by longtong-system** [comment]
> @longtong-system 旧代码已经不维护了 计算指标的例子网上很多 你可以搜搜看哈:)

谢谢您，如果有可能的话，您将之前的代码可以发一个网盘链接吗？不用维护过的，我只想要看看当初您是怎么调用就好，因为对tensorflow的用法有些不太清楚，还是麻烦您了

**Comment by MaybeShewill-CV** [comment]
@longtong-system 我本地已经没有之前版本的代码了 sry：）

**Comment by JieL00** [comment]
> 您好，我有两个问题： 1.我在您更新后的代码中找不到在tool下的calculate_model_precision函数以及fn、fp的计算函数的调用位置，请问您是在代码中去除了这部分的调用吗？您可以给例子或者将之前未去除这部分的代码公开一下吗？ 2.我通过对tusimple_lanenet_multi_gpu_trainner.py中代码的理解以及对tensorboard的调用，发现在tensorboard中所显示的图像一共9张，分别为训练集与验证集的二值分割损失、实例分割损失、总体损失、miou（2×4个图）以及学习率变化曲线图，其中并没有val_accuracy以及train_accuracy的曲线图，请问您能告诉我如何进行显示或者将之前的代码以云盘方式进行公开吗？

你好，请问你的问题最后怎么解决的呢~我现在也遇到了跟你一样的问题

**Comment by 1823449** [comment]
您好，请问您现在解决了吗？我也遇到了一样的问题，十分需要您的帮助
