### ISSUE TITLE
loop_times

### ISSUE THREAD

**Issue by longtong-system** [MaybeShewill-CV/lanenet-lane-detection#457]
您好，在进行图片的检测中，我记得您在test_lanenet.py中的115行中设定loop_time为500，请问这个有什么意义呢？虽然最后显示的单张图片的检测时间是最终除以loop_time从而使得每张图片的检测时间并不长，在设定500时发现整体的检测时间非常的长，如果改成5的话就会很快的得到检测的结果图。

**Comment by MaybeShewill-CV** [comment]
@longtong-system gpu有warmup时间 500 loop是为了抵消这部分时间的影响:)

**Comment by longtong-system** [comment]
原来是这样，谢谢
