### ISSUE TITLE
instance accuracy

### ISSUE THREAD

**Issue by longtong-system** [MaybeShewill-CV/lanenet-lane-detection#458]
您好，请问我如何判断我的实例分割结果的好坏呢？我已经能够算出了二值分割的acuuracy,fn,fp，但是针对与实例分割我确实不清楚它的检测的评价指标。

**Comment by MaybeShewill-CV** [comment]
@longtong-system 对于每个单独的实例 你依旧可以使用fn fp这些指标 不同实例之间 你可以做平均:)
