### ISSUE TITLE
检测多于4条车道线需要修改参数吗

### ISSUE THREAD

**Issue by norainnosun** [MaybeShewill-CV/lanenet-lane-detection#460]
你好,感谢您的开源,请问如果要检测多于4条车道线是不是需要修改tusimple_lanenet.yaml文件中的EMBEDDING_FEATS_DIMS参数?如果要修改这个超参数是不是lanenet也是设置了一个最多检测车道线的数量呢?谢谢

**Comment by gabaebae123** [comment]
你好，请问需要修改吗？
