### ISSUE TITLE
Small addition to the readme.md

### ISSUE THREAD

**Issue by Thomas9876** [MaybeShewill-CV/lanenet-lane-detection#462]
Hi,

Thank you very much for your great project. Just a small suggestion: could you please add to the readme page that all files of the pretrained model (not only the ckp.data...) are needed to restore the model successfully. Took me a while to realize as a newbie :-)

Thank you very much!
Thomas

**Comment by MaybeShewill-CV** [comment]
@Thomas9876 Anyone who is familiar with Tensorflow would know this in my opinion:)
