### ISSUE TITLE
remap.yml

### ISSUE THREAD

**Issue by chenruishuang** [MaybeShewill-CV/lanenet-lane-detection#463]
你好，看完了所有的issues，我还是没有明白对于自己的数据集，我应该如何生成自己的ipm_remap.yml文件，可否提示更多一些，谢谢

**Comment by MaybeShewill-CV** [comment]
@chenruishuang remap矩阵参考这个https://github.com/MaybeShewill-CV/Easy-Ipm-Client。 或者你就自己做个最简单的透视变换也能用:)

**Comment by chenruishuang** [comment]
> 
> 
> @chenruishuang remap矩阵参考这个[https://github.com/MaybeShewill-CV/Easy-Ipm-Client。](https://github.com/MaybeShewill-CV/Easy-Ipm-Client%E3%80%82) 或者你就自己做个最简单的透视变换也能用:)

谢谢你的回复  但我看了这个下面的issues   这个软件是不是并不能直接生成lanenet需要的remap.yml文件  还需要自己修改一下吗？

**Comment by MaybeShewill-CV** [comment]
@chenruishuang 是的 不能直接生成:)

**Comment by chenruishuang** [comment]
> 
> 
> @chenruishuang 是的 不能直接生成, 你可以参考这个论文自己实现一下:)

好的 谢谢

**Comment by chenruishuang** [comment]
作者你好  
![src_image](https://user-images.githubusercontent.com/38372488/97413795-30a94b00-193e-11eb-9b91-84990887ef36.png)
我的结果中车道线打的点没有完全覆盖我的ego lane  只覆盖了一部分  可否提示一下原因  谢谢

**Comment by MaybeShewill-CV** [comment]
@chenruishuang 俯视图只覆盖了部分区域或者采样点不是在俯视图的y坐标轴起点开始采样

**Comment by chenruishuang** [comment]
谢谢解答

**Comment by chenruishuang** [comment]
> @chenruishuang 俯视图只覆盖了部分区域或者采样点不是在俯视图的y坐标轴起点开始采样

谢谢解答

**Comment by chenruishuang** [comment]
作者你好，抱歉再次打扰。 关于前述车道线点只覆盖一部分，确实是因为鸟瞰图只覆盖了部分区域，所以我想自己重新生成自己的remap.yml矩阵。不过由于刚入门，按照推荐论文自己复现的IPM方法始终无法使用，作者可否推荐一些生成remap矩阵的参考代码。非常感谢！

**Comment by MaybeShewill-CV** [comment]
@chenruishuang 这个没有哈 你自己翻翻论文看看吧。最简单你就用四个点算投影矩阵好了:)

**Comment by chenruishuang** [comment]
> 
> 
> @chenruishuang 这个没有哈 你自己翻翻论文看看吧。最简单你就用四个点算投影矩阵好了:)

好的谢谢~
