### ISSUE TITLE
我实现了batchsize 大于1 的hnet训练，但是loss依然不收敛

### ISSUE THREAD

**Issue by cuicuizhang1989** [MaybeShewill-CV/lanenet-lane-detection#47]
可能是我实现有些问题，不知作者啥时候实现这个多batchsize的训练，还有就是我又回顾了一边作者的论文，觉得关于训练拟合矩阵的思想理解起来有些问题，比如作者算loss的方法，期待作者对hnet这一步的分析

**Comment by MaybeShewill-CV** [comment]
@cuicuizhang1989 感觉论文里写的这个hnet loss计算有点问题==!

**Comment by ShangJP** [comment]
@cuicuizhang1989 您好我现在也在实现batch_size大于1的hnet训练，在计算loss的时候，总是有setting an array element with a sequence.错误，我也知道这是车道点数据长度不同导致的，请问您是如何解决的，万分感谢

**Comment by cuicuizhang1989** [comment]
@ShangJP 我把数据统一长度了，采用了15个点做拟合==！

**Comment by ShangJP** [comment]
@cuicuizhang1989 那每张图片具有不同的车道数，您在计算batch的时候是怎么处理的呢，也是固定维度么？

**Comment by MaybeShewill-CV** [comment]
@cuicuizhang1989 可以稳定收敛吗？我训练的过拟合比较严重

**Comment by cuicuizhang1989** [comment]
@MaybeShewill-CV 完全不收敛，@ShangJP 似乎和车道数没有关系

**Comment by ShangJP** [comment]
@cuicuizhang1989 我也开始训练了，发现真的不收敛，一点迹象没有，我把学习率由大到小调节，并没有什么用

**Comment by MaybeShewill-CV** [comment]
@cuicuizhang1989 我觉得原文的公式不是很对

**Comment by CoderHaoranLee** [comment]
@MaybeShewill-CV 我觉得hnet loss部分，在project之后应该用Z对X， Y进行归一化，然后再拟合。拟合后利用之前的Z对X进行反归一化，然后再再进行反投影。原因有二：1，归一化之后的坐标才具有几何意义；2，归一化是非线性变换，可以对y轴进行拉伸以更有助与拟合。 （只是猜测-_-...）

**Comment by ShangJP** [comment]
@cuicuizhang1989 @MaybeShewill-CV @CoderHaoranLee 我认为网络不收敛的原因可能是用为网络输出的矩阵参数变化太大，而实际首推的矩阵参数差距就很大，网络搜索到这几个参数的概率很小，网络一直不能收敛，我是这么想的，

**Comment by CoderHaoranLee** [comment]
@ShangJP 我觉得H矩阵实际并不是将图像空间变换到实际空间（俯视图空间）的矩阵（虽然好像是论文中说是...），因为hnet loss里并没有保证H矩阵收敛后，投影后曲线是否平行。我认为H矩阵只是将图像空间中的点投影到另一个空间，在这个空间下更有利于3次曲线的拟合。

**Comment by CoderHaoranLee** [comment]
@optimal16 我觉这句话的意思应该是解释他定义的这个H矩阵的性质。即在图像空间中y值相同的两个点，变换到他定义的空间中y值仍然相同。。

**Comment by xxxy-931231** [comment]
你好 你们复现了代码吗 我遇到一些问题 如果可以的话可以加我一下微信吗 我有些问题想问 谢谢！
15521179117

**Comment by AromaticJ** [comment]
我想问下Hnet的数据集从哪里得到呢？

**Comment by MaybeShewill-CV** [comment]
@AromaticJ Hnet不需要单独的数据集 tusimple lane dataset就可以了

**Comment by vsendes** [comment]
你好，我在创建了可以读多个batch的脚本，但是一直显示在loss中有矩阵不可求逆的这么一个错误。请问您知道这会是什么原因吗？错误的指向在lanenet_hnet_loss.py的第75行。

InvalidArgumentError (see above for traceback): Input is not invertible.
	 [[Node: loss/hnet_loss/MatrixInverse = MatrixInverse[T=DT_FLOAT, adjoint=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](loss/hnet_loss/MatMul_1)]]
	 [[Node: Adam/update/_28 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1397_Adam/update", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

**Comment by MaybeShewill-CV** [comment]
@vsendes 这个计算公式我应该还有些地方写的不太对 因为我有单独的ipm模块 不太需要这个东西 所以最近一直都没有看这个 一旦有时间了 我会重新更新这个地方的 谢谢理解：）

**Comment by XRDai** [comment]
@MaybeShewill-CV 作者您好，转换为gt_image_binary和gt_image_instance的代码可以分享下吗？我写了一个好像不太对

**Comment by maliyong** [comment]
@vsendes 你好我也遇到矩阵不可逆的问题了，你是怎么解决哒

**Comment by chenyiman** [comment]
@ShangJP @MaybeShewill-CV @cuicuizhang1989 请问lanenet_hnet_loss里面输入的gt_pts是一条车道线上的坐标点吧？如果有几条车道线就会调用几次lanenet_hnet_loss的函数，可我自己的数据集是一张图好几条线，是要先判断哪些点在哪条线上，那就要在tf的图外面计算，训练就会出现问题，是不是一张图只要取一条线上的点做label就行了？

**Comment by MaybeShewill-CV** [comment]
@chenyiman 我做的时候是先把标注的点按照车道线分组 然后分组随机排序 每张图片随机取一条车道线进行训练然后所有的车道线分组数据都依次训练一遍之后再换下一张图像。但是在自己的数据集上这个网络的表现性能非常有限，还是不如传统的基于相机姿态进行ipm转换效果好，所以我还是基于具体任务做了自己的ipm模块，就不用这个hnet了。我觉得唯一的好处就是端到端适合发文章吧:)(纯属个人意见，哈哈)

**Comment by chenyiman** [comment]
@MaybeShewill-CV 那一张图不同的线训练出来的H会是相同的吗。。？因为一张图就对应一个H，而且不同图上标记的线上点的数目也不同，但设置placeholder的时候又要求是固定的维度

**Comment by chenyiman** [comment]
@CoderHaoranLee 你说的Z对X， Y进行归一化，然后再拟合。是不是就是让X,Y分别除以Z，再用得到的这个商去求W，我这样做了以后，会在迭代以后出现（Y^T*Y）不可逆的报错（见下方截图），你知道是为什么吗？还有拟合以后不用在反归一化吧？都是用Z=1的齐次坐标来反投影的。
![image](https://user-images.githubusercontent.com/39306863/50068253-edd5a280-01ff-11e9-9181-72423aa892f1.png)

**Comment by CoderHaoranLee** [comment]
@chenyiman 时间比较久了，今天又翻出来代码跑了一下，1000代没有出现您说的不可逆的情况（我感觉如果y不全是0应该就Ok吧）。可以检查一下预测的y值。拟合之后还是需要反归一化的。您说的齐次坐标应该是从图片中检测得到的然后增加了一维1，然后应该这个齐次坐标通过H变换，得到新的坐标（一个新的空间），在该空间下归一化拟合，然后反归一化。我跑的过程唯一比较诡异的事情是，loss在前面几步就已经降得很小1e-3-1e-4次方量级。之后就不怎么降了。看拟合结果还可以。。。（今天偶尔逛了一下github，才看到。。。。）

**Comment by AromaticJ** [comment]
@CoderHaoranLee @chenyiman
嗨，我遇到了同样的问题，若未归一化的话，不会或者说很少出现矩阵不可逆的情况。但是一旦x,y都除以z之后，一步都无法训练，直接就是不可逆。请问你们有解决了吗？
可以加我微信bqdmm6868一起讨论，我有一些新的想法

**Comment by AromaticJ** [comment]
@chenyiman 
> @vsendes 你好我也遇到矩阵不可逆的问题了，你是怎么解决哒
我发现在计算损失函数之前将传入损失函数计算的所有参数都先cast到双精度之后再去计算损失，能够一定程度上减缓不可逆的情况，但是在训练几千几万轮之后也有可能再次出现不可逆的情况，这个时候只能载入最近的checkpoint点，继续训练。
另外就是给将要进行可逆运算的矩阵加上一个很小的偏置，比如bias = tf.eye(3) * 1e-10
也能一定程度上减缓不可逆，但是我并不能保证多大的偏置才不会对训练结果造成太大的影响。

**Comment by julianprog3** [comment]
how did you implement the hnet? Did you merged it with the lanenet? Can you post your code?

**Comment by MaybeShewill-CV** [comment]
@julianprog3 I did not use that module. I have my own ipm module to generate bird-view image. You may see https://github.com/MaybeShewill-CV/Easy-Ipm-Client if you're interested:)

**Comment by MaybeShewill-CV** [comment]
Since I will not use hnet as ipm module I will close this issue. If you're interested in ipm module you may refer this https://github.com/MaybeShewill-CV/Easy-Ipm-Client:)
