### ISSUE TITLE
如何显示embedding图进行dbscan聚类

### ISSUE THREAD

**Issue by longtong-system** [MaybeShewill-CV/lanenet-lane-detection#472]
您好，我看了您的源码，在lanenet_postprocess.py中的_embedding_feats_dbscan_cluster这个函数中的形参embedding_image_feats，将其输出是一个3110*4的四维向量，其中四维向量分别代表的含义是什么？
还有我怎样可以得到聚类前的散点图，也就是您data/source_image/network_architecture.png中的clustering这个图

**Comment by MaybeShewill-CV** [comment]
@longtong-system 四维向量就是每个像素点对应的特征向量 聚类前的散点图你可以参考postprocess中的相关代码:)
