### ISSUE TITLE
实例分割损失太大问题

### ISSUE THREAD

**Issue by longtong-system** [MaybeShewill-CV/lanenet-lane-detection#473]
您好，我在训练过程中发现binary_loss非常的小(大概可以达到0.03左右)，但是instance_loss非常的大（仍然在13左右），导致的总体的loss也非常大，这是我训练迭代次数达到10000次的结果，多GPU训练的结果（1080ti），大概训练了一天多的时间，请问您这里出现过这样的问题么，我应该怎么去处理？

**Comment by MaybeShewill-CV** [comment]
@longtong-system instance seg loss是会比binary的大 但是也没有13这么大 调整instance seg损失相关的参数然后实验吧

**Comment by longtong-system** [comment]
请问你这里训练到instance——loss的损失小于0.1的时候大概是用时多久的呢？所有参数就是当前.yml和训练代码中的参数没变吗

**Comment by MaybeShewill-CV** [comment]
@longtong-system 训练用时记不清楚了。loss参数和现在的yml文件相同 别的参数和现在的有区别。

**Comment by longtong-system** [comment]
告诉我大概就可以的…大概能到两三天时间的训练？还是说是大概一天内就可以训练的很好啥的，因为我感觉训练的时间长到有点不理解

**Comment by MaybeShewill-CV** [comment]
@longtong-system 我的1070卡上应该是一天多我记得
