### ISSUE TITLE
Extract lane coordinates

### ISSUE THREAD

**Issue by go-zenith** [MaybeShewill-CV/lanenet-lane-detection#477]
Hi, may i know how can i extract the lane coordinates data because i want to measure the radius of curve and monitors the offset from centre? Thank you for your help.

**Comment by MaybeShewill-CV** [comment]
@go-zenith https://github.com/MaybeShewill-CV/lanenet-lane-detection/blob/66d7405d8e5284767addf31bab6a7ba17274d187/lanenet_model/lanenet_postprocess.py#L343-L380
src_lane_pts are lane in source images:)
