### ISSUE TITLE
little bug in postprocess.py (在你的lanenet_model/lanenet_postprocess.py里插值公式应该是有误的)

### ISSUE THREAD

**Issue by FlowEternal** [MaybeShewill-CV/lanenet-lane-detection#478]
First thanks for your scripts. I carefully inspected the lanenet_model/lanenet_postprocess.py and find that something wrong in lines 413--418. The original snippet is:
                # interpolation_src_pt_x = (abs(previous_src_pt_y - plot_y) * previous_src_pt_x +
                #                           abs(last_src_pt_y - plot_y) * last_src_pt_x) / \
                #                          (abs(previous_src_pt_y - plot_y) + abs(last_src_pt_y - plot_y))
                # interpolation_src_pt_y = (abs(previous_src_pt_y - plot_y) * previous_src_pt_y +
                #                           abs(last_src_pt_y - plot_y) * last_src_pt_y) / \
                #                          (abs(previous_src_pt_y - plot_y) + abs(last_src_pt_y - plot_y))

howerver for linear interploation, the deduced formulation should look like this by swapping the last and previous items:
                interpolation_src_pt_x = (abs(previous_src_pt_y - plot_y) * last_src_pt_x +
                                          abs(last_src_pt_y - plot_y) * previous_src_pt_x) / \
                                         (abs(previous_src_pt_y - plot_y) + abs(last_src_pt_y - plot_y))
                interpolation_src_pt_y = (abs(previous_src_pt_y - plot_y) * last_src_pt_y +
                                          abs(last_src_pt_y - plot_y) * previous_src_pt_y) / \
                                         (abs(previous_src_pt_y - plot_y) + abs(last_src_pt_y - plot_y))

please confirm the above inspection
thanks !

**Comment by MaybeShewill-CV** [comment]
@FlowEternal 当时考虑的时候是按照y方向的点的位置距离采样的：）

**Comment by FlowEternal** [comment]
> @FlowEternal 当时考虑的时候是按照y方向的点的位置距离采样的：）
是按照y方向点采样，但是其实和按照x还是y方向没有关系，你可以亲自推导一下。
就看最极限的情况，假设previous_src_pt_y = plot_y，带入原来的代码公式，得interpolation_src_pt_x = last_src_pt_x，但是假设的是previous_src_pt_y = plot_y，也就说待插值的点和previous_src_pt重合，必有interpolation_src_pt_x = previous_src_pt_x，和前面矛盾了。

**Comment by MaybeShewill-CV** [comment]
@FlowEternal 是你说的这个情况。当时的设想是plot_y等于previous_src_pt_y的时候等于plot_y已经把previous_src_pt_y“覆盖”了，所以不考虑这个点对当前插值点的影响，就把后一个点的值直接赋值到当前值就好。你现在的考虑是距离哪个点近哪个点对当前插值点的影响更大，我觉得也是可以的。

**Comment by FlowEternal** [comment]
好吧，谢谢解答。
还有发现一个和MMN版本相关的问题，个人测试中发现采用bisenetv2作为语义分割主干网络时候，MMN1.1.0版本前（包括1.1.0版本还有你说的MMN0.2.1.0）的MNNconverter转换pb文件时，可以转换出mmn文件，但转换时候会打印错误信息：MNNconverter Error for compute convolution shape, need channel = 192, input 32。同时前向的结果和python脚本的不一致，说明模型转换错误。（若主干网络是vgg，那就没有问题，前向结果和脚本一致）。但是当用最新的MMN-master版本编译出的converter.exe转换bisenetv2作为主干网络的lanenet的pb模型时候，就不会有这个错误，前向的结果也是正确的

**Comment by MaybeShewill-CV** [comment]
@FlowEternal 这个问题我也遇到过，之前询问过MNN的开发人员，他们告诉我说depthmultier > 1的depthwise卷积他们还不支持，不过已经安排同学去开发了。我本地的MNN还是1.1.0版本，不知道最新的master版本有没有修复这个问题。你测试的时候可以测试下cityscapes数据得到的模型，看看转换的MNN模型是不是可以正常使用:)
