### ISSUE TITLE
Tensorboard Graphs

### ISSUE THREAD

**Issue by tlhcelik** [MaybeShewill-CV/lanenet-lane-detection#482]
I started to training with start tensorboard graphics. 
But i can't see train loss graph and accuracy graph. 
How can i show this graphs ? 

I see thats :

1. summrary/binary_loss_1
2. summrary/binary_loss_2
3. summrary/instance_loss_1
4. summrary/learn_rate_1
5. **summrary/miou -> I don't know what does mean...**
6. **summrary/val_miou -> I don't know what does mean...**
6. summrary/total_loss_1
7. summrary/total_loss_2

Can you explain basically this graphs what does mean ?

**Comment by MaybeShewill-CV** [comment]
@tlhcelik miou represents mean intersection over union. https://en.wikipedia.org/wiki/Jaccard_index :)

**Comment by tlhcelik** [comment]
@MaybeShewill-CV  May you explain other graph types as basically please? If links or wiki is exist, just you can give.

**Comment by MaybeShewill-CV** [comment]
@tlhcelik Check this https://tensorflow.google.cn/tensorboard/migrate

**Comment by YuZijian1** [comment]
> 

Have you solved the problem "there are no accuracy graph" yet? Help please.

**Comment by XiaoLaBa1997** [comment]
Have you solved the problem "there are no accuracy graph" yet? Help please.
