### ISSUE TITLE
training_data_example中.txt中路径为lanenet-lane-detection/data/但是实际为lanenet-lane-detection-mater/data/

### ISSUE THREAD

**Issue by xxKomorebixx** [MaybeShewill-CV/lanenet-lane-detection#489]
这一点是否会对生成tfrecord有影响呢？

**Comment by MaybeShewill-CV** [comment]
@xxKomorebixx 会有影响 我写在data文件夹中的就是一个示例，具体需要你按照你自己的文件存储结构去实际填写:)

**Comment by xxKomorebixx** [comment]
> @xxKomorebixx 会有影响 我写在data文件夹中的就是一个示例，具体需要你按照你自己的文件存储结构去实际填写:)

谢谢！！还想问下在train过程中报错tensorflow.python.framework.errors_impl.OutOfRangeError: End of sequence [Op:IteratorGetNextSync]是要修改迭代部分的代码吗？

**Comment by xxKomorebixx** [comment]
> > @xxKomorebixx 会有影响 我写在data文件夹中的就是一个示例，具体需要你按照你自己的文件存储结构去实际填写:)
> 
> 谢谢！！还想问下在train过程中报错tensorflow.python.framework.errors_impl.OutOfRangeError: End of sequence [Op:IteratorGetNextSync]是要修改迭代部分的代码吗？

找到问题了，是之前数据集太小的问题。谢谢您！
