### ISSUE TITLE
How to train with more than 2 classes?

### ISSUE THREAD

**Issue by aj96** [MaybeShewill-CV/lanenet-lane-detection#49]
Hello, I noticed that in your config file, you specify the number of classes to be 2, but I do not see where you call this parameter in any of your scripts. Say I have multiple classes: dashed white lines, solid white lines, solid yellow lines, etc, and I would like to train LaneNet to find all the instances of these classes, how would I do this? 

I assume just changing the number of classes is not enough because in the binary segmented image, it could no longer be a binary segmented image. But then you would also have to change the instance segmentation label image. Simply giving each pixel an instance id is not good enough anymore because now you need to know which class that instance corresponds to? 

I am not familiar with instance segmentation, so I am not even sure if this is possible.

Thank you.

**Comment by MaybeShewill-CV** [comment]
@aj96 The config file was used another project of mine so you can ignore the number of classes. You should label different instance with different pixel value

**Comment by aj96** [comment]
@MaybeShewill-CV Okay. I will ignore the number of classes parameter in your config file. Then how do I do the binary segmented image? I assume this image was binary (0 or 255) because there were only two classes. Now that there are more than 2 classes, how should I label them?  For instance, if I have 5 classes, would it be appropriate to label them 0, 63, 127, 191, 255?

**Comment by MaybeShewill-CV** [comment]
@aj96 Yep you can assign those pixel value with different lane instance
