### ISSUE TITLE
Custom data training NAN as output

### ISSUE THREAD

**Issue by iamzubairnaseer** [MaybeShewill-CV/lanenet-lane-detection#490]
I'm trying to train with my own data set. I'm getting NAN value as output of training.
training cmd: python3 train_lanenet_tusimple.py
image size: 512*256
using multi gpu configuration
![Screenshot from 2021-03-16 15-02-09](https://user-images.githubusercontent.com/40863362/111291421-ff20ea00-8668-11eb-86c7-5b156b18dd4a.png)

**Comment by MaybeShewill-CV** [comment]
@iamzubairnaseer Check your dataset to see if anything wrong with it:)

**Comment by iamzubairnaseer** [comment]
@MaybeShewill-CV Thank you for replying.
I just increased my data set and now I'm getting this shape error. All image's size including binary and instance is 512*256.
![Screenshot from 2021-03-17 23-04-50](https://user-images.githubusercontent.com/40863362/111516491-c7539880-8775-11eb-918a-bd7e2d03fd48.png)
Any idea and suggestion would be helpful.

**Comment by MaybeShewill-CV** [comment]
@iamzubairnaseer image channels num wrong:)

**Comment by iamzubairnaseer** [comment]
@MaybeShewill-CV I converted gt_image, gt_binary_image, gt_instance_image into a single channel but now I'm getting reverse error. Before it was input shape is 470016 and requested shape has 156672 but now it is saying reverse.
![Screenshot from 2021-03-18 15-46-27](https://user-images.githubusercontent.com/40863362/111614652-a2a50280-8801-11eb-9e12-558c593056f3.png)

**Comment by MaybeShewill-CV** [comment]
@iamzubairnaseer ......gt_image need to be 3 channel image ==!

**Comment by iamzubairnaseer** [comment]
@MaybeShewill-CV Why is process killed?
![Screenshot from 2021-03-19 08-45-46](https://user-images.githubusercontent.com/40863362/111728942-c3b43480-888f-11eb-9cd3-eb738c8c88ca.png)

**Comment by MaybeShewill-CV** [comment]
@iamzubairnaseer Do not know why:)

**Comment by iamzubairnaseer** [comment]
@MaybeShewill-CV Thank you for your help. I solved above problem by decreasing the batch size.

**Comment by MaybeShewill-CV** [comment]
@iamzubairnaseer May caused by OOM then:)
