### ISSUE TITLE
Test model 报错

### ISSUE THREAD

**Issue by cllllll** [MaybeShewill-CV/lanenet-lane-detection#491]
测试模型
python tools/test_lanenet.py --weights_path ./model/tusimple_lanenet/tusimple_lanenet.ckpt  --image_path ./data/tusimple_test_image/0.jpg
报错：
Traceback (most recent call last):
  File "tools/test_lanenet.py", line 163, in <module>
    test_lanenet(args.image_path, args.weights_path)
  File "tools/test_lanenet.py", line 94, in test_lanenet
    net = lanenet.LaneNet(phase='test', cfg=CFG)
TypeError: __init__() got an unexpected keyword argument 'cfg'
请问应该如何修改

**Comment by MaybeShewill-CV** [comment]
@cllllll 感觉是不是你的代码没有更新, 截图看下 lanenet_model/lanenet.py 文件的22行。正确的初始化函数应该是https://github.com/MaybeShewill-CV/lanenet-lane-detection/blob/66d7405d8e5284767addf31bab6a7ba17274d187/lanenet_model/lanenet.py#L18-L30

**Comment by cllllll** [comment]
@MaybeShewill-CV 代码是新的没错
class LaneNet(cnn_basenet.CNNBaseModel):
    """

    """
    def __init__(self, phase, cfg):
        """

        """
        super(LaneNet, self).__init__()
        self._cfg = cfg
        self._net_flag = self._cfg.MODEL.FRONT_END

我唯一添加的部分在test_lanenet.py中
import sys 
sys.path.append('E:/git/lanenet-lane-detection-master')
sys.path.append('E:/git/lanenet-lane-detection-master/config')
sys.path.append('E:/git/lanenet-lane-detection-master/data_provider')
sys.path.append('E:/git/lanenet-lane-detection-master/lanenet_model')
sys.path.append('E:/git/lanenet-lane-detection-master/tools')

**Comment by MaybeShewill-CV** [comment]
@cllllll 不需要加sys.append 终端上export PYTHONPATH就好了。看报错就是说__init__函数没有cfg这个参数 可以检查下你的代码里的哪里和github上不一致

**Comment by ioorange** [comment]
请问这个问题得到解决了吗，我也是这个问题，检查了程序也没有发现什么问题，想询问一下解决办法。
