### ISSUE TITLE
关于seghead.增强训练策略

### ISSUE THREAD

**Issue by mengpengfei** [MaybeShewill-CV/lanenet-lane-detection#492]
您好大佬，看了遍你写的lanenet代码，然后反复看了下里面的bisenetv2,我看论文中使用了seghead.增强训练策略，代码里面没有实现这种策略吗

**Comment by MaybeShewill-CV** [comment]
@mengpengfei bisenetv2相关的可以参考https://github.com/MaybeShewill-CV/bisenetv2-tensorflow 这里只是用bisenetv2做lanenet的ｂａｃｋｂｏｎｅ:)

**Comment by mengpengfei** [comment]
非常感谢，lannet得中得这个训练时用seghead策略了吗

**Comment by MaybeShewill-CV** [comment]
@mengpengfei 没有

**Comment by mengpengfei** [comment]
感谢
