### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Azie233** [MaybeShewill-CV/lanenet-lane-detection#493]
hello, i just cant download your pre-traned model weights, can you give me another choice to download it ? thanks

**Comment by MaybeShewill-CV** [comment]
@Azie233 Only dropbox available now:)

**Comment by Azie233** [comment]
> @Azie233 Only dropbox available now:)
that's a pity, but thank you all the same

**Comment by MaybeShewill-CV** [comment]
@Azie233 Welcome:)
