### ISSUE TITLE
cannot find 'lanenet_model' module even after I changed my _path to my personal path

### ISSUE THREAD

**Issue by Dylee-y** [MaybeShewill-CV/lanenet-lane-detection#494]
> > > just add the module root dir to your PYTHONPATH
> > 
> > 
> > do you have specific operations?i don't know how to handle this.
> > In your terminal, input below:
> 
> `export PYTHONPATH="${PYTHONPATH}:your_path/lanenet-lane-detection/lanenet_model"`
> 
> Change your_path to your personal path for `lanenet` folder. You can append this line to your `~/.bashrc` then `source ~/.bashrc ` to activate it.

_Originally posted by @WangShuu in https://github.com/MaybeShewill-CV/lanenet-lane-detection/issues/15#issuecomment-453824473_

Hello! I am currently trying to run your code on Jetson nano(Ubuntu 18.04.5) (GNU/Linux 4.9.201-tegra aarch64)
However, I tried to append the specific operation above in ~/.bashrc , but I still get the error 
ModuleNotFoundError: No module named 'lanenet_model'.

I've also tried import sys, but I got the same error.
Is there any other way to address this problem?
Thank you in advance!

**Comment by MaybeShewill-CV** [comment]
@Dylee-y That python environment relative problem. You may google how to solve it:)
