### ISSUE TITLE
tusimple_ipm_remap.yml for custom data

### ISSUE THREAD

**Issue by iamzubairnaseer** [MaybeShewill-CV/lanenet-lane-detection#495]
What type of data does the data-array in "tusimple_ipm_remap.yml" file conatins? Are the points in the array related to the lines detected in BEV?

**Comment by MaybeShewill-CV** [comment]
@iamzubairnaseer No that's a remap matrix to map image from front view into bird view:)

**Comment by iamzubairnaseer** [comment]
Thank you for replying. I made the remap matrix using IPM. But when I tested the model, I'm not getting the correct output. Can the remap file affect the output?

**Comment by MaybeShewill-CV** [comment]
@iamzubairnaseer Yep it may affect the final result:)

**Comment by iamzubairnaseer** [comment]
Can you guess from this, what can be error-prone either annotations or remap matrix?
![Screenshot from 2021-04-16 09-11-33](https://user-images.githubusercontent.com/40863362/114970833-a2e1fd80-9e94-11eb-9fde-b381108daf42.png)

**Comment by MaybeShewill-CV** [comment]
@iamzubairnaseer The model doesn't converge:)

**Comment by Jerry-LMB** [comment]
请问如何制作自己的重映射矩阵
