### ISSUE TITLE
你好，能列举下在输入网络之前都实现了哪些方法做数据增强吗

### ISSUE THREAD

**Issue by mengpengfei** [MaybeShewill-CV/lanenet-lane-detection#496]
借鉴你得网络结构实现了网络之后泛化效果不好，能列举下在输入网络之前都实现了哪些方法做数据增强吗

**Comment by MaybeShewill-CV** [comment]
@mengpengfei 可以参考https://github.com/MaybeShewill-CV/lanenet-lane-detection/blob/master/config/tusimple_lanenet.yaml　配置文件。只使用了crop和水平翻转:)

**Comment by gabaebae123** [comment]
> 借鉴你得网络结构实现了网络之后泛化效果不好，能列举下在输入网络之前都实现了哪些方法做数据增强吗

您好 请问您后来有新增一些其他增强方法吗？效果有提升吗？
