### ISSUE TITLE
是否容易实现车道偏离检测？

### ISSUE THREAD

**Issue by TenYoDun** [MaybeShewill-CV/lanenet-lane-detection#498]
我想加入车道偏离检测，源代码是否已经有此功能，或者有什么方法可以快速地和您的代码结合实现车道偏离检测呢？

**Comment by MaybeShewill-CV** [comment]
@TenYoDun 没有这部分功能 需要你自己开发哈, 这个代码库只负责检测车道线的位置:)

**Comment by TenYoDun** [comment]
@MaybeShewill-CV 好的，感谢你回答
