### ISSUE TITLE
how to generate the binary segmentation label file ？

### ISSUE THREAD

**Issue by YgRen** [MaybeShewill-CV/lanenet-lane-detection#5]
hello，I want to make the same dataset like you in lane dataset. but there is a question about me is how to convert my lane line json label file into the binary segmentation label  file and the instance label file from original image. can you tell me how to operate it?
Thx!

**Comment by MaybeShewill-CV** [comment]
@YgRen If you use the tusimple dataset you can just simply use the cv2.polylines to draw polylines according the json label file to generate the binary segmentation label file

**Comment by YgRen** [comment]
@MaybeShewill-CV Line drawing is relatively simple for me.But I have a question why many datasets are drawn in stripe lanes.how to set the width? so the lane line semantic segmentation is lane line or strip lane ?

**Comment by MaybeShewill-CV** [comment]
@YgRen The lane width is set by yourself. I set the width with 5 in cv2.polylines function.

**Comment by YgRen** [comment]
@MaybeShewill-CV Thx,   I have got it. But I still have a question about instance segmentation dataset convert operation. When I make a lane instance dataset, my number of lanes is 0~10+ in each picture,I just need to make sure that the lane lines in each picture are of different colors or gray level?

**Comment by MaybeShewill-CV** [comment]
@YgRen Yes you should make sure each lane is of different colors of gray level

**Comment by YgRen** [comment]
thx,

**Comment by YgRen** [comment]
thx!

**Comment by chaine09** [comment]
@YgRen Do you have link for the tusimple dataset's readme file? How did you generate the binary and segmentation images?

**Comment by chaine09** [comment]
@YgRen Were you able to generate your own training data?
