### ISSUE TITLE
 organize training data encounter problems

### ISSUE THREAD

**Issue by zr940326** [MaybeShewill-CV/lanenet-lane-detection#50]
hello, I am learning your work, the organization data set has a problem, I don't understand, your traning_data_example file structure, I want to know, how the images in pictures and gt_image_instance gt_image_binary file is generated

**Comment by zr940326** [comment]
I don't know, if you can understand, if I have a question to express, please inform me.

**Comment by zr940326** [comment]
![qq 20180819085859](https://user-images.githubusercontent.com/17058316/44304435-71849d00-a38e-11e8-9bec-4a17b0f8e14c.png)
![qq 20180819090012](https://user-images.githubusercontent.com/17058316/44304437-777a7e00-a38e-11e8-837c-f5f2c32fe744.png)
![qq 20180819090034](https://user-images.githubusercontent.com/17058316/44304438-78abab00-a38e-11e8-8aa2-7595a38a5947.png)

I have downloaded good, http://benchmark.tusimple.ai/

**Comment by MaybeShewill-CV** [comment]
@zr940326 You can read tusimple lane dataset readme file it will provide you with a detailed description
