### ISSUE TITLE
error when  test

### ISSUE THREAD

**Issue by tigerdhl** [MaybeShewill-CV/lanenet-lane-detection#502]
I use the tensorflow 2.1 and  when I test the prj, it error:

"
....
....
File "/home/test/miniconda3/envs/tenf/lib/python3.6/site-packages/tensorflow_core/python/framework/tensor_shape.py", line 200, in __init__
    None)
  File "<string>", line 3, in raise_from
TypeError: Dimension value must be integer or None or have an __index__ method, got 3.0
"
---------------------------------
the command I run:python tools/test_lanenet.py --weights_path ./weights/tusimple_lanenet.ckpt.data-00000-of-00001 --image_path ./data/tusimple_test_image/0.jpg
and I open the file tensor_shape.py,find this:
"
class Dimension(object):
  """Represents the value of one dimension in a TensorShape."""

  __slots__ = ["_value"]

  def __init__(self, value):
    """Creates a new Dimension with the given value."""
    if value is None:
      self._value = None
    elif isinstance(value, Dimension):
      self._value = value
    else:
      try:
        # int(...) compensates for the int/long dichotomy on Python 2.X.
        # TODO(b/143206389): Remove once we fully migrate to 3.X.
        self._value = int(value.__index__())
      except AttributeError:
        six.raise_from(
            TypeError("Dimension value must be integer or None or have "
                      "an __index__ method, got {!r}".format(value)),
            None)
      if self._value < 0:
        raise ValueError("Dimension %d must be >= 0" % self._value)
"

**Comment by MaybeShewill-CV** [comment]
@tigerdhl Tensorflow 2.1 is not supported use tensorflow-gpu 1.15 instead:)

**Comment by tigerdhl** [comment]
> @tigerdhl Tensorflow 2.1 is not supported use tensorflow-gpu 1.15 instead:)

okey
