### ISSUE TITLE
not work gpu

### ISSUE THREAD

**Issue by blusky26** [MaybeShewill-CV/lanenet-lane-detection#509]
Hi @MaybeShewill-CV,
Thank you for your great work

I am trying to run your example code in ubuntu20.04

python tools/test_lanenet.py --weights_path /PATH/TO/YOUR/CKPT_FILE_PATH 
--image_path ./data/tusimple_test_image/0.jpg

I tried this code, got lane_detect_result.
But, do not run gpu, so operating speed is slow down.

I tried re-install cuda, nvidia...

what should i do this problem?

**Comment by MaybeShewill-CV** [comment]
@blusky26 Perhaps your tensorflow-gpu was not correctly installed. Nothing wrong here. Just make sure your tensorflow-gpu was correctly installed:)

**Comment by kk52099** [comment]
> Hi @MaybeShewill-CV,
> Thank you for your great work
> 
> I am trying to run your example code in ubuntu20.04
> 
> python tools/test_lanenet.py --weights_path /PATH/TO/YOUR/CKPT_FILE_PATH
> --image_path ./data/tusimple_test_image/0.jpg
> 
> I tried this code, got lane_detect_result.
> But, do not run gpu, so operating speed is slow down.
> 
> I tried re-install cuda, nvidia...
> 
> what should i do this problem?

i also have the  same  problem  ,do you  solve it?

**Comment by kk52099** [comment]
> Hi @MaybeShewill-CV,
> Thank you for your great work
> 
> I am trying to run your example code in ubuntu20.04
> 
> python tools/test_lanenet.py --weights_path /PATH/TO/YOUR/CKPT_FILE_PATH
> --image_path ./data/tusimple_test_image/0.jpg
> 
> I tried this code, got lane_detect_result.
> But, do not run gpu, so operating speed is slow down.
> 
> I tried re-install cuda, nvidia...
> 
> what should i do this problem?

i also have the  same  problem  ,do you  solve it? @blusky26

**Comment by blusky26** [comment]
> > Hi @MaybeShewill-CV,
> > Thank you for your great work
> > I am trying to run your example code in ubuntu20.04
> > python tools/test_lanenet.py --weights_path /PATH/TO/YOUR/CKPT_FILE_PATH
> > --image_path ./data/tusimple_test_image/0.jpg
> > I tried this code, got lane_detect_result.
> > But, do not run gpu, so operating speed is slow down.
> > I tried re-install cuda, nvidia...
> > what should i do this problem?
> 
> i also have the same problem ,do you solve it? @blusky26

not yet... i tried reinstall other version, but same problem occured

**Comment by kk52099** [comment]
@blusky26 do you  have the mode file "tusimple_lanenet_vgg.ckpt"?

**Comment by kk52099** [comment]
> > > Hi @MaybeShewill-CV,
> > > Thank you for your great work
> > > I am trying to run your example code in ubuntu20.04
> > > python tools/test_lanenet.py --weights_path /PATH/TO/YOUR/CKPT_FILE_PATH
> > > --image_path ./data/tusimple_test_image/0.jpg
> > > I tried this code, got lane_detect_result.
> > > But, do not run gpu, so operating speed is slow down.
> > > I tried re-install cuda, nvidia...
> > > what should i do this problem?
> > 
> > 
> > i also have the same problem ,do you solve it? @blusky26
> 
> not yet... i tried reinstall other version, but same problem occured

@blusky26 i  reinstall tensorflow-gpu , and  remove the  tensorflow, it is  ok!

**Comment by blusky26** [comment]
> > > > 안녕하세요 @ MaybeShewill-CV , 
> > > > 훌륭한 작업에 감사드립니다 
> > > > . ubuntu20.04 
> > > > python tools / test_lanenet.py --weights_path / PATH / TO / YOUR / CKPT_FILE_PATH 
> > > > --image_path ./data/tusimple_test_image/ 에서 예제 코드를 실행하려고합니다 . 0.jpg 
> > > > 나는이 코드를 시도했고, lane_detect_result를 얻었다. 
> > > > 그러나 GPU를 실행하지 마십시오. 따라서 작동 속도가 느려집니다. 
> > > > cuda, nvidia를 다시 설치해 보았습니다. 
> > > > 이 문제를 어떻게 해결해야합니까?
> > > 
> > > 
> > > 나는 또한 같은 문제가 있습니다, 당신은 그것을 해결합니까? 뿡뿡
> > 
> > 
> > 아직 ... 다른 버전을 다시 설치하려고했는데 같은 문제가 발생했습니다.
> 
> @ blusky26 나는 tensorflow-gpu를 다시 설치하고 tensorflow를 제거하면 괜찮습니다!

use tensorflow this code, remove tensorflow?

what do u use tensorflow-gpu version, and requirement list version?

**Comment by kk52099** [comment]
@blusky26 tensorflow_gpu==1.12.0

**Comment by blusky26** [comment]
> @blusky26 tensorflow_gpu==1.12.0
 i`m using ubuntu 20.04,cuda 10.1.

 u use ubuntu 20.04, cuda 10.1?

**Comment by kk52099** [comment]
@blusky26 python 3.5 ,ubuntu 1604  , cuda 9.0

**Comment by kk52099** [comment]
@blusky26 do you have the mode file "tusimple_lanenet_vgg.ckpt"?

**Comment by blusky26** [comment]
> @ blusky26 "tusimple_lanenet_vgg.ckpt"모드 파일이 있습니까?

refer to https://github.com/MaybeShewill-CV/lanenet-lane-detection/issues/241 

good luck!
