### ISSUE TITLE
evaluate: ground-truth and test-image size are different?

### ISSUE THREAD

**Issue by y11203090135** [MaybeShewill-CV/lanenet-lane-detection#51]
请问，测试的二值图像的大小和测试的标签图像大小不一致，在进行模型评估的时候，将二值图像的大小要resize到测试图像的大小，这样还有影响吗？

**Comment by MaybeShewill-CV** [comment]
@y11203090135 测试的二值图像和标签图像分别指什么？

**Comment by y11203090135** [comment]
256*512的预测二值图像和720*1280的对应ground-truth图像

**Comment by y11203090135** [comment]
测试图像输出的256 X 512的二值图像和对应的720 X 1280的ground-truth图像（test_label图像）

**Comment by MaybeShewill-CV** [comment]
@y11203090135 你的label图像怎么变成256*512的，你对应转换回去就好了

**Comment by y11203090135** [comment]
好的，thank you
