### ISSUE TITLE
Is this project possible running on NVIDIA jetson NX?

### ISSUE THREAD

**Issue by edwardchang0112** [MaybeShewill-CV/lanenet-lane-detection#512]
As title mentioned, I would like to implement lane detection on NVIDIA's NX, is that possible?
Since I tried to follow the steps in this github post, the some libraries in the requirements.txt not working on NX.
Anyone has this kind of experiences, please share some comments or example with me!

**Comment by MaybeShewill-CV** [comment]
@edwardchang0112 Have not tested it before. But i think this project should work properly on jetson NX
