### ISSUE TITLE
lanenet.postprocess() taking too much time

### ISSUE THREAD

**Issue by SHANK885** [MaybeShewill-CV/lanenet-lane-detection#518]
Hi, I was trying to run your code and after analyzing the model inference and post-processing time, I found out that the DBSCAN clustering part is taking too much time. My system has NVIDIA GTX 1650 ti (4 GB). The model inference time comes around 12-15 ms per sample whereas the clustering part takes 300-400 ms per sample. Is there any faster way to post-process it so that it can be used in real-time? Also, the actual research paper mentions that they have used a mean-shift approach to cluster the lanes.

**Comment by MaybeShewill-CV** [comment]
@SHANK885 You may test mean-shift method yourself. One solution to reduce cluster time cost is to reduce sample counts which used for clustering. For real time application, you'd better use tensorrt or other inference accelerate engine and cpp cluster method:)

**Comment by SHANK885** [comment]
@MaybeShewill-CV thanks for the suggestions. Any idea how we can remove the sample counts which is used for clustering?

**Comment by MaybeShewill-CV** [comment]
@SHANK885 try random sample:)

**Comment by SHANK885** [comment]
Thanks
