### ISSUE TITLE
Need help with training for two classes with custom dataset

### ISSUE THREAD

**Issue by chee0007** [MaybeShewill-CV/lanenet-lane-detection#519]
Hi,
I am trying to train two classes - Lane and Curbs using bisenetv2
I labelled lanes as 1, curbs as 2 in the binary_seg mask 
I have set NUM_CLASSES: 2, FRONT_END: 'bisenetv2' in tusimple_lanenet.yaml

The training was successful. But when I run test_lanenet.py, the binary_seg_image output is black without any labels, and the instance_seg_image looks normal with different coloured lane clusters.

The binary_seg_image output should have labels 1 and 2, but I am not getting any. Please advise if I have followed the procedures correctly. Thanks for your help.

**Comment by MaybeShewill-CV** [comment]
@chee0007 The postprocess code here was designed for tusimple dataset. You need to adjust those code yourself or you could simple add binary seg mask upon origin image:)

**Comment by chee0007** [comment]
@MaybeShewill-CV Thanks! I will try it. :)

**Comment by Petros626** [comment]
@chee0007 you were successfull?
