### ISSUE TITLE
代码和数据集路径问题

### ISSUE THREAD

**Issue by Jerome-JSC** [MaybeShewill-CV/lanenet-lane-detection#525]
@MaybeShewill-CV 
您好，我在调用 tools/generate_tusimple_dataset.py 将原始数据转换格式时出现了问题，TypeError: expected str, bytes or os.PathLike object, not NoneType，这个 path = os.fspath(path)的路径怎样设置啊，数据集需要放到代码的training_data_example这个文件夹下吗？怎样修改代码路径呢？我用的是pycharm，请指教。

**Comment by Jerome-JSC** [comment]
@MaybeShewill-CV

**Comment by MaybeShewill-CV** [comment]
@Jerome-JSC 可以自己看下https://github.com/MaybeShewill-CV/lanenet-lane-detection/blob/94be8d9a66c7bbda5ad99b10492bc406c8aee45f/tools/generate_tusimple_dataset.py#L136-L171

**Comment by Jerome-JSC** [comment]
代码里就是这样，我的也是这样报错 @MaybeShewill-CV
