### ISSUE TITLE
Questions and hints for getting started to train with own customized data

### ISSUE THREAD

**Issue by KHeap25** [MaybeShewill-CV/lanenet-lane-detection#526]
Hello,

thank you to make the code of the [paper](https://arxiv.org/pdf/1802.05591.pdf) available!
As I am at the begining of my work, I have some questions about the proposed model.

First of all, it is very interseting that the model trains the transformation matrix for the "bird's eye view", so it is more robust against slope changes and so on.
Is it possible to get the secmented images with the lanes in the bird's eye perspective?
How can the coefficent's of the fitted 3rd order polynomial be stored before they are reprojected on the original image?

Another point I would like to mention is the [training](https://github.com/MaybeShewill-CV/lanenet-lane-detection#train-your-own-model) process with customized data and the coressponding labels.
Which parameters need to be adjusted to train the model with a customized image resolution?
Where they need to be adjusted? 
Where should the test images be placed?
Which accuracy metric do you use to quantify the models accuracy? For example the [accuracy](https://github.com/MaybeShewill-CV/lanenet-lane-detection#experiment) during the training?

It would be great if someone can answer the questions and give me some hints.
I look forward to hearing from you soon.

Best regards.

**Comment by MaybeShewill-CV** [comment]
@KHeap25 1.First hnet was not used here and a fixed project remap matrix was used for bird eye convertion instead. 2. I will make this repo more easy to use on i got enough spare time:)
