### ISSUE TITLE
shuffle buffer filled

### ISSUE THREAD

**Issue by Jerome-JSC** [MaybeShewill-CV/lanenet-lane-detection#528]
训练时应该是爆显存了，调整batch size结果还是不行，请问怎样调整可以开始训练呢？
![2021-09-28 00-02-55 的屏幕截图](https://user-images.githubusercontent.com/75569365/137288075-d5262aa0-ae24-46ec-a066-c8142993d10a.png)
@MaybeShewill-CV @pauperonway @InonS @kunalgoyal9 @ryanjung94 @

**Comment by MaybeShewill-CV** [comment]
@Jerome-JSC shuffle buffer filled 是说用来shuffle的缓冲区填充满了，这个不影响显存。减小batch size重新做吧，如果batch size=1都不能训练的话 还是换个显卡好一点==！
