### ISSUE TITLE
模型训练时准确率是如何定量判定的？

### ISSUE THREAD

**Issue by Jerome-JSC** [MaybeShewill-CV/lanenet-lane-detection#529]
请问怎样训练时的准确率是怎样判定的呢，比如准确率为1或者0.9几，怎样判断检测出的车道线是好是坏呢，就是这些数值是根据什么得出的呢，请您给予一些定量的分析，谢谢您啦

**Comment by Jerome-JSC** [comment]
@MaybeShewill-CV @pauperonway @InonS @kunalgoyal9

**Comment by MaybeShewill-CV** [comment]
@Jerome-JSC 和一般的图像分割的指标计算没有什么本质区别。还是通过准确率，miou等这些指标来评判模型的好坏。具体的想要通过某个指标的值来定性、定量分析模型的好坏需要根据实际的场景来定义（比如车道线在不同镜头中的粗细不同）。最直观的方式还是直接把检测出的mask掩码图画在原图上来直观的验证检测结果:)
