### ISSUE TITLE
Detailed instructions about code execution

### ISSUE THREAD

**Issue by igormahall** [MaybeShewill-CV/lanenet-lane-detection#534]
Hello fellows.

I am a newbie and faced some issues during this code execution. However, I found these instructions that saved me a lot of time:
https://www.nnmutong.com/home/tarticle_item?id=4799

I hope this could be useful.

PS: I am sorry if this post was not proper to this discussion.

**Comment by MaybeShewill-CV** [comment]
@igormahall zan!
