### ISSUE TITLE
How Can I Found Previous Weights File

### ISSUE THREAD

**Issue by asimkymk** [MaybeShewill-CV/lanenet-lane-detection#535]
Hello I need the previous weight file which name is 'tusimple_lanenet_vgg_2018-10-19-13-33-56.ckpt-200000'. Can you give a download link for it?
Thanks

**Comment by MaybeShewill-CV** [comment]
@asimkymk old model weights are no longer supported:)

**Comment by asimkymk** [comment]
> @asimkymk old model weights are no longer supported:)

Hey thanks for reply. actally i want these files because of a ros project that is using your old version (https://github.com/AbangLZU/LaneNetRos). always getting an error just because of trying new model wights file.

**Comment by MaybeShewill-CV** [comment]
@asimkymk That ros repo use a old version of lanenet model weights which was no longer supported:)
