### ISSUE TITLE
似乎没有用bounded inverse class weighting处理不平衡？

### ISSUE THREAD

**Issue by phjhuang** [MaybeShewill-CV/lanenet-lane-detection#54]
Since the two classes (lane/background) are highly unbalanced, we apply bounded inverse class weighting, as described in [29].

由于目标类别是2类（车道/背景)高度不平衡（我的理解就是背景较车道线的像素多太多），我们应用 bounded inverse class weighting。

**Comment by MaybeShewill-CV** [comment]
@phjhuang 我在本地有应用过这个这个class weight这部分代码没有release，实际测试下来效果提高的比较有限
