### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'placeholder'

### ISSUE THREAD

**Issue by safal-305** [MaybeShewill-CV/lanenet-lane-detection#541]
File "G:\training\S\lane_detection\lanenet-lane-detection-master\lanenet-lane-detection-dependabot-pip-tensorflow-2.5.3\test_lanenet.py", line 87, in test_lanenet
    input_tensor = tf.placeholder(dtype=tf.float32, shape=[1, 256, 512, 3], name='input_tensor')
AttributeError: module 'tensorflow' has no attribute 'placeholder'

**Comment by MaybeShewill-CV** [comment]
@safal-305 use tensorflow 1.15

**Comment by codexsys-7** [comment]
it is because you haven't installed the dependencies required for the model to run, Make sure you have installed all the library versions properly.
