### ISSUE TITLE
Error generating tf_records.

### ISSUE THREAD

**Issue by codexsys-7** [MaybeShewill-CV/lanenet-lane-detection#543]
For the love of God, please tell me how did you train the model, I'm trying it for like past 3 days, I'm not even able to generate tf_records. Without tf_records I'm not able to train my model.
I'm getting an error. (ValueError: REPO_ROOT_PATH/data/training_data_example/tfrecords not exist, please check again)
Please reply ASAP MaybeSheWill.

**Comment by MaybeShewill-CV** [comment]
@codexsys-7 you need to convert your data into tfrecords first. You may get useful information in README file:)

**Comment by xinxinlv** [comment]
> 

I got the same error. My solution was: 
edit-config-tusimple_lanenet.yaml
![image-20220419200747516](https://user-images.githubusercontent.com/68861598/164127804-dc8ffa7b-3a27-4650-a345-67c47bc1919a.png)
then 
`python tools/make_tusimple_tfrecords.py`
