### ISSUE TITLE
训练自己的数据集出现nan

### ISSUE THREAD

**Issue by 12lvxiaofeng12** [MaybeShewill-CV/lanenet-lane-detection#544]
我在训练自己的数据时出现了一下的情况 Train loss: nan Train miou: nan Val loss: nan Val miou: nan...，每一个epoch都是如此
看了很多解决办法依旧无效，请问有什么解决方法吗，希望有人能解答我的问题，谢谢！

**Comment by MaybeShewill-CV** [comment]
@12lvxiaofeng12 对照readme和tusimple的数据集检查自己的数据，你这种情况极大概率就是制作标签的时候出错了。
