### ISSUE TITLE
Black mask_image

### ISSUE THREAD

**Issue by carlosdior** [MaybeShewill-CV/lanenet-lane-detection#545]
I tested the trained model and I've got a black musk image, could you help me plz?

**Comment by carlosdior** [comment]
ps it worked for ./data/tusimple_test_image/0.jpg but when I use another image it didnt

**Comment by MaybeShewill-CV** [comment]
@carlosdior postprocess was designed for tusimple image. You need to modify it if you want to use your own image. Simply you may directly visualize the segmentation mask result without postprocess:)

**Comment by carlosdior** [comment]
Thank you for your response,
when I tried to plot directly the instance segmentation I got
![image](https://user-images.githubusercontent.com/101120443/158151841-84c481e4-be45-472b-848a-063a9018e8bc.png)

**Comment by MaybeShewill-CV** [comment]
@carlosdior seems the model was not trained very well:)
