### ISSUE TITLE
圖片準確度與label比對應用

### ISSUE THREAD

**Issue by j2856256** [MaybeShewill-CV/lanenet-lane-detection#549]
您好：
我有在evaluate_model_utils.py上看到calculate_model_precision使用
但不了解要如何import，以及label_tensor輸入如何修正，可以提供該函式使用要修改的內容？

**Comment by j2856256** [comment]
而且使用Tusimple內的 test_label出現IndexError: list index out of range的錯誤發生

**Comment by j2856256** [comment]
![Screenshot from 2022-04-18 20-16-02](https://user-images.githubusercontent.com/103163006/163807053-b5424cd5-ec7e-476f-b2b8-7f2ea90fca2c.png)

**Comment by j2856256** [comment]
![Screenshot from 2022-04-18 20-18-13](https://user-images.githubusercontent.com/103163006/163807264-200fc8a5-8bd6-41fa-974b-2f9505f0d2e5.png)
![Screenshot from 2022-04-18 20-18-31](https://user-images.githubusercontent.com/103163006/163807267-966f412a-1011-4910-8895-99272071a8eb.png)
![Screenshot from 2022-04-18 20-18-41](https://user-images.githubusercontent.com/103163006/163807277-34114b7c-42f6-4903-9840-4e39909f1ea6.png)

附上程式代碼，麻煩幫忙解惑

**Comment by MaybeShewill-CV** [comment]
@j2856256 我这边这个计算准确率用的是比较朴素的方案，就是统计binaryseg中预测正确的点数 / 总点数。输入就是binaryseg的结果和对应的label。你要是测试tusimple的话可以上网搜tusimple benchmark，他们有专门的eval工具。

**Comment by j2856256** [comment]
不好意思因為我實在是程式新手
可以問一下要如何拿到binaryseg的结果和对应的label。可以提供完整的執行程式碼嗎

**Comment by MaybeShewill-CV** [comment]
@j2856256 这个你还是自己研究下吧：）
