### ISSUE TITLE
There is a method missed in LanenetCluster class

### ISSUE THREAD

**Issue by jinfagang** [MaybeShewill-CV/lanenet-lane-detection#55]
In test_lanenet_instance.py got error:

```
Traceback (most recent call last):
  File "tools/test_lanenet_instance.py", line 107, in <module>
    test_net(args.image_path, args.weights_path, args.net)
  File "tools/test_lanenet_instance.py", line 85, in test_net
    predict_color = cluster.get_instance_masks_image(ori_image=ori_image,
AttributeError: 'LaneNetCluster' object has no attribute 'get_instance_masks_image'

```

The method `get_instance_masks_image` is missed?

**Comment by jinfagang** [comment]
@MaybeShewill-CV Hi, may I ask the instance label, how to set the pixel value of each lane, just random using value between 1-255 or using the class index 1, 2, 3, 4, 5...?

**Comment by MaybeShewill-CV** [comment]
@jinfagang I use 30 50 70 90 110 to label different instance. You can any other color index to label different instance lane line.
