### ISSUE TITLE
rtx30 gpu and cuda11.3

### ISSUE THREAD

**Issue by shuyuanw** [MaybeShewill-CV/lanenet-lane-detection#550]
I'm trying to test the test_lanenet.py with GPU, however, it seems that the program can't find my cuda file although it exists. I used it from conda env with tensorflow1.15
![image](https://user-images.githubusercontent.com/59320330/164375552-7e10cf7a-619a-42c3-9aaf-5bb341efa022.png)
I checked the lib64 and it exists. Can anyone help?

**Comment by MaybeShewill-CV** [comment]
@shuyuanw Some Cuda relatived path were not correctly figured. You may find some help in stackoverflow:)
