### ISSUE TITLE
网络结构

### ISSUE THREAD

**Issue by haicaoha** [MaybeShewill-CV/lanenet-lane-detection#553]
您好，想问一下当选择bisenetV2作为网络结构时，encoder部分是哪些，decoder部分又是哪些？两个分支就是共用的哪些部分？下边是这里建造模型的代码
    def build_model(self, input_tensor, name, reuse=False):
        """

        :param input_tensor:
        :param name:
        :param reuse:
        :return:
        """
        with tf.variable_scope(name_or_scope=name, reuse=reuse):
            # build detail branch
            detail_branch_output = self.build_detail_branch(
                input_tensor=input_tensor,
                name='detail_branch'
            )
            # build semantic branch
            semantic_branch_output, _ = self.build_semantic_branch(
                input_tensor=input_tensor,
                name='semantic_branch',
                prepare_data_for_booster=False
            )
            # build aggregation branch
            aggregation_branch_output = self.build_aggregation_branch(
                detail_output=detail_branch_output,
                semantic_output=semantic_branch_output,
                name='aggregation_branch'
            )
            # build binary and instance segmentation branch
            binary_seg_branch_output = self.build_binary_segmentation_branch(
                input_tensor=aggregation_branch_output,
                name='binary_segmentation_branch'
            )
            instance_seg_branch_output = self.build_instance_segmentation_branch(
                input_tensor=aggregation_branch_output,
                name='instance_segmentation_branch'
            )
            # gather frontend output result
            self._net_intermediate_results['binary_segment_logits'] = {
                'data': binary_seg_branch_output,
                'shape': binary_seg_branch_output.get_shape().as_list()
            }
            self._net_intermediate_results['instance_segment_logits'] = {
                'data': instance_seg_branch_output,
                'shape': instance_seg_branch_output.get_shape().as_list()
            }
        return self._net_intermediate_results

**Comment by MaybeShewill-CV** [comment]
@haicaoha 这个你可以具体看一下原论文。然后对照着注释，注释里的分支名称基本都是按照论文来起的:)

**Comment by haicaoha** [comment]
请问是basenetV2的论文吗，我现在的主要问题是在lanenet论文里是编码-解码的网络结构，并且是两个分支网络；但是basenetV2的网络好像并不是编码-解码结构，并且好像二值分割和实例分割旨在最后网络尾部是不一样的，和lanenet论文中提到似乎不太一样，请问为什么这样设计网络呢







------------------ 原始邮件 ------------------
发件人:                                                                                                                        "MaybeShewill-CV/lanenet-lane-detection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月25日(星期一) 晚上6:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MaybeShewill-CV/lanenet-lane-detection] 网络结构 (Issue #553)





 
@haicaoha 这个你可以具体看一下原论文。然后对照着注释，注释里的分支名称基本都是按照论文来起的:)

**Comment by MaybeShewill-CV** [comment]
@haicaoha lanenet的网络模型也是可以修改的 binary seg和instance seg只要共享特征提取就可以了，至于特征提取你用什么网络结构都是可以实验测试的。我这里为了效率高就用了轻量网络bisenetv2
