### ISSUE TITLE
如何实现在 kitti 数据集训练

### ISSUE THREAD

**Issue by shaoxh** [MaybeShewill-CV/lanenet-lane-detection#554]
作者你好！
我想用你的 [训练好的模型](https://www.dropbox.com/sh/0b6r0ljqi76kyg9/AADedYWO3bnx4PhK1BmbJkJKa?dl=0)，直接在 kitti 上检测。但是你的程序识别后的图像尺寸会发生变化。我希望仍保持原始 kitti 的图像尺寸 1226×370。请问如何使用呢？
非常感谢！

**Comment by MaybeShewill-CV** [comment]
@shaoxh 没办法直接用 需要你自己修改postprocess的代码 或者你只做inference部分获取掩码图
