### ISSUE TITLE
Loading and running model using OpenCV's dnn module

### ISSUE THREAD

**Issue by daggarwa** [MaybeShewill-CV/lanenet-lane-detection#555]
Hi @MaybeShewill-CV Just wondering if you have tried uploading and running your model via [OpenCV's dnn module ](https://docs.opencv.org/4.x/d6/d0f/group__dnn.html#gad820b280978d06773234ba6841e77e8d) or have any experience doing that for another tensorflow model?

**Comment by MaybeShewill-CV** [comment]
@daggarwa Sorry no experiments have been done:)

**Comment by daggarwa** [comment]
@MaybeShewill-CV Do you plan to? Or can tell if anyone has successfully loaded the lanelet model using the readNetFromTensorFlow API? Getting this error currently:

```console
[ERROR:0] global /tmp/opencv/opencv-4.5.2/modules/dnn/src/dnn.cpp (3509) getLayerShapesRecursively OPENCV/DNN: []:(_input): getMemoryShapes() throws exception. inputs=1 outputs=0/0 blobs=0
[ERROR:0] global /tmp/opencv/opencv-4.5.2/modules/dnn/src/dnn.cpp (3515) getLayerShapesRecursively     input[0] = [ 1 3 416 416 ]
[ERROR:0] global /tmp/opencv/opencv-4.5.2/modules/dnn/src/dnn.cpp (3525) getLayerShapesRecursively Exception message: OpenCV(4.5.2) /tmp/opencv/opencv-4.5.2/modules/dnn/src/dnn.cpp:801: error: (-215:Assertion failed) inputs.size() == requiredOutputs in function 'getMemoryShapes'
```

**Comment by MaybeShewill-CV** [comment]
@daggarwa No plan to do that recently:)
