### ISSUE TITLE
关于remap的疑惑

### ISSUE THREAD

**Issue by mengpengfei** [MaybeShewill-CV/lanenet-lane-detection#562]
将图像转换为俯视图的矩阵不是hnet输出的吗，怎么还要用remap文件中的参数，这两个转俯视图参数什么区别

**Comment by MaybeShewill-CV** [comment]
@mengpengfei 我没用hnet而是使用了传统的几何方法完成俯视图变换:)

**Comment by mengpengfei** [comment]
你转成的俯视图是世界坐标下的俯视图还是像素坐标下的俯视图

**Comment by mengpengfei** [comment]
你是采用remap里面的相机外参转换的吗

**Comment by mengpengfei** [comment]
> @mengpengfei 对使用了相机的外参。具体你可以参考 https://ieeexplore.ieee.org/document/7734016

你用外参转过来的就是，世界坐标系下的坐标了吧，但是相机外参在车辆运动过程中是变化的，这个你考虑了没有

**Comment by MaybeShewill-CV** [comment]
@mengpengfei 这个可以通过相机和imu的外参关系进行全局坐标我的转换，但是这个不是我这个项目需要解决的问题:)
