### ISSUE TITLE
which backbone is better?

### ISSUE THREAD

**Issue by hitbuyi** [MaybeShewill-CV/lanenet-lane-detection#565]
There are two backbone nets used in  lanenet,VGG and BiseNetV2, which is better?   vgg is larger than BiseNetV2,so vgg is better in case not care about weight size?

**Comment by MaybeShewill-CV** [comment]
@hitbuyi BiseNetV2 is better. VGG is too old. Maybe you can try ocrnet or other sota segmentation architecture:)
