### ISSUE TITLE
not a valid checkpoint

### ISSUE THREAD

**Issue by gms2009** [MaybeShewill-CV/lanenet-lane-detection#568]
BiseNetV2_LaneNet_Tusimple_Model_Weights.zip 是用哪个 python 坂本创建的? 
ubuntu 16.04 python3.5 tensorflow 1.12.3   got error when run
python3 test_lanenet.py --weights_path model/tusimple/tusimple_lanenet --image_path data/tusimple_test_image/0.jpg
ValueError: The passed save_path is not a valid checkpoint: model/tusimple/tusimple_lanenet

model/tusimple has 4 files:
checkpoint                                 tusimple_lanenet.ckpt.index
tusimple_lanenet.ckpt.data-00000-of-00001  tusimple_lanenet.ckpt.meta

**Comment by MaybeShewill-CV** [comment]
@gms2009 --weights_path xxxx.ckpt

**Comment by gms2009** [comment]
working now, thanks
