### ISSUE TITLE
Val Loss Nan

### ISSUE THREAD

**Issue by pankaj251003** [MaybeShewill-CV/lanenet-lane-detection#569]
Training on Custom Data->taining data no. - ~10000 , Val data - ~ 500  -> Label data - binary 255 for lane and 0 for background  and instance  1,2 3, 4, 5,6,... for lane and 0 for background
Validity Loss coming Nan..  
But when training on small data around 100 and val data - 5 ...val loss is coming 
Please help sir  which parameter should I check

**Comment by MaybeShewill-CV** [comment]
@pankaj251003 refer to #116 #183
