### ISSUE TITLE
执行测试单个图像时报错

### ISSUE THREAD

**Issue by xxxy-931231** [MaybeShewill-CV/lanenet-lane-detection#57]
出现如下错误，希望可以给出一些意见
(py35) xieyan@xieyan-System-Product-Name:~/selfdriving/CNN-lane-detect/lanenet-lane-detection-master$ python tools/test_lanenet.py --is_batch False --batch_size 1 

I0906 15:52:30.105603 2092 test_lanenet.py:63] 开始读取图像数据并进行预处理
OpenCV Error: Assertion failed (ssize.area() > 0) in resize, file /opt/conda/conda-bld/opencv_1491943704081/work/opencv-3.1.0/modules/imgproc/src/imgwarp.cpp, line 3229
Traceback (most recent call last):
  File "tools/test_lanenet.py", line 253, in <module>
    test_lanenet(args.image_path, args.weights_path, args.use_gpu)
  File "tools/test_lanenet.py", line 67, in test_lanenet
    image = cv2.resize(image, (512, 256), interpolation=cv2.INTER_LINEAR)
cv2.error: /opt/conda/conda-bld/opencv_1491943704081/work/opencv-3.1.0/modules/imgproc/src/imgwarp.cpp:3229: error: (-215) ssize.area() > 0 in function resize

**Comment by MaybeShewill-CV** [comment]
@xxxy-931231 可以先确定一下图像输入有没有问题

**Comment by xxxy-931231** [comment]
你好 一开始我是用你的文件夹里data/tusimple_test_image/0.jpg这张图的 这张图是1280x720的 然后我把他就该成512,256还是报一样的错

我是修改的下面这个地方的地址 会不会是我这里修改错了

def test_lanenet(image_path, weights_path, use_gpu):
    """

    :param image_path:
    :param weights_path:
    :param use_gpu:
    :return:
    """
    assert ops.exists('data/tusimple_test_image/5.jpg'), '{:s} not exist'.format(image_path)

    log.info('开始读取图像数据并进行预处理')
    t_start = time.time()
    image = cv2.imread(image_path, cv2.IMREAD_COLOR)
    image_vis = image
    image = cv2.resize(image, (512, 256), interpolation=cv2.INTER_LINEAR)
    image = image - VGG_MEAN
    log.info('图像读取完毕, 耗时: {:.5f}s'.format(time.time() - t_start))

**Comment by MaybeShewill-CV** [comment]
@xxxy-931231 确认你的image_path传入值是否正确

**Comment by xxxy-931231** [comment]
我按照上面的格式执行会出现下面的错误
(py35) xieyan@xieyan-System-Product-Name:~/selfdriving/CNN-lane-detect/lanenet-lane-detection-master$ python tools/test_lanenet.py
usage: test_lanenet.py [-h] [--save_dir SAVE_DIR] [--use_gpu USE_GPU]
                       data/tusimple_test_image/0.jpg
                       model/tusimple_lanenet/tusimple_lanenet_vgg_2018-05-21-11-11-03.ckpt-94000
                       False 1
test_lanenet.py: error: the following arguments are required: data/tusimple_test_image/0.jpg, model/tusimple_lanenet/tusimple_lanenet_vgg_2018-05-21-11-11-03.ckpt-94000, False, 1

**Comment by MaybeShewill-CV** [comment]
@xxxy-931231 仔细看看readme文件
