### ISSUE TITLE
使用自己的图片测试，识别不出车道线

### ISSUE THREAD

**Issue by guodaoyi** [MaybeShewill-CV/lanenet-lane-detection#573]
![15](https://user-images.githubusercontent.com/32241606/202597024-d0c75563-9645-4628-be3f-a5bad08c2dcd.jpg)
麻烦问下，对输入图片有什么要求吗？使用自己的图片测试，识别不出车道线。

**Comment by MaybeShewill-CV** [comment]
@guodaoyi 需要自己适配后处理，可以直接看binaryseg和instance-seg的结果图：）

**Comment by MaybeShewill-CV** [comment]
![Screenshot from 2023-02-23 11-32-33](https://user-images.githubusercontent.com/15725187/220815738-4cfac614-d2a1-4bac-9d2a-76c71b4ea0e5.png)
