### ISSUE TITLE
Running the model without GPU

### ISSUE THREAD

**Issue by aghari19** [MaybeShewill-CV/lanenet-lane-detection#574]
Hello, 

I just want to run the trained model on the dataset to see how it performs. Is it possible to do that without a GPU. I downloaded the weights and put it in a folder and ran the following command: 
python tools/test_lanenet.py --weight_path weights/ --image_path ./data/tusimple_test_image/0.jpg

However, I get an error no module tensorflow and I cannot download it because I do not have a gpu. 

Is it possible to test the model without a GPU. Please let me know, 
Thank you, 
Haritha

**Comment by MaybeShewill-CV** [comment]
@aghari19 you may install a cpu version of tensorflow:)

**Comment by aghari19** [comment]
Thank you! I was able to test with one image and the algorithm works as expected. I am currently running the command provided in the readme for a single image. Is there a way I can run it on a folder of images and save the outputs to a folder. 

Please let me know, 
Thanks,

**Comment by MaybeShewill-CV** [comment]
@aghari19 You may have to modified the code urself:)

**Comment by aghari19** [comment]
Got it! Thank you for all the help!
