### ISSUE TITLE
Has anyone able to generate remap.yml for custom data ?

### ISSUE THREAD

**Issue by ajay1606** [MaybeShewill-CV/lanenet-lane-detection#575]
Hello everyone !

@MaybeShewill-CV, Thank you so much for sharing a very useful source. 
Able to get impressive lane segmentation results but post-processing needs to modify to work for custom data.

For custom datasets, need to provide `"ipm_remap.yml"`, though being able to generate an IPM image with `size 640 x 640 `, I have no idea, how to convert it to remap matrix format that is required in this code.

I have tried with "https://github.com/MaybeShewill-CV/Easy-Ipm-Client" repository as well but could get how to generate `tusimple_ipm_remap.yml` from this tool.

Could anyone please suggest, how can we generate `tusimple_ipm_remap.yml` for custom data !
Any response is much appreciated.

**Comment by MaybeShewill-CV** [comment]
@ajay1606 One way to solve this is to find ur own way do inverse perspective mapping. The other way is to design your method to do postprocess on front-view images.
