### ISSUE TITLE
Nan problem 

### ISSUE THREAD

**Issue by yousef-sbeih** [MaybeShewill-CV/lanenet-lane-detection#576]
Hello, 
When I train the model using your dataset and your config, I got all of results as nan 
So, I changed these parameters to : 
BATCH_SIZE: 2
VAL_BATCH_SIZE: 2
It worked for everything except validation results (loss and miou)
what should I do to make it work with a good results ?

**Comment by MaybeShewill-CV** [comment]
@yousef-sbeih refer to #183 #116
