### ISSUE TITLE
不太懂生成的结果分别是干什么的

### ISSUE THREAD

**Issue by InfiniteSamele** [MaybeShewill-CV/lanenet-lane-detection#577]
我训练途中不知道为什么断了，想从断掉的地方恢复训练的时候，发现这些文件都不是以ckpt结尾的，那这些文件都有什么用，我该用哪个恢复训练和做test？
储存的时候会有三份文件，格式如下：
tusimple_val_miou=0.5603.ckpt-168.data-00000-of-00001
tusimple_val_miou=0.5603.ckpt-168.index
tusimple_val_miou=0.5603.ckpt-168.meta
![B9D6B77F-CAC2-45D1-AE39-8B8E92E72CE4](https://user-images.githubusercontent.com/32623904/219526795-57c2c928-b82e-4d9c-af4c-2d378998061d.png)

**Comment by MaybeShewill-CV** [comment]
@InfiniteSamele 输入参数直接使用xxxx=0.5603.ckpt-168 就好了

**Comment by InfiniteSamele** [comment]
> @InfiniteSamele 输入参数直接使用xxxx=0.5603.ckpt-168 就好了

谢谢，不过我还有个想问的问题，我训练的时候i_loss大部份时候都是nan，连带着train loss也大部份时候都是nan，这会影响我最后测试模型吗（模型预标注）吗？如果影响的话我该怎么修改？（不好意思，我在CV这行是个新手，不是很懂那个discriminative_loss里面的一些参数是干什么的，不知道该怎么修改）

**Comment by MaybeShewill-CV** [comment]
@InfiniteSamele 会影响，下载完整的tusimple数据集试试。关于loss等于nan的问题，翻翻前面的issue，很多关于这个的解答。如果你的tusimple数据都准备正常，是不会出现loss等于nan的情况。
