### ISSUE TITLE
Can I divide the training into two stages?

### ISSUE THREAD

**Issue by cardwing** [MaybeShewill-CV/lanenet-lane-detection#58]
@MaybeShewill-CV  Hi, I wonder whether I can divide the training into two stages, i.e., first fix the pixel embedding branch and train the binary segmentation branch, then fix the binary segmentation branch and train the pixel embedding branch. Thanks a lot!

**Comment by MaybeShewill-CV** [comment]
@cardwing I find the union training process of binary segmentation and instance segmentation will lead to poor performance of the binary segmentation and what i am going to do is to divide the training into two stages and see if the performance will become better. Feel free to share the progress of this method

**Comment by cardwing** [comment]
@MaybeShewill-CV , thanks. I will report the results here, after which I will close the issue.

**Comment by MaybeShewill-CV** [comment]
@cardwing Thanks a lot

**Comment by MaybeShewill-CV** [comment]
Hahaha because this part of the code could be reused from my last work. The leader pushed me hard so I reused that backbone. I am wondering if the model could perform better if another kind of backbone was used. Once i got any progress i will release the code.:)

**Comment by cardwing** [comment]
@MaybeShewill-CV , really appreciate your hard work. Besides, I have tested the two-stage training strategy and unfortunately, it performs badly. The problem lies in the second stage, i.e., the clustering loss does not decrease (see the following figure). I think the reason is that the parameters of the clustering branch are limited (only a 3x3 convolution layer). Moreover, the 16 x 16 deconvolution layer is not rational due to the large kernel size. I think maybe using the original ENet model may be more suitable for the two stage training strategy. That is my analysis. Thanks!
![result](https://user-images.githubusercontent.com/23656119/45585908-b8c76480-b91f-11e8-877d-f6f5d8b6ddcb.png)

**Comment by cardwing** [comment]
Besides,  the first three figures are the binary segmentation result, the instance segmentation result and the mask. It is obvious that the binary segmentation result is good while the instance segmentation result is bad (the lane pixels are not differentiated, i.e., have different colors, like the fourth figure). 
![0new_bin](https://user-images.githubusercontent.com/23656119/45586104-8586d480-b923-11e8-985a-f750301792a5.png)
![0new_ins](https://user-images.githubusercontent.com/23656119/45586106-8b7cb580-b923-11e8-8803-d71330928760.png)
![0new_mask](https://user-images.githubusercontent.com/23656119/45586108-8e77a600-b923-11e8-8388-022565df3481.png)
![instance_ret](https://user-images.githubusercontent.com/23656119/45586112-9cc5c200-b923-11e8-94f3-d96240d2e01b.png)

**Comment by cardwing** [comment]
@MaybeShewill-CV , since two-stage training strategy does not work for vgg-16 / densenet + fcn model, I will re-implement the ENet model and check if it works. I will close this issue and more results will be provided if I make any progress. Thanks for your patient response.

**Comment by MaybeShewill-CV** [comment]
@cardwing Ok looking forward to your future work. I will try to implement a scnn for lane detection and check if it works better than the lanenet model
