### ISSUE TITLE
关于一个疑问

### ISSUE THREAD

**Issue by flinzhao** [MaybeShewill-CV/lanenet-lane-detection#587]
作者你好，这个模型是否可以应用到无人机航拍视角（俯拍）的车道线检测？
像下面这种图像
![h_120_v_10_1 4x_0044_D-00094](https://github.com/MaybeShewill-CV/lanenet-lane-detection/assets/103496889/f9c3bc1f-a68c-4502-8506-855768c0ea19)

**Comment by MaybeShewill-CV** [comment]
@flinzhao 不可以直接使用提供的预训练模型。需要你重新训练模型并修改目前的后处理逻辑:)

**Comment by flinzhao** [comment]
后处理需要做哪些？聚类和拟合吗？🤔

**Comment by MaybeShewill-CV** [comment]
@flinzhao 对:)

**Comment by liuyunjie123ffrgrdrgdrdg** [comment]
No module named 'lanenet'

**Comment by MaybeShewill-CV** [comment]
@liuyunjie123ffrgrdrgdrdg export project's root dir to your PYTHONPATH env variables:)
