### ISSUE TITLE
一个致命的问题

### ISSUE THREAD

**Issue by superggfun** [MaybeShewill-CV/lanenet-lane-detection#588]
我使用Conda安装的Python3.7版本，并使用 ’pip3 install -r requirements.txt‘ 运行库。当在使用 ‘D:\Alphay\Desktop\lanenet-lane-detection-master>python tools/test_lanenet.py --weights_path ./weight/lanenet --image_path ./data/tusimple_test_image/0.jpg' 测试的时候遇到报错'Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found'。我使用的Cuda12.3 bin路径中确实没有这个文件，怎么办？我认为可能是tensorflow_gpu==1.15.0版本的问题，当我把它升级到了2.x就没有这个报错了，但是又是另外的问题，真的很烫手。

**Comment by MaybeShewill-CV** [comment]
@superggfun 环境安装的问题 尤其是windows上的问题 你可以在google或者baidu上搜索一下：）

**Comment by superggfun** [comment]
我觉得不是环境问题，是版本问题
