### ISSUE TITLE
训练模型报错，tusimple_train.tfrecords not exist

### ISSUE THREAD

**Issue by welloncn** [MaybeShewill-CV/lanenet-lane-detection#589]
运行代码训练模型s时候报错：
tensorflow 1.15.0
`python tools/train_lanenet_tusimple.py
`![image](https://github.com/MaybeShewill-CV/lanenet-lane-detection/assets/4989505/c76d14b4-e2b2-4fcc-92bd-097437e36e04)

**Comment by MaybeShewill-CV** [comment]
@welloncn 看一下README里面的Data Preparation 先生成tfrecords文件再训练模型：）
