### ISSUE TITLE
 No module named 'lanenet_model

### ISSUE THREAD

**Issue by cnu-Dawn** [MaybeShewill-CV/lanenet-lane-detection#590]
我已经添加了export PYTHONPATH="${PYTHONPATH}:your_path/lanenet-lane-detection/lanenet_model" 可是为什么还是找不到

**Comment by MaybeShewill-CV** [comment]
@LoveMYChen 用你本地的真实路径代替 “your_path”，而不是输入原样的命令:)

**Comment by cnu-Dawn** [comment]
> @LoveMYChen用你本地的真实路径代替“your_path”，而不是输入原样的命令:)

已经替换了本地路径 才报错没有lanenet_model 的模块

**Comment by MaybeShewill-CV** [comment]
@LoveMYChen export PYTHONPATH=YOUR_PATH:$PYTHONPATH 再仔细检查下你的输入路径。命令启动需要在项目根目录下启动：）

**Comment by cnu-Dawn** [comment]
感谢

> @LoveMYChenexport PYTHONPATH=YOUR_PATH:$PYTHONPATH 再仔细检查下你的输入路径。命令启动需要在项目根目录下启动：）

感谢
