### ISSUE TITLE
ValueError: Cannot feed value of shape

### ISSUE THREAD

**Issue by bleedingfight** [MaybeShewill-CV/lanenet-lane-detection#6]
Thanks for your share,I want to use your model to train my data,but raise some error:
`ValueError: Cannot feed value of shape (1, 256, 512, 3) for Tensor 'instance_input_label:0', which has shape '(?, 256, 512)'`,my works include:
- draw different color on black background for instance segmentation(three channel),for example(10,10,10),(20,20,20),(30,30,30)...
- draw white line on lane otherwise black(0,0,0),(255,255,255),(I try to use json file to draw line and then use cv2.imwrite to save,when i read the image,inspecte it's shape,it's channel is 3 even if the black backgroud is zeros(720,1280),3 channel image data is ok?).
- generator data list  for example:`/xxx/image /xxx/gt_gray/gt_instance` in train.txt and val.txt
when i try to train from scrach,the code raise the error,if you can you tell me which step is error,i will appreciate for you help,thanks for your share too.
@MaybeShewill-CV

**Comment by MaybeShewill-CV** [comment]
@bleedingfight All my label image is stored in gray scale

**Comment by bleedingfight** [comment]
@MaybeShewill-CV sorry i understand it,IMREAD_COLOR flag set it to read to be 3 channel,but in you code,i can see imread's flag is setted to cv2.IMREAD_COLOR,Can i understand it that you save the instance and gray image as gray image but in code you read it as three chennel color image,but i save the gray image and instance image as three channel(it is true color image),and i imread it as 3 three color,so it my code raise error?

**Comment by MaybeShewill-CV** [comment]
@bleedingfight You may use the CV_IMREADUNCHANGED flag

**Comment by bleedingfight** [comment]
@MaybeShewill-CV  thanks for your kind help
i read the imread's flag:

IMREAD_UNCHANGED | If set, return the loaded image as is (with alpha channel, otherwise it gets cropped).
-- | --
IMREAD_GRAYSCALE | If set, always convert image to the single channel grayscale image.
IMREAD_COLOR | If set, always convert image to the 3 channel BGR color image.
IMREAD_ANYDEPTH | If set, return 16-bit/32-bit image when the input has the corresponding depth, otherwise convert it to 8-bit.
IMREAD_ANYCOLOR | If set, the image is read in any possible color format.
IMREAD_LOAD_GDAL | If set, use the gdal driver for loading the image.

i can see IMREAD_UNCHANGED is set read as origin bit,but in your code,i can see:
train_lanenet.py 108 line:
`label_img = cv2.imread(gt_label_path, cv2.IMREAD_COLOR)`
My understand is even if gt_label_path is 1 channel's grayscale image,but i read is as 3 channel,which step my understand is wrong?

**Comment by MaybeShewill-CV** [comment]
@bleedingfight The label is divided into binary label and instance label. You may check the data_provider file

**Comment by bleedingfight** [comment]
@MaybeShewill-CV  thank for your help,i thinks i found the reason
i read the instance demo image of your gt_image_instance,if i use IMREAD_UNCHANGED,the image be imread as (720,1280),Is it that grayscale image be read with flag IMREAD_UNCHANGED,it will be 1 channel,because of the flag changed default IMREAD_COLOR,so imread can read as image's bit instead of BGR image.

**Comment by MaybeShewill-CV** [comment]
@bleedingfight Yes the default cv2.imread type is color image

**Comment by bleedingfight** [comment]
@MaybeShewill-CV  my code raise error for loss is nan,i check my image,i found that my resized image's pixle be changed for interpolation,i think it may be the reason of my error,so i have two question:
1,if my image have different size i can use the code?(1920x1080,1280x1080)
2. if my image too small I can use the code?(224,224)
I'am sorry to waste your precious time,thanks for your help

**Comment by MaybeShewill-CV** [comment]
@bleedingfight Since the model is based on fully convolution network the image shape will not be the problem you can feed the model with any image of any shape. Maybe you should use the nearest interpolation method when you change the size of your label image.

**Comment by bleedingfight** [comment]
@MaybeShewill-cv，thanks for your kind。
I try it in train-lanenetshell.py，alter the only not is nearest interpolate to nearest 。but the result is same。loss nan。I try to
decease the lrto0.00000001,itcan. output. some epoch and then. loss nan。have some other way to avoid it.by the. way,tools include three train*,all can be 
use to. train. my. model? or. i. can. delete. instanse. segmentation?

**Comment by MaybeShewill-CV** [comment]
@bleedingfight You can also only train the binary segmentation branch if you don not care the lane instance

**Comment by bleedingfight** [comment]
@MaybeShewill-CV
It's means that. i use. git. checkout. to a branch(binary) to train or just. run. lanenet_binary_segmentation.py

**Comment by MaybeShewill-CV** [comment]
@bleedingfight What i mean is the model's binary segmentation brance can be trained alone to detect the lanes but it can not recognize each lane instances. You can read the origin paper for details

**Comment by y11203090135** [comment]
@bleedingfight 
请问：为什么训练您的数据集时，在图片预处理
label_img = cv2.imread(gt_label_path, cv2.IMREAD_UNCHANGED)时，可以将
(720, 1280, 3)变为(720, 1280)
我用自己的训练集，处理之后
(720, 1280, 3)还是(720, 1280，3)
这是什么原因呢？

**Comment by bleedingfight** [comment]
@y11203090135 数据是作者MaybeShewill-cv的，他说要处理成灰度图，你说的处理后的是指哪里？查看一下文档说明，我好久没弄这个了，按照说明一步步弄是可以的，我之前试过只是损失nan没法解决后来没弄了！

**Comment by y11203090135** [comment]
@bleedingfight  可以了，thank you!

**Comment by chaine09** [comment]
@y11203090135 can you translate in english?
