### ISSUE TITLE
NotFoundError (see above for traceback): Key lanenet_loss/inference/encode/conv1_1/bn/beta not found in checkpoint

### ISSUE THREAD

**Issue by 131404060321** [MaybeShewill-CV/lanenet-lane-detection#60]
你好，当我用自己训练的模型进行测试(test_lanenet.py)的时候，出现了这样的错误：NotFoundError (see above for traceback): Key lanenet_loss/inference/encode/conv1_1/bn/beta not found in checkpoint
是不是因为我用了dense net（我是从头开始训练的）作为我的训练模型的缘故？

**Comment by MaybeShewill-CV** [comment]
@131404060321 如果你没有加载预训练参数那么不应该有这样的问题啊,这个问题说的是在预先保存的图文件里没有找到这个名字的节点

**Comment by 131404060321** [comment]
感谢你的及时回复。我是在测试时加载自己训练的模型的时候报的错，可能是我训练时用的是dense net的模型，而测试模型的默认好像是vgg net。我把测试时用的net_flag改为dense就不再报错了。

**Comment by MaybeShewill-CV** [comment]
默认是vgg哈
