### ISSUE TITLE
tusimple数据集的accuracy能训到多少

### ISSUE THREAD

**Issue by Derteanoo** [MaybeShewill-CV/lanenet-lane-detection#61]
我将tusimple标注过的数据集按4：1的比例分成train和val。train_accuracy能到90%以上，但val_accuracy始终超不过60%。

**Comment by MaybeShewill-CV** [comment]
@Derteanoo 在验证集合上的accuracy能达到91.5%，并不能达到论文里提到的96.2%，我想这部分应该是由于基础网络不同和Hnet的关系。

**Comment by MurphyChengIsMe** [comment]
@MaybeShewill-CV 想請問作者在分割該數據集的時候是按照多少比例進行分割的呢? 還有想問一下在測試集達到91.5%的結果，訓練時的val accuracy約在多少呢?

**Comment by MaybeShewill-CV** [comment]
@MurphyChengIsMe 数据集就是tusimple的数据集 它已经把训练集和测试集分开了。具体的可以去看tusimple的介绍。我说的91.5%就是在tusimple的测试集上。

**Comment by MurphyChengIsMe** [comment]
@MaybeShewill-CV 好的我了解了，謝謝您

**Comment by MaybeShewill-CV** [comment]
@MurphyChengIsMe 好的 欢迎分享结果：）
