### ISSUE TITLE
数据标注问题

### ISSUE THREAD

**Issue by vsendes** [MaybeShewill-CV/lanenet-lane-detection#62]
你好，我想用自己的数据集进行训练，请问数据是用什么方法标注的呢？

**Comment by MaybeShewill-CV** [comment]
@vsendes tusimple数据集是在车道线上打点 然后自处理将这些点自己连接成车道线生成训练数据集的。具体信息你可以参考tusimple lane dataset哈

**Comment by MaybeShewill-CV** [comment]
@yanzistudio tusimple数据集只是在通过打点的方式来记录车道线，这些点是不是在车道线的中间位置我没有确定过。至于车道线的宽度，在你制作数据集的时候需要自己设置你连接的polyline的宽度，你设置的这个宽度就是每一根车道线的宽度。

**Comment by yanzistudio** [comment]
@MaybeShewill-CV 感谢回复！所以这个车道线的宽度是我们自己预先设置好的哈，明白。还有一个问题想请教一下，你觉得类似的方法如果用在top-view的地图的车道线检测的话，效果会好吗？我们的网络可以准确区分车道线和其他lane marker(比如箭头)吗？再次感谢！

**Comment by MaybeShewill-CV** [comment]
@yanzistudio 俯视图的话也没有问题哈  需要你有相应的标注就可以

**Comment by yanzistudio** [comment]
@MaybeShewill-CV 好的，感谢回复！也感谢你分享代码:)

**Comment by yinhai86924** [comment]
车道线宽度指的是每个点的横坐标吗

**Comment by MaybeShewill-CV** [comment]
@yinhai86924 不是 是指描述这个车道线的多段线的宽度 cv2.polyline中的width参数:)

**Comment by yinhai86924** [comment]
谢谢你的回复，我看了readme中介绍说你训练完一次数据是200000张图片，图森的训练集只有3626X20=72520张图片，且图森的训练集每个视频切片只有20帧，并且只有最后一帧标注了，可以生成训练所要求的二值图以及实例分割图，其他19帧没有标注，无法生成，想问一下我们训练的时候其他19帧都参加了训练吗？还是只有最后一帧进行了训练，如果是这样实际参加训练的图片只有3626张是吗，epochs数据等于200000怎么取的  每次迭代用了多少张图片，谢谢 我现在是初学者！向您请教了

**Comment by MaybeShewill-CV** [comment]
@yinhai86924 是迭代了那么多次 不是用了那么多图像:)
