### ISSUE TITLE
训练结果 ：train_accuracy 0.83左右   val_accuracy不超过0.7

### ISSUE THREAD

**Issue by 131404060321** [MaybeShewill-CV/lanenet-lane-detection#64]
我用dense net重头开始训练的，但结果并不理想。我看你给出的训练模型刚开始的accuracy就在0.9之上的，这是你用 vgg16 初始化的结果还是你是在你之前训练模型的基础上开始训练的结果呢？

**Comment by MaybeShewill-CV** [comment]
@MaybeShewill-CV readme里面说到的模型是基于vgg网络训练 vgg初始化参数是用imagenet训练的参数初始化的。如果你想选择使用densenet最好能找到一个比较好的初始化参数

**Comment by 131404060321** [comment]
您是说直接用vgg的参数初始化encode部分就能得到0.9左右的accuracy吗？还有就是我该如何做才能为dense net找到一个比较好的初始值？用一个固定不变的相对较大的学习率预训练出一个初始化参数模型吗？

**Comment by MaybeShewill-CV** [comment]
@131404060321 是的 直接使用vgg参数初始化encoder部分 然后整个encoder decoder部分使用vgg网络。dense net初始值可以使用imagenet数据集训练的参数作为初始化参数。
