### ISSUE TITLE
cost is nan

### ISSUE THREAD

**Issue by JiHoonYu** [MaybeShewill-CV/lanenet-lane-detection#65]
I have a problem to train my dataset.
training is stopped with nan

![binary_label](https://user-images.githubusercontent.com/43312134/46584090-220f4300-ca9a-11e8-95b7-0ac32d900336.png)
![instance_label](https://user-images.githubusercontent.com/43312134/46584091-23d90680-ca9a-11e8-9918-460833f33b19.png)

there are my training dataset
both images are made using matlab. 
lane markers  are represented as 255 in binary image.
in instance image, lane markers are represented as 20, 70, 120 and 170 respectively.
I just wonder whether my dataset is wrong or I have to tune the hyperparameters such as delta v, delta d

![image](https://user-images.githubusercontent.com/43312134/46584310-c4302a80-ca9c-11e8-8b6e-540cf39ab05a.png)
there is a my training progress

please get some help.

**Comment by MaybeShewill-CV** [comment]
@JiHoonYu Did you train the model based on the tusimple lane dataset?

**Comment by JiHoonYu** [comment]
@MaybeShewill-CV I use mixed dataset that has tusimple dataset and CUlane dataset.
also I try to train scratch using both vgg16 weights and your pretrained weights

**Comment by MaybeShewill-CV** [comment]
@JiHoonYu This may be caused by the super parameters. You may alse see this #33
