### ISSUE TITLE
Generating binary segmentation label file and instance segmentation label file

### ISSUE THREAD

**Issue by Raj7kumar7** [MaybeShewill-CV/lanenet-lane-detection#68]
I have several images of lane.Now i want to use them to train my  own model but i don't know how to create  binary segmentation label file and instance segmentation label file.Is there any tool to label them or how to do it?
Kindly help

Regards

**Comment by MaybeShewill-CV** [comment]
@Raj7kumar7 You may check the tusimple lane dataset and it's readme file to get some help:)

**Comment by chaine09** [comment]
@MaybeShewill-CV  Can you provide the link to the tusimple lane dataset? Thanks

**Comment by chaine09** [comment]
@MaybeShewill-CV I still can't figure out how to generate the instance and binary images from https://github.com/TuSimple/tusimple-benchmark/blob/master/doc/lane_detection/readme.md. Still reading the repo.

Can I just create an image similar to these? And just convert it to grayscale?
