### ISSUE TITLE
关于VGG_MEAN

### ISSUE THREAD

**Issue by 131404060321** [MaybeShewill-CV/lanenet-lane-detection#69]
VGG_MEAN表示的是训练集上像素的平均RGB的值，而代码是直接令：VGG_MEAN = [103.939, 116.779, 123.68]  该值显然不是训练样本的均值，这个应该会对训练结果有影响吧？还是说所有的样本都大致符合这种分布？

**Comment by MaybeShewill-CV** [comment]
@131404060321 这个数据是imagenet数据集的平均值。因为imagenet数据集的数据规模比较大，如果使用训练数据的均值会影响泛华能力

**Comment by 131404060321** [comment]
OK, I get it
