### ISSUE TITLE
how to solve the import error?

### ISSUE THREAD

**Issue by YgRen** [MaybeShewill-CV/lanenet-lane-detection#7]
when I run the command python tools/train_lanenet.py, the error as follows: from config import global_config ImportError:no moudle named 'config'
can you tell me how to solve the import error? thx!

**Comment by zijianzhang** [comment]
求问这个问题解决了嘛

**Comment by MaybeShewill-CV** [comment]
@zijianzhang Add all the module to your PATHONPATH or you can use the sys.path.append function:)

**Comment by HussainGhazaly** [comment]
how to add them to PATHONPATH
