### ISSUE TITLE
ImportError: No module named 'glog'

### ISSUE THREAD

**Issue by Raj7kumar7** [MaybeShewill-CV/lanenet-lane-detection#70]
Even though i have install glog using pip .I am still getting error as ImportError: No module named 'glog'.
Can you help me in solving it?

Regards

**Comment by MaybeShewill-CV** [comment]
@Raj7kumar7 If you are using python3 then you may install glog by sudo pip3 install glog

**Comment by Pari-singh** [comment]
I tried installing glog all the possible ways, through pip3, conda, apt-get and none works. glog is shown to be installed in the environment but is unaccessible to use by python for some reason. Could you shed some light how you installed it, as I see even outside this repo, people are finding it difficult to get glog work.

Thanks

**Comment by nisha1729** [comment]
This might help: https://github.com/benley/python-glog/issues/8
