### ISSUE TITLE
How many images did you train with?

### ISSUE THREAD

**Issue by Toraudonn** [MaybeShewill-CV/lanenet-lane-detection#71]
I'm trying to train with the TuSimple dataset and I was wondering how many total images you used to train the model.
I looked through the json file and found that there are only 3626 annotated images in the training_data.
If you used more data, did you use the other 19 frames in each clips?

Thanks in advance!

**Comment by MaybeShewill-CV** [comment]
@Toraudonn The model was trained on the whole 3626 annotated images in tusimple dataset.

**Comment by Toraudonn** [comment]
@MaybeShewill-CV So, no more training data? Thanks!
