### ISSUE TITLE
The current implementation does not seem to be using HNET?

### ISSUE THREAD

**Issue by spolu** [MaybeShewill-CV/lanenet-lane-detection#75]
Hi! Very nice work.

I believe from reading your code that you're not using HNET + polynomiual fit. Any rationale as to why you're not fitting the output of the clustering?

**Comment by MaybeShewill-CV** [comment]
@spolu Because I found the HNet seems not converge in my experiment. I have not got enough
 spare time for this recently I will complete it afterwards.

**Comment by spolu** [comment]
Good to know, I'll keep an eye out!

**Comment by MaybeShewill-CV** [comment]
@spolu You're welcome

**Comment by mikeedi** [comment]
Can you provide code for training hnet?

**Comment by MaybeShewill-CV** [comment]
@mikeedi Since I have my own ipm module there is not enough time for updating this. I will update it once I got enough spare time.
