### ISSUE TITLE
bounded inverse class weighting

### ISSUE THREAD

**Issue by gismo07** [MaybeShewill-CV/lanenet-lane-detection#8]
In the _Towards End-to-End Lane Detection: an Instance Segmentation Approach_ paper there is mentioned, that to balance the binary training a bounded inverse class weighting is used.

Did you also used that technique?

**Comment by MaybeShewill-CV** [comment]
@gismo07 That technique has not been used in this implementation yet I will release the complete version in the future.

**Comment by gismo07** [comment]
Ok thats nice. Thank you!
