### ISSUE TITLE
为什么代码中训练的时候是用的CPU

### ISSUE THREAD

**Issue by wcg5262** [MaybeShewill-CV/lanenet-lane-detection#80]
想请教一下作者，代码中训练部分为什么换成了CPU，验证部分也是CPU？

**Comment by MaybeShewill-CV** [comment]
@wcg5262 训练依然是使用GPU资源啊==！ 你可以查看train脚本

**Comment by wcg5262** [comment]
@MaybeShewill-CV 可是您代码中train.py的214行之后不还是进行训练吗。。  我是个初学者  还望您解答

**Comment by MaybeShewill-CV** [comment]
@wcg5262 train_lanenet.py文件的214行没有任何和cpu或者gpu设置有关系的东西，你更新代码了吗。或者直接贴你的截图

**Comment by wcg5262** [comment]
![Uploading 图片.png…]()

**Comment by wcg5262** [comment]
更新代码了  就是上周您发的代码

**Comment by wcg5262** [comment]
啊 我自己加了一些注释 可能代码的行数跟您的不一样  我说的是您原代码的200行之后

**Comment by wcg5262** [comment]
@MaybeShewill-CV

**Comment by wcg5262** [comment]
@MaybeShewill-CV 更新代码了 就是上周您发的代码  我自己加了一些注释 可能代码的行数跟您的不一样 我说的是您原代码的200行之后  就是您注释的# training part 之后

**Comment by MaybeShewill-CV** [comment]
@wcg5262 只是把data feed pipline放在cpu上处理了 整个的训练过程还是在gpu上。

**Comment by wcg5262** [comment]
@MaybeShewill-CV  好 我再研究下代码 谢谢您的解答  还有个问题  如果我想增大数据集 比如加一些CUlane的图片 我首先要做json文件是吗？

**Comment by MaybeShewill-CV** [comment]
@wcg5262 不一定要做json文件 只要找一种形式能记录你标注的结果就可以 你记在文本文件里也可以 只要你自己看得懂就可以啦：）

**Comment by wcg5262** [comment]
@MaybeShewill-CV  好的 谢谢指点
