### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by liulang201** [MaybeShewill-CV/lanenet-lane-detection#81]
你好，我试图去阅读你的代码，可是关于lanenet_data_processor里面有一些不明白的地方，请问你那儿有一份比较详细的注释么

**Comment by MaybeShewill-CV** [comment]
@liulang201 这个就是我本地的代码 那个代码逻辑很简单 就是从train.txt文件中获取文件列表 然后实现一个循环方法可以不断调用next_batch方法：）

**Comment by MaybeShewill-CV** [comment]
@liulang201 嗯, 是用了tusimple的数据，样本可以根据tusimple的readme说明来制作，那个说明文件会教你怎么把标注的车道线点对应在原始图像上。

**Comment by MaybeShewill-CV** [comment]
@liulang201 可以留个邮箱我发readme给你

**Comment by liulang201** [comment]
2276956434@qq.com,很感谢

**Comment by MaybeShewill-CV** [comment]
@liulang201 发给你了

**Comment by liulang201** [comment]
很感谢
