### ISSUE TITLE
Color

### ISSUE THREAD

**Issue by teaddicted** [MaybeShewill-CV/lanenet-lane-detection#82]
Hey,

In the previous model the embedding image used to be like this:
![screenshot from 2018-10-30 17-04-05](https://user-images.githubusercontent.com/26036961/47716945-0268d600-dc66-11e8-8eea-fe8c16539d83.png)

But now, the color range is changed:
![screenshot from 2018-10-30 17-03-25](https://user-images.githubusercontent.com/26036961/47716944-01d03f80-dc66-11e8-8168-79166cbc9eee.png)

Can you please tell me if there's any way to go back to the same r-g-b color range? I'm trying to apply image processing on these images to see if any post-processing on them can be of any use.

Thanks

**Comment by MaybeShewill-CV** [comment]
@teaddicted The embedding result is a mat with 4 channels according to the new model and the old model's embedding dimension is 3. The number of embedding dimensions can be any number so the embedding result is not a tradition image with r-g-b channel it is a feature map instead. If you want to use the origin model's embedding result you need to go back to the old code and download the old model weights file:)

**Comment by teaddicted** [comment]
@MaybeShewill-CV Ahan got it. Btw, did you see any significant change in accuracy between 94k and 200k epochs' models?

**Comment by MaybeShewill-CV** [comment]
@teaddicted The 200K model performs slightly better than the 94K but the new model's training process is more stable and will not got stuck in nan loss easily

**Comment by teaddicted** [comment]
@ MaybeShewill-CV gotchya thanks...I'll wait for the CULane model :)
