### ISSUE TITLE
我看你代码中的instance loss 包括了背景0，但感觉论文中是不包含的

### ISSUE THREAD

**Issue by sunybhog** [MaybeShewill-CV/lanenet-lane-detection#83]
我看你代码中的instance loss 包括了背景0，但感觉论文中是不包含的背景？

**Comment by MaybeShewill-CV** [comment]
@sunybhog 如果不需要背景 那么在没有背景掩码的测试图上你觉得应该如何区分车道线和非车道线呢？你也可以参考这个文章https://arxiv.org/pdf/1708.02551.pdf：）

**Comment by MaybeShewill-CV** [comment]
@sunybhog 如果不需要背景 那么在没有背景掩码的测试图上你觉得应该如何区分车道线和非车道线呢？你也可以参考这个文章https://arxiv.org/pdf/1708.02551.pdf ：）

**Comment by zhangcheng999** [comment]
你好，我也有这个疑问，instance loss中计算不同车道线距离的l_dist是从mu一步步得到的，而这个mu里面是包含了背景向量的，我看论文里面是说“With C denoting the number of clusters (lanes)...”，不过我更改为只计算车道线的距离后发现训练和之前没有太大的区别。就是一直以来都是loss为nan的问题，我按照您最新的代码更改了优化方法，loss阈值等，还是有nan的情况，而且每次都是l_dist是nan，但是把nan保存的embedding和instance label拉出来单独测l_dist是有值的，不知道为啥，我用的模型是resnet50，数据是culane+tusimple

**Comment by MaybeShewill-CV** [comment]
@zhangcheng999 单独训练某一个数据集也会出现nan的情况吗？ 如果单独训练tusimple的数据集也会出现nan的情况 那可能你得检查你的resnet50模型，或者给resnet50一个比较好的初始值。我自己训练culane至今为止还没有出现nan的情况哈：）

**Comment by zhangcheng999** [comment]
谢谢回复～之前用VGG训tusimple是没有问题的，我再试试用resnet单独训一训tusimple

**Comment by MaybeShewill-CV** [comment]
@zhangcheng999 嗯 单独训练我觉得应该是问题不大的

**Comment by HanqingXu** [comment]
> @zhangcheng999 单独训练某一个数据集也会出现nan的情况吗？ 如果单独训练tusimple的数据集也会出现nan的情况 那可能你得检查你的resnet50模型，或者给resnet50一个比较好的初始值。我自己训练culane至今为止还没有出现nan的情况哈：）
@MaybeShewill-CV 你好，我最近使用cityscape数据集希望进行多类的车道线实例分割，也是一直出现NAN问题。我用控制变量的方法确定是l_var的问题.现在进行训练,最后发现语义分割的损失函数变成无穷，实例分割损失函数中：l_var 为0，l_dist为nan ,l_reg 也是0。其他具体表现1.实例分割层和语义分割层的共享层都会变成无穷，pixel_embedding之后经过了一层relu,所有层数的值都变成了0。2.将训练的数据集使用单张数据，程序可以跑通
请问有类似的经历吗

**Comment by MaybeShewill-CV** [comment]
@HanqingXu 没有处理过你说这种情况。
