### ISSUE TITLE
cv.resize图片大小

### ISSUE THREAD

**Issue by liulang201** [MaybeShewill-CV/lanenet-lane-detection#87]
你好，你的代码中，图片resize大小以后，标签和原始的图片中的像素点还能匹配的上么，我使用pytorch改写的代码后，在训练过程中遇到了这个问题

**Comment by MaybeShewill-CV** [comment]
@liulang201 resize大小都变了肯定匹配不上了。。。。 或者我可能没懂你的意思：）

**Comment by liulang201** [comment]
这个问题可能有点幼稚，我的意思是原始图片和gt_binary图片resize以后，每个像素点的标签对应不上，是怎么进行一个训练的，怎么还原为原始图像大小

**Comment by MaybeShewill-CV** [comment]
@liulang201 先按照原图大小生成图像然后再缩放就好了

**Comment by liulang201** [comment]
可是resize之后会损失标记信息

**Comment by liulang201** [comment]
比如720*1280的图片，缩小为360*640以后，会损失一些像素点，而这些像素点可能包含了标记信息

**Comment by MaybeShewill-CV** [comment]
@liulang201 但是对应的原始图像也进行相应的缩放了啊，只要label和原始的图像能够对应上就可以:)
