### ISSUE TITLE
Generating `gt_image_instance` and `gt_image_binary`

### ISSUE THREAD

**Issue by chaine09** [MaybeShewill-CV/lanenet-lane-detection#88]
The original images for `gt_image_instance` and `gt_image_binary` I generated are in RGB format. Which is why I got this error initially:

> ValueError: Cannot feed value of shape (2, 256, 512, 3) for Tensor 'instance_input_label:0', which has shape '(2, 256, 512)'

So I changed it to grayscale, using

```
>> from PIL import Image
>> img = Image.open('image.png').convert('LA')
>> img.save('greyscale.png')
```

Then I retrained my model, and get this error:

`ValueError: Cannot feed value of shape (2, 256, 512, 4) for Tensor 'instance_input_label:0', which has shape '(2, 256, 512)'`

Why is this?

**Comment by MaybeShewill-CV** [comment]
@chaine09 The instance label placeholder's shape is [batch_size, height, width] but you feed it with a ndarray with [batch_size, height, width, channel] shape. Shape mismatch you can google how use placeholder and feed dict in tensorflow:)

**Comment by chaine09** [comment]
@MaybeShewill-CV Oh, I already know how to use placeholder and feed dict. I fed it with a grayscale image. And yet the shape is `(2, 256, 512, 4)`?

**Comment by MaybeShewill-CV** [comment]
@chaine09  That should be checked by yourself

**Comment by chaine09** [comment]
@MaybeShewill-CV I tried to use the same images for both binary and segmentation images. I used only the binary images for both. Then trained it with no errors.

However, the accuracy started to decrease while training until it reaches 0.

**Comment by MaybeShewill-CV** [comment]
@chaine09 No the instance labels and the binary labels are different.

**Comment by chaine09** [comment]
Hi @MaybeShewill-CV. Is it correct that I create a json file according to

```
{
  'raw_file': str. 20th frame file path in a clip.
  'lanes': list. A list of lanes. For each list of one lane, there is only width index on the image.
  'run_time': list of float. The running time for each frame in the clip. The unit is millisecond.
}
```

Then should I draw the lines using `cv2.polylines`? Both for binary and instance images?

**Comment by MaybeShewill-CV** [comment]
@chaine09 It is up to you to use opencv polylines or other spline fit functions.

**Comment by chaine09** [comment]
@MaybeShewill-CV Then after that I should convert the image to grayscale? 

So you manually looked for this points that lie on the lane lines?

**Comment by chaine09** [comment]
@MaybeShewill-CV Have you not tried training your own dataset?

**Comment by chaine09** [comment]
@MaybeShewill-CV Can you please send the link of the complete Tusimple Dataset? Does this include both binary and instance images?

**Comment by MaybeShewill-CV** [comment]
@chaine09 The tusimple dataset only contains the json file with label info. The label image must be made by yourself. Go find yourself.

**Comment by chaine09** [comment]
@MaybeShewill-CV okay, so once I have the images. Do you what the proper format for the binary and instance labels are (e.g. grayscale, etc.)
