### ISSUE TITLE
怎么生成tusimple数据的eval文件（pred_file.json）

### ISSUE THREAD

**Issue by 131404060321** [MaybeShewill-CV/lanenet-lane-detection#90]
你好，在生成模型后需要评估模型，要生成一个pred_file.json文件，格式和tusimple数据集标注的格式一样。请问，有没有现成的代码或者是大概的思路方法？

**Comment by MaybeShewill-CV** [comment]
@131404060321 这个需要自己去查看tusimple的介绍:)

**Comment by MaybeShewill-CV** [comment]
@131404060321 那就需要你自己写一下了:)

**Comment by cardwing** [comment]
@131404060321 , I will post the codes which can generate pred_file.json [here](https://github.com/cardwing/Codes-for-Lane-Detection).
