### ISSUE TITLE
Resizing of binary images

### ISSUE THREAD

**Issue by david-bernstein** [MaybeShewill-CV/lanenet-lane-detection#93]
I noticed that on line 209 of train_lanenet.py the training binary image is resized using nearest value interpolation. However on line 269 the same interpolation is not used for the validation images. Is this correct? Does it make a difference?

**Comment by MaybeShewill-CV** [comment]
@david-bernstein The different interpolation function used in validation process almost make no difference. You can also use the same interpolation method in validation process to test:)
