### ISSUE TITLE
聚类问题

### ISSUE THREAD

**Issue by wushilian** [MaybeShewill-CV/lanenet-lane-detection#96]
有一个疑问，代码里的聚类是不是没有用到位置信息？我训练自己的数据发现，embedding图是正确的，但聚类出来的mask一团糟。

**Comment by 131404060321** [comment]
@wushilian 我也发现了这个问题，embedding分支返回的只是各像素点的向量表示形式（不知是否带有类别信息，或者能不能把类别信息保存下来），而聚类任务本身是不需要标签信息的，所以聚类后的结果只有多少类而没有每类的具体类别信息（即车道线的相对位置）。。。。

**Comment by MaybeShewill-CV** [comment]
@wushilian 聚类纯粹是基于embedding出来的特征向量。你说的embedding的图是正确的然而聚类出来的mask一团糟不太明白你具体想表达的意思:)

**Comment by wushilian** [comment]
@MaybeShewill-CV @131404060321 我觉得聚类不应该只利用embedding的特征向量，也应该考虑位置关系，也就是相邻位置的像素更有可能是同一个实例

**Comment by MaybeShewill-CV** [comment]
@wushilian 那你可以根据你的想法在embedding的基础上不只是用mean shift聚类 可以在mean shift的基础上加上你的策略 或者你可以修改instance branch的损失函数加上位置信息来做强监督:)

**Comment by MaybeShewill-CV** [comment]
@131404060321 你可以根据你的具体情况来修改mean shift的聚类结果 可以在mean shift聚类结果的基础上加上你指定的规则来消除你说的这种情况

**Comment by 131404060321** [comment]
@MaybeShewill-CV 感谢回复。正如前面所说，聚类出的结果是无序的，不仅如此，聚类出来的类别个数也是不确定的（因为车道线的个数是在变化的）。在这种情况下，我不知道该如何添加规则才能使得车道线的相对位置信息在聚类过程中被保存下来，你有什么好的方法或者思路吗？

**Comment by MaybeShewill-CV** [comment]
@131404060321 mean shift聚类本身就是无法确定聚类的类别个数的。比如你可以确定聚类簇与簇之间需要一定的间隔之类的:)
