### ISSUE TITLE
LR_DECAY_STEPS and LR_DECAY_RATE not used

### ISSUE THREAD

**Issue by david-bernstein** [MaybeShewill-CV/lanenet-lane-detection#98]
These two variables are declared in the global_config file but not used in the training script:

__C.TRAIN.LR_DECAY_STEPS = 410000
__C.TRAIN.LR_DECAY_RATE = 0.1

**Comment by MaybeShewill-CV** [comment]
@david-bernstein Yep the config file is copied from another task of my own so some of the config options are not used. I will clean it up later. Thanks:)

**Comment by david-bernstein** [comment]
Ok, no problem, thank you!
