### ISSUE TITLE
python tools/test_lanenet.py --is_batch False --batch_size 1 --weights_path model_weights_file/ --image_path data/tusimple_test_image/0.jpg

### ISSUE THREAD

**Issue by ytgcljj** [MaybeShewill-CV/lanenet-lane-detection#99]
(lanenet-env) launchx-16-500@launchx16500-System-Product-Name:~/github/lanenet-lane-detection$ python tools/test_lanenet.py --is_batch False --batch_size 1 --weights_path model_weights_file/ --image_path data/tusimple_test_image/0.jpg
I1120 13:39:40.379039 12708 test_lanenet.py:78] 开始读取图像数据并进行预处理
I1120 13:39:40.388536 12708 test_lanenet.py:84] 图像读取完毕, 耗时: 0.00939s
2018-11-20 13:39:41.954750: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "tools/test_lanenet.py", line 251, in <module>
    test_lanenet(args.image_path, args.weights_path, args.use_gpu)
  File "tools/test_lanenet.py", line 110, in test_lanenet
    saver.restore(sess=sess, save_path=weights_path)
  File "/home/launchx-16-500/github/lanenet-env/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1717, in restore
    + compat.as_text(save_path))
ValueError: The passed save_path is not a valid checkpoint: model_weights_file/

**Comment by MaybeShewill-CV** [comment]
@ytgcljj Please read the README file carefully. The weights_path should be the ckpt model file path:)

**Comment by ytgcljj** [comment]
我从这个网址下载的https://www.dropbox.com/sh/tnsf0lw6psszvy4/AAA81r53jpUI3wLsRW6TiPCya?dl=0
我从这个网址下载的https://www.dropbox.com/sh/tnsf0lw6psszvy4/AAA81r53jpUI3wLsRW6TiPCya?dl=0
I download https://www.dropbox.com/sh/tnsf0lw6psszvy4/AAA81r53jpUI3wLsRW6TiPCya? Dl=0 from this website.
![16](https://user-images.githubusercontent.com/27713475/48769369-6e36df80-ecf6-11e8-85dc-b21a68ad37e3.jpg)

**Comment by MaybeShewill-CV** [comment]
@ytgcljj The weights_path should be ROOT_DIR/model_weights_file/tusimple_lanenet_vgg_xxxxx.ckpt-20000
